### PR TITLE
Rename International edition (again).

### PR DESCRIPTION
**Pull request by gklopper**
I like this one...

intl1
intl2

cc @paperboyo

### CODE REVIEW

**Comment by paperboyo** [comment]
:gem:!

The only alternative abbreviation on mobile would be to use flag images :)

**Comment by gklopper** [comment]
Although editorial still don't like it, want *INT* now

**Comment by gklopper** [comment]
Sorry Matt :cry:

**Comment by paperboyo** [comment]
:gb: :us: :earth_americas:

:speak_no_evil:

Thanks, Grant!

**Pull request merged**
