### PR TITLE
Add Pete F to humans.txt

### PR DESCRIPTION
**Pull request by bryophyta**
## What does this change?

Add Pete Faulconbridge to `humans.txt`

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

### CODE REVIEW

**Review by ioannakok — APPROVED** [review]
🎉

**Review by OllysCoding — APPROVED** [review]
Welcome!

**Review by oliverlloyd — APPROVED** [review]
Welcome to the team 🎉

**Review by AshCorr — APPROVED** [review]
Woop woop! Welcome aboard!

**Pull request merged**
