### PR TITLE
Correct vertical alignment of social share numbers

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

**Before**

screenshot 2019-02-25 at 14 40 14

**After**

screenshot 2019-02-25 at 14 40 35

### CODE REVIEW

**Comment by shtukas** [comment]
Problem is currently happening (pre-merge) on this page: https://www.theguardian.com//fashion/gallery/2016/sep/23/london-tattoo-convention-in-pictures

**Comment by shtukas** [comment]
Another black background: https://www.theguardian.com/fashion/gallery/2019/feb/16/we-love-six-fashion-fixes-for-the-week-ahead-in-pictures

screenshot 2019-02-25 at 14 47 17

**Comment by shtukas** [comment]
And a white one: https://www.theguardian.com/fashion/2019/feb/16/anna-wintour-a-rare-face-to-face-with-the-most-important-woman-in-fashion

screenshot 2019-02-25 at 14 47 51

**Comment by shtukas** [comment]
Note: The original problem was caused by `_gallery.head.scss` , but the last two examples are caused by `_content.global.scss`. Both files needed update.

**Review by gtrufitt — APPROVED** [review]

**Review by SiAdcock — APPROVED** [review]
💅

**Pull request merged**
