### PR TITLE
test for svg support outside of ismordern test

### PR DESCRIPTION
**Pull request by sndrs**
you can be not modern and support svg, and if you aren't modern, we don't know either way

required by #8009

### CODE REVIEW

**Comment by robertberry** [comment]
:+1:

**Comment by ironsidevsquincy** [comment]
Should we move the other tests, flex etc, out as well?

**Comment by sndrs** [comment]
yeah we could do - this was specifically to manage inline svgs, but i think it would useful. we'd need to check `testCssSupport` worked in non-modern though. the test for svg should work whatever

**Comment by ironsidevsquincy** [comment]
http://stackoverflow.com/questions/9869112/i-need-compatible-javascript-code-for-document-createelementns-in-older-versio

**Comment by stephanfowler** [comment]
:+1:

**Pull request merged**
