### PR TITLE
Show /all links in Topics area on curated fronts

### PR DESCRIPTION
**Pull request by JustinPinner**
## What does this change?

On wider breakpoints, some fronts have been given treats with screen shot 2016-04-11 at 17 18 12 links to the /all tag page;
screen shot 2016-04-11 at 17 05 04

On narrower breakpoints these treats are hidden as their columns are removed, and so is the link to the /all page;
screen shot 2016-04-11 at 17 06 20

And in this state, the live site doesn't include any link to today's stories in their Topics area;
screen shot 2016-04-11 at 17 07 53

On some fronts, we do already see an "All today's stories" link in the Topics section near the end of the page, but this is due to the curated content they contain, and not because of the presence of the treats.

Now, if we don't have a pre-existing /all link in Topics and we do have a treat with an /all link, we'll show that in the Topics area;
screen shot 2016-04-11 at 17 14 07

Even at very narrow breakpoints;
screen shot 2016-04-11 at 17 24 21
## What is the value of this and can you measure success?

It gives readers on mobile devices the opportunity to explore more of the content related to the front they are viewing. If it's particularly successful we may see an uplift in traffic to /all pages (and therefore content) from mobile devices, but at the very least we're making a navigation route available consistently across formats. 
## Does this affect other platforms - Amp, Apps, etc?

No.
## Request for comment

cc @rich-nguyen @janua 
## 

_Does this PR meet the [contributing guidelines](https://github.com/guardian/frontend/blob/issue_pr_templates/.github/CONTRIBUTING.md#submission)?_

### CODE REVIEW

**Comment by janua** [comment]
LGTM :+1:

**Comment by paperboyo** [comment]
That’s :gem:, but it won’t fix the fact that the information infrastructure/browsing is neither predictable nor consistent enough. Keeping with the long-established Grauniad’s tradition, we are much better at it at the arcane URL level than at the UI one :sadpanda:. Finally fixes: https://github.com/guardian/frontend/issues/8792, though! BTW, how are they “today’s”?!

**Comment by JustinPinner** [comment]
@paperboyo They're "today's" stories because the /all page generally starts displaying content from the current date. I'm not sure I can address your other comments right now. Is this a conversation that's been had already or should be had soon? What kind of forum do you need?

**Comment by paperboyo** [comment]
@JustinPinner “today’s” may give a false hint that it will take me to a place where only a limited number of items live. While, in truth, this is the only place where _all_ items live.

This PR is great and brings more consistency! My comments were general (too general, as always!) and the problem is long-standing so there is no rush. There are tons of stuff I would like to see when it comes to better browsing/surfacing/discovery UX and I’m sure that you guys are discussing it all the time (although, I wouldn’t know.) Any forum is good, including, or even preferably, a :beers: one :wink:

**Pull request merged**
