### PR TITLE
Import the atom rendering library

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Specifics to be discussed

### CODE REVIEW

**Comment by sndrs** [comment]
how WIP is this? ready for review or subject to change?

**Comment by regiskuckaertz** [comment]
Yes please go ahead, we think you're better positioned to tick those boxes off, as they are platform-specific.

**Comment by regiskuckaertz** [comment]
Oops, wrong PR.

**Comment by regiskuckaertz** [comment]
No, this one is not ready. I've just copy-pasted my work into frontend but still need to figure how it can play ball with the existing infrastructure. May need your help and @TBonnin 's on this.

**Pull request closed without merging**
