### PR TITLE
use egyptian for crossword cell text

### PR DESCRIPTION
**Pull request by desbo**

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Have you got a screenshot? :smile:

**Comment by desbo** [comment]
:)
screen shot 2015-07-21 at 17 03 37

seems like the previews also need a bit of work, looking at that now.

**Comment by sndrs** [comment]
:mask:

**Comment by paperboyo** [comment]
Preferred @sndrs’s choice. And in any case, at that size, one of our sans-serifs would be more legible. Just sayin’.

Also, a pedant in me: is there a way to center the letters better (look at “I”s), maybe ``    font-variant-numeric: tabular-nums;`` or more specifically ``font-feature-settings: "tnum";`` (FF only)? Probably not, though. What’s the purpose of this comment, again?

**Comment by desbo** [comment]
@paperboyo yeah, I preferred it too... I questioned the change to egyptian but it's a blocker.
pretty sure those rules only affect numbers so wouldn't make any difference to our crossword :(

**Comment by paperboyo** [comment]
> pretty sure those rules only affect numbers

Aw, of course you’re right, silly me...

**Comment by desbo** [comment]
switched to sans, 
screen shot 2015-07-29 at 11 15 09

**Comment by OliverJAsh** [comment]
:+1:

**Pull request merged**
