### PR TITLE
Updated humans.txt

### PR DESCRIPTION
**Pull request by gklopper**
A number of people have moved onto other teams (or companies). 

Introduced an "Alumni & Colleagues" section to keep them in.

never actually deleted anyone, just moved them around a bit.

### CODE REVIEW

**Comment by johnduffell** [comment]
is this something I should have added myself to? maybe we can auto generate from the git history ;)

**Comment by phamann** [comment]
:+1: Ship it!

**Comment by gklopper** [comment]
Git history is too narrow an interpretation of who is in the team.

Just grab this branch and add yourself to the PR.

**Comment by gklopper** [comment]
Also, not everyone wants their name on this. Within reason we allow people to describe themselves how (and if) they want.

**Comment by johnduffell** [comment]
:+1: I'm happy now!

**Pull request merged**
