### PR TITLE
Status alerts on userhelp feedback page

### PR DESCRIPTION
**Pull request by MatthewJWalls**
## What does this change?

[this PR for feedback purposes, no changes]

Whenever something like discussion goes down, userhelp gets a flood of emails that they have to pick though. They have requested that there be a configurable alert on the [tech feedback page](https://www.theguardian.com/info/tech-feedback) that will display a message when our services are down

The intent for it to work is: userhelp becomes aware of an issue, they go to some small internal tool that lets them set a status message, and the message is displayed on the feedback page as an alert until userhelp clears it. All administrative responsibility is handled by userhelp.

We can implement this either on the front or backend. It'd be nice to have it work without JS; so backend would be good if we're ok with the extra serverside call to get the status (only on the feedback controller).

For the interface that userhelp would use to set the status; frontend admin? Some tiny outside service?

@guardian/dotcom-platform any thoughts on this?

### CODE REVIEW

**Comment by TBonnin** [comment]
The only issue I can foresee if we want this feature to happen server side is the delay to show/hide the alert/message due to the cache.

**Comment by NataliaLKB** [comment]
> For the interface that userhelp would use to set the status; frontend admin? Some tiny outside service?

Definitely think it should be frontend admin. I don't want another url to remember!

**Comment by TBonnin** [comment]
Given this service would be the responsibility of UserHelp, I am not sure I would like it to be in frontend

**Comment by NataliaLKB** [comment]
> Given this service would be the responsibility of UserHelp, I am not sure I would like it to be in frontend

Fair point. Then the question is what team is responsible for it? If it is us, I would rather it be in frontend, but if it is not then I wouldn't.

**Pull request closed without merging**
