### PR TITLE
Tweak styling for user account area tablet to wide

### PR DESCRIPTION
**Pull request by NataliaLKB**
## What does this change?

This PR brings the styling for the User account/sign in area just a bit more inline with the designs from @zeftilldeath 

## What is the value of this and can you measure success?

Looks nicer, on leftCol screens the menu is a bit shorter

## Does this affect other platforms - Amp, Apps, etc?

Nope

## Screenshots
**Desktop (or tablet in landscape view):**

screen shot 2017-06-20 at 12 09 12

**LeftCol:**

screen shot 2017-06-20 at 12 08 59

**Wide:**

screen shot 2017-06-20 at 12 08 35

## Tested in CODE?

Nope

### CODE REVIEW

**Comment by NataliaLKB** [comment]
cc @paperboyo because why not 😄

**Comment by gustavpursche** [comment]
@NataliaLKB in https://github.com/guardian/frontend/pull/17170/commits/f81c10e1b52200ef5ca022384ff9b980282da860 I enhanced the pseudo borders, so they are now. All the rest looks really good to me, so 👍

**Review by gu-stav — APPROVED** [review]

**Comment by NataliaLKB** [comment]
Awesome @gustavpursche !!

@zeftilldeath just pointed this out to me: 
image

The pillars aren't properly aligned anymore 😓 . Unfortunately I can't run the project on my personal laptop so it will have to wait until tomorrow to fix.

**Comment by gustavpursche** [comment]
@NataliaLKB Will fix :) So you can focus on stuff that's fun tomorrow 🌞

**Comment by gustavpursche** [comment]
@zeftilldeath @NataliaLKB Yesterday Zef and I refactored the alignment principles and bit. This should be reflected in the recent changes. Now everything is aligned again.

Screenshots are up to date.

**Comment by NataliaLKB** [comment]
Beautiful 👍 !

**Pull request merged**
