### PR TITLE
Extend outstream frequency

### PR DESCRIPTION
**Pull request by rich-nguyen**
Extend ab test until january 1

### CODE REVIEW

**Review by scottp719 — APPROVED** [review]
👍

**Comment by SiAdcock** [comment]
Is that a bank holiday? 😛

**Comment by ScottPainterGNM** [comment]
Damnit Rich!

**Comment by rich-nguyen** [comment]
I blame the approver.

**Comment by ScottPainterGNM** [comment]
@SiAdcock it isn't, I expect you to be here

**Comment by rich-nguyen** [comment]
He failed the test. @SiAdcock passed

**Review by SiAdcock — APPROVED** [review]
Nice date!

**Pull request merged**
