### PR TITLE
Should need valid GU_LA cookie for account pages (recent auth)

### PR DESCRIPTION
**Pull request by Calum-Campbell**
##### Ensures you need a valid SC_GU_LA cookie for the following pages : 
- https://profile.theguardian.com/contribution/recurring/edit
- https://profile.theguardian.com/account/edit
- https://profile.theguardian.com/membership/edit
- https://profile.theguardian.com/digitalpack/edit
- https://profile.theguardian.com/contribution/recurring/edit
- https://profile.theguardian.com/email-prefs

#### Adds tests for the AuthenticationAction and profileRedirectService

NB: You can access any /consents pages with either : 
 - valid GU_U & SC_GU_U cookie
- valid GU_RP cookie

## What is the value of this and can you measure success?
- return security of these pages to previous levels 

## Does this affect other platforms - Amp, Apps, etc?
No

## Tested in CODE?
No

### CODE REVIEW

**Review by jfsoul — COMMENTED** [review]
We desperately need tests for all these scenarios.  Is there anything at all right now?

**Comment by Calum-Campbell** [comment]
@jfsoul agree, there even is a test for this but not sure it's right... Will try add some extra testing into this.

**Comment by Calum-Campbell** [comment]
closing while I write some more extensive tests

**Comment by Calum-Campbell** [comment]
@jfsoul @rahilb this is re-opened now

**Review by rahilb — APPROVED** [review]
great stuff!

**Pull request merged**
