### PR TITLE
Add preconnect instructions to the HTML <head>

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

This adds 5 `preconnect` instructions to the HTML <head> of non AMP pages

Before:

```
<link rel="dns-prefetch" href="https://assets.guim.co.uk/"/>
<link rel="dns-prefetch" href="https://i.guim.co.uk"/>
<link rel="dns-prefetch" href="https://api.nextgen.guardianapps.co.uk"/>
<link rel="dns-prefetch" href="https://hits-secure.theguardian.com"/>
<link rel="dns-prefetch" href="//j.ophan.co.uk"/>
<link rel="dns-prefetch" href="//ophan.theguardian.com"/>
<link rel="dns-prefetch" href="//phar.gu-web.net"/>
<link rel="dns-prefetch" href="//www.google-analytics.com"/>
<link rel="dns-prefetch" href="//sb.scorecardresearch.com"/>
```

After:

```
<link rel="dns-prefetch" href="https://assets-code.guim.co.uk/"/>
<link rel="dns-prefetch" href="https://i.guim.co.uk"/>
<link rel="dns-prefetch" href="https://code.api.nextgen.guardianapps.co.uk"/>
<link rel="dns-prefetch" href="https://hits-secure.theguardian.com"/>
<link rel="dns-prefetch" href="//j.ophan.co.uk"/>
<link rel="dns-prefetch" href="//ophan.theguardian.com"/>
<link rel="dns-prefetch" href="//phar.gu-web.net"/>
<link rel="dns-prefetch" href="//www.google-analytics.com"/>
<link rel="dns-prefetch" href="//sb.scorecardresearch.com"/>

<link rel="preconnect" href="https://assets-code.guim.co.uk/"/>
<link rel="preconnect" href="https://i.guim.co.uk"/>
<link rel="preconnect" href="//interactive.guim.co.uk"/>
<link rel="preconnect" href="//www.google-analytics.com"/>
```

### Tested

- [x] Locally
- [x] On CODE (optional)

### CODE REVIEW

**Comment by shtukas** [comment]
@SiAdcock 
As discussed, going to:
- Try and find recommendations on whether or not too many preconnect instructions are harmful (not that we are doing "too many").
- Figure out whether we should preconnect to interactives (even though not every page has interactives)
- Add waterfall screenshots of before and after.

**Comment by SiAdcock** [comment]
Summary of our quick chat:

- do we still need to `dns-prefetch` and `preconnect` for Ophan, since the JS is bundled in the application? We certainly don't make any connection to `j.ophan.co.uk` so these can definitely go
- can we also include `interactive.guim.co.uk`? I appreciate that this is not called on every page, which begs the question: is there any harm in `preconnect`-ing to domains that are not used?

**Comment by shtukas** [comment]
** TEST: 2 ** ( Note a tiny regression for Document Complete this time )

*Before*

screenshot 2018-12-05 at 13 29 10

*After*

screenshot 2018-12-05 at 13 29 18


*Before*

screenshot 2018-12-05 at 13 30 28

*After*

screenshot 2018-12-05 at 13 30 41

**Comment by shtukas** [comment]
**TEST: 3**

*Before*

screenshot 2018-12-05 at 13 35 14

*After*

screenshot 2018-12-05 at 13 35 23

*Before*

screenshot 2018-12-05 at 13 35 42

*After*

screenshot 2018-12-05 at 13 35 51

**Comment by SiAdcock** [comment]
This is 👍 👍 👍 👍 👍 👍 fantastic @shtukas, I'm amazed such a tiny change has made such a large difference. Do you know whether you were testing against a mobile device?

Some general observations:

- In each test, the time to first byte is much lower in the _after_ run. This discrepancy may account for the much lower metrics for start render, time to interactive, etc. I wonder what might be causing that, as I wouldn't expect it to be affected here.
- Also the regression you noticed is interesting, because the second test requested about 600KB more content. Presumably you're hitting the `/uk` front each time, so  I'm not sure what might be causing this.

These are not blockers to merging, I think there's enough advantage in merging regardless of these discrepancies. But It's useful to learn that running simulated performance tests is not enough to form a strong conclusion.

**Review by SiAdcock — APPROVED** [review]
🐎 🐎 🐎

**Comment by AWare** [comment]
Can we keep these hacks from merging too close to each other and only after we know the perf data is good in ophan?

**Comment by NataliaLKB** [comment]
Awesome!

**Comment by shtukas** [comment]
> Can we keep these hacks from merging too close to each other and only after we know the perf data is good in ophan?

I talked with Alex and merging now.

**Comment by shtukas** [comment]
@SiAdcock 

> These are not blockers to merging, I think there's enough advantage in merging regardless of these discrepancies. But it's useful to learn that running simulated performance tests is not enough to form a strong conclusion.

I ran 6 tests against PROD before merging and 9 tests afterwards (spread over a couple of hours). Interestingly there are so much fluctuations in the numbers on PROD, from one test to another, that I can not conclude with **certainty** that this change actually brought the benefits we saw on CODE. Obviously `preconnect`ing is a good thing, but I can't tell with **precision** how much better the live site is because of it :)

> In each test, the time to first byte is much lower in the after run. This discrepancy may account for the much lower metrics for start render, time to interactive, etc. I wonder what might be causing that, as I wouldn't expect it to be affected here.

I noticed that as well. I can't explain it either...

**Comment by mchv** [comment]
As mentioned previously, excellent work @shtukas 🥇

**Comment by mchv** [comment]
As mentioned previously, excellent work @shtukas 🥇

**Pull request merged**
