### PR TITLE
Stop using keywords for travel targeting

### PR DESCRIPTION
**Pull request by kelvin-chappell**
This isn't used and never really worked very well anyway.

### CODE REVIEW

**Review by JonNorman — APPROVED** [review]
So was the initial purpose to target specific travel offers based on the keywords of the page?

**Comment by kelvin-chappell** [comment]
That was the idea.  But all the feeds code is probably in need of a review.

**Comment by regiskuckaertz** [comment]
:1st_place_medal:

**Comment by JonNorman** [comment]
Yeah I mean if someone were to raise a PR that removed all the `FeedRequest` `FeedReader` code then maybe I might accidentally +1 it and maybe that'd be the end of it....

**Pull request merged**
