### PR TITLE
Remove old (GAE) Avatar logic and configuration

### PR DESCRIPTION
**Pull request by nicl**
This removes the old avatar upload code now that the new system has been running for a while and works!

I believe I've caught most of this, but I'm not sure who knows this code anymore - I believe it predates the existing Identity team.

### CODE REVIEW

**Comment by nicl** [comment]
@guardian/guardian-frontend can somebody review? The build appears to be generally broken at the moment, so it's difficult for me to know whether the code here builds correctly.

**Comment by OliverJAsh** [comment]
@nicl The build is passing now!

**Comment by nicl** [comment]
@OliverJAsh thanks. Do you fancy reviewing? I don't think there's anyone who owns this code as such.

**Comment by OliverJAsh** [comment]
As much as I understand this, it looks good to me! :+1:

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <Re: [frontend] Remove old (GAE) Avatar logic and configuration (#10013)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Pull request merged**
