### PR TITLE
Lint for svg issues.

### PR DESCRIPTION
**Pull request by AWare**
## What does this change?
Fails the compile if you have anything base64'd in a png, or if it's too big*

*currently 136kb, we might need to better target this

### CODE REVIEW

**Review by gtrufitt — APPROVED** [review]

**Review by SiAdcock — APPROVED** [review]
Nice! It would be awesome if we could pass SVGs through an optimiser at this point, so we don't have to rely on people always optimising the hell out of their SVGs at checkin

**Comment by gtrufitt** [comment]
Can this 🚢 @AWare?

**Comment by AWare** [comment]
This can 🚢  @gtrufitt  (wow sorry)

**Comment by gtrufitt** [comment]
Rebased and tested. 

Shipping.

tenor-23088704

**Pull request merged**
