### PR TITLE
Fix video fronts for unenhanceable devices (iPad)

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

[iPads do not run enhanced JavaScript on fronts](https://github.com/guardian/frontend/blob/master/common/app/templates/inlineJS/blocking/shouldEnhance.scala.js#L43).

In #19851, a change was made to initialise YouTube atoms in the enhanced JavaScript, as opposed to embedding the YouTube iframe on the server side.

The result for iPad users is that on fronts, YouTube atoms appear as unclickable grey squares, without even a placeholder image. A dismal experience.

To address this, this change:

- shows the placeholder image by default. This was previously hidden because the YouTube iframe was embedded in the server-rendered HTML and enhanced on the client (see #15277). Now the iframe is added as an enhancement on the client, we can safely show the placeholder straight away
- makes the YouTube atom clickable when not enhanced. If the browser is not modern, clicking the atom navigates the user to the canonical video page.

## Screenshots

**Before**

screen shot 2018-09-04 at 18 07 40

**After**

sep-04-2018 18-06-08

## What is the value of this and can you measure success?

Improves the experience on iPad by showing placeholder images when available.

For future consideration:

- Embed iframe in server-rendered HTML if YouTube atom doesn't have a placeholder image. I think @GHaberis warned me that this is possible. Note that in this instance we will not be able to check whether user wants personalised ads.
- Inject iframe only when user clicks (shows intent) on the placeholder. This will save us forcing the user to download a bunch of YouTube JavaScript that may not get executed

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Accessibility test checklist

- [x] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/) - still unaccessible 😞 
- [x] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/) - still non-navigable 😞 
- [x] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by paperboyo — APPROVED** [review]
I obviously can’t comment on specifics, but the experience is so bad currently, that this will be a life-saver. Also, great points for the future consideration! 👏

**Review by akash1810 — APPROVED** [review]
small change, MASSIVE impact! 🎉

**Review by kelvin-chappell — APPROVED** [review]
Excellent! Thanks for fixing. 👍

**Comment by SiAdcock** [comment]
> small change

It took me like 3 hours to understand the CSS and template logic 😅

**Pull request merged**
