### PR TITLE
Zindex

### PR DESCRIPTION
**Pull request by uplne**
This should add some logic to handling z-index in our code base.

I've decided to go with mixed naming convention.

Low level z-index numbers are using more vague naming: alpha, beta etc because it can be used anywhere.

Then we have more literal higher numbers which has well defined purpose.
I suppose most of the z-index used in our code base should be in the alpha range anyway.

I've used it already for header, footer and container links. Everything seems to be [working ok](https://www.browserstack.com/screenshots/27ef8992a5c82c0191da55c4ab6621d89491004c).

### CODE REVIEW

**Comment by piuccio** [comment]
:+0.5:

@JustinPinner recently worked on z-index

**Comment by JustinPinner** [comment]
I like this idea, especially for those layers with meaningful names as it'll be blindingly obvious when you're about to stray into reserved territory. 

I wonder if we can do better than alpha, beta and gamma though as their meanings are still a bit opaque I think. It doesn't feel like adding + n to one of those will really remove much of the confusion over which elements should lie over others within that band.

What if `alpha` became `images`, `beta` became `text` and `gamma` became `menus`. Or something like that anyway? Might we need something for `effects` or similar? I guess the values of these don't really matter too much as long as there's some scope to inject new ones in between others.

Does that make sense?

**Comment by sammorrisdesign** [comment]
@JustinPinner I agree. But they probably need to be quite vague, right? Like what if you wanted `text` above an `image`?

**Comment by uplne** [comment]
@JustinPinner I see you point.

We can go with more Twitter boostrap way:

1. define this high priority objects we have (modal, overlay, nav etc) with 800+

2. define some middle space that can be used for things like images and other things we may need higher zindex for in the future and we can create ranges for that as needed: $zindex-overtext which will be range from 100 and can be used for anything that needs to be higher than text (images fix).

3. range below 99 will be wild wild west because, truly, we don't care what is happening there.

**Comment by piuccio** [comment]
One thing to keep in mind when using z-index is that `u-faux-block-link__overlay` must have the highest z-index among all the elements inside `fc-item__container`. Right now that value is `0` which is fine as long as all the others are `0`.

If you give a higher z-index to the trail image or the headline or anything, the click hack won't work anymore.

**Comment by uplne** [comment]
@piuccio good point.

So theoretically after applying this new logic `u-faux-block-link__overlay` should have zindex set to $zindex-overlay (1050) and that should take care of that it will be always the highest number inside the `fc-item__container`.

**Comment by piuccio** [comment]
@upine As long as any other overlay has a higher z-index (search box, tooltips and ads ...) and probably playable too (video player, gallery?)

**Comment by paperboyo** [comment]
Hi,

This is great! Just remember we do have a gallery Lightbox overlay (which suffered from higher z-indexed ads bursting through from the site below, like https://github.com/guardian/frontend/issues/8588 and at other times). There is also a notification level.

I wonder if there won't always be some legitimate exceptions that should be easy to be warned about but still possible to override the imposed logic, like e.g. the cut outs overlaying nav UI shown in https://github.com/guardian/frontend/issues/8935#issuecomment-94707577.

Regards
Mateusz

**Comment by uplne** [comment]
@paperboyo good point too.

I took that into consideration. Lightbox should have the second highest zindex `$zindex-overlay`. Only higher is the `$zindex-popover` which should be for breaking news/notifications. But it would be easy to change if we want. That is one of the advantages of this. We will have more control over which objects would be affected if we decide to change zindex for some group or switch groups.

The beauty of this is also that there is still a big range of free zindex values (up and down) to take care of some exceptions if needed.

FYI: we are in the testing phase of the variations of the main navigation and if any of it will go to 100%, it will make #8935 obsolete.

**Comment by uplne** [comment]
@piuccio you need to also consider the stacking context.

Things inside `fc-item__container` have different stacking context that `search box` has etc. So we should be ok. Stop by and I can explain in detail if you would be interested.

**Comment by uplne** [comment]
I've simplified it a lot after this discussion. So now we have only the top priority levels and we don't really care about anything below 800.

**Comment by johnduffell** [comment]
Looks like a great idea so we have a more defined concept of indexes, as we do have trouble with overlapping stuff sometimes. However we should totally ship this before it becomes our oldest PR ;)

**Comment by uplne** [comment]
@johnduffell It needs plus one

**Comment by johnduffell** [comment]
Oops sorry I forgot to add that in!! :+1:

**Pull request merged**
