### PR TITLE
Remove fastdom-idle

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

Remove another unused module in `lib`.

## What is the value of this and can you measure success?

Less code to maintain. This module was also breaking the rule of no application dependencies in `lib` modules.

## Does this affect other platforms - Amp, Apps, etc?

No

## Tested in CODE?

No

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]
Boom! 🎆

**Comment by gtrufitt** [comment]
As discussed f2f, ideally this would be *the* way we do fastdom but there's probably a refactoring task to ⬆️ upgrade fastdom or wrap all fastdom calls like this?

**Comment by SiAdcock** [comment]
I've added this as a Performance-related task to the [Client Side Defeat in Detail Document](https://docs.google.com/spreadsheets/d/1uUms84HMp2M1ju4uVUbFRImd8D7fxgpQxCkWmf76av8/edit#gid=0)

**Review by sndrs — APPROVED** [review]
should have done something with this, nice one

**Pull request merged**
