### PR TITLE
remove unused assets

### PR DESCRIPTION
**Pull request by alexduf**
## What does this change?
cleanup unused assets
## What is the value of this and can you measure success?
Less clutter
## Does this affect other platforms - Amp, Apps, etc?
No
## Screenshots
No!

@guardian/guardian-frontend

### CODE REVIEW

**Comment by MatthewJWalls** [comment]
PR build results: 
* https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15518/screenshots/mobile.png 
* https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15518/screenshots/wide.png 
* https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15518/screenshots/tablet.png 
* https://s3-eu-west-1.amazonaws.com/prbuilds/PR-15518/screenshots/desktop.png 

 -automated message

**Review by DiegoVazquezNanini — APPROVED** [review]

**Comment by TBonnin** [comment]
I am reverting this because those files seems to be used in prod https://kibana.gu-web.net/goto/46671b477c180bf952e34c6bd78b1f5b

**Comment by NataliaLKB** [comment]
@alexduf This might be what was causing the issues:
https://github.com/guardian/frontend/blob/master/common/app/templates/javaScriptConfig.scala.js#L22

cc @rich-nguyen

**Comment by alexduf** [comment]
Sorry everyone, I completely missed the fact that this could cause such damage.
Thanks @TBonnin for reverting, and thanks @NataliaLKB for finding the origin of the problem.
I'll take more time to clean it up properly

**Comment by NataliaLKB** [comment]
@alexduf these things happen. Thanks in advance for removing some unused assets. 

Also, thank @rich-nguyen for finding the problem!

**Comment by johnduffell** [comment]
CODE 😭

**Comment by TBonnin** [comment]
Not your fault @alexduf. We can use this incident to learn and improve our process
However:
- Let's get to the bottom of this issue. Should we have a build failure in this case? How did some of the apps even deployed successfully? @jfsoul @NataliaLKB will follow up on this
- Also is there a flaw in our panic shading mechanism that prevent apps to recover under high traffic?
- How can we improve our process? In this case the deployment of some apps fails and the [deploy dashboard](https://kibana.gu-web.net/goto/541ce6a8a807e814204567d13548d1c2) (private) clearly showed something went wrong after deploying.

Stay tuned

**Pull request merged**
