### PR TITLE
Retire fluid250 and scrollable-mpu

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Not in use anymore: the fluid250v1–4, the scrollable MPU and the 88x70 size

- [x] confirmation from AU
- [x] creative templates deactivated in DFP

### CODE REVIEW

**Comment by sndrs** [comment]
giphy

**Comment by regiskuckaertz** [comment]
commercial.js is the heaviest asset right now, but this is going to change. We're indeed getting rid of everything 😃

**Comment by regiskuckaertz** [comment]
[Retire fluid250 and scrollable MPU](https://trello.com/c/r18oh5k6/193-retire-fluid250-and-scrollable-mpu)

**Review by lps88 — APPROVED** [review]
👍

**Pull request merged**
