### PR TITLE
Run analytics as soon as possible

### PR DESCRIPTION
**Pull request by gklopper**
Measurement has shown us that for a number of people, tracking is not running.

Analytics should be our top priority and this is the simplest thing we can do to see if that improves.

cc @janua @OliverJAsh

### CODE REVIEW

**Comment by OliverJAsh** [comment]
:+1: Skeptical about how this will help but worth a go!

**Comment by janua** [comment]
I'm not so sceptical! We should be doing this earlier regardless if it fixes anything or not.

If it doesn't matter, then let's do it at the very end? *tongue in cheek*

**Comment by gklopper** [comment]
I dont' expect this to make a massive difference on its own. It might solve
the IE 9 problem in which case it will make a big difference but not for
the reasons I hoped.

It should do some things though.

1. Reinforce the idea in anyone that sees it to think of Analytics first.
2. Make our Analytics slightly less susceptible to the whims of the
internet (due to it running earlier).

Grant

On 15 July 2015 at 11:24, Francis <notifications@github.com> wrote:

> I'm not so sceptical! We should be doing this earlier regardless if it
> fixes anything or not.
>
> If it doesn't matter, then let's do it at the very end? *tongue in cheek*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9779#issuecomment-121568530>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by OliverJAsh** [comment]
All of the JS is here is swimlaned, which is why I am skeptical about what
difference this might make. Unless our swimlaning is broken.

On Wed, 15 Jul 2015 at 11:59 Grant Klopper <notifications@github.com> wrote:

> I dont' expect this to make a massive difference on its own. It might solve
> the IE 9 problem in which case it will make a big difference but not for
> the reasons I hoped.
>
> It should do some things though.
>
> 1. Reinforce the idea in anyone that sees it to think of Analytics first.
> 2. Make our Analytics slightly less susceptible to the whims of the
> internet (due to it running earlier).
>
> Grant
>
> On 15 July 2015 at 11:24, Francis <notifications@github.com> wrote:
>
> > I'm not so sceptical! We should be doing this earlier regardless if it
> > fixes anything or not.
> >
> > If it doesn't matter, then let's do it at the very end? *tongue in cheek*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/guardian/frontend/pull/9779#issuecomment-121568530>.
> >
>
> --
>
> ------------------------------
> Visit theguardian.com. On your mobile and tablet, download the Guardian
> iPhone and Android apps theguardian.com/guardianapp and our tablet
> editions
> theguardian.com/editions. Save up to 57% by subscribing to the Guardian
> and Observer - choose the papers you want and get full digital access.
> Visit subscribe.theguardian.com
>
> This e-mail and all attachments are confidential and may also be
> privileged. If you are not the named recipient, please notify the sender
> and delete the e-mail and all attachments immediately. Do not disclose the
> contents to another person. You may not use the information for any
> purpose, or store, or copy, it in any way. Guardian News & Media Limited
> is not liable for any computer viruses or other material transmitted with
> or as part of this e-mail. You should employ virus checking software.
>
> Guardian News & Media Limited is a member of Guardian Media Group plc.
> Registered
> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.
> Registered
> in England Number 908396
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9779#issuecomment-121580987>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by gklopper** [comment]
In these cases its not normally "broken" that is a problem, it is when
things are slow.

Grant

On 15 July 2015 at 12:02, Oliver Joseph Ash <notifications@github.com>
wrote:

> All of the JS is here is swimlaned, which is why I am skeptical about what
> difference this might make. Unless our swimlaning is broken.
>
> On Wed, 15 Jul 2015 at 11:59 Grant Klopper <notifications@github.com>
> wrote:
>
> > I dont' expect this to make a massive difference on its own. It might
> solve
> > the IE 9 problem in which case it will make a big difference but not for
> > the reasons I hoped.
> >
> > It should do some things though.
> >
> > 1. Reinforce the idea in anyone that sees it to think of Analytics first.
> > 2. Make our Analytics slightly less susceptible to the whims of the
> > internet (due to it running earlier).
> >
> > Grant
> >
> > On 15 July 2015 at 11:24, Francis <notifications@github.com> wrote:
> >
> > > I'm not so sceptical! We should be doing this earlier regardless if it
> > > fixes anything or not.
> > >
> > > If it doesn't matter, then let's do it at the very end? *tongue in
> cheek*
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/guardian/frontend/pull/9779#issuecomment-121568530
> >.
> > >
> >
> > --
> >
> > ------------------------------
> > Visit theguardian.com. On your mobile and tablet, download the Guardian
> > iPhone and Android apps theguardian.com/guardianapp and our tablet
> > editions
> > theguardian.com/editions. Save up to 57% by subscribing to the Guardian
> > and Observer - choose the papers you want and get full digital access.
> > Visit subscribe.theguardian.com
> >
> > This e-mail and all attachments are confidential and may also be
> > privileged. If you are not the named recipient, please notify the sender
> > and delete the e-mail and all attachments immediately. Do not disclose
> the
> > contents to another person. You may not use the information for any
> > purpose, or store, or copy, it in any way. Guardian News & Media Limited
> > is not liable for any computer viruses or other material transmitted with
> > or as part of this e-mail. You should employ virus checking software.
> >
> > Guardian News & Media Limited is a member of Guardian Media Group plc.
> > Registered
> > Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.
> > Registered
> > in England Number 908396
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/guardian/frontend/pull/9779#issuecomment-121580987>.
> >
>
> --
>
> ------------------------------
> Visit theguardian.com. On your mobile and tablet, download the Guardian
> iPhone and Android apps theguardian.com/guardianapp and our tablet
> editions
> theguardian.com/editions. Save up to 57% by subscribing to the Guardian
> and Observer - choose the papers you want and get full digital access.
> Visit subscribe.theguardian.com
>
> This e-mail and all attachments are confidential and may also be
> privileged. If you are not the named recipient, please notify the sender
> and delete the e-mail and all attachments immediately. Do not disclose the
> contents to another person. You may not use the information for any
> purpose, or store, or copy, it in any way. Guardian News & Media Limited
> is not liable for any computer viruses or other material transmitted with
> or as part of this e-mail. You should employ virus checking software.
>
> Guardian News & Media Limited is a member of Guardian Media Group plc.
> Registered
> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.
> Registered
> in England Number 908396
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9779#issuecomment-121582663>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
