### PR TITLE
Add how to view preview CAPI locally

### PR DESCRIPTION
**Pull request by gtrufitt**
## What does this change?
Documentation to run preview

@guardian/dotcom-platform

### CODE REVIEW

**Comment by gtrufitt** [comment]
any1?

**Comment by tomrf1** [comment]
sorry, I missed this.
Worth noting that you need CAPI `API Gateway invocation` credentials from janus, which is available to all who have frontend dev permissions

**Comment by gtrufitt** [comment]
Thanks @tomrf1 added!

**Review by tomrf1 — APPROVED** [review]
👍

**Pull request merged**
