### PR TITLE
Sticky ad: replace test with switch

### PR DESCRIPTION
**Pull request by OliverJAsh**
Test details and outcome available at https://docs.google.com/document/d/1ld7wRfkZh9UUeH2-IVm3GgipNyJNOFjPKJs1XPDDnKw/edit#heading=h.3mu5tihudrpv.

We are now ready to switch 100% of users to the new version.

### CODE REVIEW

**Comment by Jholder112233** [comment]
:gem:

**Comment by Jholder112233** [comment]
And :+1:

**Comment by Calanthe** [comment]
Great!

**Comment by NataliaLKB** [comment]
:+1: :sparkles: :ship:

**Comment by OliverJAsh** [comment]
I'll put this live tomorrow morning and then turn the switch on.

On Tue, 9 Feb 2016 at 16:44 Natalia Baltazar <notifications@github.com>
wrote:

> [image: :+1:] [image: :sparkles:] [image: :ship:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/11902#issuecomment-181950479>.
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by paperboyo** [comment]
:gem:!

**Pull request merged**
