### PR TITLE
Wrap the whole job in a try / catch as it fails on the await call

### PR DESCRIPTION
**Pull request by jennysivapalan**
@janua you were right https://github.com/guardian/frontend/pull/10884 didn't work. The future times out so adding a try / catch around the job.

### CODE REVIEW

**Comment by JustinPinner** [comment]
:+1:

**Comment by janua** [comment]
:-1: 
Why can't this happen inside the context of the `Future`? Why do we have to use `Await` at all?

**Comment by jennysivapalan** [comment]
After @janua :-1: I had a little :cry: then we removed the `Await` and added a timeout on the `WS` call. Viewing this with `?w=1` is best.

**Comment by janua** [comment]
Much better! Hopefully `20 seconds` will be enough!
You will be able to find out quite quickly by looking at the logs for `TimeoutException`s.
:+1:

**Pull request merged**
