### PR TITLE
Make mega nav scrollable

### PR DESCRIPTION
**Pull request by johnduffell**
Just a small bug fix to let the scrolling of the meganav work again when it's sticky
@uplne @sndrs

### CODE REVIEW

**Comment by johnduffell** [comment]
actually, this seems to fix it on my laptop, but it is still strange on mobile breakpoint and I'm struggling to work out why

**Comment by uplne** [comment]
We can look at it tomorrow together.

We need to make new meganav @Pearson82

**Comment by OliverJAsh** [comment]
Filed a bug for this at https://github.com/guardian/frontend/issues/10148.

**Comment by johnduffell** [comment]
all things being well, @uplne will ship this fix for tablet breakpoint and have a look at the similar mobile issue tomorrow

**Comment by sndrs** [comment]
tablet breakpoint is not a big deal for us, compared to mobile (now our most used breakpoint). be good to focus on that first if possible, and get it fixed asap. let me know if i can help

**Comment by uplne** [comment]
:+1:

**Pull request merged**
