### PR TITLE
Remove pinned block flag and experiment

### PR DESCRIPTION
**Pull request by abeddow91**
# DO NOT MERGE UNTIL APPROVED BY CP

## What does this change?
Removing the experiment flag for the pinned post feature

### CODE REVIEW

**Review by joecowton1 — DISMISSED** [review]
Waiting for CP approval before merging.

**Review by oliverlloyd — COMMENTED** [review]
I'm sure you're already on top of this but we should be sure to have good comms around this change. Can we also include Dotcom in this please? We will need to have an overview of the change and how it works so we can handle any support requests. Thanks!

**Comment by joecowton1** [comment]
> I'm sure you're already on top of this but we should be sure to have good comms around this change. Can we also include Dotcom in this please? We will need to have an overview of the change and how it works so we can handle any support requests. Thanks!

@oliverlloyd have mentioned this on to @humaislam who is handling comms

**Review by marjisound — APPROVED** [review]
LGTM

**Pull request merged**
