### PR TITLE
Nicer opt-in engagement alert

### PR DESCRIPTION
**Pull request by walaura**
## What does this change?
Makes the engagement banner that will show up for users coming from newsletters look nicer

## Screenshots
screen shot 2018-02-20 at 4 34 31 pm
screen shot 2018-02-20 at 4 34 35 pm

### CODE REVIEW

**Comment by SiAdcock** [comment]
c/c @paperboyo for SVG optimisation tips 😄

**Comment by Amohkhan** [comment]
Can you add me as a reviewer on this, please

**Comment by walaura** [comment]
@Amohkhan i actually can't :( not sure why
screen shot 2018-02-19 at 10 38 06 am

**Review by Calum-Campbell — APPROVED** [review]
Pending svg comments 👍 !

**Comment by paperboyo** [comment]
I would just run it through https://jakearchibald.github.io/svgomg/. And maybe reduce the empty space below in the whole banner, but that’s just personal observation…

**Comment by walaura** [comment]
@paperboyo design is still a bit up in the air i'm afraid. Nice catch on the SVG! May I ask why the assets aren't svg compressed as part of the build step? They are moved to a `/dist` folder and everything

**Comment by paperboyo** [comment]
> design is still a bit up in the air i'm afraid

👍 



> why the assets aren't svg compressed as part of the build step?

I wouldn’t know anything about that, I’m afraid.

**Comment by Amohkhan** [comment]
@walaura Can you bring up the text on both the banners, it should be hanging quite tightly to the top of the banner,  and the button is a bit misaligned from the text, if you could move it to the right slightly on mobile, and to the left slightly on desktop, please and thank you

**Comment by Amohkhan** [comment]
Oh and there a few more circles to add to mobile please, near the bottom left of the banner :)

**Pull request merged**
