### PR TITLE
Upgrade React from 16.7.0 to 16.8.3

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

Upgrade React from 16.7.0 to 16.8.3

## What is the value of this and can you measure success?

Health

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
🆙

**Comment by AWare** [comment]
if crosswords are happy, i'm happy

**Comment by shtukas** [comment]
Tested on CODE, merging now. 

screenshot 2019-02-28 at 08 16 11

**Comment by shtukas** [comment]
All fine in PROD post merge.

**Pull request merged**
