### PR TITLE
suppress save for later on short pages

### PR DESCRIPTION
**Pull request by NathanielBennett**
Don't duplicate sfl for later on short pages - as per social share buttons. 
Red arrows indicate where the buttons were: 

@Jholder112233 - I was going to do some silly javascript, but that's _much_ cleaner. Look OK?

deduped-sfl

deduped-sfl-mob

### CODE REVIEW

**Comment by Jholder112233** [comment]
@NathanielBennett You could save a lot of duplication here by just wrapping 
```html
<div class="js-save-for-later submeta__save-for-later" data-position="bottom"></div>
```
 in the SaveForLaterSwitch.isSwitchedOn if statement

**Comment by NathanielBennett** [comment]
@Jholder112233 good call - hows that?

**Comment by Jholder112233** [comment]
Looks good! :+1:

**Comment by NathanielBennett** [comment]
Ta

**Comment by OliverJAsh** [comment]
This was added because people might scroll to the bottom of content, where the SFL button in the sidebar will no longer be in view. I'm not sure if removing it is the best solution. I think someone else proposed removing the button at the bottom if the content type is picture/video, because the user is unlikely to scroll the SFL button out of the viewport.

**Comment by Jholder112233** [comment]
@OliverJAsh Surely that logic also applies to the share buttons then? Either is fine for me but they should at least be consistent.

**Comment by ScottPainterGNM** [comment]
I had raised the point before about picture/video/audio pages as the first
SFL button is generally visible within the viewport at all times and it
looks especially strange on mobile.

On 28 August 2015 at 11:55, Josh Holder <notifications@github.com> wrote:

> @OliverJAsh <https://github.com/OliverJAsh> Surely that logic also
> applies to the share buttons then? Either is fine for me but they should at
> least be consistent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/10312#issuecomment-135739463>.
>



-- 
Scott Painter
QA Analyst | Dotcom

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by ScottPainterGNM** [comment]
I think the above solution looks cleaner then what was in place originally
though!

On 28 August 2015 at 11:57, Scott Painter <scott.painter@theguardian.com>
wrote:

> I had raised the point before about picture/video/audio pages as the first
> SFL button is generally visible within the viewport at all times and it
> looks especially strange on mobile.
>
> On 28 August 2015 at 11:55, Josh Holder <notifications@github.com> wrote:
>
>> @OliverJAsh <https://github.com/OliverJAsh> Surely that logic also
>> applies to the share buttons then? Either is fine for me but they should at
>> least be consistent.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/guardian/frontend/pull/10312#issuecomment-135739463>.
>>
>
>
>
> --
> Scott Painter
> QA Analyst | Dotcom
>



-- 
Scott Painter
QA Analyst | Dotcom

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
