### PR TITLE
Jspm integration

### PR DESCRIPTION
**Pull request by rich-nguyen**
Reopening pull request #9222. Issues:
- ophan module was not loading - due to a nullable dependency, which is interpreted as `{}` in SystemJs.
- interactives - boot.js was being loaded as https and then timing out. So now we are making the protocol relative to the original `data-interactive` attribute, rather than the page's protocol.
- babel error - Babel had a dependency that caused an [error](https://github.com/babel/babel/issues/1014) in ie9

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Nice work!

The problems we had:

* IE9 Babel error, fixed by upgrading
* Interactives were loading over HTTPS on preview (due to HTTPS static asset), but they only support HTTP
* Browsers without `window.performance` were falsly passing the duck typing inside of Ophan, because SystemJS always exports an object whereas RJS/curl let you export `undefined`.

**Comment by uplne** [comment]
What about the commercial third parties? Wasn't some error related to this too?

**Comment by rich-nguyen** [comment]
yes, the crux of that problem was krux. updated the url to make sure it is http, not https

**Comment by piuccio** [comment]
This PR broke http://www.theguardian.com/preferences and http://www.theguardian.com/help/accessibility-help

the react version in bower was `0.11` while jspm uses `0.13`. Our react scripts are using `.renderComponent` which should be renamed as `.render`.

**Comment by OliverJAsh** [comment]
Will fix, ta!

**Pull request merged**
