### PR TITLE
Autoplay video

### PR DESCRIPTION
**Pull request by jamesgorrie**
Whenever you land on a video page - autoplay.
As discussed with Piers / Yannick / Editorial.

### CODE REVIEW

**Comment by rich-nguyen** [comment]
This was specifically added on editorial request. It used to be autoplay everywhere. People were complaining that they were seeing the same video (and adverts) over and over, but were revisiting the same video page for the purposes of seeing the comments again. Shouldn't this be a user option?

Also, does mobile remain non-autoplay?

> plus ça change, plus c’est la même chose

**Comment by jamesgorrie** [comment]
> Shouldn't this be a user option?
Potentially.

> It used to be autoplay everywhere...  does mobile remain non-autoplay
It now only autoplays on video pages and desktop.

**Comment by jamesgorrie** [comment]
I'm speaking to Editorial on Monday - so I will let you know then.

**Comment by jamesgorrie** [comment]
Closed as there was a misunderstanding with Editorial.

**Pull request closed without merging**
