### PR TITLE
Move new navigation from Enhanced to Standard

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

This change moves the new navigation module from the Enhanced JS bundle into Standard for the duration of the new navigation's AB test.
## What is the value of this and can you measure success?

We have found that, if the user taps the menu icon when the page first loads, but before all DOM manipulation has completed, there is a ~500ms delay between the user interaction and the menu opening. Moving the navigation module from enhanced into standard reduces this delay to ~350ms. For slower connections, the improvement is more dramatic.

As part of the AB test, we will determine whether users tend to tap the menu icon while the DOM is still being loaded.

Finally, the Details polyfill is being loaded in the wrong place, and should be loaded inline. Since the new navigation is the only module that uses it, it is safe to remove the polyfill for now. In a future PR, I will add it to the correct place. 
## Does this affect other platforms - Amp, Apps, etc?

Nope

### CODE REVIEW

**Comment by rich-nguyen** [comment]
> if the user taps the menu icon when the page first loads

How often do we think this is happening?

The difference between standard and enhanced, alongside the technical implications you have mentioned, is that things that are in standard are considered so important that they should run before our commercial system. We haven't communicated that well as a team, admittedly, but do you think we should? It would make it easy to have discussions about what should be in standard. Improving the response time of something which isn't in the critical path for rendering, should be considered enhanced, in my view.

**Comment by SiAdcock** [comment]
Thanks @rich-nguyen 

The new header is not yet live, so no real users have experienced the delay yet. It was just something that came up in QA.

I agree it would be helpful to understand what constitutes a standard module and what is enhanced, to help us make better decisions about where to load modules.

It's hard for me to make a judgement call as to whether primary navigation should be loaded before the commercial system. In our tests, interacting with the menu on a device with a poor 3G connection had a 4 second response time. Poor response times would likely skew the success of the new navigation's A/B test. Happy to discuss further

**Comment by johnduffell** [comment]
sounds like the debate is about order of loading, but we have to avoid just bumping things up arbitrarily.  Is this going back to the drawing board, if so it should probably close for now?

**Comment by SiAdcock** [comment]
Yeah, a new plan for loading the navigation is currently being formalised. I'll close this for now.

**Pull request closed without merging**
