### PR TITLE
Hide vertical rule behind bg

### PR DESCRIPTION
**Pull request by regiskuckaertz**
https://trello.com/c/SDDkpCnt

Not ideal if the background changes, but we can fix if it happens.

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
Also stick the caption in the left column for showcase and supporting images cc @akemitakagi

**Comment by akemitakagi** [comment]
@regiskuckaertz Captions in the left column looks great. Will you move the share icons under the captions in the left column as well? (for showcase and supporting image)

**Comment by regiskuckaertz** [comment]
Agreed to do that separately as the changes required can have a lot of side effects.

**Comment by akemitakagi** [comment]
:+1:

**Pull request merged**
