### PR TITLE
Fix Potential Null in Dev-Build

### PR DESCRIPTION
**Pull request by kelvin-chappell**
I've been getting NPEs sometimes, so this is a harmless fix.

### CODE REVIEW

**Comment by robertberry** [comment]
Wonder if it might be better if it throws an error message saying "Run grunt compile" or whatever. CC @rich-nguyen

**Comment by kelvin-chappell** [comment]
Yes, that's a good idea.  I realise that's why it was happening now.

**Comment by rich-nguyen** [comment]
Yeah i think you still want an exception, but a more useful one as @robertberry mentioned. possibly tweak this so that it throws something meaningful?

**Comment by kelvin-chappell** [comment]
Yes, will do.

**Comment by kelvin-chappell** [comment]
Now throwing a friendly exception instead.

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
