### PR TITLE
Incorporate test for currentSrc support from picturefill 2.3.1

### PR DESCRIPTION
**Pull request by sndrs**
Adds updates from https://github.com/scottjehl/picturefill/releases/tag/2.3.1 ([full story](https://css-tricks.com/please-update-picturefill)).
# Testing

@ScottPainterGNM – screenshot smoke tests [seems ok](https://www.browserstack.com/screenshots/4d69cf92af61b6941a0850cd78718648addeba67), but a quick browser check would be useful, namely just that:
- [x] images appear as normal on fronts

### CODE REVIEW

**Comment by ScottPainterGNM** [comment]
I'll take a look!

**Comment by gklopper** [comment]
:+1:

**Comment by ScottPainterGNM** [comment]
Checked across most popular browsers across network/section/tagged fronts and the different territories and all images displaying as expected. QA :+1:

**Comment by sndrs** [comment]
thanks @ScottPainterGNM - probably a bit late to merge this now, but will 1st thing on monday when I'm back (if anyone else wants to before then, go for it)

**Pull request merged**
