### PR TITLE
Fallback for immersive interactives for core & no js users

### PR DESCRIPTION
**Pull request by holder-josh**
If you currently try to load an 'immersive' interactive whilst opted in to the Core site, you get a blank page:

screen shot 2015-09-16 at 17 50 55

With these changes it'll put the 'content' field of the Interactive embed into an article looking page for Core and no JS users:
screen shot 2015-09-16 at 17 53 29

I'll test this on a wide variety of interactives before merging and speak to Visuals regarding the changes.

This also tweaks the styling of the non-immersive interactive template for non-js/core users, but only so that it matches the above screenshot.

Q: Do we need to explain to users that they're seeing a stripped back view?

### CODE REVIEW

**Comment by paperboyo** [comment]
Wow. That’s so good for _so many reasons_! :gem: 

> Q: Do we need to explain to users that they're seeing a stripped back view?

I would say: yes.

**Comment by rich-nguyen** [comment]
looks good. For javascript and modern browsers, how many times is the content loaded?

**Comment by Jholder112233** [comment]
@rich-nguyen There's no change in the number of times the content is loaded, it's just now being cleaned out of the noscript tags we get from CAPI so that Core users can see it too, then it's styled up. The initial payload always had the raw content for SEO reasons.

In my experience, the interactive's boot.js would generally load fresh content from a Google Sheet, but that's down to each interactive.

**Comment by stephanfowler** [comment]
:+1: great

Let's separately think about how interactives _could_ be booted by core users, manually. Maybe move the boot logic out of isModernBrowser and inject a "run the interactive" button that's only visible in core..?

**Pull request merged**
