### PR TITLE
monitor whether people print our stuff

### PR DESCRIPTION
**Pull request by johnduffell**
Someone emailed userhelp to say an article didn't print correctly (missing sections). I investigated and also noticed if you print landscape the sides were cut off.  It's great that we have a print stylesheet, but it seems like it isn't the most loved part of our site.  But should we be caring more?

After some questions, it turns out no-one really knows whether users are printing much, and if that, what they are printing.  So I decided to get coding...

So I have put in a small beacon to detect if people change the stylesheet to the "print" one, which should be a reasonable approximation.  This isn't supported on ie9 but most other things can handle it.

If there are a lot, we can try to break it down by page type - I can imagine recipes and sudokus are more heavily printed than the network front.

### CODE REVIEW

**Comment by piuccio** [comment]
:+1: if only it wasn't conflicting :wink:

**Comment by phamann** [comment]
:-1: I'm concern with the amount of custom cloudwatch metrics we are starting to use, as these are very expensive. For something like this that doesn't need accurate real-time measurement can you not just use omniture for this?

**Comment by phamann** [comment]
As discussed you can use our built in navigation interaction tracking here:
https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/analytics/omniture.js#L326

**Comment by johnduffell** [comment]
thanks, that's very useful info! will update... cheers

**Pull request closed without merging**
