### PR TITLE
show locale timezone against football fixture kick-off times and match days

### PR DESCRIPTION
**Pull request by GHaberis**
It had been reported that the football fixtures page was confusing for users not within the GMT timezone. This is because matches are grouped (server side) into match days and the match day displayed is the GMT date (although this isn't stated anywhere). Kickoff times are however updated to the local timezone (client side). The match day and kick off time using different timezones and not stating which zone they were using caused confusion.

This PR adds the locale timezone code against the match day and the kick-off times.

## What does this change?

Adds the locale timezone code against the match day and the kick-off times.

## What is the value of this and can you measure success?

Provide more info to users about dates to avoid confusion.

## Does this affect other platforms - Amp, Apps, etc?

No

## Screenshots

Before desktop

picture 46

After desktop

picture 45

Before mobile

picture 47

After mobile

picture 48

## Tested in CODE?

No

### CODE REVIEW

**Comment by GHaberis** [comment]
@guardian/dotcom-platform if anyone can take a look at this that'd be great, thanks!

**Comment by SiAdcock** [comment]
Looks good to me. Is it worth adding a JS unit test?

**Comment by GHaberis** [comment]
@SiAdcock thanks! yep I'm happy to add some tests around the changes to relativedates.js.

**Comment by GHaberis** [comment]
@SiAdcock i've put some new unit tests in around relativeDates.

**Review by SiAdcock — APPROVED** [review]
Nice 👍

**Comment by SiAdcock** [comment]
All nice, except SASS lint error causing failing build 😅

**Comment by NataliaLKB** [comment]
@GHaberis Hey! Is this ready to be merged in soon?

**Comment by GHaberis** [comment]
@NataliaLKB yes it's ready to go but I need to look at the failing check!

**Comment by GHaberis** [comment]
@NataliaLKB sass validation error has been fixed so merging this now

**Comment by NataliaLKB** [comment]
Great! Thanks @GHaberis :)

**Pull request merged**
