### PR TITLE
Improve tab order for edition picker

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

- Moves the edition picker in the DOM to better reflect its visual position.
- Adds outline on focus for consistency with other links and buttons in the header

## Screenshots

dec-11-2018 11-23-53

## What is the value of this and can you measure success?

Currently the tab order of the header is:

1. Skip to main content
2. Banner ad
3. Edition picker
4. Logo

This doesn't reflect the visual structure of the page, making the tab order surprising.

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [x] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by NataliaLKB — APPROVED** [review]
Makes sense! If you haven't already, check what happened with no JS before merging.

**Review by GHaberis — APPROVED** [review]
👍

**Comment by SiAdcock** [comment]
@NataliaLKB good consideration! I just tested and it works fine. I'll merge tomorrow.

**Comment by NataliaLKB** [comment]
Awesome! 🚢

**Pull request merged**
