### PR TITLE
Remove unused JS modules

### PR DESCRIPTION
**Pull request by gtrufitt**
## What does this change?

Removes the following modules that aren't imported into the application anywhere:

- content-websocket
- sticky-social
- socially-referred-burners
- social-most-popular
- track-ad-load ( @regiskuckaertz this isn't used elsewhere is it?)
- take-while
- filterPairs
- date-formats
- subsciber-number-form
- history-containers 

## What is the value of this and can you measure success?

Less files to convert.

## Does this affect other platforms - Amp, Apps, etc?

No.

## Tested in CODE?

No.

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
@gtrufitt nope 👍  don't you remove them from the `es5toes6` map too?

**Comment by gtrufitt** [comment]
> don't you remove them from the es5toes6 map too?
Yup, will do now

**Review by gu-stav — APPROVED** [review]
🚀 🔥 LGTM

**Review by sndrs — APPROVED** [review]
🔥 🔥

**Comment by sndrs** [comment]
> don't you remove them from the es5toes6 map too?

we can regenerate that when we're ready to open it up. i guess a lot things may change before then

**Pull request merged**
