### PR TITLE
Remove eval and simplify font loading

### PR DESCRIPTION
**Pull request by mchv**
## What does this change?

The associated change are removing the use of `eval` to load fonts. I think the usage is absolutely not needed as we could simply rely on `JSON.parse` because the `guFont` fonction only return `css` property.

I don't think interactives are directly relying on this, but I may be wrong.   

@sndrs 

## Does this change need to be reproduced in dotcom-rendering ?

- [X] No

## What is the value of this and can you measure success?

Stop using `eval` which is considered dangerous, as well as improving performances.  

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [X] No

### Does this change break ad-free?
- [X] No

### Does this change update the version of CAPI we're using?
- [X] No, all the existing database files are just fine

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by sndrs — APPROVED** [review]
yeah _much_ nicer

afaik nothing else uses this endpoint, but i'm not 100% certain

@gtrufitt anything else you can think of?

**Comment by gtrufitt** [comment]
Yeah, this makes sense to me.

This does look like as if it is built into the [previous interactive atom template](https://github.com/guardian/interactive-atom-template-DEPRECATED/blob/6d102ca6d9ff443100780ec7ea5869da7e4cd9f0/harness/blank.html#L55) though. So lots of existing atoms out there use the `eval` approach to get fonts...

The new template doesn't seem to use it, so that's a positive.

**Comment by mchv** [comment]
@gtrufitt I think this is just `harness` part of the template, which is used to test locally in development mode when working on the `atom` but not used once the atom has been published.

**Comment by gtrufitt** [comment]
> @gtrufitt I think this is just `harness` part of the template, which is used to test locally in development mode when working on the `atom` but not used once the atom has been published.

Ah yes, you're right, that's good news then!

**Review by gtrufitt — APPROVED** [review]

**Comment by mchv** [comment]
I have test that it works locally so merging now.

**Comment by paperboyo** [comment]
Hi. No idea if this is related, really: none. But it’s the first time in years, that reloading a front or changing it or coming back from an article to it, I see a FOUC… In case this is unrelated, I apologise, but something has changed (latest Firefox and Chrome betas on Windows).

**Comment by paperboyo** [comment]
For the record, I cannot repro the above FOUC in neither browser…

**Pull request merged**
