### PR TITLE
Playable liveblogs: more text in update

### PR DESCRIPTION
**Pull request by stephanfowler**
- Animate a single 3-line liveblog update
- Keep the trailtext
- Don't add to small ("list item") card sizes 
- Fixed position ellipsis, with "fade under" effect

liveblogs-v2

### CODE REVIEW

**Comment by johnduffell** [comment]
:+1: see what you mean about the design love needed, maybe if the ellipsis is hard we need to find another way to show that it's not a complete sentence e.g. fading away

**Comment by uplne** [comment]
Add some width, height and background color matching the bg color of update to the `:before` so it will overlay the text

**Comment by stephanfowler** [comment]
Awaiting sign-off from editorial...

**Comment by gklopper** [comment]
>Awaiting sign-off from editorial...

Who signs off? Surely it can't take this long.

**Comment by stephanfowler** [comment]
+adding Piers and Theresa


On 3 June 2015 at 11:03, Grant Klopper <notifications@github.com> wrote:

> Awaiting sign-off from editorial...
>
> Who signs off? Surely it can't take this long.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9253#issuecomment-108284541>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by stephanfowler** [comment]
Signed off.

On 3 June 2015 at 15:01, Stephan Fowler <stephan.fowler@theguardian.com>
wrote:

> +adding Piers and Theresa
>
>
> On 3 June 2015 at 11:03, Grant Klopper <notifications@github.com> wrote:
>
>> Awaiting sign-off from editorial...
>>
>> Who signs off? Surely it can't take this long.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/guardian/frontend/pull/9253#issuecomment-108284541>.
>>
>
>


-- 
Theresa Malone
Assistant digital editor
theguardian.com
@tmalone <https://twitter.com/tmalone>
020 3352 3824

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by paperboyo** [comment]
Hello,

Super-tiny thingy. Tested in Chrome and Firefox. At zoom levels different than 100% the next line is showing up severely truncated like so (FF, 133% zoom):

liveblog playable

Regards
Mateusz

**Comment by paperboyo** [comment]
Hmmm, also something is not entirely kosher with that "fade under" effect...

hmm

**Comment by stephanfowler** [comment]
https://github.com/guardian/frontend/pull/9646 fixes this:


> Super-tiny thingy. Tested in Chrome and Firefox. At zoom levels different
> than 100% the next line is showing up severely truncated like so (FF, 133%
> zoom):
>
> [image: liveblog playable]
> <https://cloud.githubusercontent.com/assets/6032869/8180516/5594190a-1416-11e5-907c-9bcfd2f8e868.jpg>
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
