### PR TITLE
ES6 convert acquisitions epic tests

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

Converts remaining acquisition epic tests to ES6

### CODE REVIEW

**Comment by SiAdcock** [comment]
FYI @guardian/contributions

**Comment by joelochlann** [comment]
Hey @SiAdcock, I've made some changes on master which will make it hard for you to resolve these conflicts - but I know what to do so I'll clean it up now!

**Comment by SiAdcock** [comment]
Oh wow, thanks @joelochlann!

**Review by joelochlann — APPROVED** [review]
Great stuff! Thanks a lot for doing this

**Comment by SiAdcock** [comment]
Awesome, thanks so much for fixing those conflicts! 🎉

**Pull request merged**
