### PR TITLE
Remove notification call

### PR DESCRIPTION
**Pull request by gtrufitt**
Bug - Notification CTA showing on all liveblogs

### CODE REVIEW

**Comment by johnduffell** [comment]
tricky one! :+1: good work

**Comment by OliverJAsh** [comment]
Static typing would have saved us ;-)

**Comment by jennysivapalan** [comment]
@OliverJAsh this has become your mantra!

**Comment by johnduffell** [comment]
@OliverJAsh :heart_eyes: static typing :stuck_out_tongue:

**Comment by gtrufitt** [comment]
I'm beginning to come around to the idea :laughing:

**Pull request merged**
