### PR TITLE
Use thumbnail image in hosted content trails

### PR DESCRIPTION
**Pull request by kelvin-chappell**
This reduces the size of images used in hosted content trails, to give quicker and smaller downloads.  Trails in amp pages are also reduced in size.

Eg. 
Before:
image

After:
image

### CODE REVIEW

**Comment by paperboyo** [comment]
Is there a reason we are not using the normal image pipeline here (mediaservice's master asset>image resizer>optimised image at the exact dimensions needed+possible HiDPI version)?

**Comment by kelvin-chappell** [comment]
@paperboyo We're trying to keep the model for hosted content simple and completely separate from everything else, but there's no particular reason why images should be handled differently.  It's just getting access to the image-handling templates involves coercing the model into a different shape.  I'll have a look at the feasibility of it.

**Comment by paperboyo** [comment]
Thanks! It’s just from imaging POV, mediaservice’s own pre-optimised crops (shown in above screenshot) provide much less choice of sizes, file formats and aren’t as optimised as via the proper route. They risk looking sub-standard especially next to beutiful HiDPI dotcom imagery.

But if have no access to dotcom’s image pipeline, it may indeed be quite a challenge, I presume...

**Review by lps88 — APPROVED** [review]
Looks good

**Comment by kelvin-chappell** [comment]
[Reduce size of trail images in hosted content](https://trello.com/c/9Pt3bQcq/98-reduce-size-of-trail-images-in-hosted-content)

**Pull request merged**
