### PR TITLE
Remove whitelist for articles on DCR

### PR DESCRIPTION
**Pull request by MatthewJWalls**
## What does this change?

Removes whitelist from the Article Picker.

Note that there is already a feature switch in place, so we can still turn DCR off (since there is no picker for AMP, this will *only* turn off the article picker).

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/master/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by shtukas — APPROVED** [review]

**Comment by gtrufitt** [comment]
We should build in tone/news to 'supported' I guess and the A/B test?

**Comment by nicl** [comment]
@MatthewJWalls @gtrufitt yep news tone was added a short while ago. I'll look into adding the a/b test today!

**Comment by nicl** [comment]
@gtrufitt and @MatthewJWalls have added code for the AB test:

* the experiment definition itself
* an `abTests` field to the data model sent to DCR so that we can add it to the client-side config object there, which the Ophan tracking script can then pick up

**Comment by MatthewJWalls** [comment]
@nicl changes look good, if you're happy with with we can merge

**Comment by nicl** [comment]
Update, the relevant JS code here to capture this is: https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/experiments/ab-ophan.js#L89.

**Pull request merged**
