### PR TITLE
removing quote icons that appear not to be used

### PR DESCRIPTION
**Pull request by NataliaLKB**
Another PR with icon deletions. This one for quote icons. Again, these don't seems to be used anywhere on the site. 

Note that these quotes ...
image

... have already been turned into an inline-svg and therefore not effected.

See issue #10241 for more details.

### CODE REVIEW

**Comment by davidrapson** [comment]
Build's failing, but looks unrelated. Nice cleanup work though :+1: couple more of these and you'll have a negative commit ratio–which is something to be envied!

**Comment by NataliaLKB** [comment]
@davidrapson Thats my goal!

**Comment by davidrapson** [comment]
Good luck! I want to know how @rich-nguyen managed to get -1M, that's who you need to beat.

screen shot 2015-08-25 at 16 32 52

**Comment by NataliaLKB** [comment]
:dizzy_face: amazing. @rich-nguyen  :clap:

**Comment by NataliaLKB** [comment]
All tests pass, merging!

**Comment by paperboyo** [comment]
On an unrelated note, that icon is broken for years... https://github.com/guardian/frontend/issues/7263#issuecomment-64241581

17babbf0-7409-11e4-8fc7-b5df9303a9b6


I'm more than happy to edit SVG, but do not have the source and it's all inlined now, so I would have to make sure I'm not breaking something. If someone would be willing, I'm game!

**Comment by NataliaLKB** [comment]
@paperboyo very happy to take a look at this. In this situation I would probably use [this quote svg](https://github.com/guardian/frontend/blob/master/static/src/inline-svgs/icon/quote.svg) instead of the [quote mask](https://github.com/guardian/frontend/blob/master/static/src/images/global/quote-mask.svg) (outline). It would prevent this sort of colour bleed.

**Comment by paperboyo** [comment]
Thanks, @NataliaLKB! Makes sense. Sent email.

**Pull request merged**
