### PR TITLE
Cutout images should be displayed behind text

### PR DESCRIPTION
**Pull request by JustinPinner**
I've opened this PR just for some feedback at this stage. It's not necessarily ready to be merged yet.

The issue of Frankie Boyle's coffee mug (https://github.com/guardian/frontend/issues/8935) caused us to to reconsider how we layer text and images on the fronts, and this is the result (I've forced the images to be further to the left than usual for the purposes of these screen caps);

screen shot 2015-04-24 at 15 11 54

screen shot 2015-04-24 at 16 35 22

### CODE REVIEW

**Comment by paperboyo** [comment]
Hi,

Yeah - looks bad either way :laughing:

But, since it was my idea (just like Windows 7), I think I agree with myself that readability first...

(Related https://github.com/guardian/frontend/issues/7552).

Regards
Mateusz

**Comment by piuccio** [comment]
Is this on any breakpoint?
On desktop if you move the mouse over the headline it's underlined and the class `u-faux-block-link--hover` is not applied to the parent element

**Comment by JustinPinner** [comment]
@piuccio This is mainly an issue on mobile breakpoints. The problem was that you couldn't see all the headline text when an image runs over the headline's space. Are you saying that the change to the z-index has stopped the `u-faux-block-link--hover` from working?

**Comment by piuccio** [comment]
yes.
Maybe it should be limited only to mobile breakpoints

**Comment by JustinPinner** [comment]
@paperboyo has raised a few issues concerning cut-outs and text layering. Maybe @uplne's proposed z-index named band changes (https://github.com/guardian/frontend/pull/9061) will help us settle this down and fix it all in one go?

I think I'll close this PR in the meantime. We can re-open it if we think the minor tweaks it contains are worthwhile in isolation.

**Pull request closed without merging**
