### PR TITLE
Use slim header for Identity pages

### PR DESCRIPTION
**Pull request by marchibbins**
Implements global `header` and `main` for Identity pages, doing away with `identityMain` and `identityHeader` and the maintenance headache along with it.

Had a back and forth on our team whether `hasSlimHeader` and `shouldHideAdverts` could move to `Page` rather than `Metadata`/`Content`, since Identity pages aren't "content" and the ad containers are served on all "pages" regardless. This seemed to be the simplest implementation, short of matching against `IdentityPage` rather than "section" as I have done (which would require importing from the Identity app).

### CODE REVIEW

**Comment by phamann** [comment]
:+1: Awesome sauce. Nice +/- ratio too.

**Comment by phamann** [comment]
Screenshot?

**Comment by marchibbins** [comment]
Screenshot!

image

Waiting for thumbs up from @jamesoram's testing.

**Comment by phamann** [comment]
Fresh!

**Comment by gklopper** [comment]
:+1:

**Comment by marchibbins** [comment]
Update on this, @jamesoram wants to test this on Identity CODE but we can't get a successful build due to out of date switches in `master`. Once those are resolved he'll run his tests and we'll get this up.

**Comment by jamesoram** [comment]
:+1:

**Pull request merged**
