### PR TITLE
Remove grunt karma

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?
- remove karma from grunt, and update karma deps
- remove a lot of deps which seem to be historical (no refs to them in the code, don't prevent tests from running)
- removes `grunt coverage`, since it's not actually being called by anything, and adds `make coverage`

## What is the value of this and can you measure success?

clearing out grunt, basically. not advocating no coverage, just this is not being used currently and requires grunt, so we don't really want this version, at the very least
## Does this affect other platforms - Amp, Apps, etc?

no
## Request for comment

@guardian/dotcom-platform @rich-nguyen

### CODE REVIEW

**Comment by NataliaLKB** [comment]
Hey @sndrs . This is amazing to clean this all up! Super impressed by the number of lines deleted.
I pulled down this branch to test things out and ran `make reinstall` and then this:

image

Should I be expecting more detail?

**Comment by sndrs** [comment]
hmmm, yeah ideally!

not sure how you've got there... if you run `./tools/run-task test --verbose`, what do you get?

**Comment by piuccio** [comment]
Adding coverage was my first PR! 

You can also remove the coverageReporter from this file https://github.com/guardian/frontend/blob/master/static/test/javascripts/conf/settings.js

**Comment by sndrs** [comment]
> Adding coverage was my first PR!

I remember that actually!

it's not going for good, just from grunt :)

maybe i'll add to `make` actually

think plan is to move to jest if possible, one reason for which is the baked in coverage report

**Comment by sndrs** [comment]
@NataliaLKB

>Should I be expecting more detail?

I hope that #14821 will deal with the feedback

**Comment by NataliaLKB** [comment]
Thanks @sndrs !

**Comment by NataliaLKB** [comment]
other than the merge conflict, this lgtm 👍

**Comment by sndrs** [comment]
@piuccio `grunt coverage` > `make coverage` :)

**Comment by sndrs** [comment]
@NataliaLKB if you get a sec, do you still get that error? i cannot recreate it locally...

**Comment by NataliaLKB** [comment]
@sndrs no I don't get the error anymore! It looks much better. Thank you :)

**Review by NataliaLKB — APPROVED** [review]

**Comment by rich-nguyen** [comment]
looks good 👍

**Pull request merged**
