### PR TITLE
Add Omniture prop21: list of components on the page

### PR DESCRIPTION
**Pull request by OliverJAsh**

### CODE REVIEW

**Comment by gklopper** [comment]
I think there is a 255 character limit to props. Could you run that by Matt Kopka?

**Comment by crifmulholland** [comment]
Hmm, actually it's a 100 char limit; I forgot about that. That's not going to work. 

We'll need to use s.list 2 variable instead. I've confirmed with Matt K.

C

**Comment by OliverJAsh** [comment]
Updated. Can I get a :+1: please? :smile:

**Comment by gklopper** [comment]
Why not :+1:

**Pull request merged**
