### PR TITLE
Add helper for async tests using promises

### PR DESCRIPTION
**Pull request by OliverJAsh**
Updated some tests as an example.

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Thoughts @piuccio @sndrs @rich-nguyen?

**Comment by piuccio** [comment]
I don't like much creating new globals and wrapping jasmine, although I did it myself in facia-tool with a `test` function and I kinda regret it. It's less readable, other people might not be aware of this implementation.

However it's a huge shame that jasmine does not support promises as well as mocha. I'd prefer to push changes in jasmine. Remember when async in jasmine was just horrible (`runs` and `waitFor`)? Eventually they fixed it.

I'll give a +0.5, if it's fine for others, merge it, but I don't think I'll use it.

**Comment by rich-nguyen** [comment]
I agree with @piuccio

**Comment by OliverJAsh** [comment]
By the sounds of https://github.com/jasmine/jasmine/issues/681, they're really set on not adding support for it. We can wait but it might never happen!

**Pull request closed without merging**
