### PR TITLE
Dcr ads css bundle

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

Bundling of commercial css to Dotcom Rendering

## Does this change need to be reproduced in dotcom-rendering ?

- [ ] No
- [X] Yes (please indicate your plans for DCR Implementation)

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [x] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [x] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/master/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by mxdvl** [comment]
Following discussion with @shtukas & @ioanna0, this change should be integrated in PROD for testing in DCR.

**Comment by mxdvl** [comment]
@GHaberis can you please review the Webpack bundling?

**Review by shtukas — APPROVED** [review]

**Review by gtrufitt — CHANGES_REQUESTED** [review]
Hello! Pinged in chat, but would be good to chat further about the problem you're trying to solve here as this is against one of the core goals of DCR.

**Comment by mxdvl** [comment]
As discussed, we will inject required CSS via JS: https://github.com/guardian/frontend/pull/22751

**Pull request closed without merging**
