### PR TITLE
Restrict `outstream` ad sizes to `inline1` slots

### PR DESCRIPTION
**Pull request by simonbyford**
## What does this change?

Restrict `outstreamDesktop` and `outstreamGoogleDesktop` ad sizes to `inline1` slots instead of _all_ inline slots.
 
Also, remove references to the `video`  ad size as it has been removed: https://github.com/guardian/commercial-core/pull/527

## Does this change need to be reproduced in dotcom-rendering ?

- [x] Not exactly, but there is a related change here: https://github.com/guardian/dotcom-rendering/pull/4408
- [ ] Yes 

## What is the value of this and can you measure success?

Serving wide ads in `inline2+` slots was causing display issues. This hopefully fixes the problem.

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by ashishpuliyel — APPROVED** [review]
Nice. Thank you @lucymonie for your help with this one.

**Comment by arelra** [comment]
Do we need to remove any decoration from `render-advert.ts`? For example:

https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/commercial/modules/dfp/render-advert.ts#L117

**Comment by simonbyford** [comment]
> Do we need to remove any decoration from render-advert.ts? For example:
> 
> https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/commercial/modules/dfp/render-advert.ts#L117

I have done @arelra 🙂 

https://github.com/guardian/frontend/pull/24812/files#diff-abb04b5b6a931e5a0b5437434adb4a443063b13dfd84eaaf74950031ac6cf128

**Comment by arelra** [comment]
> > Do we need to remove any decoration from render-advert.ts? For example:
> > https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/commercial/modules/dfp/render-advert.ts#L117
> 
> I have done @arelra 🙂
> 
> https://github.com/guardian/frontend/pull/24812/files#diff-abb04b5b6a931e5a0b5437434adb4a443063b13dfd84eaaf74950031ac6cf128

Doink! Great thanks :)

**Pull request merged**
