### PR TITLE
 use thumbnail for media atom poster image when main media

### PR DESCRIPTION
**Pull request by akash1810**
## What does this change?
This is a request from Editorial with the following use-case:
- We have a match report video about player A vs player B and the thumbnail is A v B.
- We then have an article about player A which isn't primarily about the match.
- We want to embed the video in this article, however the thumbnail doesn't exactly match the tone of the article.
- Use the article's thumbnail image instead, which is typically more relevant

Also removes the `YouTubePosterOverride` switch. It's always on, so no longer needed.

## Screenshots
(these don't exactly match the use-case described above...)

From https://www.theguardian.com/football/2018/nov/04/kasper-schmeichel-cardiff-match-like-cup-final-leicester that's using this video - https://www.theguardian.com/football/video/2018/nov/04/leicester-city-players-attend-vichai-srivaddhanaprabhas-bangkok-funeral-video

### Before
image

### After
image

## What is the value of this and can you measure success?
Since moving to Atoms, the multimedia team have commented that they're reluctant to use videos in main media as it makes the content look stale. This is because an Atom only has 1 image.

Before Atoms, it was possible to set a different image for a video on each use. This change is bringing that functionality back.

## Checklist
- [x] Demo to Editorial
- [ ] ???
- [ ] Profit

### Does this affect other platforms?

- [ ] AMP 
- [x] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [x] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Accessibility test checklist

- [x] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [x] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [x] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [x] On CODE (optional)

### CODE REVIEW

**Comment by paperboyo** [comment]
That’s very interesting and the need for it (or something akin) is clearly explained and well reasoned. I just wonder:
- is there any control over this behaviour or is it automagic and applied to all, always?
- if there is control, are the overrides visible in atom usages in MAM?
I’m just thinking hard and failing to come up with examples where it might not be what we (all) want. (which may mean this is just very sensible!)

**Comment by akash1810** [comment]
> is there any control over this behaviour or is it automagic and applied to all, always?

There's control insofar as you can choose the article thumbnail in Composer. You can't opt out of this behaviour - you can, however, use the same image in the thumbnail to that of the Atom.

> if there isn’t control, does this mean that Main Imge (Youtube poster) field in MAM is now only applied to Youtube and the Composer video page?

In body embeds get the Atom image too. The override only applies to fronts and, with this change, main media.

**Comment by akash1810** [comment]
Essentially, this is graduating [this PR](https://github.com/guardian/frontend/pull/15916) to main media elements too. The UX is slightly better (no flicker) as we've moved to loading the player on click rather than on page load.

**Review by jukecraft — COMMENTED** [review]
As discussed in person, only minor comments:

- removing the `YouTubePosterOverride` feature toggle is mixed in with the change here
- unclear what happens with `!playable` in `youtube.scala.html`

**Review by NataliaLKB — APPROVED** [review]
Code looks good!

**Comment by akash1810** [comment]
> removing the `YouTubePosterOverride` feature toggle is mixed in with the change here

Just noticed that change is in its own commit. Can we be lazy and say that's good enough? If we want to add the switch back in, we can revert that commit... 🤞 🙏 

> unclear what happens with `!playable` in `youtube.scala.html`

This looks to be the only use of this property - https://github.com/guardian/frontend/blob/master/common/app/views/fragments/items/facia_cards/contentCard.scala.html#L140. This is for Fronts - you can choose to disable inline video playback on fronts.

I've tested it in DEV and the feature still works... so I'm not entirely this check was doing anything...

**Pull request merged**
