### PR TITLE
Implement heading block elements (dotcom-rendering)

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

The current implementation of `TextBlockElement` doesn't really care what HTML element it takes. Most instances of `TextBlockElement` are `<p>` tags. But some articles ([example](https://www.theguardian.com/crosswords/crossword-blog/2019/feb/04/meet-the-setter-cullen-smurf)) split the text content into sections using `<h2>` elements. As a result the `<h2>` elements are also `TextBlockElements`.

This change casts `<h2>` elements as newly-defined `HeaderBlockElement`s. 

As a side effect, it removes the wrapper tag from `HeaderBlockElement` and `TextBlockElement`

**Before**

```json
{
  "elements": [
    {
      "html": "<p>Lorem ipsum</p>",
      "_type": "model.dotcomrendering.pageElements.TextBlockElement"
    },
    {
      "html": "<h2>Dolor sit alor</h2>",
      "_type": "model.dotcomrendering.pageElements.TextBlockElement"
    }
  ]
}
```
**After**

```json
{
  "elements": [
    {
      "html": "Lorem ipsum",
      "_type": "model.dotcomrendering.pageElements.TextBlockElement"
    },
    {
      "html": "Dolor sit alor",
      "_type": "model.dotcomrendering.pageElements.HeadingBlockElement"
    }
  ]
}
```

I'm open to suggestion on:

- whether the removal of wrapper elements is a good thing
- the naming
- how to improve the horrible imperative Scala
-  whether this whole thing is even a good idea at all

## What is the value of this and can you measure success?

In `dotcom-rendering` (AMP), we insert ads between `TextBlockElements`. However it is undesirable to add an ad immediately after a `<h2>`. By casting `<h2>`s as a newly-defined `HeadingBlockElement`, all our problems are solved.

In the future, we could possibly do _other things_ with the `HeadingBlockElement` in `dotcom-rendering`.

### Does this affect other platforms?

We'll need to update dotcom-rendering to account for `HeadingBlockElement`s before we merge this change

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by nicl** [comment]
Hmm, this is interesting! I haven't really looked at the code so just thoughts on the approach here:

I really like:

* introducing custom element types to model things better/make our lives easier

I'm not sure about:

* how deep is the rabbit hole?

I.e. text block elements are p's yep, but I'm not sure how much other markup they can contain - I'm guessing quite a lot. Do we special case this h2 type because it helps with ads, and then ignore other versions of paragraphs?

**Comment by SiAdcock** [comment]
> I'm not sure how much other markup they can contain

We could potentially find that out. But perhaps `<h2>` should be the special case and everything else remains a `TextBlockElement` until we have a reason for it to be a custom element? It's worth flagging that this change sets a precedent, that this approach is Okay By Us™️.

> do we want to respect the precise markup of the tools here

On reflection I think we do for now. If Composer is sending us non-semantic markup then extracting inner HTML is not going to save us as the inner HTML might contain non-semantic markup. In my mind it's better to try to fix this in Composer rather than re-abstracting / cleaning it in frontend or DCR.

**Comment by nicl** [comment]
Thanks @SiAdcock. Just a couple more thoughts:

* should we give the element a more specific name? It will be difficult to introduce other header type elements in the future with this/unclear what they mean.

* re respecting markup, I really meant if we abstract h2's here into an element, there's nothing preventing us serving them as h3s (etc.) in DCR. We can try and keep them the same, but it's a discipline-based approach.

**Comment by AWare** [comment]
I think it might be right to take this as an opportunity to inline `Cleaner.split` or to change it to output the type of the element. I guess this will also impact https://github.com/guardian/frontend/pull/21148 which I'll rewrite when you merge this.

**Comment by SiAdcock** [comment]
@nicl 

> should we give the element a more specific name

Good point. Composer calls this "subheading", so maybe we should follow this with `SubheadingBlockElement`?

> if we abstract h2's here into an element, there's nothing preventing us serving them as h3s 

True. In Composer, the icon for this element is literally a big bold H2, which seems to convey the intent to the author.

screen shot 2019-03-06 at 14 23 40

Might this introduce the possibility for inconsistency, or generating unexpected markup? Happy to discuss though, I don't hold a strong opinion here.

**Comment by gtrufitt** [comment]
+1 on this. More structure is always going to be a good thing IMO.

- `SubheadingBlockElement` sounds good, maybe we could talk to Ed Tools/ CAPI people about their conventions for Thrift naming conventions
- The h2/h3 thing I don't think is a major concern - that's on Composer for painting `h2` on a 'button' but it's up to the platform to defined the most semantic markup.

My reservation is - should we even be doing this here? It feels like something that is probably useful across platforms so should it be pushed up stream to flexContent or CAPI? Maybe @RichieAHB @regiskuckaertz have thoughts.

**Comment by regiskuckaertz** [comment]
First off, great work @SiAdcock ❤️  My only recommendation would be to try and avoid parsing the html twice (once in `Cleaner.split`, another in `replaceLinksInElement`). It would be a fun exercise to write a backtracking parser around that ugly `Jsoup` to remove that "imperative style".

I echo @gtrufitt 's thoughts, headings come in many different flavours and right now, the only way to customise them is to let go of Composer entirely and create an interactive 😱 It's probably out of scope for this PR, but indeed as I'm thinking about the future of CAPI it seems like an interesting use case. Perhaps they deserve an [`ElementType`](https://github.com/guardian/content-api-models/blob/master/models/src/main/thrift/content/v1.thrift#L40) of their own, after which both journalists/designers upstream and dotcom/apps downstream can enjoy more freedom and control.

**Review by AWare — APPROVED** [review]
While it would be great for headings to be modeled in CAPI, I think this is a really useful step forwards. 

I think @regiskuckaertz has a super good point about figuring out a better way to work with JSOUP. But I think the current multiple instantiations of JSOUP to avoid leaking its ugly types is a fairly happy medium- otherwise we'd need to put quite a lot of actual design work into the cleaners.

**Comment by AWare** [comment]
And sort of further, if we find any more surprises in `TextBlock` we should probably keep extracting them as their own blocks. And then moving that logic up the stack as time etc allows.

**Comment by gtrufitt** [comment]
Think these are fair points - lets make sure we document and share that document widely (Ed tools and CAPI!) so they can think about it too!

**Comment by SiAdcock** [comment]
Thanks for your thoughts @aware, @gtrufitt and @regiskuckaertz. Definitely keen to push this and any other useful elements we discover further up the stack, when we have more experience using them. We have some documentation of [the elements that dotcom-rendering supports](https://github.com/guardian/dotcom-rendering/tree/master/docs/elements), although these probably need reviewing. There's a [Trello card](https://trello.com/c/EgwkIG8Z/488-tidy-up-element-documentation) to do this.

>  lets make sure we document and share that document widely (Ed tools and CAPI!) so they can think about it too!

👍 And apps too!

**Comment by RichieAHB** [comment]
Just chiming in here after the merge 😑 I think composer could (and hopefully will) do a lot better here. There’s nothing stopping us adding headings of any kind right now to the content.

I’m not sure they deserve an ElementType of their own as in future it’s our aim to have one consistent structured, nestable data model. Creating headings as an ElementType would restrict our modelling of headings to the top level of our model.

That said, there’s probably a lot more to discuss here and I may be missing some clarity.

Ultimately the quicker we move away from HTML as a model, the better. One of our short term plans is to add more noting-like features to compose (“web only” and “print only tags”). The way HTML models white space is already causing problems with notes that include spaces at the end of them which are then being removed.

I feel like our modelling of our text content is something that is well worthy of discussion soon!

Other than that, nice work!!

**Pull request merged**
