### PR TITLE
Amp styling

### PR DESCRIPTION
**Pull request by NataliaLKB**
This PR containers:
- Breaking down the AMP styles into separate files
- Removing `development` attr for prod
- Reducing line height in standfirst:
  BEFORE 
  image

AFTER 
image
- Reducing margin around text, and removing margin on body images:

BEFORE
image

AFTER
image

cc @johnduffell

### CODE REVIEW

**Comment by paperboyo** [comment]
Would have to see it to believe myself, but I believe caption would look better aligned with text that has some margin than with the image that has none. I may be wrong, though.

**Comment by NataliaLKB** [comment]
@paperboyo like this:

image



I will update :).

**Comment by paperboyo** [comment]
Thanks, @NataliaLKB! It looks better IMHO.

**Comment by stephanfowler** [comment]
:+1: - esp the full bleed in-body images

**Comment by johnduffell** [comment]
great! just my comments about play.isdev on the development attribute and the scala.css extensions
:+1:

**Comment by NataliaLKB** [comment]
All tests and validation fine locally. Merging!

**Pull request merged**
