### PR TITLE
Add survey message to International Edition

### PR DESCRIPTION
**Pull request by robertberry-zz**
screen shot 2015-04-24 at 14 27 39

### CODE REVIEW

**Comment by phamann** [comment]
:+1:

**Comment by uplne** [comment]
Btw I've noticed this behaviour with buttons on mobile so it might be happening on this too.

**Comment by robertberry** [comment]
@uplne Hmm that's weird ... can you raise an issue? It'll be due to the length of the buttons I guess.

**Comment by uplne** [comment]
@robertberry I will do

**Pull request merged**
