### PR TITLE
Update switch around LiveBlogChromeNotifications

### PR DESCRIPTION
**Pull request by janua**
@gtrufitt Yeah yeah... :smirk:

### CODE REVIEW

**Comment by gtrufitt** [comment]
I would change the val - just for consistency with the rest of the test name references (unless you find a secret place that is used too...)

**Comment by gtrufitt** [comment]
Other than that 👍

**Comment by NathanielBennett** [comment]
:+1: How about changing the 'Owners' value as well. Anyone would think you're frightened of responsibility ...

**Comment by janua** [comment]
@NathanielBennett What are you on about? Nobody owns this anymore, and you **are** the person who worked on it.

**Pull request merged**
