### PR TITLE
Use UTC date string for Omniture prop7

### PR DESCRIPTION
**Pull request by robertberry-zz**
CC @gklopper @mkopka

### CODE REVIEW

**Comment by gklopper** [comment]
:+1:

**Comment by johnduffell** [comment]
does @mkopka want the time as well? I suspected not until I noticed in some old test data [here](https://github.com/guardian/frontend/blob/master/onward/test/resources/r2-business.html#L7229) it also has the time

**Comment by robertberry** [comment]
Oh. Dunno. I could just output the UTC string in that case

@mkopka it would look like 2015-05-26T16:34:45.010Z

**Comment by mkopka** [comment]
umm no just the date will suffice thanks

On 26 May 2015 at 17:35, Rob Berry <notifications@github.com> wrote:

> Oh. Dunno. I could just output the UTC string in that case
>
> @mkopka <https://github.com/mkopka> it would look like
> 2015-05-26T16:34:45.010Z
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9266#issuecomment-105595749>.
>



-- 
Thanks - Matt


(L)  0203 35 (33044)
(M) 07508 589 888

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by sndrs** [comment]
:+1:

**Pull request merged**
