### PR TITLE
Postponing ab-bolivian-wrestling-autoplay switch expiration

### PR DESCRIPTION
**Pull request by TBonnin**
## What does this change?

Postponing ab-bolivian-wrestling-autoplay switch expiration
## What is the value of this and can you measure success?

Build is green :green_heart:

### CODE REVIEW

**Comment by kelvin-chappell** [comment]
Weird! :+1:

**Comment by uplne** [comment]
It's being used in ab.js and main.js https://github.com/guardian/frontend/search?utf8=%E2%9C%93&q=BolivianWrestlingAutoplay

**Comment by uplne** [comment]
:+1:

**Comment by TBonnin** [comment]
You are right @uplne. Will ask @jamesgorrie later. I am just gonna postpone the expiration for now so build is green

**Comment by ScottPainterGNM** [comment]
@jamesgorrie is on leave today but might be worth catching up with @akash1810 regarding it today.

**Pull request merged**
