### PR TITLE
Increase identityLibVersion for new identity newsletter theRuralNetwork

### PR DESCRIPTION
**Pull request by QuarpT**
## What does this change?

Set identityLibVersion for new identity newsletter theRuralNetwork
see https://github.com/guardian/identity/pull/1954

## Does this change need to be reproduced in dotcom-rendering ?

- [X] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## What is the value of this and can you measure success?

The option for this newsletter appears on the /complete-consents page.

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]

**Comment by jfsoul** [comment]
I might be wrong but I believe this may no longer be necessary? There's now a scheduled job that periodically fetches newsletter metadata from the API. We removed releasing from the docs 
 to reflect that https://github.com/guardian/identity/blob/main/docs/adding-newsletters.md

**Comment by oliverlloyd** [comment]
Oh nice. We did discuss that it's preferable to do this via an api call - glad to hear we're closer on that then we thought!

**Comment by QuarpT** [comment]
> I might be wrong but I believe this may no longer be necessary? There's now a scheduled job that periodically fetches newsletter metadata from the API. We removed releasing from the docs
> to reflect that https://github.com/guardian/identity/blob/main/docs/adding-newsletters.md

Looks like it's still needed here https://github.com/guardian/frontend/blob/main/identity/app/controllers/editprofile/ConsentsJourney.scala#L120

but maybe it would only be a small task to replace this with the scheduled job

**Comment by QuarpT** [comment]
@jfsoul https://github.com/guardian/frontend/pull/24147

**Pull request merged**
