### PR TITLE
Remove epic for Brexit cohort

### PR DESCRIPTION
**Pull request by lmath**
## What does this change?
Removes the [special epic for the Brexit cohort](https://github.com/guardian/frontend/pull/17204).

## What is the value of this and can you measure success?
We're at the end of the window when these users should be seeing this epic, and so it should be removed because it's no longer relevant. 

## Does this affect other platforms - Amp, Apps, etc?
No. 

## Tested in CODE?

Apologies for the perhaps overenthusiastic cc-ing but @guardian/contributions helped me a bunch with the PR to add that epic and perhaps @guardian/membership-and-subscriptions @guardian/dotcom-platform have thoughts on whether the join date cookie should stay?

### CODE REVIEW

**Comment by jfsoul** [comment]
I would lean towards removing the join date cookie if it's no longer used.  Not only do we get to remove some code (and pre-empt everyone forgetting why it was there in the first place 😄 ), but some users tend to be a bit anti-tracking so less cookies can't hurt there either.

**Review by DiegoVazquezNanini — APPROVED** [review]
Thanks @lmath

**Comment by johnduffell** [comment]
I think our main problem is as far as I know we don't have any data to know if it was a success.  If it was a great success, we will definitely be doing it at the "trump bumps" and onwards.  If not, who knows.

But actually anyone working on the trump bump will be looking at these PRs to revert parts so maybe not a bad idea to revert.

**Comment by lmath** [comment]
OK thanks @jfsoul @DiegoVazquezNanini @johnduffell. I think it makes sense to remove the join date cookie since it's easy enough to re-add it if needed. 

Can one of you look at commit 4c593c4? Do I need to think more carefully about existing join date cookies?

**Comment by johnduffell** [comment]
there's some code somewhere for cleaning up old cookies to save bandwidth and not taking up too much space in the headers.  Although I forgot why we didn't use localstorage for this field in the end?

**Comment by lmath** [comment]
Do I need to consider anything else when removing this cookie?

**Review by nicl — APPROVED** [review]
Chatted with @gustavpursche IRL and we think this is fine. @SiAdcock might know better though!

**Pull request merged**
