### PR TITLE
Adslot in comments

### PR DESCRIPTION
**Pull request by Calanthe**
The 300x250 adslot was added to the comments container - only when the user is logged in:

screen shot 2015-06-08 at 17 16 33

### CODE REVIEW

**Comment by davidrapson** [comment]
@Calanthe What's the context behind "only when the user is logged in"?

**Comment by uplne** [comment]
@davidrapson when user is logged in the order of containers is different.

Not logged in user would see:
1. article
2. related content
3. comments (has ad)
4. most popular (has ad)

Logged in user will see:
1. article
2. comments (has ad)
3. related content
4. most popular (has ad)

See which containers have ads. So as we try not to put too many ads next to each other we want at least one container in between. That's why we want to show ad in comment section only when user is logged in (there is related content container in between).

**Comment by johnduffell** [comment]
looks good :+1: but consider whether some kind of test would provide value here

**Comment by uplne** [comment]
@johnduffell very good point

**Comment by Calanthe** [comment]
I will include unit tests in one of the next pull request.

**Pull request merged**
