### PR TITLE
Refactor the fluid 250 adverts

### PR DESCRIPTION
**Pull request by regiskuckaertz**
This is initially to allow the Merchandising team to use a simplified version of that component, but I caught the bug and decided to get rid of as much redundancy as I could.

I did not try to get too fancy with the code, so the result is still as ugly as it initially was, just a few KB smaller.

### CODE REVIEW

**Comment by uplne** [comment]
In this case, I think, the most important thing is to make sure that all parties know what is happening and everything is 100% tested.

**Comment by regiskuckaertz** [comment]
What do you mean? I made it so that nothing changes in DFP—which explains the ugly detection in `breakoutIframe`

**Comment by regiskuckaertz** [comment]
I'll add some unit tests :smiley:

**Comment by jbreckmckye** [comment]
All looks OK :+1:

**Comment by uplne** [comment]
Is this worth unit testing? Definitely don't focus too much on testing DOM manipulations.

**Comment by uplne** [comment]
Definitely nice work removing a lot of code :+1: :hammer:

**Comment by regiskuckaertz** [comment]
There's definitely a lot going on in this supposedly simple module. A lot of it comes from the sheer number of parameters and their respective values in DFP. We should add this to the list of TODOs for next quarter. Anyway, let's merge this mozafucka.

**Comment by uplne** [comment]
Whatever you add to TODO has ~5% chance to be really done.

**Comment by regiskuckaertz** [comment]
@uplne actually you got that already covered in your doc, under the heading **Creatives** :fist:

**Comment by OliverJAsh** [comment]
Nice work removing 361 lines from the codebase :-) :+1:

**Comment by regiskuckaertz** [comment]
@OliverJAsh yeah :wine_glass:

**Pull request merged**
