### PR TITLE
Banner below the first container server test removed

### PR DESCRIPTION
**Pull request by uplne**
Sad day but the maintenance of this got tricky over time.

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
😭 

There is some code in `slice-adverts` too, if I remember.

I'll revive this during the next hack day 🔥

**Comment by jbreckmckye** [comment]
👍 - but it's a shame nothing came of this.

**Comment by uplne** [comment]
@regiskuckaertz I've updated slices

**Comment by regiskuckaertz** [comment]
🎸 🎶  rock'n'roll

**Comment by jbreckmckye** [comment]
👍

**Comment by gtrufitt** [comment]
😭

**Pull request merged**
