### PR TITLE
Switch off thrashers for ipad

### PR DESCRIPTION
**Pull request by michaelwmcnamara**
This change is to hide thrashers for any ipad visitors.

Change is behind the "IPadNoThrasher switch"

The aim of this change is to test whether thrashers are effecting ipad crashes by disabling them overnight and then comparing the metrics given to us by our AWS beacons with a baseline from a previous day where thrashers were present on the front.

### CODE REVIEW

**Comment by uplne** [comment]
Why not to remove thrasher container in the back end?

**Comment by michaelwmcnamara** [comment]
Mainly for simplicity - this is only for an overnight test after which the changes will be removed. If we decide to do this permanently then doing it in the back end might be a better way to go about it.

**Comment by uplne** [comment]
It's just that by using JS and adding one more selector you are actually adding some more work for the browser. It won't do any harm in this case but in overall clean and 100% accurate test would be to not add this container to the page at all.

**Comment by uplne** [comment]
:+1:

**Pull request merged**
