### PR TITLE
Update omniture.js

### PR DESCRIPTION
**Pull request by mkopka**
[AppMeasurement1.5.2.txt](https://github.com/guardian/frontend/files/44826/AppMeasurement1.5.2.txt)
Updated with Adobes latest version of their library 1.5.2
At the moment dotcom is using JS-1.4.1

### CODE REVIEW

**Comment by johnduffell** [comment]
what changed? is this risky?

**Comment by mkopka** [comment]
only thing that changed was adobes latest library became available.  We've done this before as otherwise we start having an out of date version the site.
Not risky.

**Comment by johnduffell** [comment]
if you're happy, I'm happy! :+1:

**Comment by jbreckmckye** [comment]
@mkopka - did you need help merging this in? When we deploy this, is there anything we should look for to check that everything is still fine?

**Comment by jbreckmckye** [comment]
I'm going to merge this in on @mkopka's behalf and check that we're still making the call to hits.theguardian.com as a smoketest.

**Comment by rich-nguyen** [comment]
:+1: thanks @jbreckmckye

**Pull request merged**
