### PR TITLE
Html email json endpoint for CMT

### PR DESCRIPTION
**Pull request by QuarpT**
## What does this change?

Html endpoint for emails, required by CMT provider.
The entire HTML result is set as the html attribute on a json object
This differs from the current .json path where the html only includes the page body

## Screenshots

picture 49

## What is the value of this and can you measure success?

Integration with new CMT provider

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by jfsoul** [comment]
Given that we're not 100% sure whether this will be required I am tempted to suggest we add an expiring switch for this, so we can clean it up at a later date.  The on/off state of the switch would probably be the same though... so it might be overkill.

**Comment by NataliaLKB** [comment]
> Given that we're not 100% sure whether this will be required I am tempted to suggest we add an expiring switch for this, so we can clean it up at a later date. The on/off state of the switch would probably be the same though... so it might be overkill.

I am pretty sure this is required based off the meeting I had on Monday with @paulbrown1982 and @markjamesbutler

**Review by NataliaLKB — APPROVED** [review]
Good code improvements here!

**Comment by NataliaLKB** [comment]
> I am pretty sure this is required based off the meeting I had on Monday with @paulbrown1982 and @markjamesbutler

@jfsoul I just chatted with Paul and you are right it *might* not be needed, but it is fairly trivial to remove the part about the .json so I am happy with this not being part of a switch for now.

**Comment by NataliaLKB** [comment]
@QuarpT Thanks for doing this so quickly!

Could you do the same with all the other `/email` routes we have?

**Comment by jfsoul** [comment]
> I am happy with this not being part of a switch for now

No worries, just a thought 😄

**Comment by QuarpT** [comment]
changing the path to from `/email.json` to `.emailjson` to avoid any overlap with `.json`

**Pull request merged**
