### PR TITLE
URGENT re-naming based on EU law

### PR DESCRIPTION
**Pull request by zeftilldeath**
# Under article 17 of regulation (EU) no 1169/2011, names currently used for meat products and meat preparations will be reserved exclusively for products containing meat

After a thorough investigation I have concluded that **our navigation does not contain any meat**, and therefore I have pre-emptively renamed all instances of `veggie-burger` to `veggie-disc` across our codebase, in compliance with EU directives.

Screen Shot 2019-04-05 at 11 16 59

You can read more [here](https://www.theguardian.com/food/2019/apr/04/eu-to-ban-non-meat-product-labels-veggie-burgers-and-vegan-steaks).

Thank you for your time.

### CODE REVIEW

**Comment by SiAdcock** [comment]
I guess we can change this back after ~~29th March~~ ~~12th April~~ 22nd May

**Comment by zeftilldeath** [comment]
@SiAdcock Yeah! Dependent on whether we decide to comply or not. I think we should focus a lot of our resources on monitoring the UK's approach to this.

**Review by SiAdcock — APPROVED** [review]
🍔 🇪🇺

**Review by SiAdcock — CHANGES_REQUESTED** [review]
We need to block this as changing the component name will cause D&I some headache 😞

**Comment by zeftilldeath** [comment]
For any EU litigation lawyers reading this in the future... _I tried_.

**Comment by SiAdcock** [comment]
[Sad times](https://github.com/guardian/frontend/pull/15863#issuecomment-280730703)

**Pull request closed without merging**
