### PR TITLE
Just a minute

### PR DESCRIPTION
**Pull request by zeftilldeath**
The minute needs a "vanilla" colour scheme and design that could be applied to any theme or event. There was also room for a few design tweaks to get it more inline to its app sista - so we can proudly pop minute articles on fronts. 

SWAK 💋 
cc @gtrufitt @blongden73 @samdesborough @stephanfowler 

You came here for pictures didn't you?

mobile

desktop

grid

### CODE REVIEW

**Comment by gtrufitt** [comment]
👀  Looks great. 😍

**Comment by paperboyo** [comment]
Fat red bars - good riddance, along with night-time blues! Nice typography (esp. Comic Sans), but descenders make sweet love to ascenders in the headlines.

I'm not sure about captions on top of pics, though: one is hard to read - spells future pains; they are inconsistent with the rest of the Guardian, inconsistent with videos, consistent with the Daily Mail... Some opaque logic sometimes forces them properly below the pics on mobile, though... so that they are not consistent even from one half a minute to the next. Logic opaque to me that is - The Wooden Eye™.

_The above constitutes a personal opinion. The characters and sentences in this story are purely fictitious. If the depiction of certain journalistic practices should have resulted in similarities with the practices of the Daily Mail newspaper, these similarities are neither intended nor coincidental but inevitable._

**Comment by zeftilldeath** [comment]
Good spot @paperboyo . Have resolved the line-height issue and standardised the captions with the rest of the site.

**Comment by desbo** [comment]
Looks good! Right now we only apply the minute template to the US minute tag so we should make it work on the other minute tags (is there a generic one yet?) as well.

**Comment by gtrufitt** [comment]
*et voilà*

The minute ***tone** is now applying the minute article styling. I have also updated the logo to use the article badge as per the section badging and scoped the email sign-up to just the US Minute.

Any other thoughts?

screen shot 2016-09-16 at 11 34 35
screen shot 2016-09-16 at 11 34 42
screen shot 2016-09-16 at 11 34 57

**Review by gtrufitt — APPROVED** [review]
LGTM. @desbo Could you scan over? Not changed much from the original work we did but a quick second eye would be good. Cheers!

**Review by desbo — APPROVED** [review]

**Comment by gtrufitt** [comment]
image

I thought you'd just written that

**Comment by desbo** [comment]
man that would've been pretentious

**Comment by gtrufitt** [comment]
@gtrufitt approved this comment.

**Pull request merged**
