### PR TITLE
feat: removed abTests from subs banner

### PR DESCRIPTION
**Pull request by damien-shaw-guardian**
## What does this change?

We had an AB-test running from feb 3rd to feb 27th. The test turned out to be inconclusive, so we decided to end the test and use the original copy. 

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## Screenshots

Screen Shot 2020-03-02 at 16 50 32

## What is the value of this and can you measure success?
n/a
## Checklist
- removed code in subs banner template
- removed subs banner display logic 

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [x] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [x] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/master/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by rupertbates** [comment]
I think you need to remove the test from here as well: https://github.com/guardian/frontend/blob/417dd58a7ca6a49be2616170c99a19711f68e753/static/src/javascripts/projects/common/modules/experiments/ab-tests.js#L25

**Comment by rupertbates** [comment]
And remove the switch from here: https://github.com/guardian/frontend/blob/e9c673e88d8133f72e69fa4bd8f90bcf65e3c1de/common/app/conf/switches/ABTestSwitches.scala#L109

**Review by rupertbates — CHANGES_REQUESTED** [review]
See comments above

**Review by rupertbates — APPROVED** [review]
👍

**Review by jfsoul — APPROVED** [review]

**Pull request merged**
