### PR TITLE
Extract identity to guardian/identity-frontend-old repo

### PR DESCRIPTION
**Pull request by danmassie**
The identity team have cloned the frontend project to https://github.com/guardian/identity-frontend-old and have removed everything apart from the identity project from it. This will now be used to build the frontend identity artifact so that the identity project is not impacted by js changes. 

This is a short term solution while the new identity frontend application is being built and tested. https://github.com/guardian/identity-frontend.

### CODE REVIEW

**Comment by danmassie** [comment]
Parking for now until we decide what to do with assets.

**Comment by johnduffell** [comment]
what's happening with this one?

**Comment by rich-nguyen** [comment]
@danmassie yes, this is a move that I hugely support, but this PR is a month old. Should it be closed, and we investigate the assets issues together? cc @markjamesbutler

**Comment by johnduffell** [comment]
are we still using identity built from frontend or does it need deleting?

**Comment by ScottPainterGNM** [comment]
If Dan has now gone should this PR be closed?

**Comment by rich-nguyen** [comment]
yep, it can be re-opened when its ready to merge.

**Comment by janua** [comment]
This never made it?

**Comment by johnduffell** [comment]
seems not, half the stuff still gets served from frontend and half now from identity-frontend, I guess in the long term it could all get extracted to make it consistent.

**Pull request closed without merging**
