### PR TITLE
Hide expand icon on images for Core/no JS users

### PR DESCRIPTION
**Pull request by holder-josh**
This expand icon doesn't work without app.js, so let's hide it.

screen shot 2015-09-22 at 13 58 50

### CODE REVIEW

**Comment by stephanfowler** [comment]
:+1:

**Comment by jbreckmckye** [comment]
Would it maybe be more convenient to have some kind of 'core-hidden' or 'js-off-hidden' class in the markup? It'd make things a bit quicker to hide and would mean you could reason about the appearance of the element from the markup alone.

**Comment by Jholder112233** [comment]
@jbreckmckye good point! We do indeed have a 'modern-visible' class. I'll switch it to using that.

**Comment by davidrapson** [comment]
@jbreckmckye For my education as much as everyone else: the class name Josh was mentioning is defined here https://github.com/guardian/frontend/blob/master/static/src/stylesheets/base/_state.scss 

That file is a bit nebulous (`.shut > .pane` doesn't feel like it belongs there for example) but the top block does at least document what common state classes are available.

**Comment by jbreckmckye** [comment]
@davidrapson - good to know about

**Pull request merged**
