### PR TITLE
Removing Foresee

### PR DESCRIPTION
**Pull request by TBonnin**
It is not used anymore

## What is the value of this and can you measure success?
Less code ✂️ 

## Tested in CODE?
Yes

### CODE REVIEW

**Review by NataliaLKB — APPROVED** [review]

**Comment by rich-nguyen** [comment]
Have you confirmed no-one is using this? I had to revert my last attempt! https://github.com/guardian/frontend/pull/12283

**Review by rich-nguyen — APPROVED** [review]
Hopefully this is fine now, i think surveys are now ad-served. There was a consumer insight team who used to use this, I'd double check with them, if they are still around.

**Comment by TBonnin** [comment]
thanks @rich-nguyen 
Let me know what you find out.

**Comment by stephanfowler** [comment]
@rich-nguyen @TBonnin I've confirmed with Megan Cox that Foresee is no longer used by the org. The contract expired in March.

**Pull request merged**
