### PR TITLE
AUDIO: Add subscription svgs

### PR DESCRIPTION
**Pull request by ajwl**
## What does this change?

This adds the 3 icons for the audio subscription services. 

I'm told they have been optimised. 

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
Perhaps rename the `audio-tag-page` folder as just `audio`?

**Review by regiskuckaertz — APPROVED** [review]

**Comment by ajwl** [comment]
@regiskuckaertz done

**Comment by regiskuckaertz** [comment]
These builds take so long 😵

**Comment by ajwl** [comment]
Please merge if you spot when it finally passes

**Pull request merged**
