### PR TITLE
Facia tool jspm

### PR DESCRIPTION
**Pull request by piuccio**
**WARNING** This will crash your browser!

I've split the PR in 4 commits, DON'T look at the entire diff, there are too many changes
- d8eb509 : Remove bower and its components. As the name says it simply removes all files we had in bower/components
- 5ad3606 : Stop using global underscore and jQuery. Add `define(['underscore', 'jQuery']` in every file that depends on those. No more global variables

You can safely ignore those two commits
- 0d6dcfe : JSPM. This is the most interesting, it contains all the changes needed to use JSPM in facia-tool
- 83349b2 : JSPM inside the build. Change grunt to download JSPM dependencies.

Tested locally, but it would be nice to try again
- [x] Config tool functionality
- [x] Facia tool functionality
- [x] Confirm changes in tool show up on facia

### CODE REVIEW

**Comment by gklopper** [comment]
I tend to just :+1: anything with a delete ratio like that :wink:

**Comment by piuccio** [comment]
I tested locally.

@michaelwmcnamara when you have some time, would you mind having a look at this pull request, please. It really scares me

`npm install && grunt prepare compile` to make sure the assets are up to date.

**Comment by phamann** [comment]
6 days. Whats the plan?

**Comment by piuccio** [comment]
Updated to fix unit tests.
@stephanfowler would you like to review this? :grin:

**Comment by piuccio** [comment]
I've pushed an update on README.md

To test locally you need to

> ```
sudo npm -g install jspm
jspm endpoint config github
```
>
>It'll ask for a GitHub access token. Go to GitHub Settings -> Applications and [generate new token](https://github.com/settings/tokens/new). Default scopes are fine.

**Comment by stephanfowler** [comment]
`npm -g install jspm` worked for me, ie without `sudo`

**Comment by michaelwmcnamara** [comment]
Can only run facia-tool as my facia-end-to-end is not working.
Checked on facia tool project - no new issues on the editorial or config tool.
We should confirm changes are passed from tool through to facia if someone cn get this project working. Otherwise +1

**Pull request merged**
