### PR TITLE
Es6 lib fastdom promise

### PR DESCRIPTION
**Pull request by nicl**
Note, we have no types for fastdom. I could attempt this here if people think it valuable?

## What does this change?

Converts fastdom-promise to ES6.

## What is the value of this and can you measure success?

ES6.

## Does this affect other platforms - Amp, Apps, etc?

Nooo.

## Screenshots

Not today sorry.

## Tested in CODE?

No.

### CODE REVIEW

**Comment by SiAdcock** [comment]
Nice one! Yeah, I think defining types for `fastdom` could be really useful 😄

**Comment by nicl** [comment]
@SiAdcock okay this is done. As discussed, we've expurged fastdom-errors with great joy.

**Comment by sndrs** [comment]
not sure if this is a good place for this, but latest fastdom actually bundles a promised version? we couldn't use it because it's written in es6...

**Comment by nicl** [comment]
Okay, we've bailed from the fastdom update attempt in this PR as it would complicate things a bit. Is this now okay to merge? @SiAdcock @sndrs

**Review by SiAdcock — APPROVED** [review]
Tight 👍

**Pull request merged**
