### PR TITLE
Remove polyfill-io mvt

### PR DESCRIPTION
**Pull request by gu-stav**
## What does this change?

Removes polyfill-io mvt test.

## What is the value of this and can you measure success?

Polyfill.io is at 100% now - so it's just a code removal.

## Does this affect other platforms - Amp, Apps, etc?

No.

## Screenshots

No.

## Tested in CODE?

No.

### CODE REVIEW

**Comment by jfsoul** [comment]
How about the switch in `PerformanceSwitches.scala`?

**Review by NataliaLKB — APPROVED** [review]
Awesome!

**Comment by jfsoul** [comment]
How about the stuff in `OptInController.scala` as well - is that redundant now?

**Comment by gustavpursche** [comment]
@jfsoul Sorry forgot about those references. Could you have a final 👀 now?

**Review by SiAdcock — APPROVED** [review]

**Review by jfsoul — COMMENTED** [review]
Thanks 👍

**Pull request merged**
