### PR TITLE
Secure path

### PR DESCRIPTION
**Pull request by gklopper**
Assets url now understands whether you are HTTP or HTTPS

### CODE REVIEW

**Comment by johnduffell** [comment]
:+1: is this to fix security warnings when you import http assets from an https domain?

**Comment by robertberry** [comment]
:+1: Is the SSL bit part of the cache key on Fastly too?

**Comment by gklopper** [comment]
Hmm, on second thought this won't work :(

**Comment by gklopper** [comment]
SSL terminates at Gastly, not the ELB

**Comment by gklopper** [comment]
Gastly [oops]

**Comment by robertberry** [comment]
Dawwww.

**Pull request closed without merging**
