### PR TITLE
One XL Veggie Burger please

### PR DESCRIPTION
**Pull request by zeftilldeath**
As a means of increasing the discoverability of the veggie burger, here are a few visual changes.
 
# Before
before

# After
after

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]

**Comment by sndrs** [comment]
awful lot of magic numbers creeping in here. i'm not sure if that's a bad thing or ok?

**Comment by paperboyo** [comment]
### Before
afterer
### After
afterer
### Afterer
afterer

**Comment by gustavpursche** [comment]
@paperboyo You forgot the possibilities of `<blink />` ;)

**Comment by paperboyo** [comment]
click me baby

**Comment by paperboyo** [comment]
@zeftilldeath Oh, small thing: fatter lines trickled down to (still) smaller slim header diet burger upsetting bun-to-ingredients burger ratio.

**Pull request merged**
