### PR TITLE
Adds GE 2019 badge

### PR DESCRIPTION
**Pull request by duarte**
## What does this change?

Ain't nothing but a humble badge

**Do not merge**
I will merge this on Monday 11/11 at 6am, as per editorial request.

### CODE REVIEW

**Review by gtrufitt — APPROVED** [review]
lgtm

**Comment by jeteve** [comment]
Probably a naive question, but I can see the badge being defined, but not used. Is there some magic somewhere that uses it at the right place just because it's defined?

**Comment by shtukas** [comment]
I talked offline with Jerome. Motion in progress to move badges definition and management this possibly somewhere else.

**Comment by duarte** [comment]
Might be useful to know that there is a [feature request for the Tag Manager tool to handle badges](https://trello.com/c/DqIDgqoX/608-add-a-badge-attribute-to-the-tag-manager-editorial-requests-designed-badges-for-our-most-important-content-such-as-paradise-pape), which I hope might be picked up soon!

In my opinion, the Tag Manager would be the ideal place to handle this, as the badge really is it's a property of the tag. In addition, the current system doesn't fully satisfy because we should actually have two separate badges: one for dark, one for light background pages. Not to mention, how doing a PR for this is cumbersome for something that could be simple, particularly in cases where editorial requests a specific launch time. Lastly, having it in the Tag Manager would also help implementing badges in the apps!

**Comment by jeteve** [comment]
That's great, thanks @duarte for pointing me to this!

It would be fantastic indeed if one could define a badge against a tag. I'll help pushing in this direction!

**Pull request merged**
