### PR TITLE
Update omnitureMedia.js

### PR DESCRIPTION
**Pull request by mkopka**
Added channel to media events to make our guardian core segment (which is defined based on site sections) compatible with video events

s.linkTrackVars = 'events,eVar11,prop41,eVar43,prop43,eVar44,prop44,prop9,channel';

### CODE REVIEW

**Comment by phamann** [comment]
:+1:

**Comment by phamann** [comment]
@mkopka I need to test this first, as your last one broke our tests :wink:

**Comment by mkopka** [comment]
@phamann we have Mary Hamilton in the US really pushing to have this made available. Do we know when we can tell her this should be out there by please?

**Comment by phamann** [comment]
I'm closing this as couldn't test your branch because its external. So re-opened with #8996

**Pull request closed without merging**
