### PR TITLE
Use "normalised" R1 paths when pressing/redirecting/take-downing 

### PR DESCRIPTION
**Pull request by philmcmahon**
## What does this change?
Ensures that all possible variations of a page url are taken down by the page presser - http/https and normalized/non-normalized paths.
### Tested

- [ ] Locally
- [x] On CODE (optional)

### CODE REVIEW

**Comment by philmcmahon** [comment]
Also need to make sure that when people add redirects using the redirect tool the redirect is added for the normalised version of the url. When normalising it we should log out which version we are actually redirecting for future poor souls trying to debug this elegant mess

**Comment by AWare** [comment]
R1 articles are uniquely identified by this regex.
```regex
^/(.*)/[0|1]?,[\d]*,(-?\d+),[\d]*(.*)
```

Thus they are uniquely identified by a string and a (signed) number.

https://www.theguardian.com/arts/pictures/image/0,,arts/pictures/image,.html

Is identified by `arts/pictures/image` and `arts/pictures/image`.

So we can change the URL _a lot_ and still get a 200. 

https://www.theguardian.com/arts/pictures/image/0,1337,-10805206878,1337.this_still_resolves

Because this content is old, we're ignoring a lot of the problems with having a many to one relation between URL and content piece. 

But we can't ignore:

- Adding or removing redirects 😐
- Pressing this content to fix http mixed mode 😭
- Taking down content 😞

Things we might want to think about eventually:

- Content that has been re-pressed on the non canonical URL will just have a useless S3 representation.
- 301- Moved Permanently

**Comment by philmcmahon** [comment]
Nice work 👍

**Comment by philmcmahon** [comment]
Relevant gif
coin press gif

💯 for 🚚 ing on with this

**Comment by philmcmahon** [comment]
I tested this on CODE and redirects appear to still be working. lets merge it asap tomorrow morning

**Pull request merged**
