### PR TITLE
Sfl signed out users

### PR DESCRIPTION
**Pull request by NathanielBennett**
This does 2 things
(a) Enables sfl for all signed out users ( via the standard signin flow ) 
(b) Removes sfl functionality from fronts, tag pages and containers

### CODE REVIEW

**Comment by desbo** [comment]
cuts to make the tories proud, :+1:

**Comment by NathanielBennett** [comment]
<rant level="wheres-my-labour-party-ballot>
Yeah - the codes still all in github though, so can be put back at any time. Unlike sure start centres and sixth form colleges, libraries and a & e departments
</rant>

**Comment by OliverJAsh** [comment]
Has this been discussed with regard to Andrea’s email, titled "Data on saving from fronts/containers"? I think Andrea wanted us to keep the buttons on fronts et al so we can investigate further.

**Comment by OliverJAsh** [comment]
Also, let's look at the data for the test before we ship it completely. How many users actually sign in because of SFL?

**Comment by rich-nguyen** [comment]
No sass deletions?

**Pull request merged**
