### PR TITLE
Remove unsued apple touch icons

### PR DESCRIPTION
**Pull request by gtrufitt**
## What does this change?

Quicker to delete than raise a ticket...

image

@guardian/dotcom-platform

### CODE REVIEW

**Comment by paperboyo** [comment]
> Quicker to delete than raise a ticket...

👏 I would like to have stats on how many tickets took long time to log/prioritise/pick up than to actually fix. half-;-)

**Comment by gtrufitt** [comment]
> > Quicker to delete than raise a ticket...
> 
> 👏 I would like to have stats on how many tickets took longer time to log/prioritise/pick up than to actually fix. half-;-)

On Frontend sadly not, on dot-components though...

**Review by philmcmahon — APPROVED** [review]
Am sure you know what's happening here but do we need to replace these icons with new ones?

**Comment by gtrufitt** [comment]
Sorry, should have explained better, they are different in the source

image


But in apples wisdom, if there's an icon then they ignore the source code.

So these are 'unused' but used by virtue of being there even though there are alternatives

**Comment by philmcmahon** [comment]
Aha makes sense!

**Pull request merged**
