### PR TITLE
Send UK engagement banner traffic to support.theguardian

### PR DESCRIPTION
**Pull request by JustinPinner**
## What does this change?
Follows up on changes made here: https://github.com/guardian/frontend/pull/17986

When the `uk-supporter-traffic-to-new-support-frontend` switch is ON and the reader is known to be UK-centric, we set the destination of traffic from the engagement banner to `support.theguardian.com`

## What is the value of this and can you measure success?
Getting ready to switch over everything. The switch remains OFF in PROD until we're all set.

## Does this affect other platforms - Amp, Apps, etc?
No, web only.

## Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?
No

## Screenshots
**Switch ON, user in GB**
screen shot 2017-10-12 at 12 11 21

and re-checking the epic with the same configuration;
screen shot 2017-10-12 at 12 12 01

and a liveblog epic, to be thorough;
screen shot 2017-10-12 at 12 16 41

**Switch ON, user in US**
screen shot 2017-10-12 at 12 13 49

**Switch OFF**
screen shot 2017-10-12 at 12 20 27

**After updating the button caption**
Switch ON
screen shot 2017-10-12 at 14 40 24

Switch OFF
screen shot 2017-10-12 at 14 41 38

(these were captured at a slightly narrow breakpoint, and the button and icons usually move around like this)

## Tested in CODE?
Yes

cc @rupertbates @Ap0c @svillafe @davidfurey

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]

**Review by svillafe — APPROVED** [review]
LGTM

**Review by Ap0c — APPROVED** [review]
Gave it a run locally, looks good 🐆

**Comment by JustinPinner** [comment]
Thanks for the approvals all. Unfortunately the engagement banner tests failed last night, so I had to make a couple of changes - primarily extracting the switch and location checks into their own `support-utilities.js` file. That also required a re-visit to the epic code. I've re-tested everything locally again and it still looks good. Will re-do on CODE when the build is ready.

**Comment by Ap0c** [comment]
Had another look locally, seems to work fine 🌻

**Review by joelochlann — APPROVED** [review]
LGTM

**Pull request merged**
