### PR TITLE
Alt history ranking 

### PR DESCRIPTION
**Pull request by stephanfowler**
Allow internal assessment, to see if we can make the history tags more maintainable by getting rid of the unwieldy whitelist. Adding `#alt-history` to a url produces a different ranking of your history tags.

Notably:
- doesn't apply a whitelist (exposes a more personalised set of tags)
- favours front tags over article tags by a factor of 10 (ie downplays obscure tags picked up from news articles)

### CODE REVIEW

**Comment by johnduffell** [comment]
looks good :+1: 
also wondered if there's a central place for the tags that are editionalised?  I notice you've had to hard code a few bits of info

**Comment by stephanfowler** [comment]
@johnduffell yes, though the point of this PR is to see if we can avoid having _any_ hardcoded items at all.

**Comment by phamann** [comment]
Out of interest, why a url hash and not a switch?

**Comment by stephanfowler** [comment]
@phamann just so a few internal people can try it out first, as I think the results could be significantly different.

**Pull request merged**
