### PR TITLE
stop liveblogs jumping

### PR DESCRIPTION
**Pull request by johnduffell**
image
image
becomes:
image
happy days @OliverJAsh @stephanfowler

### CODE REVIEW

**Comment by paperboyo** [comment]
They should also not jump when there is a new update and I'm in the middle reading/watching, TBH. But that's another kettle of fish...

**Comment by Jholder112233** [comment]
@paperboyo watch this space :wink:

**Comment by stephanfowler** [comment]
:+1: !

**Comment by NataliaLKB** [comment]
:+1:

**Pull request merged**
