### PR TITLE
Upgrade guardian source libs

### PR DESCRIPTION
**Pull request by tjmw**
## What does this change?

This upgrades the versions of source-foundations, source-react-components and source-react-components-development-kitchen libs. 

Although this seems like a big change (it was on DCR) as far as I can tell these libraries are used much less frequently on frontend:

1. `@guardian/source-foundations` - used for breakpoint values by some commercial JS and is a peer dependency of `@guardian/braze-components`.
2. `@guardian/source-react-components` - I think only exists as it's a peer dependency required by `@guardian/braze-components`
3. `@guardian/source-react-components-development-kitchen` - I think only exists as it's a peer dependency required by `@guardian/braze-components`

From `@guardian/braze-components` perspective, I'm happy with these updates (already in this state on DCR).

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No Already handled in guardian/dotcom-rendering#6178
- [ ] Yes (please indicate your plans for DCR Implementation)

## What is the value of this and can you measure success?

New shiny source libs!

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [x] On CODE (optional)

### CODE REVIEW

**Comment by tjmw** [comment]
@guardian/commercial-dev I think the only frontend client side code affected by this change other than Braze related stuff is commercial code (looks like various places use `breakpoints` from `source-foundations). TypeScript and the tests are happy but just want to check you're okay with this PR?

**Review by tomrf1 — APPROVED** [review]
👍

**Review by arelra — APPROVED** [review]
As long as the breakpoints are the same all good from commercial dev!

**Review by mxdvl — APPROVED** [review]
Thanks for this!

**Pull request merged**
