### PR TITLE
Remove puzzles banner 0% A/B test

### PR DESCRIPTION
**Pull request by marialani**
## What does this change?
This removes the 0% A/B test aspect of the call to the contributions service (support-dotcom-components) to request the puzzles banner when on puzzle pages. The banner will continue to work as expected minus being a part of a 0% A/B test.

When removing the the AB test, we discovered that the puzzles banner was broken on Frontend. This was probably not a massive issue as 99.9% of articles pages are now rendered via DCR. The changes in this PR restore normal functionality: the puzzles api call is made and banner is displayed on puzzles pages.

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## Screenshots
No visual changes have been made to the puzzle banner:
Screenshot 2021-08-02 at 10 42 37

## What is the value of this and can you measure success?
The banner continues to work as expected with the objective of encouraging more users to download the puzzles app.

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [x] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [x] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [x] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [x] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [x] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [x] On CODE (optional)

Co-authored by @lucymonie

### CODE REVIEW

**Review by rupertbates — APPROVED** [review]
LGTM 👍

**Review by zekehuntergreen — APPROVED** [review]

**Comment by GHaberis** [comment]
I think we'd like to keep the Feature Switch and the corresponding `isPuzzlesBannerSwitchOn` conditional check. Hopwever we do want to remove the ab test import here https://github.com/guardian/frontend/blob/3bb1f605a14bd8efc427667afa8418847830d252/static/src/javascripts/projects/common/modules/experiments/ab-tests.ts#L2 and remove the module https://github.com/guardian/frontend/blob/main/static/src/javascripts/projects/common/modules/experiments/tests/puzzles-banner.js.

**Review by GHaberis — CHANGES_REQUESTED** [review]
I've left a comment regarding retaining the feature switch

**Comment by marialani** [comment]
> I've left a comment regarding retaining the feature switch

I've just restored the puzzles banner feature switch and the `isPuzzlesBannerSwitchOn` conditional check

**Review by GHaberis — APPROVED** [review]
Looks good 👍

**Pull request merged**
