### PR TITLE
CSS importing typo fix

### PR DESCRIPTION
**Pull request by johnduffell**
edited: actually the data-reload is needed for csdevmode and the project name is also needed for loading the right CSS file in the first place
The dot is back on the preview/dev-build
before:
image
after:
image

### CODE REVIEW

**Comment by janua** [comment]
:+1:

**Comment by sndrs** [comment]
sorry john, :-1: i think…

i think this will kill `csdevmode`, plus [`Static.css.projectCss()`](https://github.com/guardian/frontend/blob/2dcbb6d9978cebec975a66df856ce660bb82a401/common/app/assets/assets.scala#L74) already knows about the `projectName`, doesn't it?

**Comment by johnduffell** [comment]
@sndrs how about now? =)

**Comment by sndrs** [comment]
:+1:  now :)

**Pull request merged**
