### PR TITLE
add crossword print css

### PR DESCRIPTION
**Pull request by desbo**
before: 
screen shot 2015-08-04 at 12 29 36

after:
screen shot 2015-08-04 at 12 24 54

### CODE REVIEW

**Comment by davidrapson** [comment]
I mean the before screenshot looked pretty solid to me, but this is better :+1: 

As an aside, what's the general view about having inline `@media print` blocks with the component styles it affects, rather than one big print CSS file? I've no doubt this has been discussed before and there's a good reason not to, but just wanted to ask.

**Comment by OliverJAsh** [comment]
@davidrapson I suspect we just want to avoid adding bloat to our CSS files that won't be used in the majority of cases—not sure if it has been discussed. Do you have any thoughts?

**Comment by davidrapson** [comment]
@OliverJAsh Yeah, my only reaction was seeing a BEM fragment `crossword__cell` without the parent which just reminded me that you are loosing some of the context of where these styles apply which is why I like keeping print styles with the component themselves. Completely get the tradeoffs about bloating the CSS files though.

**Comment by OliverJAsh** [comment]
@davidrapson I completely agree, all the code should be in one place and separation should be a build concern. There might be a creative solution to this!

**Comment by davidrapson** [comment]
@OliverJAsh Yep, might be a post-css / post-processor task which can combine `@media print` blocks…or something.

Sorry @desbo, hijacking your PR. Will take this offline :+1:

**Comment by paperboyo** [comment]
> I mean the before screenshot looked pretty solid to me, but this is better

Couldn't agree more :laughing:

> I've added a button to download the pdfs in both js and noscript versions instead.

That's quite an addition! Could I see the screenshot, pls? There are these instances where there seems to be the need for a print version of specific images/galleries (I get similar requests every now and then). Currently, there is no easy/not clunky/consistent way to achieve this. Please take a look at these examples:

http://www.theguardian.com/lifeandstyle/2013/jun/19/secret-garden-colouring-in-adults

http://www.theguardian.com/politics/gallery/2015/apr/08/the-general-election-colouring-in-book-in-pictures

Maybe that button could be reused somewhere beyond just crosswords?

**Comment by desbo** [comment]
@paperboyo we already have pdfs for most crosswords, so it was just a case of adding a link. I'll probably tweak the style a bit, but it's basically the same as the old versions of the crosswords (hold on to your hat):

screen shot 2015-08-04 at 18 35 35

**Comment by paperboyo** [comment]
Thanks, @desbo! Looks good! Reusing it in more places is, most probably, quite an undertaking (tools, PDF generation, frontends), but, maybe, something to consider in the future...

**Comment by jennysivapalan** [comment]
:+1: :tada:

**Comment by heralder99** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <Re: [frontend] add crossword print css (#10018)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Pull request merged**
