### PR TITLE
Remove kicker and byline links from cards (except Dream Snaps)

### PR DESCRIPTION
**Pull request by robertberry-zz**
Some minor refactoring too

### CODE REVIEW

**Comment by johnduffell** [comment]
:+1: good refactoring
I assume there is a good justification for doing this. Depending on that, screenshots might be useful.

**Comment by robertberry** [comment]
@johnduffell Nothing visual has changed. It's just the kicker and byline are no longer separate links. The whole card links to the article (except if it has sublinks on it).

**Comment by johnduffell** [comment]
ok sounds good!

**Comment by janua** [comment]
Can you find out if `FrontendLatestSnap` is used anywhere else? I always wanted to remove this class and it's base trait, but always needed it in (from what I remember) a minimal set of places.

**Comment by robertberry** [comment]
@janua It's used in a bunch of other places. I prefer to match on ADTs than Strings everywhere, so I think we should keep it.

**Comment by janua** [comment]
@robertberry Oh me too, but it's complete repetition from what comes from `facia-scala-client`. It just exists and is used because we are now in a new format/context/types.

**Comment by robertberry** [comment]
Hmm OK, but let's look at that in a separate pull request, as it is still pretty entangled.

**Comment by paperboyo** [comment]
Hi,

My nomenclature ignorance may be showing here, but does that mean that this:

separate links on tiles

won't be possible any more?!

Regards
Mateusz

**Comment by johnduffell** [comment]
@paperboyo I was confused for the same reason - we really need a frontend glossary!

**Comment by robertberry** [comment]
@paperboyo Yes, that's exactly what it means

**Comment by paperboyo** [comment]
:sadpanda: That's awful! We keep removing these small features!

I hope we have hard data showing that readers are getting to places they didn't wanna visit! Otherwise, soon, we will get rid of ability to go straight to comments, straight to series...

And then, there is going to be just one big overlay over the whole front taking readers to just one very important article :astonished:

Bad kitty!

**Comment by robertberry** [comment]
Request came from @theresamalone. I'll go find out more about it

**Comment by paperboyo** [comment]
:beer: for reconsidering! I'm already gathering counterarguments (:beer: + :beer: = :beers:)...

**Comment by robertberry** [comment]
OK, so it turns out there's been a bunch of user testing done, and basically nobody clicks on those links intentionally. If you're using a device other than a desktop it's not obvious that clicking on certain areas of the card will take you not to the article but to a tag page (as there's no underline on hover over as you don't hover over), and that means it's confusing for users.

The request has come from a bunch of people from design, UX, and editorial.

**Comment by paperboyo** [comment]
Unless we are getting thousands of emails every day from angry readers, I can see one legitimate reason for removal of these... Half-legitimate. And for removal of only half of these, actually.

Some kickers take you to the series/tag fronts, some (custom) aren't. And they are impossible to distinguish. This is inconsistent. This was bugging me for some time. The solution would be to use that (again, what's the name??):

that thingy

for all of the actionable ones and leave the kickers non-interactive. But I have not proposed that, because I do not particularly like the design of the above thingy, because I do not understand why that thingy is there since we have actionable kickers and for other reasons as well.

But I can't see a reason for the removal of byline links... Other than that someone clicked on one of them and didn't like the result...

Regards
Mateusz

**Comment by robertberry** [comment]
That thingy is basically the latest story for 'The Politics Sketch'. And they are gonna keep the links on those.

I'm not particularly bothered about removing these links as I don't think very few people intentionally follow them, and they do add to page weight and DOM depth, and I'm happy with even minor reductions to that ...

**Comment by paperboyo** [comment]
[obviously, I do not argue with you personally, here, @robertberry!]

> nobody clicks on those links intentionally

I do. Learning takes time and if we remove them, we will act against those who already learned their usefulness. Also, if nobody is clicking on them - how come anyone minds them being there? Also, we should measure a drop to tag/profile fronts. 

> If you're using a device other than a desktop it's not obvious that clicking on certain areas of the card will take you not to the article but to a tag page (as there's no underline on hover over as you don't hover over), and that means it's confusing for users.

Oh, so direct to-comments links are going to go as well?! And recently introduced direct links to liveblog blocks?! Sublinks also do not have underlines on mobile last time I've checked...

> and they do add to page weight and DOM depth

:laughing: I won't argue with that! :laughing:

Sad to see them go without a proper justification, though...

Regards
Mateusz

**Comment by janua** [comment]
I click them too when I use the site.

**Comment by johnduffell** [comment]
It's the rules now @paperboyo - every time you add something you have to delete something else, one in one out.  Since Rob's added so much in the last couple of years behind, he has a lot of stuff to delete this month ;)

**Comment by crifmulholland** [comment]
The kickers are used really inconsistently across the site, so it's not easy to learn and has some issues with SEO. The bylines are clicked and used often.

**Comment by robertberry** [comment]
I think sublinks are visually more obviously separate things. Although I'm not a fan of how they work either. In terms of accessibility on mobile, I think they're pretty bad. I find it very difficult to click on one on my phone and usually end up at the wrong article.

I'm not really sure about the direct link to comments, myself. I know they're there but I never click them personally. I'm going to want to read at least a bit of the article before I go look to see what the trolls are saying. :wink:

**Comment by robertberry** [comment]
@crifmulholland They are? Then why was I asked to remove them?

**Comment by paperboyo** [comment]
But the most important argument to keep them wouldn't be that I use them. I would risk a hypothesis that they constitute a significant traffic driver to the otherwise underused tag/profile fronts. If not the biggest. Would someone with Omniture skillz be willing to help me to construct a more number-driven argument, as these, for some not entirely clear reason, seem to matter more than common sense? (@mkopka?).

Regards
Mateusz

**Comment by paperboyo** [comment]
I love lost battles, so disregard, if not interested. A poor man's analysis using Ophan, suggests that indeed direct byline links on cards are (were) often the biggest traffic driver to author's profile pages. They are (were) by often a significant margin more important than an article page referrals for a story of respective author displayed on a network front.

Traffic to author's profile page:

| Story on UK front | from UK front | from that story |
|---|---|---|
| 1 | 92 | 13 |
| 2 | 70 | 57 |
| 3 | 125 | 31 |
| 4 | 165 | 191 |

Regards
Mateusz

**Pull request merged**
