### PR TITLE
Add SFL empty view

### PR DESCRIPTION
**Pull request by OliverJAsh**
image

### CODE REVIEW

**Comment by paperboyo** [comment]
Is it worth removing Remove all button in this instance?

**Comment by OliverJAsh** [comment]
Yes, or disabling it, but not for this small (in proportion of users) test.

On Fri, 19 Jun 2015 12:52 Mateusz <notifications@github.com> wrote:

> Is it worth removing Remove all button in this instance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9549#issuecomment-113487959>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by rich-nguyen** [comment]
:+1: yep, just check the copy

**Comment by crifmulholland** [comment]
Remember this is a stepped launch, rather than just a small test. We'll want to ramp up traffic quickly, so we'd be best removing the button now if possible.

**Pull request merged**
