### PR TITLE
Convert `detect.js` to TypeScript

### PR DESCRIPTION
**Pull request by chrislomaxjones**
## What does this change?

> TODO

## Does this change need to be reproduced in dotcom-rendering ?

- [X] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## What is the value of this and can you measure success?

> TODO

### Tested

- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by mxdvl** [comment]
We’ve done something a little different tackling a specific part of detect before: #24443

**Comment by Jakeii** [comment]
@chrislomaxjones still working on this?

**Comment by chrislomaxjones** [comment]
@Jakeii I haven't touched it since opening the PR. Feel free to take it from here if you've got an eye on it 🙂

**Comment by Jakeii** [comment]
Closing in favour of #25601

**Pull request closed without merging**
