### PR TITLE
Upgrade to content-api-client 31.1.0 for special crossword support

### PR DESCRIPTION
**Pull request by andrew-nowak**
## What does this change?

Upgrade the content-api-client, to get the latest version of CAPI models, which includes support for the upcoming "special crosswords" series.

Normally we'd need to also add the new series name to many of the [crossword](https://github.com/guardian/frontend/blob/12ce055553176605f338b4aed1258ebd70a5cbb7/applications/conf/routes#L20-L24) [route](https://github.com/guardian/frontend/blob/12ce055553176605f338b4aed1258ebd70a5cbb7/dev-build/conf/routes#L22-L26) [regexes](https://github.com/guardian/frontend/blob/12ce055553176605f338b4aed1258ebd70a5cbb7/preview/conf/routes#L17), but they already contain "special", presumably for some previous version of special crosswords.

We no longer need to update the crossword player CSS, since #27336

## Checklist

- [ ] Tested locally, and on CODE if necessary
- [x] Will not break dotcom-rendering
- [x] Will not break our database – if updating CAPI, [updated and committed the database files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)
- [x] Meets our accessibility [standards](https://github.com/guardian/recommendations/blob/e647ef695199ea3116ea20d827ef0f1364270a39/accessibility.md)
  - [x] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
  - [x] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#Keyboard)
  - [x] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#colour)

### CODE REVIEW

**Comment by andrew-nowak** [comment]
For what it's worth, I didn't need to upgrade the client in order to get a test crossword to render on [preview CODE](https://preview.code.dev-gutools.co.uk/crosswords/special/1), but I'll still raise this PR to at least keep the client up to date

**Review by JamieB-gu — APPROVED** [review]
Should this have been a major release of the CAPI models/client, since it widens the `CrosswordType` enum and therefore creates a breaking change?

**Comment by andrew-nowak** [comment]
> Should this have been a major release of the CAPI models/client, since it widens the `CrosswordType` enum and therefore creates a breaking change?

[I'll avoid the philosophical debate of "is a widening of an enum a breaking change" here]

Release numbers are now automated by https://github.com/guardian/gha-scala-library-release-workflow, so we humans don't get a say in which number gets incremented. Specifically, the [mima library](https://github.com/lightbend-labs/mima) is detecting compatibility levels and, at least currently, doesn't consider this a breaking change, although there's an [open issue on the topic](https://github.com/lightbend-labs/mima/issues/200)

**Comment by rtyley** [comment]
Thanks Andrew, that's a good summary - and many thanks for pointing out https://github.com/lightbend-labs/mima/issues/200, which I hadn't seen, but explains the version-number-increment that `sbt-version-policy`/`mima` chose here.

Just to get pedantic and mention on this point tho':

> Release numbers are now automated by https://github.com/guardian/gha-scala-library-release-workflow, so we humans don't get a say in which number gets incremented.

...it's true that you can't stop the workflow from incrementing the version-number if it wants to, but as a human you _can_, if you wish, **also** increment the number yourself if you think a change warrants it. So if you have a significant change in a PR, you can manually update `version.sbt` in that PR (ie doing a major-number increment), and when the PR is merged that will guarantee a major-number increment. So humans _can_ get some say!

Of course, for that to be useful, a human would need to know that there was an compatibility issue in a PR (eg for the human to consider adding an enum value a breaking change) and also for the human to anticipate that whatever gha-scala-library-release-workflow was going to do, was not going to be a big enough increment (I guess the easiest way to establish that would be to do a PREVIEW release, which would show what version number `sbt-version-policy` was going to select).

**Pull request merged**
