### PR TITLE
Make sure surveys are displayed nicely

### PR DESCRIPTION
**Pull request by oilnam**
Tweak the values in the space finder so that surveys are displayed nicely, and not too close to other ads.

@regiskuckaertz @MahanaC

### CODE REVIEW

**Review by regiskuckaertz — APPROVED** [review]
Question: is it displayed in pages where Outbrain is displayed too? If yes, we need to make sure it is taken into account as a non-compliant impression.

**Comment by gtrufitt** [comment]
Is this running @GHaberis I thought it was off?

**Comment by oilnam** [comment]
@gtrufitt Nope it's been running, although it's targeting a very limited fraction of the audience. Is that OK with you guys?

**Comment by MahanaC** [comment]
@gtrufitt you might be confused with the other survey we ran earlier (orange), which has been turned off

**Comment by MahanaC** [comment]
@oilnam looks good! 👍

**Comment by gtrufitt** [comment]
> you might be confused with the other survey we ran earlier (orange), which has been turned off

I am :) Thanks

**Comment by GHaberis** [comment]
@oilnam if this survey is injected after the article content (in the same position you'd see a contributions epic for example) then it'll need adding to the clashingTests list in ab-test-clash.js as it means outbrain will need to be registered as non-compliant.

**Pull request merged**
