### PR TITLE
Consider iPad 1 not modern

### PR DESCRIPTION
**Pull request by robertberry-zz**
Part II of fixing iPad crashes.

Part III is disabling images for non-modern browsers ....

### CODE REVIEW

**Comment by gklopper** [comment]
:+1:

**Comment by michaelwmcnamara** [comment]
Still crashing if on the ipad I have javascript turned on.

**Comment by gklopper** [comment]
@michaelwmcnamara fix will (hopefully) be this + fewer containers.

**Comment by michaelwmcnamara** [comment]
another step closer I guess :-)

**Pull request merged**
