### PR TITLE
Cleanup all the things

### PR DESCRIPTION
**Pull request by DiegoVazquezNanini**
## What does this change?
- Simplifies some logic like:
filter(_.nonEmpty).isDefined => exists
reverse.take(5).reverse => takeRight(5)
get(FOO).getOrElse(BAR) => getOrElse(FOO, BAR)
map(FOOBAR).flatten => flatMap(FOOBAR)
- Various formatting simplifications.
All changes should be non-controversial, but let's wait for the comment and opinions.

@guardian/guardian-frontend

### CODE REVIEW

**Comment by nicl** [comment]
Does Frontend have a Scala style guide? Might be worth making it explicit if not and then blatting with Scalariform and integrating it as part of the build (in the same way they do for the JS).

As a counter opinion, the problem with this kind of big change is it confuses the git history substantially.

**Review by TBonnin — APPROVED** [review]
Very helpful.
Some formatting ones like parenthesis or not could be controversial but it doesn't really matter. ;)
We could discuss introducing some formatting/linting if everybody feels like it would be useful. I would be fine with that even though you lose a little flexibility

**Comment by kelvin-chappell** [comment]
👍 

In general I'd distinguish between optimisations and matters of style.
`filter(_.nonEmpty).isDefined => exists` is a definite improvement
but brackets can be used to clarify in some situations even if not strictly necessary.

This is something that shouldn't be automated!

I find this plugin useful in my global sbt config though: https://github.com/HairyFotr/linter

**Comment by gklopper** [comment]
Scala has a style guide http://docs.scala-lang.org/style/ and IntelliJ warns you if you do something like the nonEmpty isDefined stuff and suggests the proper thing.

Grant

Sent from my iPhone

> On 23 Nov 2016, at 13:49, Kelvin Chappell <notifications@github.com> wrote:
> 
> 👍
> 
> In general I'd distinguish between optimisations and matters of style.
> filter(_.nonEmpty).isDefined => exists is a definite improvement
> but brackets can be used to clarify in some situations even if not strictly necessary.
> 
> This is something that shouldn't be automated!
> 
> I find this plugin useful in my global sbt config though: https://github.com/HairyFotr/linter
> 
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by DiegoVazquezNanini** [comment]
Thanks, all for the comments.
I used Intellij and the built-in scala style guide to get a list of edit suggestions. 
Try it: Analyze > Inspect Code ...

**Comment by nicl** [comment]
👍 for an automated formatter of some kind @TBonnin .  Yes you lose some freedom, but the consistency and avoidance of bikeshedding that you gain are massive wins from my perspective. Obviously, the platform team would need to favour this for it to happen though.

**Pull request merged**
