### PR TITLE
Sync local date to server, for relative dates

### PR DESCRIPTION
**Pull request by stephanfowler**
Use the page's render time as the basis of "now", for the purpose of relative time calculations. Because if a user's device has its local time/zone incorrectly set, our relative dates can be wildly out.

### CODE REVIEW

**Comment by piuccio** [comment]
Looks good. I'm just wondering if there's any duplication with date manipulation in other parts, like live blogs. If so, it would be nice to have a utility that computes time relative to the page load.

Otherwise :+1:

**Comment by stephanfowler** [comment]
@piuccio - sorry the branch name is misleading; the PR actually changes the general util for relative dates. So it'll affect liveblog content pages, comments, etc.

**Comment by piuccio** [comment]
right. what confused me is that the file is inside `modules/ui/`. I was expecting it to be inside `utils/`, but probably I don't understand precisely the difference between an utility and a module :grin:

**Comment by stephanfowler** [comment]
Nor do I!

**Pull request merged**
