### PR TITLE
Remove requirejs-text plugin, move rjs svg-loader into tests

### PR DESCRIPTION
**Pull request by gu-stav**
## What does this change?

Removes requirejs text plugin, refactored tests and moved svg-loader into the test directory.

## What is the value of this and can you measure success?

Webpack everywhere!

## Does this affect other platforms - Amp, Apps, etc?

No.

## Tested in CODE?

- [x] Test in CODE

### CODE REVIEW

**Comment by sndrs** [comment]
```
     ***** ***          **             ***** *    **   ***    
  ******  * **       *****          ******  *  *****    ***   
 **   *  *  **      *  ***         **   *  *     *****   ***  
*    *  *   **         ***        *    *  **     * **      ** 
    *  *    *         *  **           *  ***     *         ** 
   ** **   *          *  **          **   **     *         ** 
   ** **  *          *    **         **   **     *         ** 
   ** ****           *    **         **   **     *         ** 
   ** **  ***       *      **        **   **     *         ** 
   ** **    **      *********        **   **     *         ** 
   *  **    **     *        **        **  **     *         ** 
      *     **     *        **         ** *      *         *  
  ****      ***   *****      **         ***      ***      *   
 *  ****    **   *   ****    ** *        ******** ********    
*    **     *   *     **      **           ****     ****      
*               *                                             
 **              **                                           
 ```

**Comment by sndrs** [comment]
if we're renaming the bower package manually, should we remove it from `bower.json` and out of `components`? maybe to `vendor`? 

totally happy to not have it managed by bower, but currently it _is_: the changes would be overwritten by running `bower install` (although admit that's unlikely)

**Comment by gustavpursche** [comment]
> if we're renaming the bower package manually, should we remove it from bower.json and out of components? maybe to vendor?

I agree with you. Is there a `vendor/` you have in mind already, or would you create a new directory?

> totally happy to not have it managed by bower, but currently it is: the changes would be overwritten by running bower install (although admit that's unlikely)

But if it happens, you'd see some local changes in your repo which would be very confusing.

**Comment by sndrs** [comment]
probably just create one at the same level as `components`?

**Comment by gustavpursche** [comment]
@sndrs I finally moved it into `helpers/` since this is the place, where the legacy svg-loader lives already, so they are in one place. Found this a bit better, than adding another directory.

Are you ok [with that](https://github.com/guardian/frontend/pull/15918/commits/fccc83efd96676cd76af073946615c2133a4d214)?

**Comment by SiAdcock** [comment]
@gustavpursche I think that's a good location. Don't forget to delete all the stuff in `static/test/javascripts-legacy/components/text` too 😄

**Comment by gustavpursche** [comment]
@SiAdcock  I removed the legacy text-loader, so this should be ready to merge.

**Review by SiAdcock — APPROVED** [review]

**Pull request merged**
