### PR TITLE
Fix logos in amp

### PR DESCRIPTION
**Pull request by kelvin-chappell**
On amp platform, the img tag has to be an amp-img.

### CODE REVIEW

**Comment by NataliaLKB** [comment]
Thanks for doing this! Styling for the logos also needs to be done for AMP. Will that be done in this PR, or a subsequent one?

**Comment by SiAdcock** [comment]
Nice one @kelvin-chappell 

For reference, AMP-specific styles could be added to [this file](https://github.com/guardian/frontend/blob/master/common/app/views/fragments/amp/stylesheets/main.scala.html), or imported as a fragment at the bottom

**Comment by kelvin-chappell** [comment]
@NataliaLKB Will fix styling in another PR.  I'll add it to our list of issues.

**Comment by Calanthe** [comment]
👍

**Comment by gtrufitt** [comment]
Hey @kelvin-chappell, this is still failing AMP validation due to a different issue: https://amp.theguardian.com/cities/2015/feb/24/private-london-exposed-thames-path-riverside-walking-route#development=1

The implied layout 'CONTAINER' is not supported by tag 'amp-img'

The error explanation is here: https://www.ampproject.org/docs/reference/validation_errors.html#implied-layout-isnt-supported-by-amp-tag

I believe you want to add `layout="fixed"` attribute to the `amp-img` element: https://github.com/ampproject/amphtml/blob/master/spec/amp-html-layout.md#fixed and add the fixed height and width of the logo. You can see an example in metaInline.scala.html

You may want to do this as part of your styling PR?

image


cc/ @guardian/dotcom-platform

**Pull request merged**
