### PR TITLE
Only intercept fetch events in SW if they're to secure endpoints

### PR DESCRIPTION
**Pull request by sndrs**
it doesn't let you fetch them anyway, should stop errors like these:

screen shot 2016-01-04 at 11 43 25
screen shot 2016-01-04 at 11 43 54

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Sounds sensible and I think it's good for us to start clearing up errors when running in HTTPS mode, although I think the bigger problem we have here is mixed content.

Seeing as this change effects the offline page, you should be able to test if it still works. To do this locally:

* Run `make compile` (you need compiled assets for the offline page as it can't cache the small modules)
* Go to http://localhost:9000/info/developer-blog to install the SW. You might already have a SW installed, in which case either ensure the new one takes over (see Dev Tools) or just do the test in an incognito window if it's easier.
* Go offline (Dev Tools network throttling)
* Refresh and the offline page should appear

**Comment by johnduffell** [comment]
note it's easier to view this one with [?w=0](https://github.com/guardian/frontend/pull/11440/files?w=0)

I can't see a reason not to ship this one? so :+1: .  although in related news now capi stores a secureFile attribute for video files so if we switch to that it should fix the first one anyway

**Comment by OliverJAsh** [comment]
Ship it or close :ship:

**Comment by sndrs** [comment]
whoopsie

**Comment by OliverJAsh** [comment]
Was this a mistake? If we're merging I would like to know the offline page has been tested.

**Pull request merged**
