### PR TITLE
Initialise phone number reflection on application startup

### PR DESCRIPTION
**Pull request by markjamesbutler**
# Initialise phone number reflection on application startup
## What does this change?

This moves the potentially slow reflection code into application startup rather than executing on rendering of the account edit page.
## What is the value of this and can you measure success?

Faster rendering of the account edit page.  Blocking reflection code is removed from page rendering.
## Does this affect other platforms - Amp, Apps, etc?

No
## Screenshots

None
## 

_Does this PR meet the [contributing guidelines](https://github.com/guardian/frontend/blob/issue_pr_templates/.github/CONTRIBUTING.md#submission)?_

### CODE REVIEW

**Comment by jamespamplin** [comment]
:+1: looks good to me

**Comment by johnduffell** [comment]
great! 👍

**Comment by johnduffell** [comment]
is reflection really that slow?  I thought it was a bad idea because it takes away compile time safety?  perhaps swapping the hard coded list for reflection is swapping one thing for another.  Personally I'd prefer the list.  Good on you for fixing the Canada problem though, I got completely stumped by that one.

**Comment by janua** [comment]
@johnduffell Good question...
http://stackoverflow.com/questions/435553/java-reflection-performance
Which leads to http://docs.oracle.com/javase/tutorial/reflect/index.html

**Comment by johnduffell** [comment]
@janua thanks for googling that for me 😝 I guess they mean the JIT can't compile it very well.

Interestingly, in that document oracle think the drawbacks of reflection are Performance Overhead, Security Restrictions and Exposure of Internals.  They didn't think about compile time safety?

**Comment by johnduffell** [comment]
come on, ship it! 😝

**Pull request merged**
