### PR TITLE
Add extra variant to Membership message, extend test

### PR DESCRIPTION
**Pull request by davidrapson**
Adds and extra variant to the Membership message, testing different copy for the message. Extends test.

screen shot 2015-07-10 at 16 02 31
screen shot 2015-07-10 at 16 00 36

@dominickendrick @stephanfowler

### CODE REVIEW

**Comment by stephanfowler** [comment]
We've suffered previously from adding new variants into already-running tests. The user bucketing becomes inconsistent/confusing - so it's worth asking the data team first before you do that....

**Comment by davidrapson** [comment]
@stephanfowler Good point. We have no issue with running this as a new test, don't need to add anything to the existing one. I've updated the test IDs, look OK to you now?

**Comment by stephanfowler** [comment]
:+1: yep

**Comment by davidrapson** [comment]
Confirmed on PROD

screen shot 2015-07-13 at 11 36 27

**Pull request merged**
