### PR TITLE
Better Geolocation

### PR DESCRIPTION
**Pull request by robertberry-zz**
Uses Maxmind's CSV of cities (http://www.maxmind.com/GeoIPCity-534-Location.csv) to look up the latitude and longitude of the city name and country name that Fastly gives us.

We then query Accuweather using that data instead, so as not to get strange mismatches.

### CODE REVIEW

**Comment by rich-nguyen** [comment]
that's a big data file!

**Comment by robertberry** [comment]
Hmm ... it is. Don't think the box will have any issues loading it into memory though. But maybe I shouldn't check it into this repository. :/

**Comment by rich-nguyen** [comment]
No probs with memory, it has just bumped up by 18MB though. A test that expects X number of entries in your map would be useful to ensure csv parsing has worked.

super :+1:

**Comment by robertberry** [comment]
@rich-nguyen Ta, just added a test for that

**Pull request merged**
