### PR TITLE
Warn against accessing properties on JS config

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

There have been a number of errors introduced into production caused by us attempting to access properties on the `config` object that do not exist. It is simple to guard against this type of error by using the [`get` method](https://github.com/guardian/frontend/blob/master/static/src/javascripts/lib/config.js#L10-L14) that is provided by `config`.

This change introduces a lint rule to warn against direct access of properties on `config`, and to prefer the use of the `get` method instead.

## What is the value of this and can you measure success?

There are currently 71 occurrences of direct property access on the `config` object, which are a source of potential defects. In future PRs we can gradually eliminate theses accesses, and eventually disallow direct access entirely. For now it's useful to have visibility over where these property accesses are occurring.

## Does this affect other platforms - Amp, Apps, etc?

No

## Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

No

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]
I like the change, but:

- for the dev experience we need to work out a proper `config.get()` mock for the tests
- because it's potentially breaking things to access the properties directly, this should be an `error` instead of a `warn`, I think. We could merge it in it's current state, start fixing the warnings and then turn this into an `error`

What do you think?

**Comment by NataliaLKB** [comment]
> We could merge it in it's current state, start fixing the warnings and then turn this into an error

👍 💯

**Review by NataliaLKB — APPROVED** [review]
Great!

**Comment by SiAdcock** [comment]
Thanks both. I'll work on a `config.get()` mock separately, then start killing these warnings! 🐙

**Comment by sndrs** [comment]
nice

**Pull request merged**
