### PR TITLE
Rounded icon

### PR DESCRIPTION
**Pull request by uplne**
This PR is refactoring the rounded icons (social media, topNav icons, liveblog - autoupdate, live icon, gallery show full image icon.

The main goal is mainly increased maintainability but there are some minor savings on CSS and definitely on HTML size.

Icons remains their sizes.

screen shot 2015-01-02 at 11 16 41
screen shot 2015-01-02 at 11 16 49
screen shot 2015-01-02 at 11 17 03
screen shot 2015-01-02 at 11 17 29
screen shot 2015-01-02 at 11 17 36
screen shot 2015-01-02 at 11 17 39
screen shot 2015-01-02 at 11 17 56
screen shot 2015-01-02 at 11 21 18

### CODE REVIEW

**Comment by austinh7** [comment]
:+1:

**Comment by sammorrisdesign** [comment]
Is there a case for making these part of `pasteup-buttons`, seeing as they're standardised components that we want to behave in the same way.

Just asking for a friend.

**Comment by uplne** [comment]
The JS added social icons slipped through. I added it in the latest commit:
screen shot 2015-01-06 at 15 03 33

**Comment by uplne** [comment]
@sammorrisdesign the thing is that this rounded-icon class isn't really a component. It's just abstraction of the rounded styles. But good point and I will think about how we can possibly include it.

**Comment by marchibbins** [comment]
Seems quite a lot of icons were missed in this. Any chance of an update to `identityHeader`?

image

**Comment by uplne** [comment]
Thank you. I am already working on fix for this.

**Comment by marchibbins** [comment]
@uplne great, do you have an ETA or should I put one through? Looks like just a small mark-up change.

**Comment by marchibbins** [comment]
Fixed with #7800 — thanks!

**Pull request merged**
