### PR TITLE
Add object rest/spread properties to babel

### PR DESCRIPTION
**Pull request by joelochlann**
Add [Babel plugin](https://babeljs.io/docs/plugins/transform-object-rest-spread/) to main frontend config so we can use object rest/spread syntax, i.e. stuff like

```javascript
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
console.log(x); // 1
console.log(y); // 2
console.log(z); // { a: 3, b: 4 }
```

and

```javascript
let n = { x, y, ...z };
console.log(n); // { x: 1, y: 2, a: 3, b: 4 }
```

### CODE REVIEW

**Review by sndrs — APPROVED** [review]
...nice

**Comment by SiAdcock** [comment]
Should we also add this to [`development`](https://github.com/guardian/frontend/blob/42ba80286f2a532083fdf70006035dbca88add64/.babelrc#L28)?

**Comment by sndrs** [comment]
@SiAdcock ooh yeah v good point. may as well add to top level, so it's included everywhere?

**Review by sndrs — CHANGES_REQUESTED** [review]
shall we move it to top level `plugins`, so all envs pick it up?

**Comment by sndrs** [comment]
looks ok to me – @SiAdcock all ok with you?

@joelochlann if you want to be doubly certain this won't break anything, might be handy to diff the compiled JS of this branch against master

**Comment by SiAdcock** [comment]
Does `-1955 lines` from yarn.lock sound right?

**Comment by joelochlann** [comment]
@SiAdcock what doesn't look right about it?

**Comment by SiAdcock** [comment]
There are changes to packages that should not have been affected by this change (i.e. yargs, webpack, webpack-dev-server, caniuse-lite).

**Comment by sndrs** [comment]
might need to merge master in too

**Comment by joelochlann** [comment]
@SiAdcock have a look at #17808. yarn seems to think a lot of stuff should change just by virtue of running `yarn add --dev babel-plugin-transform-object-rest-spread`. Any thoughts?

**Comment by SiAdcock** [comment]
Interesting, I guess the upgrade has to v1.0.x has caused things in the yarn.lock to get moved around. I seem to remember something equally bewildering happening around v0.14

Weird that there's a discrepancy now between the yarn.lock on this branch and that on #17808... which is correct, I wonder?

**Review by SiAdcock — APPROVED** [review]
Looks good, sorry for the `yarn` pain 😖

**Comment by joelochlann** [comment]
Yeah I know, I'm not sure how this branch got in a weird state but I trust the other branch since it's the result of just a single command.

On this branch, I just:
- Pulled the latest master
- Reset the `yarn.lock` and `package.json` to what was on master
- Ran `yarn add --dev babel-plugin-transform-object-rest-spread`
- ...and got the diff from #17808

**Comment by joelochlann** [comment]
After running `yarn install`, all the deleted stuff gets re-instated and I get the diff from earlier with the 73 added lines. Weird.

**Comment by SiAdcock** [comment]
download 5

Possibly related: yarnpkg/yarn#4379

**Pull request merged**
