### PR TITLE
Add callback rule for handling vertical-align on DFP iframes.

### PR DESCRIPTION
**Pull request by JonNorman**
## What does this change?
DFP add a `vertical-align` property directly to all of their iframes. This can adversely affect the smoothness of the expanding/collapsing transitions that we have on those creatives.

This change adds a callback such that whenever a fluid ad size is delivered, the `vertical-align` property is removed.

## What is the value of this and can you measure success?
This creates parity in behaviour between our DFP native styles and the previous approach for serving special creatives such as fabrics.

### CODE REVIEW

**Comment by JonNorman** [comment]
[Native Fabric Template Migration - (Fabric Video Expandable) Issue](https://trello.com/c/efdblgMa/84-native-fabric-template-migration-fabric-video-expandable-issue)

**Comment by JonNorman** [comment]
[Native Fabric Template Migration - (Fabric Expandable) Issues](https://trello.com/c/9DTBSoyU/83-native-fabric-template-migration-fabric-expandable-issues)

**Review by rich-nguyen — APPROVED** [review]

**Comment by rich-nguyen** [comment]
I would do a quick bit of browser testing.

**Comment by JonNorman** [comment]
I have tested on latest Chrome and latest Firefox. Hardly exhaustive, but I'll keep an eye on it.

**Pull request merged**
