### PR TITLE
Revealed and styled sharing buttons AMP

### PR DESCRIPTION
**Pull request by zeftilldeath**
A couple of selectors in here that aren't compliant with the AMP spec, but are unavoidable until the html changes. 

Updated:
screen shot 2015-10-02 at 10 22 33

### CODE REVIEW

**Comment by Jholder112233** [comment]
The sharing icons look larger than on dotCom. If I remember correctly we scale the icons to 88% or something.

**Comment by stephanfowler** [comment]
These'll need a sanity check one they're out. OK to test them in prod though...
@michaelwmcnamara @ScottPainterGNM

**Comment by zeftilldeath** [comment]
@Jholder112233 Good spot, I've reduced their size.

**Comment by ScottPainterGNM** [comment]
Happy to take a look - just ping me when it's out

**Comment by stephanfowler** [comment]
@ScottPainterGNM on second thoughts, test it on CODE; the issue is whether the buttons cause a share of the _canonical_ URL - not whatever domain you happen to be viewing on (AMPs are actually going to be on google.com)

**Comment by zeftilldeath** [comment]
Good to go now?

**Comment by stephanfowler** [comment]
:+1: yep

**Comment by ScottPainterGNM** [comment]
The share buttons all render correctly across a host of devices that I checked on browerstack and link to the correct gu.com short URL that @Jholder112233 advised comes from CAPI. Good news!

**Comment by stephanfowler** [comment]
Nice one - thanks all.

On 5 October 2015 at 10:24, Scott Painter <notifications@github.com> wrote:

> The share buttons all render correctly across a host of devices that I
> checked on browerstack and link to the correct gu.com short URL that
> @Jholder112233 <https://github.com/Jholder112233> advised comes from
> CAPI. Good news!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/10739#issuecomment-145473568>.
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
