### PR TITLE
Add oauth switch for autosignin

### PR DESCRIPTION
**Pull request by emma-p**
Implement switch for autosignin by overriding the idWebAppUrl set in the configuration

### CODE REVIEW

**Comment by rich-nguyen** [comment]
I'm not sure about the benefit of http switch. Can you come chat to one of us about this?

**Comment by gklopper** [comment]
Yeah, kill HttpSwitches

**Comment by rich-nguyen** [comment]
Just had a quick chat, @emma-p is going to update this PR

**Comment by emma-p** [comment]
@rich-nguyen I removed the HttpSwitches for the social signin features, let me know if that looks ok, thanks

**Comment by rich-nguyen** [comment]
:+1:

**Comment by tudorraul** [comment]
:+1:

**Comment by jamesoram** [comment]
Removing the switches removes our ability to run tests in parallel and also means we can't trust the test results as anyone can go and change the settings while the tests are running :-1:

**Pull request merged**
