### PR TITLE
Use optimised picturefill

### PR DESCRIPTION
**Pull request by sndrs**
Uses optimised version of picturefill (see https://github.com/guardian/picturefill/pull/5) to massively reduce DOM trashing, and remove code that we don't use.

Fingers crossed, this will have an impact on the recent crash reports we've been seeing...

In safari 8, loading network front, before:

screen shot 2015-02-23 at 18 51 17

after

screen shot 2015-02-23 at 14 09 51
### Confirm all images load on network front
- [x] IE8 - ~~only loads lowest res~~
- [x] IE9
- [x] IE10
- [x] IE11
- [x] Safari 5
- [x] Safari 5.1
- [x] Safari 6
- [x] Safari 7
- [x] Safari 8
- [x] FF latest
- [x] Chrome < 38
- [x] Chrome latest
- [x] usual mobile tests
### Confirm performance & jank is not diminished or is improved
- [x] Safari 5
- [x] Safari 6
- [x] older iOS devices

### CODE REVIEW

**Comment by uplne** [comment]
Nice. It also seems to be around .5s faster which is great.

**Comment by phamann** [comment]
As discussed via email, we will be moving the rest of the content images over to PictureFill within the next few days. Therefore I think it makes sense to move this initialisation in `javascriptLaterSteps.scala.html` in this PR.

This ensures it gets ran sooner. For the interim you can just wrap the function call in a conditional: 

```js
if(guardian.config.page.isFacia) { images.upgradePicture('.facia-page'); }
```

**Comment by sndrs** [comment]
@uplne hopefully it's faster, but those screenshots are from local, and sbt doesn't really have a consistent load time in my experience :wink:

**Comment by robertberry** [comment]
Whatcha mean, Alex? SBT is as solid as my code!

**Comment by sndrs** [comment]
screenshots for last version http://www.browserstack.com/screenshots/c2c2f20365bfdc759d7e10770a39275c5ebff54c

**Comment by robertberry** [comment]
:+1: Merge it you mutha

**Comment by michaelwmcnamara** [comment]
:+1:  :ship:

**Pull request merged**
