### PR TITLE
New Header: search should search

### PR DESCRIPTION
**Pull request by NataliaLKB**
## What does this change?

Making search work on the new header. 

It works like this:

search-example

Without javascript it still searches the query, just not our site. 
## What is the value of this and can you measure success?

People can find things via search, even though it takes you off our page, and onto Google.
## Does this affect other platforms - Amp, Apps, etc?

Nope!
## Request for comment

cc @SiAdcock @stephanfowler

### CODE REVIEW

**Comment by TBonnin** [comment]
Is there a way to come back once the reader is in Google interface?

**Comment by NataliaLKB** [comment]
@TBonnin there are two.

1. Since all the links are guardian links if they click on one they will come back.
2. The back button

Other than that, none so far. 😞  Maybe @stephanfowler has some ideas?

**Comment by NataliaLKB** [comment]
> In the screenshot above, there is a flash of a suggestion: do we have control over it? can we style it? Or is it browser/OS?

@paperboyo it is the browser. And it might be because I am actually on a desktop in that example

**Comment by SiAdcock** [comment]
Code looks great 👍

**Pull request merged**
