### PR TITLE
Add data-test-id attributes used by new identity functional tests

### PR DESCRIPTION
**Pull request by niklasvincent**
We are improving our functional tests, but at the moment our identifiers are too ambiguous (relying on CSS classes).

With this change, the elements our tests rely on get unique `data-test-id` attributes.

### CODE REVIEW

**Comment by davidrapson** [comment]
Hey, quick question on this one. On Membership we've been slowly standardising on using [`qa-` prefixed IDs or class names for functional tests](https://github.com/guardian/membership-frontend/blob/master/docs/FRONTEND.md#functional-testing). Are you following the convention from frontend as a whole here, or is this your preferred convention? If so I'll bear it in mind as it might be worth us on Membership using the same convention.

Looks like everyone is agreed on the principle of using dedicated hooks for functional tests, just curious what conventions other teams are settling on.

This is good stuff though.

**Comment by phamann** [comment]
@davidrapson Originally we did use prefixed classes and IDs but wanted a stronger separation of concerns so settled on the `data-test-id` pattern instead. This also has the added benefit that it avoids accidental removal of classes etc.

**Comment by phamann** [comment]
:+1:

**Comment by davidrapson** [comment]
@phamann Thanks. I like the pattern, I'll bear it in mind as we update our functional tests too.

As you were @nlindblad :+1:

**Comment by nlindblad** [comment]
Thanks guys!

**Pull request merged**
