### PR TITLE
Ab sticky bottom fix

### PR DESCRIPTION
**Pull request by Calanthe**
AB test with sticky banner at the bottom is refactored and fixed (I hope).

### CODE REVIEW

**Comment by uplne** [comment]
I am a little bit worried what it will do with older devices as it is doing a lot of DOM accessing but as it is an AB test :+1:

**Comment by Calanthe** [comment]
Which reminds me that I should use fastDOM.

**Comment by uplne** [comment]
:+1:

**Comment by stephanfowler** [comment]
:+1: for using `isParticipating` in bootstrap/common.js

**Pull request merged**
