### PR TITLE
Add more apple touch icon static images (and move one existing)

### PR DESCRIPTION
**Pull request by JustinPinner**
We are frequently polled for our icon files which we send on to the desktop backend. Now we can just serve them from our static assets.

I know that the one I set up yesterday will begin to 404 after this is merged, but that's ok as I'll be able to put out more Fastly changes to fix that very soon.

cc @jennysivapalan

### CODE REVIEW

**Comment by jennysivapalan** [comment]
:+1: :apple: :green_apple: :apple:

**Comment by paperboyo** [comment]
These images came from well optimised 17-colours apple-touch-icon.png of 2961b. But some have bloated to 70 KB! :laughing:

Ideally, someone who made apple-touch-icon.png should create all the derivatives. Here I just optimised them (6.18 KB instead of 252 KB):

apple-touch-icon-120x120_opt
apple-touch-icon-114x114_opt
apple-touch-icon-76x76_opt
apple-touch-icon-72x72_opt
apple-touch-icon-57x57_opt
apple-touch-icon-152x152_opt
apple-touch-icon-144x144_opt

**Comment by zeftilldeath** [comment]
These icons are the old brand, they need to be the batman g. :scream:

**Comment by paperboyo** [comment]
Oh my g! :laughing:

**Comment by zeftilldeath** [comment]
ee487fe6-c9cf-11e5-8b70-bf51f3b1fe9d
esssse487fe6-c9cf-11e5-8b70-bf51f3b1fe9d
esddssse487fe6-c9cf-11e5-8b70-bf51f3b1fe9d

**Comment by ScottPainterGNM** [comment]
You know this means you'll have to hand in your tote bags and mugs now

**Comment by JustinPinner** [comment]
Ok you lot. If someone can get me a bunch of the correct logo images, cropped appropriately and named as follows;

apple-touch-icon-114x114.png
apple-touch-icon-120x120.png
apple-touch-icon-144x144.png
apple-touch-icon-152x152.png
apple-touch-icon-57x57.png
apple-touch-icon-72x72.png
apple-touch-icon-76x76.png
apple-touch-icon120x120.png
apple-touch-icon152x152.png
apple-touch-icon76x76.png
apple-touch-icon.png

Yeah, that'd be great.
thatdbegreat

**Comment by zeftilldeath** [comment]
As seen as you asked so nicely, I'll hook you up! :laughing:

**Comment by JustinPinner** [comment]
Thanks @zeftilldeath. Comedians.

Anyway, that's the logo we've been serving since NGW launched. Which is nice.

**Comment by zeftilldeath** [comment]
Guess this is the equivalent of dusting an old corner of a house and finding damp.

**Comment by zeftilldeath** [comment]
Or a dead rat.

**Pull request merged**
