### PR TITLE
Use when’s ES6 Promise shim

### PR DESCRIPTION
**Pull request by OliverJAsh**
https://github.com/cujojs/when/tree/master/es6-shim

This allows us to listen for unhandled promise rejections, and thus to console log + log to Sentry (instead of letting them slip away into the dark). TLDR: we'll be logging more errors.

To do:
- [x] Test in all browsers

### CODE REVIEW

**Comment by janua** [comment]
Looks great :+1:

**Comment by OliverJAsh** [comment]
FYI: Chrome intend to implement the `unhandledRejection` event: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/SRsFwwEgnUQ

**Comment by desbo** [comment]
nice :+1:

**Comment by rich-nguyen** [comment]
`when` is pretty big though...

**Comment by OliverJAsh** [comment]
I forgot to mention: this depends on an update to requirejs (2.1.20), which is a transitive dependency of grunt-contrib-requirejs, which fixes an issue I had: https://github.com/jrburke/r.js/issues/833.

npm won't do this for you. Unfortunately the only way to update this with npm, AFAIK, is to blitz the module:

```
$ rm -rf node_modules/grunt-contrib-requirejs && npm i
# confirm you have the update with:
$ npm ls requirejs
frontend@0.1.0 /Users/OliverJAsh/Development/frontend
└─┬ grunt-contrib-requirejs@0.4.4
  └── requirejs@2.1.20
```

**Pull request merged**
