### PR TITLE
Add page with rich link to amp validation test

### PR DESCRIPTION
**Pull request by gtrufitt**
@jfsoul Smallest PR ever... Do you want me to add any more? Can we add live blogs or will they be out of date when they become dead blogs?

### CODE REVIEW

**Comment by jfsoul** [comment]
Is this missing the test data file?

Yeah I think we should add liveblog examples now that `amp-live-list` is out in the wild.  We could leave that for @SiAdcock who might have a better idea of all the cases to cover?

**Comment by jfsoul** [comment]
Oh and also we should add the same endpoint to in `tools/amp-validation/index.js`

...I can already see the duplication of these is going to be annoying 😕

**Comment by gtrufitt** [comment]
Oh yeah! Well - live list is already wild 🦁🦁 but yeah, lets leave it
until Big Si is back.

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by SiAdcock** [comment]
I'll be happy to add a live blog to the AMP Validation tests. I'm not 100% clear on when a URL should be added to `tools/amp-validation/index.js` and when it should be added to `ArticleAmpValidityTest.scala`. I guess the latter blocks the build if it fails, and the former runs on a schedule?

I don't think there's a guaranteed way of testing a live live blog (as opposed to a dead one). But I also don't think the markup pertinent to AMP validation and structured data changes when a live blog dies. Happy to discuss

**Pull request closed without merging**
