### PR TITLE
Remove accidentally committed bundle config file

### PR DESCRIPTION
**Pull request by OliverJAsh**
@JustinPinner I don't think you meant to add this file?

This file was removed from `gitignore` by https://github.com/guardian/frontend/pull/10504/files#diff-a084b794bc0759e7a6b77810e01874f2L64, because we no longer generate this file. (It was moved)

### CODE REVIEW

**Comment by gtrufitt** [comment]
:+1:  - This does seem to get generated still though (I get it too...). Was discussing with Rich whether it should be in gitignore on Friday though

**Comment by OliverJAsh** [comment]
@gtrufitt By what? It was removed here: https://github.com/guardian/frontend/pull/10504/files#diff-0b8371040a48919248df224b81605655L93

**Comment by gtrufitt** [comment]
I'm not sure... :/ I've just run ``grunt compile`` and it doesn't seem to generate it... If I notice it again I'll let you know!

**Comment by jennysivapalan** [comment]
I've got it sitting in my `Untracked files` list. Has something re-added it?

**Comment by OliverJAsh** [comment]
I don't think so. We used to generate the file, but I renamed the file we
generate and removed the old entry from gitignore. This means it will
suddenly appear as untracked for people, as the file is on your system but
no longer ignored. Maybe I should have done the comms to tell people they
can delete it.

On Mon, 28 Sep 2015 at 12:01 Jenny Sivapalan <notifications@github.com>
wrote:

> I've got it sitting in my Untracked files list. Has something re-added
> it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/10658#issuecomment-143712741>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by jennysivapalan** [comment]
Ah I see, I didn't realise it came through with the Offline work. Yeah I think an short email would help.

**Pull request merged**
