### PR TITLE
:es6: prepareGoogletag

### PR DESCRIPTION
**Pull request by regiskuckaertz**
@sndrs @SiAdcock Flow was complaining when trying to access `config.libs` (which is defined in `JavascriptConfig.scala.js`, presumably because Flow doesn't know anything about it). I turned the exported object into an [unsealed object](https://flow.org/en/docs/types/objects/#toc-unsealed-objects) to work around that.

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
LGTM 👌

**Comment by SiAdcock** [comment]
Good catch, @regiskuckaertz . I wonder if in the future we should create a type for `window.guardian.config`? It will make it safer to query.

**Comment by regiskuckaertz** [comment]
I started with that. I had a `ScalaJsConfig` type with all the keys:
```
config = (window.guardian.config: ScalaJsConfig)
```
and had another type `JsConfig = ScalaJsConfig & LocalJsConfig` that was the type of the exported object, but it did not help for my specific purposes so I removed it 😅

**Comment by sndrs** [comment]
>  I wonder if in the future we should create a type for window.guardian.config?

i guess the only place that should be touching that is `lib/config`, that's probably enough to keep it safe?

**Pull request merged**
