### PR TITLE
World cup 2018

### PR DESCRIPTION
**Pull request by adamnfish**
Do not merge yet! We'll look at this today, @nicl 

TODO:
* get leagueTables data enabled for this tournament with PA
* confirm with PA identity of the semi-final matches and adjust ordering based on what we hear
* replace Brazil BigFatFinal picture with a Russia one (/generic one to save time in the future)
* tweak display so spider doesn't run over the "uk times" message

## What does this change?

Adds World Cup 2018 to sport, including a wallchart.

## What is the value of this and can you measure success?

Enables our World Cup coverage, and creates an automatic embeddable wallchart for the competition.

## Screenshots

Note the Brazil icon for now, and the mostly hidden "uk times" message at the bottom.

screenshot 7

### CODE REVIEW

**Comment by nicl** [comment]
UPDATE: I'm going to pick this up with some help from @superfrank on the design side!

**Comment by nicl** [comment]
* [x] get leagueTables data enabled for this tournament with PA
* [x] confirm with PA identity of the semi-final matches and adjust ordering based on what we hear
* [ ] replace Brazil BigFatFinal picture with a Russia one (/generic one to save time in the future)
* [ ] tweak display so spider doesn't run over the "uk times" message

**Comment by nicl** [comment]
I've updated styling for football tables and team crests to fix alignment and spacing issues.

**Previously**

screen shot 2018-05-16 at 16 35 28

**Now**

screen shot 2018-05-16 at 16 35 18

**Comment by nicl** [comment]
@sndrs thanks for comments. I've tried to fix them so let me know if this is gtg now from your perspective!

**Review by sndrs — APPROVED** [review]
lgtm!

**Comment by Jester232** [comment]
InlaG but AlwAys room for improvement

**Pull request merged**
