### PR TITLE
Anchor links with sticky situation fixed

### PR DESCRIPTION
**Pull request by Calanthe**
Before:
screen shot 2015-07-20 at 17 26 16

After:
screen shot 2015-07-20 at 17 26 26

This is the fix for https://github.com/guardian/frontend/issues/9776

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Does this mean there's going to be more spacing between paragraphs of text where one has a link with a name attribute?

**Comment by uplne** [comment]
In theory no. Unless there are no additional styles for some links with the a name attribute.

The padding is pushing link 50px down but negative margin is pulling it back with -50px which means the position is not changing.

It seems that browses are not taking into account negative values when calculating anchor position but I haven't done any additional research around it.

**Comment by OliverJAsh** [comment]
> It seems that browses are not taking into account negative values when calculating anchor position but I haven't done any additional research around it. But that's why this works.

It would be good to understand why this works and then document it by leaving a comment beside the code?

**Comment by OliverJAsh** [comment]
Just so we don't have code we don't understand, or forget its purpose.

**Comment by Calanthe** [comment]
I added a comment. Now will ask QAs to help me testing it.

**Comment by OliverJAsh** [comment]
:+1: but failing tests

**Comment by michaelwmcnamara** [comment]
+1

**Comment by OliverJAsh** [comment]
Closing #9776

**Pull request merged**
