### PR TITLE
Add JS circular dependency module to build.

### PR DESCRIPTION
**Pull request by JonNorman**
### Background
On Friday there was a tricky-to-debug [problem](https://github.com/guardian/frontend/pull/16819/commits/3dcfba330524af0381e96b0bf57b0e3a0db0b240) ultimately caused by a circular dependency between es6 modules. When circular dependencies arise, one of the modules will be instantiated as an empty object in order to break the instantiation deadlock, before being subsequently fully resolved, see [here](https://github.com/webpack/webpack/issues/1788) for details.

### What does this change?
This PR adds in a build step to test for circular dependencies during the building of the javascript.

- It will be immediately clear when a circular dependency is introduced (it throws an error during the bundling - it could be more concise; given the dependency graph is by definition a cycle, one path printout would probably suffice:
```
Error: Circular dependency detected:
static/src/javascripts/projects/commercial/modules/dfp/dfp-env.js -> static/src/javascripts/projects/commercial/modules/dfp/Advert.js -> static/src/javascripts/projects/commercial/modules/dfp/define-slot.js -> static/src/javascripts/projects/commercial/modules/dfp/prepare-switch-tag.js -> static/src/javascripts/projects/commercial/modules/dfp/dfp-env.js,Circular dependency detected:
static/src/javascripts/projects/commercial/modules/dfp/Advert.js -> static/src/javascripts/projects/commercial/modules/dfp/define-slot.js -> static/src/javascripts/projects/commercial/modules/dfp/prepare-switch-tag.js -> static/src/javascripts/projects/commercial/modules/dfp/dfp-env.js -> static/src/javascripts/projects/commercial/modules/dfp/Advert.js,Circular dependency detected:
static/src/javascripts/projects/commercial/modules/dfp/prepare-switch-tag.js -> static/src/javascripts/projects/commercial/modules/dfp/dfp-env.js -> static/src/javascripts/projects/commercial/modules/dfp/Advert.js -> static/src/javascripts/projects/commercial/modules/dfp/define-slot.js -> static/src/javascripts/projects/commercial/modules/dfp/prepare-switch-tag.js,Circular dependency detected:
static/src/javascripts/projects/commercial/modules/dfp/define-slot.js -> static/src/javascripts/projects/commercial/modules/dfp/prepare-switch-tag.js -> static/src/javascripts/projects/commercial/modules/dfp/dfp-env.js -> static/src/javascripts/projects/commercial/modules/dfp/Advert.js -> static/src/javascripts/projects/commercial/modules/dfp/define-slot.js
    at bundler.run (/Users/jon_norman/dev/frontend/tools/__tasks__/compile/javascript/webpack.js:28:27)
    at /Users/jon_norman/dev/frontend/node_modules/webpack/lib/Compiler.js:256:15
    at Compiler.emitRecords (/Users/jon_norman/dev/frontend/node_modules/webpack/lib/Compiler.js:351:37)
    at /Users/jon_norman/dev/frontend/node_modules/webpack/lib/Compiler.js:249:12
    at /Users/jon_norman/dev/frontend/node_modules/webpack/lib/Compiler.js:344:11
    at next (/Users/jon_norman/dev/frontend/node_modules/tapable/lib/Tapable.js:154:11)
    at Compiler.compiler.plugin (/Users/jon_norman/dev/frontend/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/jon_norman/dev/frontend/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/jon_norman/dev/frontend/node_modules/webpack/lib/Compiler.js:341:8)
    at Compiler.<anonymous> (/Users/jon_norman/dev/frontend/node_modules/webpack/lib/Compiler.js:336:14)
make: *** [compile-javascript] Error 1
```

- It adds a couple of seconds to the build time (~2% increase), which seems reasonable (see testing below).
- It can be configured to not throw an exception on the detection of a circular dependency (it's conceivable that we may need to introduce one in future).

### Have you tested this?
image

### CODE REVIEW

**Review by kelvin-chappell — COMMENTED** [review]
Is yarn.lock supposed to be there?

**Comment by JonNorman** [comment]
@kelvin-chappell yeah I initially excluded it from the commit but then got a warning saying that `package.json` had changed out of sync with `yarn.lock`.

I believe this is the correct behaviour, see [docs here](https://yarnpkg.com/lang/en/docs/yarn-lock/).

**Comment by kelvin-chappell** [comment]
In that case it looks good to me.  But you probably need a second opinion!

**Review by SiAdcock — APPROVED** [review]
LGTM 👍

**Pull request merged**
