### PR TITLE
Get the internalPageCode from CAPI

### PR DESCRIPTION
**Pull request by piuccio**
But keep using internalContentCode until FAPI is fixed

@janua

### CODE REVIEW

**Comment by janua** [comment]
Where's the version bump?

**Comment by piuccio** [comment]
thought we wanted to do it in 2 steps. Let me put that in

**Comment by janua** [comment]
I suppose we can. I think we should find out why it doesn't work in it's current state first.

**Comment by janua** [comment]
:+1:

**Pull request merged**
