### PR TITLE
People prefer Int. to Intl.

### PR DESCRIPTION
**Pull request by gklopper**
cc @robertberry

### CODE REVIEW

**Comment by robertberry** [comment]
I liked Intl. :(

**Comment by robertberry** [comment]
:+1:

**Comment by gklopper** [comment]
Surely people realise the growth limitations of calling this [Int](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#MAX_VALUE)

**Comment by crifmulholland** [comment]
what happened to Global?

**Comment by robertberry** [comment]
Chris Moran will convince them when we start getting negative millions of page views

**Comment by gklopper** [comment]
The under the hoods section called global ruled that out. We could have managed the test, but after that would have been chaos.

**Comment by robertberry** [comment]
Also Global is another word we use as programmers. STOP USING OUR WORDS

**Comment by gklopper** [comment]
Next thing you know they want `/static` :frowning:

**Comment by paperboyo** [comment]
I wander if, in principal, people whom let others people decide correctfullness by committee will literally get us all get medieval on our own us to a adverse affect. Just after we finish reading another article denouncing media for writing another article about Game of Thrones written by the people who mistake auto white balance for an optical illusion.

Int’l or Intl (no dots) or Global (which means a slightly different - more correct? - thing). Ish.

Dobranoc
Mateusz

**Pull request merged**
