### PR TITLE
Log error

### PR DESCRIPTION
**Pull request by OliverJAsh**
Because it's useful.

### CODE REVIEW

**Comment by piuccio** [comment]
why?

**Comment by rich-nguyen** [comment]
I'm not sure about this either. Also, did you check for `console` for IE awesome-ness compatibility?

**Comment by OliverJAsh** [comment]
We are catching the error and reporting it to Sentry, but the error doesn't appear in the console. You see an error occured because Raven logs "captured error", but it doesn't give you the original stack trace.

All errors should be logged. If we're catching them to report to Sentry, we should most definitely be logging them alongside that.

**Comment by OliverJAsh** [comment]
> did you check for console for IE awesome-ness compatibility?

Very good point, thanks!

**Comment by piuccio** [comment]
I'll tell you what Patrick once told me.

> Don't use console.log

And if you really need it, consider a custom logger, something along the lines of [`report-errors`](https://github.com/guardian/frontend/blob/master/facia-tool/public/js/utils/report-errors.js). You don't want to repeat that ugly bit of code every time.

Moreover if `console` is not defined you'll still have a `ReferenceError` exception in IE. Better check that `window.console` is defined.

Having said that I'm still :-1: 
You only look at the console during development, so you're shipping completely useless code for the user.

**Comment by OliverJAsh** [comment]
> You only look at the console during development, so you're shipping completely useless code for the user.

Uglify has an option to strip these IIRC.

> You only look at the console during development

You need stack traces for debugging.

> Moreover if console is not defined you'll still have a ReferenceError exception in IE. Better check that window.console is defined.

Done!

I agree it could be abstracted so we don't have to remember to protect ourselves each time.

**Comment by OliverJAsh** [comment]
It's important to remember that uncaught exceptions are automatically logged by the browser. In this case, we are catching the error only to report it to Sentry with extra metadata (`feature: 'weather'`) (if uncaught, it would be automatically reported thanks to `window.onerror`). Just because we're doing that doesn't mean we want to lose the error logging, hence why I've added it back here.

**Comment by piuccio** [comment]
Did you merge by accident?

**Comment by OliverJAsh** [comment]
@piuccio Did you want to reply to my comments above? It wasn't an accident! I was being impatient.

**Comment by piuccio** [comment]
> Moreover if console is not defined you'll still have a ReferenceError exception in IE. Better check that window.console is defined.
> Done!

You didn't

> I agree it could be abstracted so we don't have to remember to protect ourselves each time.
Nothing changed

Nobody gave a +1

The build on TeamCity failed.

I'm quite surprised you merged already.

**Comment by OliverJAsh** [comment]
Acknowledged, I broke the rules.

Does it make sense why I added the logging?

**Pull request merged**
