### PR TITLE
load notification bootstray via require

### PR DESCRIPTION
**Pull request by NathanielBennett**
# My Awesome Pull Request

(not)
## What does this change?

Load the notifications module as a standard require module
## What is the value of this and can you measure success?

Notifications would work( As opposed to not at all )
## Does this affect other platforms - Amp, Apps, etc?

None
## Screenshots

See here: https://github.com/guardian/frontend/pull/12259
## 

_Does this PR meet the [contributing guidelines](https://github.com/guardian/frontend/blob/issue_pr_templates/.github/CONTRIBUTING.md#submission)?_

### CODE REVIEW

**Comment by sndrs** [comment]
does this mean we shipping notifications code to every enhanced user?

**Comment by OliverJAsh** [comment]
It does. When we're in a HTTPS world, all enhanced users will need this so it makes sense to include it in the enhanced file. In the interim it's such a small module, it shouldn't add much to enhanced. Is that ok?

**Comment by OliverJAsh** [comment]
:+1: from me if @sndrs is ok with this

**Comment by sndrs** [comment]
just for paper trail, chatted in slack about moving this to liveblog bootstrap rather than main enhanced. :+1: for that from me

**Pull request merged**
