### PR TITLE
Add buttons to new pasteup2016 library

### PR DESCRIPTION
**Pull request by sammorrisdesign-zz**
## What does this change?

This moves `pasteup-buttons` over to the new pasteup components library (of which you can read more about [here](https://github.com/guardian/frontend/pull/12490).
## Request for comment

@sndrs 
## 

_Does this PR meet the [contributing guidelines](https://github.com/guardian/frontend/blob/issue_pr_templates/.github/CONTRIBUTING.md#submission)?_

### CODE REVIEW

**Comment by sndrs** [comment]
do you reckon this should get some screen shots, to make sure buttons are actually being rendered properly?

**Comment by sndrs** [comment]
think we should get some other eyes on this: @desbo @uplne @Calanthe @regiskuckaertz @OliverJAsh anyone fancy having a look?

**Comment by uplne** [comment]
I think it's good. My only question is if we still need to keep the pasteup name (legacy reasons?). Can we just put it into `objects` folder because basically `button` is just an object with modifications. It is not component nor module.

**Comment by uplne** [comment]
👍

**Comment by sndrs** [comment]
'pasteup' will still be released to npm as a module, for 3rd parties to consume, this just moves it's home to front-end, not various other repos

**Pull request merged**
