### PR TITLE
Extending a/b tests

### PR DESCRIPTION
**Pull request by davidfurey**
## What does this change?

Extends two email a/b tests

## What is the value of this and can you measure success?

Flyer - still to work out how future a/b tests will work so extending
this one for now

Opinion - more data needed to make decision

## Does this affect other platforms - Amp, Apps, etc?

no

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]

**Review by katebee — APPROVED** [review]
👍

**Comment by katebee** [comment]
Aside thought: when these tests end, any JS on the relevant email interactive will have to be updated/deleted, so that app users also stop being bucketed.

**Comment by davidfurey** [comment]
Yes, good to remember the apps.  There is quite a bit of tidying up to do when the test ends, merging the lists, removing the magic around unsubscribing and updating the interactives. Maybe I should have extended the tests for longer!

**Comment by rich-nguyen** [comment]
@davidfurey I don't think the deploy to PROD succeeded here. It hung. This will be deployed with my changes.

**Comment by davidfurey** [comment]
@rich-nguyen thanks!

**Pull request merged**
