### PR TITLE
Show slideshow thumbnail in facia tool

### PR DESCRIPTION
**Pull request by piuccio**
Looks like this

screen shot 2015-05-05 at 17 10 03

### CODE REVIEW

**Comment by stephanfowler** [comment]
:+1: looks good

**Comment by piuccio** [comment]
Rebased to remove the merge commit and added the possibility to drag thumbnails.

You can also click on the thumb and it'll open the origin page in a new tab. If you drag an image url, it'll open the image, if you drag a crop from the grid, ideally it should open the grid again, but so far it open the image itself.

Need to discuss with @theefer on a way to link back to the original page

**Comment by paperboyo** [comment]
Already a :gem:! Thanks!

Can you rearrange by dragging to change the lineup?

Linking back to Grid would be useful to recrop. The path seems to be media.gutools.co.uk/images/[mediaID], but there probably is a much betterer magic way.

Regards
Mateusz

**Comment by piuccio** [comment]
You can sort of rearrange by dragging.
Say you drag image 1 over image 3, the result is:  1 | 2 | 1
It doesn't swap 1 with 3, but simply copies what you drag to the destination. That's the best I can do without making things overly complex.

**Comment by paperboyo** [comment]
Clever! Thx.

**Comment by theefer** [comment]
In the future I want to build a small API to resolve URLs, so you could give it say an image URL and it'd give you back the media-api URL, or a Grid UI URL, etc.

But in the meantime, it'd probably be OK to construct the URL in the way @paperboyo said (note: I've munged the URL in his comment, please avoid posting links to our internal tools on public repos), so all you need is the media ID. You can extract the ID from any image URL, but that's more brittle; I *really* recommend you store the media ID somewhere, as it will become a requirement for image usage soon.

Thanks!

**Comment by paperboyo** [comment]
Me - not clever. Sorry, @all :(

**Comment by theefer** [comment]
No worries, not the end of the world.

**Pull request merged**
