### PR TITLE
Selection sharing z-index fix

### PR DESCRIPTION
**Pull request by zeftilldeath**
Selection sharing was showing behind showcased images. Thanks @paperboyo for spotting.

screen shot 2016-01-26 at 14 30 57

### CODE REVIEW

**Comment by Jholder112233** [comment]
:+1:

**Comment by Jholder112233** [comment]
I'm going to be shipping some other stuff shortly @zeftilldeath, want me to merge this then too?

**Comment by zeftilldeath** [comment]
@Jholder112233 Yes please!

**Comment by paperboyo** [comment]
Thanks, @zeftilldeath.

**Comment by uplne** [comment]
Because this is on body scope. It should use on of the z-indexes from _zindex.scss

**Comment by zeftilldeath** [comment]
Thanks @uplne didn't know about that.

**Comment by uplne** [comment]
:+1:

**Pull request merged**
