### PR TITLE
CSS logging: Cors workaround

### PR DESCRIPTION
**Pull request by stephanfowler**
Ajax in any external stylesheets, then re-add them inline. Because JS can't access CSS rules in external stylesheets.

### CODE REVIEW

**Comment by robertberry** [comment]
That's gonna be a bit of a performance headache isn't it? :sob:

**Comment by stephanfowler** [comment]
This only affects < 1000 users / day. The only proper solution seems to be CSS served from the base domain, as @phamann suggests.

Re. forcing added stylesheets to be ignored by using a dummy `media` value, it seems you actually _can't_ inject one with a value that doesn't - or couldn't - apply to the current device. So even using `media="print"` - which anyway seems perverse - it wouldn't get injected on mobile.

**Comment by sndrs** [comment]
really? is this not what you're trying to do?

screen shot 2015-02-11 at 20 53 37

**Comment by stephanfowler** [comment]
Sorry I wasn't being clear; you _can_ add to the DOM, but it wont appear in `document.styleSheets` unless the media type is either relevant or absent.

**Comment by robertberry** [comment]
Oh riiiiiight. That makes a lot more sense - the stylesheet is probably never compiled (or interpreted or whatever) unless it's going to be used

**Comment by stephanfowler** [comment]
Yep. And I'll be dammed if I'm going to parse it with JS.

**Comment by sndrs** [comment]
this is really weird. the fact that it appears in `document.styleSheets` with a wonky `media` is exactly what the loading technique this is trying to accommodate uses. though it uses `link`s

**Comment by stephanfowler** [comment]
@sndrs I agree. Maybe injected `style` tags have different behaviour to initially present `link` tags. Did you confirm by doing `document.stylesheets` in your console example?

**Comment by sndrs** [comment]
@stephanfowler yeah i did. but in fact, sometimes it worked fine, i couldn't work out what i'd done to kick it in though.

**Comment by stephanfowler** [comment]
@sndrs - running the below in Chrome, it only accepts the last three media examples. Firefox accepts them all... except one! I will now walk away from this horror.

```
var examples = ['only x', 'only-x', 'x only', 'x', 'screen', 'print', '(max-width: 10000px)'];

function showMedia(prefix) {
  var m = [prefix];
  for (var i=0; i<document.styleSheets.length; i+=1) {
    m.push(i + ' ' + document.styleSheets[i].media.mediaText)
  }
  console.log(m.join('\n'));
}

function addSs(media) {
   var ss = window.document.createElement("style")
   ss.media = media;
   ss.innerText = 'a {color: #00f}';
   document.getElementsByTagName('head')[0].appendChild(ss);
}
showMedia('BEFORE')
examples.forEach(addSs)
showMedia('AFTER')
```

**Comment by robertberry** [comment]
:+1:

**Pull request merged**
