### PR TITLE
All retina iPads see universal fronts all the time.

### PR DESCRIPTION
**Pull request by JustinPinner**
The core fronts test for retina iPads consistently showed an improvement in the length of time those readers were on the site, and we had a marked drop in emails to user help, so we're making the change permanent.

@michaelwmcnamara are you happy with these new beacons?

### CODE REVIEW

**Comment by johnduffell** [comment]
great :+1: happy ipad users! :ship:

**Comment by stephanfowler** [comment]
:+1: - though this increases the pressure to fix ad loading (think only the first one gets loaded?)

**Comment by michaelwmcnamara** [comment]
+1 does exactly what it says on the tin :-)

**Comment by JustinPinner** [comment]
We're waiting for some comms to happen before merging. Shouldn't be too long.

**Comment by JustinPinner** [comment]
@michaelwmcnamara you mentioned this had been given the go-ahead. Could you confirm that here? Thanks.

**Comment by michaelwmcnamara** [comment]
Confirmed - we are good to go.

**Pull request merged**
