### PR TITLE
Revert "Midterms interactives header switch "

### PR DESCRIPTION
**Pull request by rcrphillips**
Reverts guardian/frontend#20619

### CODE REVIEW

**Comment by NataliaLKB** [comment]
Looks like this has a conflict. It will have be resolved before it can be merged

**Comment by rcrphillips** [comment]
@NataliaLKB hopefully that's ok now?

**Review by NataliaLKB — APPROVED** [review]
Thanks! In Future rebasing is usually better within a PR rather than merging.

**Comment by rcrphillips** [comment]
@NataliaLKB one day I'll get it right!

**Pull request merged**
