### PR TITLE
Update frontend installation docs 📜 ✨ 

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

The frontend installation docs are cluttered, disorganised and full of redundancy. This PR introduces some opinionated changes to make them easier to follow:

- Moves "Run the app" to top level heading
- Remove suggestion of installing NVM via Homebrew (a broken and unsupported approach)
- Reordering of automatic setup instructions to emphasise the need for Java SDK
- Moved Docker way down to the "Optional steps" section as most people won't need to use it
- Prefer `make watch` over `make compile`. Prefer port 3000 over port 9000 for developer convenience
- Remove repeated instructions on how to clone this repo(!)
- Remove note about `imagemin` not working on newest Node.js(?)
- Fix broken links
- Some formatting changes

## What is the value of this and can you measure success?

The updated document structure should be easier to follow from top to bottom, as a person who is installing frontend for the first time.

## Does this affect other platforms - Amp, Apps, etc?

No

## Tested in CODE?

No

### CODE REVIEW

**Comment by jfsoul** [comment]
@SiAdcock remember that a proportion of these pushes will be triggering fresh builds in TC.  You could consider pushing at the end unless critical - you're up to 4 builds so far for a docs change 😄

**Comment by jfsoul** [comment]
> You could consider pushing at the end unless critical

Or cancel TC jobs

**Comment by SiAdcock** [comment]
Apologies @jfsoul, I wanted to test changes to the markdown in the GitHub GUI as there are some strange formatting anomalies. I will cancel builds in future.

**Comment by NataliaLKB** [comment]
@SiAdcock Github markdown is definitely different! I have a sublime plugin which helps for testing.

**Review by NataliaLKB — APPROVED** [review]
Looks good to me!

**Comment by TBonnin** [comment]
We should probably remove docker. Nobody is using it.

**Pull request merged**
