### PR TITLE
Different way of parsing soulmates

### PR DESCRIPTION
**Pull request by kelvin-chappell**
This is a different approach to dealing with exceptions in the soulmates feed.

/cc @JonNorman

### CODE REVIEW

**Comment by JonNorman** [comment]
Awesome! This is much nicer than my approach to doing it. :+1:

When I went to use `asOpt`, it didn't seem to work as instead of getting a `None` I was still getting the exception (and thus `flatMap` didn't help)...but this is great, I'll close the PR I raised :)

**Comment by JonNorman** [comment]
Just one small additional comment: is there a good reason that the SoulmatesFeedTest is `@DoNotDiscover` and `with ConfigredTestSuite`?

**Comment by kelvin-chappell** [comment]
@JonNorman If you ask @rich-nguyen he'll be able to explain the test suite business.

**Comment by rich-nguyen** [comment]
looks great, just what me and @JonNorman were going to do 👍

**Pull request merged**
