### PR TITLE
Install rangefix

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

`lib/client-rects.js` contains code taken from [`rangefix`](https://github.com/edg2s/rangefix) a few years back. Now `rangefix` is an installable module (edg2s/rangefix#7), so this change replaces the former with the latter.

## What is the value of this and can you measure success?

Less code for us to maintain, more up-to-date fixes for cross-browser issues

## Does this affect other platforms - Amp, Apps, etc?

No

## Tested in CODE?

No

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]
Nice one. Should we maybe add an eslint warning for `getBoundingClientRect()` as a next step?

**Comment by SiAdcock** [comment]
@gustavpursche, `rangefix` fixes [Range.getClientRects](https://developer.mozilla.org/en-US/docs/Web/API/range/getClientRects) and [Range.getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/range/getBoundingClientRect) (as opposed to [Element.getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect). I'm not sure if it is possible to write a lint rule that prevents us from calling these methods on Ranges, but still allows us to call them on Elements.

**Review by rich-nguyen — APPROVED** [review]
Thanks for updating, @SiAdcock !

**Comment by TBonnin** [comment]
@SiAdcock is away for a couple of weeks. 
@gustavpursche: Since you seem familiar with it, would you mind merging this PR when you have some time?

**Comment by gustavpursche** [comment]
@TBonnin Happy to take it over.

**Pull request merged**
