### PR TITLE
Add live blog and sport live blog to AMP tests

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

As discussed in #14095, we should ensure that AMP live blogs and sport live blogs pass validation.
## Request for comment

@gtrufitt @jfsoul @TBonnin

### CODE REVIEW

**Comment by TBonnin** [comment]
👍

**Comment by jfsoul** [comment]
Were the test fixtures for these already present?

**Comment by SiAdcock** [comment]
Good shout @jfsoul, now added!

**Comment by jfsoul** [comment]
sehr gut 👍 

As discussed earlier I am planning to move out a few of these scala tests in another PR.

**Pull request merged**
