### PR TITLE
Garnett - Added styling for 'Topics'

### PR DESCRIPTION
**Pull request by akemitakagi**
## What does this change?
Garnett - Added styling for 'Topics'

## What is the value of this and can you measure success?
N/A

## Does this affect other platforms - Amp, Apps, etc?
N/A

## Screenshots
N/A

## Tested in CODE?
Yes.

### CODE REVIEW

**Comment by akemitakagi** [comment]
@sndrs I have cleaned up the code and now the build is green!

**Comment by akemitakagi** [comment]
@sndrs I have cleaned up the code and now the build is green!

**Review by sndrs — APPROVED** [review]
couple of things discussed IRL, great once fixed!

**Comment by akemitakagi** [comment]
I will replace the multi lines when we have better solution.

**Pull request merged**
