### PR TITLE
add new svg

### PR DESCRIPTION
**Pull request by NathanielBennett**
## What does this change?

That @superfrank has made a nice new svg for live notifications on mobile. This one's only 3K
## What is the value of this and can you measure success?

Takes off the load and looks nice. That might be a no
## Does this affect other platforms - Amp, Apps, etc?

No
## Screenshots

new-svg

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@paperboyo - is this optimised?

**Comment by jamesgorrie** [comment]
👍

**Comment by paperboyo** [comment]
> is this optimised?

Great job! One decimal place!

**Comment by superfrank** [comment]
Ofcourse it's optimised! It's Super optimised - 3K!

Tomorrow, I'll take a look at making the copy fit around the image like so. Not sure whether this should be done before we merge:
image

**Pull request merged**
