### PR TITLE
Update expiry date of chrome notifications test in JS

### PR DESCRIPTION
**Pull request by janua**
@NathanielBennett @gtrufitt

### CODE REVIEW

**Comment by gtrufitt** [comment]
Switch update?

**Comment by janua** [comment]
@gtrufitt Switch was already updated to the same date in #13262

**Comment by gtrufitt** [comment]
👍 💃

**Comment by janua** [comment]
Oops, #14130 :smile:

**Comment by NathanielBennett** [comment]
:+1: (Sorry in planning. Go for it)
(When did we <i> start </i> this test?

**Comment by janua** [comment]
Ages ago, but it's not really a test.

**Pull request merged**
