### PR TITLE
Add MaxMostRead to MostPopularAgent

### PR DESCRIPTION
**Pull request by janua**
We are currently displaying 12 items; it should be capped to 10.

@jfsoul

### CODE REVIEW

**Review by jfsoul — APPROVED** [review]
Might be worth having a comment to explain that this is in case we filter out paid-for items.

**Comment by TBonnin** [comment]
Is it a big deal if we don't show 10 (in case we filtered out a few paid-for content)?

**Comment by jfsoul** [comment]
> Is it a big deal if we don't show 10 (in case we filtered out a few paid-for content)?

You would think not, but we always get an email complaining when there are less than 10 😄

**Comment by LATaylor-guardian** [comment]
The email of those complaining is only internal though.

**Comment by janua** [comment]
Yes we always get complaints about it but only internally. I don't see a problem with having more guarantees of showing 10 though!

**Pull request merged**
