### PR TITLE
remove old html template and tidy up tailor getURL method

### PR DESCRIPTION
**Pull request by GHaberis**
## What does this change?

- Remove tailor-survey-overlay.html, this was used for Tailor (Orange) Survey (the one with the overlay). This is no longer running so this template can go.
- Tidied up the getURL method in tailor.js which chains query parameters to baseURL.
- Add bypassStorage argument to fetchData function

## What is the value of this and can you measure success?

Removes redundant code

## Does this affect other platforms - Amp, Apps, etc?

No

## Screenshots

N/A

## Tested in CODE?

No

### CODE REVIEW

**Comment by oilnam** [comment]
@GHaberis piggybacking on this PR, @lindseydew suggested that instead of having a flag to bypass the local cache we could simply set the cache to expire after 2 seconds, so that we still group together multiple requests to Tailor but we effectively make a new call to Tailor for every pageview.

**Review by MahanaC — APPROVED** [review]
Looks good! I think @oilnam is thinking of including some other changes in this

**Comment by GHaberis** [comment]
@guardian/dotcom-platform if someone can take a quick look at the tailor.js changes that'd be great!

**Review by SiAdcock — APPROVED** [review]
LGTM 👍

**Pull request merged**
