### PR TITLE
baseline for yellow play button on fronts test

### PR DESCRIPTION
**Pull request by akash1810**
baselining https://github.com/guardian/frontend/pull/13217
## Request for comment

@jamesgorrie @harrysalmon

### CODE REVIEW

**Comment by jamesgorrie** [comment]
👍

**Comment by harrysalmon** [comment]
Would it be worth excluding the video front for this?

**Comment by jamesgorrie** [comment]
> Would it be worth excluding the video front for this?

For UX, probably.

**Comment by akash1810** [comment]
> For UX, probably.

I disagree. I'd argue if the test succeeds, we'd make all play buttons yellow.

**Comment by jamesgorrie** [comment]
Go forth and test then.

**Pull request merged**
