### PR TITLE
Revert "CSS logging: cross-origin the stylessheets"

### PR DESCRIPTION
**Pull request by stephanfowler**
Reverts guardian/frontend#8269

### CODE REVIEW

**Comment by sndrs** [comment]
:+1: bye bye

**Comment by phamann** [comment]
Why the revert?

**Comment by stephanfowler** [comment]
A. Turns out it's unsupported; Chrome correctly adds an Origin header to the request, but still doesn't let JS access the CSS selectors.
B. It broke Preview, weirdly. The request gave a Cors error.

**Comment by phamann** [comment]
@stephanfowler Ok. Let's have a chat about this. As I've always wanted to experiment with serving our CSS of the top level domain to avoid the extra DNS lookup.

**Pull request merged**
