### PR TITLE
svg illustration updated, styles tweaked

### PR DESCRIPTION
**Pull request by superfrank**
## What does this change?

Illustration updated to be complete/glow added.
## Screenshots

image
## Request for comment

@katebee

### CODE REVIEW

**Comment by zeftilldeath** [comment]
Can you run illustrations this big through svgo, and we remove the xmlns/all the junk illustrator adds.

**Comment by katebee** [comment]
👍  💎 🍺

**Comment by superfrank** [comment]
Mateusz haunts  my PR's 👻 . Sorted, cheers!

**Comment by zeftilldeath** [comment]
He haunts all of our PRs 👯

**Comment by paperboyo** [comment]
giphy2

**Pull request merged**
