### PR TITLE
Adblock message understands which contributors I read

### PR DESCRIPTION
**Pull request by gklopper**
The first part of my hackday project made the "support us" adblock message understand the contributors I read.

Thought this might actually be useful, so making a PR at this point.

If I read one of the contributors then I will get that message.

contrib

### CODE REVIEW

**Comment by crifmulholland** [comment]
Nice...

**Comment by JuliaBellis** [comment]
Interesting! Thanks Grant.

On 17 November 2015 at 14:04, Grant Klopper <notifications@github.com>
wrote:

> The first part of my hackday project made the "support us" adblock message
> understand the contributors I read.
>
> Thought this might actually be useful, so making a PR at this point.
>
> If I read one of the contributors then I will get that message.
>
> [image: contrib]
> <https://cloud.githubusercontent.com/assets/76709/11213447/01396300-8d34-11e5-9633-275e3d4f6047.png>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/guardian/frontend/pull/11142
> Commit Summary
>
>    - Adblock message understands which contributors I read
>
> File Changes
>
>    - *M*
>    static/src/javascripts/projects/common/modules/commercial/donot-use-adblock.js
>    <https://github.com/guardian/frontend/pull/11142/files#diff-0> (14)
>    - *M* static/src/javascripts/projects/common/modules/onward/history.js
>    <https://github.com/guardian/frontend/pull/11142/files#diff-1> (13)
>
> Patch Links:
>
>    - https://github.com/guardian/frontend/pull/11142.patch
>    - https://github.com/guardian/frontend/pull/11142.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/11142>.
>



-- 

Julia Bellis

Product Manager - Members

Guardian News & Media

-----

julia.bellis@theguardian.com

-----

@hooliaaa <https://twitter.com/Hooliaaa>

-----

Kings Place, 90 York Way,

London N1 9GU

theguardian.com

​-----

​​Download the Guardian app for Android
<https://play.google.com/store/apps/details?id=com.guardian&hl=en_GB> and
iOS​ <https://itunes.apple.com/gb/app/the-guardian/id409128287?mt=8>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by johnduffell** [comment]
I like it!  quick win :+1: but watch out for jimmy's comment

**Comment by gklopper** [comment]
I'm not going to be able to finish this soon. Either someone else will need to take it over and test it, or else shut it down.

Note, that I think I did something that makes it not work on your first visit (hack day code)

**Comment by rich-nguyen** [comment]
closing for @gklopper , still a few issues to iron out ("it was my hackday code"). Oh dear...

**Comment by jbreckmckye** [comment]
@rich-nguyen - I'm working on this branch right now

**Comment by rich-nguyen** [comment]
@jbreckmckye sorry didn't know! thanks for that

**Comment by jbreckmckye** [comment]
Just made another little change at Mario's suggestion - if there's only one message from a familiar face, we just sample the whole pool rather than keep showing the same message on every page.

**Pull request merged**
