### PR TITLE
Gallery for AMP

### PR DESCRIPTION
**Pull request by johnduffell**
amp-carousel isn't yet supported but I've put it in anyway.

I've also split out a "main" template for AMP so we can put common stuff there, it should complement the splitting out of the CSS you did @NataliaLKB 

I'm not sure how much of the lightboxing stuff I should have left in, I feel like I shouldn't put it in at all to fit with the philosophy, but I'm keen to just get something in and we can refine later.

However I'd still be interested in opinions and suggestions!

image

### CODE REVIEW

**Comment by gklopper** [comment]
:+1:

**Comment by NataliaLKB** [comment]
@johnduffell looks great :+1: . I agree with your decision to take out all the lightboxing stuff for now. We can always add bits in later.

**Comment by gklopper** [comment]
I'm not totally convinced by the `if(isAmp){}` statements.

Would it be better for it to have its own set of templates?

**Comment by johnduffell** [comment]
so the outcome of the isAmp if statement discussuions are that we're doing the right thing so far, but we should use the right combination of if statements for small changes and separate templates for big differences.
Once we have the basics out the door we will revisit the gallery and image code with a view to making them one rather than mostly duplicated.

**Pull request merged**
