### PR TITLE
update amp identifier to new spec

### PR DESCRIPTION
**Pull request by johnduffell**
The document marker will change so I'm just updating to match - only merge when it's ready to go!

@NataliaLKB

### CODE REVIEW

**Comment by NataliaLKB** [comment]
Great! :balloon: :+1:  . Hopefully we will find out soon when to deploy this change :).

**Comment by gklopper** [comment]
:+1:

**Comment by NataliaLKB** [comment]
We just received the email that this is ready to :ship: :)

**Comment by johnduffell** [comment]
@NataliaLKB just updated this to the latest endpoints and just made the tweaks to bring everything up to standard, please could you just have another look to sanity check?  It seems to work ok locally.

**Comment by NataliaLKB** [comment]
Perfect :+1:

**Pull request merged**
