### PR TITLE
Adjust spacing on gallery caption

### PR DESCRIPTION
**Pull request by zeftilldeath**
Before:
screen shot 2015-09-21 at 17 10 57

After:
screen shot 2015-09-21 at 17 11 51

### CODE REVIEW

**Comment by Jholder112233** [comment]
:+1:

**Comment by sndrs** [comment]
if you're making the change already, be good to use a space (since you _have_ to with `-`)

:+1: tho

**Comment by johnduffell** [comment]
careful not to merge onto a red build :scream:

**Comment by johnduffell** [comment]
I'm ready to deploy, your change looks tiny so I assume you're good to go? :)

**Comment by zeftilldeath** [comment]
Ah, sorry just getting introduced to this all. Didn't know the build was red.

**Comment by johnduffell** [comment]
that's fine it takes time to understand it all!  when you get time you should really update your photo and github display name though

**Pull request merged**
