### PR TITLE
Refactoring Fronts and Email high level templates

### PR DESCRIPTION
**Pull request by TBonnin**
Goal:
- No big high level twirl templates
- Small templates with minimal logic (maybe one if or for loop)
- Easy to swap a 'component' html by another one's html
- No shared code that is only used for a given type of content
- Easy to modify a single page without affecting any other pages.

Drawback:
- Duplication on the fragments composition level

Rather than having a [shared main](https://github.com/guardian/frontend/blob/master/common/app/views/main.scala.html) template with conditions based on the content, each page is [composed of small templates](https://github.com/guardian/frontend/blob/tbonnin/refactor-templates/facia/app/pages/FrontPage.scala#L36-L60). 
This allow templates to be free of logic based on the content type ([example](https://github.com/guardian/frontend/blob/3b6a6892e844d7004403a7242e47580d3cd87b49/common/app/views/fragments/head.scala.html#L13-L15)). For instance most of the code in [the main template](https://github.com/guardian/frontend/blob/master/common/app/views/main.scala.html) is irrelevant to Fronts
It also move a lot of the logic from twirl land to Scala land (no more `@definining`, `match` or complex conditions in the twirl template)

### CODE REVIEW

**Comment by rich-nguyen** [comment]
Is there also a risk that we encourage pages to diverge and customise their own fragment compositions unnecessarily? So it would become much more tempting to choose your own fragments, even if a standardised head would have worked fine. I wouldn't go as far as saying this is a negative, but I do wonder if that's the long-term approach we want ("everyone is free to choose the fragments they want to include for the head, copy-paste if you're not sure").

There's also a risk of being unable to impose any fragment ordering, but that's an unknown issue really at this point.

**Comment by TBonnin** [comment]
Thank you for your comment @rich-nguyen. Your first concern is very valid. 
I am not sure this is a better approach, they both have advantages and inconvenients. I am interested in what people think. I would like to be convinced that this is improving the codebase. If the consensus is that it only moves complexity elsewhere I won't pursue in this direction.

**Comment by NataliaLKB** [comment]
> It also move a lot of the logic from twirl land to Scala land (no more @definining, match or complex conditions in the twirl template)
❤️

**Comment by NataliaLKB** [comment]
> I am not sure this is a better approach, they both have advantages and inconvenients. I am interested in what people think. I would like to be convinced that this is improving the codebase. If the consensus is that it only moves complexity elsewhere I won't pursue in this direction.

I am in two minds too. I certainly think this is improving what we have because it focuses on small fragments and moves much of the logic to Scala (outside the templates). 

What about if we limit this to only creating a new main template for different content types?

**Comment by TBonnin** [comment]
@NataliaLKB I feel like having a main template for each content type would lead to the same consistency issues @rich-nguyen has mentioned. It's a solution that is very close to what I propose in this PR and therefore it has the same problem I think.

**Comment by mchv** [comment]
@TBonnin I think this is the right move in terms of sustainability and maintenance of the templates

**Comment by TBonnin** [comment]
@mchv The question is then: we are working on a new way to render UI (using javascript) and therefore Twirl will be abandoned entirely. Do we want to invest time in heavily refactoring those templates if we are going to throw them away in a couple of months? It might help with the transition but I am not sure it worth the effort.

**Comment by mchv** [comment]
@TBonnin  I can't answer that question 😃

**Comment by TBonnin** [comment]
😝

**Comment by NataliaLKB** [comment]
> @NataliaLKB I feel like having a main template for each content type would lead to the same consistency issues @rich-nguyen has mentioned

@TBonnin  What I understood was that the issue of consistency was about other teams and future developers customising their own fragment compositions unnecessarily. I pictured this as for every new type of page (immersive, photo essay) people may create a new fragment composition. 

However, if you limit it to content types we have a finite number of them and it would have to be up to our team to create them. 

I may have misunderstood the problem mentioned by @rich-nguyen [here](https://github.com/guardian/frontend/pull/17823#issuecomment-330579404)

**Comment by SiAdcock** [comment]
Unrelated, but I thought I should chip in with my opinion. Composing pages in this way will help with the migration to our CSS componentisation solution, as small templates are effectively analogous to Preact components that can be swapped out when the time comes. The current approach, using huge "god templates" full of nested conditionals, makes the migration path very tricky.

It might not be perfect, as Rich points out it could be misused and lead to fragmentation of page design. However the fragmentation of design has already been happening with the god template approach, in a way that is far more difficult to implement, maintain, unpick or understand.

**Comment by TBonnin** [comment]
@NataliaLKB @SiAdcock 
I have refactored fronts, article email and fronts emails. I am planning to tackle article in a following PR to avoid pushing to many changes at once.
This PR is ready. Can you give me a thorough review? Thank you

Note: The PR touches a lot of files but a big part of it is renaming the `main` template into `mainLegacy` to allow passing the `Page` argument as an implicit, since all templates takes a `Page` argument and it makes calling the code nicer by not having to repeat `page` everywhere.

**Review by SiAdcock — APPROVED** [review]
LGTM 👍

**Pull request merged**
