### PR TITLE
Add the MVT header value into the config object.

### PR DESCRIPTION
**Pull request by JonNorman**
## Background
Currently when running an MVT, a control and a variant must be set up as separate tests in order to access and identify the page views of each in the data lake.

## What does this change?
This PR aims to simplify this, such that the `variant`/`control` nature of the test participation is exposed in the `guardian.config.tests` object and thus makes its way to the data-lake.

**This is a potentially breaking change depending on how the `tests` object is parsed downstream in the data lake!**

Looking in the `clean.pageview` table, the value for each test in the config object is parsed as a `string`, not a `boolean` and so I don't believe that this will break any type constraints as it gets ingested:

image

Currently the only people with MVTs running (included in `ActiveTests`) are @rich-nguyen ([CommercialClientLoggingVariant](https://github.com/guardian/frontend/blob/master/common/app/mvt/MultiVariateTesting.scala#L65)) and @NataliaLKB ([ABNewDesktopHeader](https://github.com/guardian/frontend/blob/master/common/app/mvt/MultiVariateTesting.scala#L67))

I don't want to disrupt the running of your tests, if it looks like this might then I'll pop over and we can have a chat about how to mitigate that.

## What is the value of this and can you measure success?
Easier to track the results of MVTs.

## Does this affect other platforms - Amp, Apps, etc?
No.

## Screenshots
**Before**
image

**After**
image

### CODE REVIEW

**Review by NataliaLKB — APPROVED** [review]
Seems like a reasonable change to me! The desktop mvt test won't be affected right now.

**Comment by NataliaLKB** [comment]
fyi @TBonnin @jfsoul

**Comment by rich-nguyen** [comment]
I wonder if the existence of the key is enough to show you are in some way part of the test, then you can have a cleaner value.

**Comment by JonNorman** [comment]
Yeah I've taken out the `switchStatus` as it is _always_ going to be true given the `filter(_.isParticipating)` statement above, which directly checks the switch.

**Pull request merged**
