### PR TITLE
Return canonical container for a front

### PR DESCRIPTION
**Pull request by jennysivapalan**
Return the canonical container for a front. The endpoint will sit on `/canonical-container/[front-path].json`

If a front has a canonical collection set this is returned otherwise the top collection is used.

cc @stephanfowler @janua

### CODE REVIEW

**Comment by janua** [comment]
:+1:
Nice changing the `id` to `collectionId`. If you see any of these that could be changed then go for it!

**Comment by jennysivapalan** [comment]
After chatting wih @stephanfowler we need to handle fall back cases for edition and section. I'll close this PR for now and re-open when that is added.

**Comment by jennysivapalan** [comment]
@stephanfowler I've added the fallbacks in based on section then edition. Do you want to give this a run through on your branch?

**Comment by jennysivapalan** [comment]
Closing as merged with #9971

**Pull request closed without merging**
