### PR TITLE
Rename robust functions for clarity and improve console logging of caught errors

### PR DESCRIPTION
**Pull request by OliverJAsh**
The robust function name doesn't tell you what it's doing, so I renamed it.

For caught errors (by `swimlane`) and for all raven captured errors (by `raven.wrap`), we were only console logging the error object. This doesn't produce a very nice output: http://jsbin.com/vimuxu/edit?js,output. Now we log caught errors as warnings, along with a reason (caught by swimlane / captured by Raven) and print the stack trace. Much friendlier.

Before:
image

Notice there is no way to see the stack trace of the actual error. The stack trace provided is just one generated by `console.error` for where the error object was logged—not where the error itself happened (`error.stack`). This is why I avoid `console.error`.

image

After:
image

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Hoping to get some improvements to `console.error` into Chrome. https://code.google.com/p/chromium/issues/detail?id=510652

**Comment by gklopper** [comment]
:+1: - is it possible to only `raven.install()` if you fall into the % of people that will report errors or is there too much raven code around?

**Comment by OliverJAsh** [comment]
Why would you want to do that? @gklopper 

AFAIK, we currently install for everyone but in the `shouldSendCallback` determine whether the error should be logged: https://github.com/guardian/frontend/pull/9790/files#diff-f19e61649c05527ea34fd7188a4ca0e0R80

**Comment by gklopper** [comment]
Yeah, don't install if you are not going to use it, but I do understand some of the wrapping will be used regardless of whether you log or not.

**Comment by OliverJAsh** [comment]
Perhaps we could do `Math.random() < 0.2 && raven.install();`? That would
mean log errors for ~20% of users, instead of log ~20% of errors.

On Thu, 16 Jul 2015 at 10:51 Grant Klopper <notifications@github.com> wrote:

> Yeah, don't install if you are not going to use it, but I do understand
> some of the wrapping will be used regardless of whether you log or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9790#issuecomment-121910479>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
