### PR TITLE
Remove some AB tests. Modify some switches.

### PR DESCRIPTION
**Pull request by stephanfowler**
@theefer : I've not removed your personal containers module, I only removed it from AB tests along with some other stuff. Just to keep things light for launch. We can reintroduce later (maybe as a "labs" preference switch rather than a zero-audience AB test.)

### CODE REVIEW

**Comment by robertberry** [comment]
:+1: Good man

**Comment by theefer** [comment]
Fair enough :+1:

**Comment by theefer** [comment]
Although I'm going to miss it, how am I going to find interesting content on the front now? :sweat: :tongue:

**Comment by stephanfowler** [comment]
@theefer We'll get it back in there. I promise.

**Pull request merged**
