### PR TITLE
Fix measure-timing.js for when there are multiple measurements

### PR DESCRIPTION
**Pull request by marjisound**
## What does this change?

In measureTiming.js:
`window.performance` is used to measure time between a start and end event. `performance.mark` is used to create a timestampt in the browser's performance entry with a given name (e.g performance.mark('start');)

`performance.measure` is used to measure the time difference between 2 keys.

`performance.getEntriesByName` is used to get the list of all measurements with a specific name. So everytime a new measurement is made `perf.measure('myPerf', 'myPerf-start', 'myPerf-end');`, an item with name 'myPerf' will be added to this list.

In the measureTiming code, it is getting the first item measureEntries[0] so the result would always be the value of the first 'myPerf' measurement, even when there are multiple 'myPerf' measurement

## Changes: 
Updates the clear function in initPerf, so that when clear is called, all the marked keys and the measures that was taken as part of the current initPerf instance will be cleared from the browser performance entry.

This way if the consumer wants to measure time multiple times with the same name, they can decide if they want to clear the marked keys and measurements.

## Does this change need to be reproduced in dotcom-rendering ?

- [ ] No
- [ ] Yes (please indicate your plans for DCR Implementation)

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by oliverlloyd** [comment]
What if there's a use case where multiple entries were desired? This is how `window.performace` works now and if we change this with our abstraction we could end up restricting who is able to use it (or worse, confusing people by changing the expected behaviour and deleting their data).

This code is currently [duplicated in DCR](https://github.com/guardian/dotcom-rendering/blob/150fc2d81e6a66d9c3336185e874fc8cd0288546/dotcom-rendering/src/web/browser/initPerf.ts) so any changes here would naturally be expected to flow into that codebase too but I'm not sure this edit would survive the transition (it could break other use cases) and if that happens the code to measure pinned post timing will also break (once it lands in DCR).

What do you think about having a wider review for how this code is used in both places and proposing a version of it in @guardian/libs?

**Comment by marjisound** [comment]
> What do you think about having a wider review for how this code is used in both places and proposing a version of it in @guardian/libs?

Thanks @oliverlloyd I wasn't aware that similar functionality is used in the DCR. I will do an analysis of all the consumptions both within the frontend and dcr and share the results later here 👍

**Comment by marjisound** [comment]
As a result of a discussion with @oliverlloyd we thought for now we can get away by just updating the `clear` function so it can properly clear all the marked keys and measure name that have been added as part of the current `initPerf` instance. 

Anothe PR was made in dcr to do the similar change in `initPerf`

**Review by oliverlloyd — APPROVED** [review]
clear means clear!

**Pull request merged**
