### PR TITLE
Upgrade to new React

### PR DESCRIPTION
**Pull request by OliverJAsh**
I broke this when upgrading React in jspm world in 858ea36431458081ad4e9dbf83423269492c6fdc

### CODE REVIEW

**Comment by rich-nguyen** [comment]
:+1:

**Comment by piuccio** [comment]
Why do we bundle react inside `static/src/javascripts/components/react/react.js` ?

**Comment by OliverJAsh** [comment]
We commit all Bower dependencies because Bower has no shrinkwrap facility.

On Tue, 23 Jun 2015 at 11:45 Fabio Crisci <notifications@github.com> wrote:

> Why do we bundle react inside
> static/src/javascripts/components/react/react.js ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9575#issuecomment-114441666>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by piuccio** [comment]
and I thought we moved out of bower

**Comment by OliverJAsh** [comment]
Still trying…

On Tue, 23 Jun 2015 at 11:54 Fabio Crisci <notifications@github.com> wrote:

> and I thought we moved out of bower
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9575#issuecomment-114443703>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
