### PR TITLE
Fix megalog import

### PR DESCRIPTION
**Pull request by jfsoul**
It looks like there is a problem with the import of megalog on one of the teamcity agents.  ~~This is an attempt to fix that by just putting the require inside the try...catch.~~  Using a dependency not specified in the `package.json` :nauseated_face: 

~~Will probably just remove megalog later, I don't think we should be using it.~~ This fix removes megalog.

### CODE REVIEW

**Comment by sndrs** [comment]
any joy trying a clean build?

**Comment by jfsoul** [comment]
Clean build has broken the build on the agent that was working.  Unfortunately my fix doesn't pass linting (incidentally: linting is how it got into this dangerous state with the `require` outside the try...catch in the first place 🙃 ).

I'm just going to remove megalog.

**Comment by sndrs** [comment]
the package hasn't changed for 18 months odd. seems very odd it would suddenly not be found?

**Comment by jfsoul** [comment]
> the package hasn't changed for 18 months odd. seems very odd it would suddenly not be found?

I think the problem is that the `require` call was moved outside the `try... catch` at some point due to linting.  For whatever reason the agents haven't run a clean build since then.  Given that it's been 4 months, I am quite surprised - but that's all I can think of.

**Comment by gustavpursche** [comment]
@jfsoul Mmh, it seems to be in the [package.json](https://github.com/guardian/frontend/blob/master/package.json#L103).

**Review by NataliaLKB — APPROVED** [review]
Makes sense to me!

**Comment by NataliaLKB** [comment]
@gustavpursche 
> @jfsoul Mmh, it seems to be in package.json.

But its not in [this package.json](https://github.com/guardian/frontend/blob/master/tools/amp-validation/package.json). Maybe thats why it can't find megalog! I still vote we just remove it from the validator

**Comment by sndrs** [comment]
yeah might as well remove. 

node will look up and up i think for modules it can't find, before failing

**Pull request merged**
