### PR TITLE
Use em-dash instead of hyphens in Epic messages

### PR DESCRIPTION
**Pull request by desbo**

### CODE REVIEW

**Comment by Mullefa** [comment]
Should we use `&mdash;` to make it explicit?

**Comment by jranks123** [comment]
👍  can't wait to see the conversion rate hit the roof

**Review by jranks123 — APPROVED** [review]

**Comment by sndrs** [comment]
this has been really bugging me :) nice one!

but yeah, maybe `&mdash;`?

**Comment by paperboyo** [comment]
🎆 

But shouldn’t it be en-dash? At least that’s what’s being used all over the site. Em-dash looks more American. I would love to know if we have any automation here (in Composer/Scribe) or does it all come from manual input?

dash

**Comment by desbo** [comment]
thanks all, I'll change this to `&ndash;`

@paperboyo I'm not sure what automation exists in our tools (someone on the tools team is bound to know though) but in this case the copy isn't coming from composer or scribe, it's just a part of the code

**Review by Mullefa — APPROVED** [review]
💨

**Pull request merged**
