### PR TITLE
 Update RR links to support new header test 

### PR DESCRIPTION
**Pull request by tompretty**
## What does this change?
Send last one off contribution date to SDC for our "support again" header test. The corresponding DCR PR is: https://github.com/guardian/dotcom-rendering/pull/3091/files#diff-5021052c4003acf93b233ffc9614f5baab19911581b166f4318997430c36330eR110-R115

## Does this change need to be reproduced in dotcom-rendering ?

- [ ] No
- [x] Yes (please indicate your plans for DCR Implementation)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [x] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [x] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by mxdvl — COMMENTED** [review]
I can see no issues from a commercial perspective. Do you need our explicit approval?

**Comment by TomPretty** [comment]
> I can see no issues from a commercial perspective. Do you need our explicit approval?

Cheers Max! I don't think so - I guess PRs automatically tag your team? I've tagged the other contribs devs to take a look!

**Review by tomrf1 — APPROVED** [review]
👍

**Comment by mxdvl** [comment]
Yes, @guardian/commercial-dev is [CODEOWNER](https://github.com/guardian/frontend/blob/13093c24dda0abe5f6eb04be0eaa8252739fc5ee/.github/CODEOWNERS#L5) of commercial modules :)

**Pull request merged**
