### PR TITLE
Commercials css tidy up

### PR DESCRIPTION
**Pull request by Calanthe**
Commercials' components css tidy up based on the css-reports tool.

Good job @stephanfowler @robertberry and @rich-nguyen

### CODE REVIEW

**Comment by robertberry** [comment]
Cool :smile: :+1: 

I've just updated the tool so it should be showing a lot more selectors soon ... it was missing most of the data set!

**Comment by stephanfowler** [comment]
:+1: great!

**Comment by phamann** [comment]
:heart: this!

**Comment by rich-nguyen** [comment]
this is great!

**Pull request merged**
