### PR TITLE
Main media captions in immersive style templates

### PR DESCRIPTION
**Pull request by zeftilldeath**
Captions are now visible on templates with an immersive style header. As requested by photo editors. Due to template restraints, I've had to insert the code twice in different templates. 

screen shot 2018-07-12 at 15 20 12
screen shot 2018-07-12 at 15 20 26
screen shot 2018-07-12 at 15 20 38
screen shot 2018-07-12 at 15 20 51

Thanks @QuarpT for the twirly goodness.

### CODE REVIEW

**Review by Joshua-David — APPROVED** [review]
Nice one Zef

**Comment by paperboyo** [comment]
This is great and will stop these fields being left in a poor state by the Editors. Also, may stop having to add this manually at the bottom of the body. Good times long overdue!

Some observations:

- if the edits are carried out to Composer fields after the piece was launched, the changes in CAPI are not reflected on the frontend. [Example](https://www.theguardian.com/news/2018/jul/13/poles-apart-the-bitter-conflict-over-a-nations-history-poland-monuments-communism-soviet-union):

image

CAPI:

image

- is the repetition visible in the first screenshot intentional?

- `Main image: Photograph:` problem can be sorted e.g. by dynamically combining three CAPI fields instead of using the composite Credit field. `imageType` would need to be decapitalised.

**Comment by paperboyo** [comment]
> dynamically combining three CAPI fields instead of using the composite Credit field

Just a reminder that in specific circumstances 1 + 1 ≠ 2. We have some [magic that modifies `credit` field](https://github.com/guardian/flexible-content/pull/1528).

**Comment by zeftilldeath** [comment]
@paperboyo The link doesn't work for me, got another?

**Pull request merged**
