### PR TITLE
Added a new email banner to email news letter 'The Snap'

### PR DESCRIPTION
**Pull request by akemitakagi**
## What does this change?
Added a new email banner to email news letter 'The Snap'

## Screenshots
the-snap

### Does this affect other platforms?
No

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?
No

### Does this change break ad-free?
No

### Does this change update the version of CAPI we're using?
No

### Accessibility test checklist

Colour contrast passed

### Tested
No

### CODE REVIEW

**Comment by gtrufitt** [comment]
There's a submodule added that I don't think you would have meant to add `submodule frontend added at 7bf717`?

**Review by gtrufitt — COMMENTED** [review]
Hey, this looks good, but just need to remove the submodule! If you ping me I'll approve when that's gone :)

**Comment by akemitakagi** [comment]
Thank you, I will remove the submodule. I have no idea why it added...

**Review by gtrufitt — APPROVED** [review]
👍

**Pull request merged**
