### PR TITLE
Purple rain

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

Add a feature switch to make the default weather icon be purple rain
## Screenshots

screen shot 2016-04-21 at 21 42 37

### CODE REVIEW

**Comment by JustinPinner** [comment]
👍 👍 👍 🎸 👑 💀 😢

**Comment by paperboyo** [comment]
:gem:!

**Comment by gtrufitt** [comment]
💜

**Comment by AWare** [comment]
image

**Pull request merged**
