### PR TITLE
<picture> again

### PR DESCRIPTION
**Pull request by samdesborough**
Same as last time but with a change to picturefill that fixes the iOS issue we saw last night.

The problem was that picturefill reprocesses every element on the page whenever a resize event is fired, and for some reason iOS Safari fires that event on scroll. The fix is to only reprocess if the browser width has actually changed rather than on any resize event. There's a 250ms debounce so it'll take that long to update image sizes when it has to. 

The next version of picturefill should include more general performance fixes so we can revisit this when it's out.

### CODE REVIEW

**Comment by robertberry** [comment]
Awesome. Well done on figuring this out. We should test on a bunch of devices tomorrow, happy to lend a hand

**Comment by phamann** [comment]
Ironically the Picturefill team released the [`2.3 beta`](https://github.com/scottjehl/picturefill/releases/tag/2.3.0-beta) last night which fixes many of the issues we forked to fix. I know its annoying, but i'd like to give that a go first.

I'm also having second thoughts on a our use of the full `<picture>` element implementation vs `` with `srcset` & `sizes`, mainly due to it to adding a ton more nodes to the DOM which we cannot afford.

Let's chat when you are in this morning.

**Comment by robertberry** [comment]
It's easy enough to switch over to img with srcset.

On 12 February 2015 at 09:29, Patrick Hamann <notifications@github.com>
wrote:

> Ironically the Picturefill team released the 2.3 beta
> <https://github.com/scottjehl/picturefill/releases/tag/2.3.0-beta> last
> night which fixes many of the issues we forked to fix. I know its annoying,
> but i'd like to give that a go first.
>
> I'm also having second thoughts on a our use of the full <picture>
> element implementation vs  with srcset & sizes, mainly due to it to
> adding a ton more nodes to the DOM which we cannot afford.
>
> Let's chat when you are in this morning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/8296#issuecomment-74041369>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by samdesborough** [comment]
The beta will still need forking for the resize fix, so I think we should stick with our version until 3.0 comes out and have a look at srcset/sizes in the meantime

**Comment by phamann** [comment]
ships-shipping-ships-blue-marlin

**Pull request merged**
