### PR TITLE
Consolidate media type styles for Garnett

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

Now media is a design type and audio, gallery and video are modifiers of the item card. I have reflected this in the code structure

### CODE REVIEW

**Comment by GHaberis** [comment]
@SiAdcock is this required now https://github.com/guardian/frontend/pull/18491 has been merged?

**Comment by SiAdcock** [comment]
Yeah, this is a continuation of @blongden73's excellent work in that PR

**Comment by GHaberis** [comment]
@SiAdcock OK I see, this just reorganises the changes from https://github.com/guardian/frontend/pull/18491 so they sit more appropriately within the code structure?

**Review by GHaberis — APPROVED** [review]
👍

**Pull request merged**
