### PR TITLE
byline img size fix

### PR DESCRIPTION
**Pull request by uplne**
Before:
screen shot 2015-12-01 at 17 10 26

After:
screen shot 2015-12-01 at 17 09 45

CC @johnduffell

### CODE REVIEW

**Comment by johnduffell** [comment]
don't forget to remove it from here too: https://github.com/guardian/frontend/blob/06fa6124404b8d71cc9d578e8c0fd3d03ca9871b/common/app/views/main.scala.html#L36

**Comment by johnduffell** [comment]
and https://github.com/guardian/frontend/pull/9487/files#diff-ee913680739104818d4de725be46fce4R41

**Comment by uplne** [comment]
@johnduffell done

**Comment by johnduffell** [comment]
did you do the second one? https://github.com/guardian/frontend/pull/9487/files#diff-ee913680739104818d4de725be46fce4R41

**Comment by uplne** [comment]
By second one you mean has-localnav?

I've looked up all usages of has-widenav and removed them.

**Comment by johnduffell** [comment]
I just mean remove the code I linked to second that I added in the same pr, I think it's only used for the code you removed:
```
+  // arbitrary cutoff, feel free to tweak - https://github.com/guardian/frontend/pull/9487
+  val repelCutout: Boolean = links.size > 5
+
```
:stuck_out_tongue_closed_eyes:

**Comment by uplne** [comment]
Ah I see

**Comment by uplne** [comment]
I am closing this PR as it has some weird conflicts with master. I will create a new one.

**Pull request closed without merging**
