### PR TITLE
New email headers

### PR DESCRIPTION
**Pull request by Joshua-David**
## What does this change?
Email banners - added in two new designs for bookmarks and the long read emails

## What is the value of this and can you measure success?
Not applicable 

## Does this affect other platforms - Amp, Apps, etc?
No

## Screenshots
Not applicable 

## Tested in CODE?
No

### CODE REVIEW

**Comment by gustavpursche** [comment]
@Joshua-David Could you please compress the images a bit more? Just tested it with https://tinypng.com - first image goes from 23kB to 8kB :)

**Comment by Joshua-David** [comment]
@gustavpursche sure thing, have just compressed them further and pushed

**Review by gu-stav — APPROVED** [review]
Nice, thanks! Rest of the code looks good to me.

**Review by NataliaLKB — APPROVED** [review]
Seems fine to me!

**Comment by NataliaLKB** [comment]
> Screenshots not applicable 

😆 Not sure this really made sense. Surely screenshots are always applicable on a design change. Regardless I trust that you have tested how this looks.

**Pull request merged**
