### PR TITLE
Clear out old clean-up code from the header JS

### PR DESCRIPTION
**Pull request by sndrs**
been a month, time to go

### CODE REVIEW

**Comment by jbreckmckye** [comment]
I thought there was a module somewhere that let us clear out old legacy localstorage keys, but I can't find it any longer...

**Comment by sndrs** [comment]
this needs to run outside the module system, unfortunately

**Comment by jbreckmckye** [comment]
I can't remember what the module is, but it essentially clears localstorage entries for keys that were once used, but aren't used any more. You're not relying on the property any more so you shouldn't need the value to be cleared in the critical path scripts.

**Comment by jbreckmckye** [comment]
:+1:

**Pull request merged**
