### PR TITLE
Inline first image of a tweet at mobile breakpoint

### PR DESCRIPTION
**Pull request by gklopper**
We don't upgrade tweets at mobile for perf reasons. This is most annoying for images.

This inlines images at mobile breakpoints.

tweets

### CODE REVIEW

**Comment by johnduffell** [comment]
:+1: that's great!  just a random thought - will the image be reloaded if the tweet is enhanced (at other breakpoints), or does it use the exact same url for the enhanced version?

**Comment by gklopper** [comment]
There is just 1 image URL per image

**Comment by NataliaLKB** [comment]
Looks good! :+1:

**Comment by gklopper** [comment]
having said that, since we call in Twitter javascript, they could theoretically do anything they want

**Comment by janua** [comment]
:+1:

**Pull request merged**
