### PR TITLE
Drag images in their textarea

### PR DESCRIPTION
**Pull request by piuccio**
You can now drag and drop images into any image textarea (slideshow, cutout, replace).

Works dragging from the grid, or any image url (however once validated, the url must be guim.co.uk)

@stephanfowler 
fyi @theefer

### CODE REVIEW

**Comment by theefer** [comment]
Nice one! Would love to see it in action too.

**Comment by paperboyo** [comment]
Woohoo! :gem:! Thanks, @piuccio!

It used to work only for the Replace image by dragging over the whole of the item (bar showing in the bottom). Is that now removed and replaced by dragging onto text area of Replace image (needing extra click to expose it) or do both methods work?

Regards
Mateusz

**Comment by stephanfowler** [comment]
:+1: good one

**Comment by piuccio** [comment]
@paperboyo both methods work

**Comment by paperboyo** [comment]
@piuccio Cool! Thx!

**Pull request merged**
