### PR TITLE
Use `JsValue` Not `String` For DCAR

### LINKED ISSUE #27616: Consider Sending JSON To DCAR Without Converting To String
In general, for methods that involve sending JSON to DCAR, we first convert that JSON to a `String`:

https://github.com/guardian/frontend/blob/badc416fea72386526e907380f7e361078d9c218/common/app/renderers/DotcomRenderingService.scala#L214-L215

https://github.com/guardian/frontend/blob/badc416fea72386526e907380f7e361078d9c218/common/app/model/dotcomrendering/DotcomRenderingDataModel.scala#L194-L197

and then POST that `String` to DCAR:

https://github.com/guardian/frontend/blob/badc416fea72386526e907380f7e361078d9c218/common/app/renderers/DotcomRenderingService.scala#L56-L69

However, we're typically working with Play JSON:

https://github.com/guardian/frontend/blob/badc416fea72386526e907380f7e361078d9c218/common/app/model/dotcomrendering/DotcomRenderingDataModel.scala#L116-L117

and it should be possible to pass an instance of this to WS directly without going via an intermediate `String`[^1]. Doing this may be better for performance; we should test this.

[^1]: https://www.playframework.com/documentation/3.0.x/ScalaWS#Submitting-JSON-data

### PR DESCRIPTION
**Pull request by JamieB-gu**
Frontend posts the data for articles, fronts, tags pages and so on to DCAR as JSON, using `WSClient`. At the moment the following steps are taken to transform from an instance of a case class in frontend to the format that `WSClient` uses (`BodyWritable`):

```
case class instance -> JsValue -> String -> BodyWritable
```

The final transformation here, `String -> BodyWritable`, is handled by `WSClient`, as it defines an implicit way to get from one type to the other[^1]. However, it also defines a way to do this for a `play-json` `JsValue`[^2], so we do not need to convert to a `String` beforehand. We should be able to pass a `JsValue` to `WSClient` directly, removing one of the transformation steps:

```
case class instance -> JsValue -> BodyWritable
```

The way to achieve this is by modifying our methods that use `WSClient.post` to take a `JsValue` payload instead of a `String`. We are then able to update the `toJson` methods on each of our models to remove the `Json.stringify` step. However, aside from `RemoteRender` requests, these `toJson` methods are also used to provide for `JsonFormat` requests via the `renderJson` method, which at the moment requires a `String`. This method, though, makes use of Play's `Writeable`, which also includes an implicit transformation to get from a `play-json` `JsValue`[^3]. So we can update it to take a `JsValue` instead, and save the additional `String` transformation step here too.

Note that there is one exception where we're using `circe` instead of `play-json`, for crosswords, so in that case we're transforming from one to the other via `String`.

Paired with @rtyley 

[^1]: https://www.playframework.com/documentation/3.0.x/api/scala/play/api/libs/ws/WSBodyWritables$.html#writeableOf_String:play.api.libs.ws.BodyWritable[String]
[^2]: https://www.playframework.com/documentation/3.0.x/api/scala/play/api/libs/ws/WSBodyWritables$.html#writeableOf_JsValue:play.api.libs.ws.BodyWritable[play.api.libs.json.JsValue]
[^3]: https://www.playframework.com/documentation/3.0.x/api/scala/play/api/http/Writeable$.html#writeableOf_JsValue:play.api.http.Writeable[play.api.libs.json.JsValue]

### CODE REVIEW

**Comment by rtyley** [comment]
Lovely stuff! I see the tests have failed, but from a quick look at the [logs](https://github.com/guardian/frontend/actions/runs/12050925737/job/33600828256?pr=27641#step:10:713), maybe the only failing test was `DotcomRenderingServiceTest`:

```
[info] DotcomRenderingServiceTest:
[info] post
[info] - should return a 404 for DCR 415 errors *** FAILED ***
[info]   java.lang.IllegalArgumentException: Can't find a private method named: post
[info]   at org.scalatest.PrivateMethodTester$Invoker.invokePrivate(PrivateMethodTester.scala:247)
[info]   at renderers.DotcomRenderingServiceTest.$anonfun$new$1(DotcomRenderingServiceTest.scala:52)
```

...this is because the test is mocking the `post()` method, which has been changed to take a `JsValue` payload, rather that a `String`:

https://github.com/guardian/frontend/blob/55da434a4978fac7669fb49ac0da8e5e577fcc79/common/test/renderers/DotcomRenderingServiceTest.scala#L38-L55

Incidentally, it was quite hard to search the logs for the failure. Using something like https://github.com/test-summary/action or https://github.com/EnricoMi/publish-unit-test-result-action could make finding failing tests on Frontend much friendlier?

**Comment by JamieB-gu** [comment]
> Thanks @JamieB-gu and @rtyley this sounds good to me. I'm not fully clued up on the full impact of this change, and it's possible future travellers will want to know, so I was hoping you could answer for the record:
> 
> 1. Are we likely to observe any benefits as a result of this change, other than the apparent reduction in complexity?
> 2. Do you know why we went down the `JsValue -> String -> BodyWritable` path in the first place?
> 3. Are we making any trade-offs by doing this?
> 
> Thanks in advance 🙏

Thanks @SiAdcock! To answer the questions:

1. Yes we hope so, we believe it may result in a performance improvement for two reasons. The first is that we're no longer doing this extra transformation step, so it may result in lower CPU usage. The other is that we're no longer creating extra `String`s in memory, which will hopefully reduce memory usage and garbage collection.
2. Deferring to @rtyley below.
3. Deferring to @rtyley below.

**Comment by rtyley** [comment]
> 2. Do you know why we went down the `JsValue -> String -> BodyWritable` path in the first place?

The Playframework hides away the existence `BodyWritable`, using an implicit transformation to transform the object (whether a `JsValue` or a`String`) into bytes that can be transmitted over the HTTP connection. So most developers wouldn't have been aware of the `BodyWritable` part! So the question becomes: why did `JsValue -> String` occur? I think  that's probably not an area that many developers were aware that a performance optimisation could occur - the code [originally occurred](https://github.com/guardian/frontend/pull/20528/files#diff-226a2f55912aeab5d0800fe01df264dd358642019223e3b4676940359360a3a6) in https://github.com/guardian/frontend/pull/20528 in October 2018, when the method was originally called, accurately, `toJsonString`. It was probably copied and pasted a lot since then!

> 3. Are we making any trade-offs by doing this?

Can't think of any negatives - the code is more strongly-typed, and the copying operations look to be more efficient because they're not doing unnecessary array-copying!

**Review by SiAdcock — APPROVED** [review]

**Comment by rtyley** [comment]
I've taken a quick look at the [graphs](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2?graph=~(metrics~(~(~'Application~'G1_Young_Generation-gc-count-per-min~'ApplicationName~'facia~'Stage~'PROD~(visible~false))~(~'.~'G1_Young_Generation-gc-time-per-min~'.~'.~'.~'.~(yAxis~'left~visible~false~stat~'Maximum))~(~'AWS*2fAutoScaling~'GroupInServiceInstances~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~stat~'Minimum~period~60~visible~false))~(~'Application~'front-download-latency~'ApplicationName~'facia~'Stage~'PROD~(stat~'SampleCount~visible~false))~(~'.~'front-not-modified-download-latency~'.~'.~'.~'.~(stat~'SampleCount~visible~false))~(~'AWS*2fEC2~'CPUUtilization~'AutoScalingGroupName~'frontend-PROD-FaciaStack-1AZBJHR7UVRVD-AutoscalingGroup-1HT7KW72DG2K0~(yAxis~'right~period~900~visible~false))~(~'.~'NetworkIn~'.~'.~(visible~false))~(~'Application~'front-decoding-latency~'ApplicationName~'facia~'Stage~'PROD~(period~900~visible~false))~(~'.~'front-download-latency~'.~'.~'.~'.~(visible~false))~(~'.~'G1_Young_Generation-gc-count-per-min~'.~'applications~'.~'.~(visible~false))~(~'...~'article~'.~'.)~(~'.~'G1_Young_Generation-gc-time-per-min~'.~'applications~'.~'.~(stat~'Maximum))~(~'...~'article~'.~'.~(stat~'Maximum)))~view~'timeSeries~stacked~false~region~'eu-west-1~stat~'Average~period~300~start~'-PT12H~end~'P0D~yAxis~(right~(min~0)~left~(min~0))~annotations~(vertical~(~(color~'*232ca02c~label~'PR*20*2327641*20deployed~value~'2024-12-13T13*3a07*3a00.000Z))))&query=~'*7bApplication*2cApplicationName*2cStage*7d*20Stage*3d*22PROD*22*20MetricName*3d*22G1_Young_Generation-gc-time-per-min*22) after this got merged at 1:07pm - I was wondering if garbage collection might have noticeably improved due to these changes, and unfortunately there's been no obvious overall change, at least not yet. Still, I think the change is still justified in terms of code clarity!

image

**Pull request merged**
