### PR TITLE
Story Package Container Tweaks

### PR DESCRIPTION
**Pull request by sammorrisdesign-zz**
Various tweaks made to the story package container that were omitted from the last PR (because that was turning into a monster). This includes...
- **General cleanup of presentation** that involves removing a few overrides and picking a few different slices. Also no more 5:2 crops.
- **Add optional snap group** by adding a new sub-grouping of content. This adds a `snap` group to the `dynamic/story-package` container. The intention for doing this is to achieve something [like this (design pending)](http://c.sammorr.is/afQS) for the election coverage coming up.
- **Allow the standard slice level of a dynamic container take multiple slices** and then use it when you add 5 stories to the `dynamic/story-package`.

Improvements and less lines of code. Am I doing it right?

cc @robertberry @sndrs @phamann

### CODE REVIEW

**Comment by phamann** [comment]
> The intention for doing this is to achieve something [like this (design pending)](http://c.sammorr.is/afQS) for the election coverage coming up.

Only if the design in that image stays the same

**Comment by sndrs** [comment]
sass looks fine, and nothing i can spot in scala but i'd check with someone who can be more sure, given how important this would be? :+1: for sass though

**Comment by robertberry** [comment]
It looks good to me, but test a few fronts to make sure the containers are coming out the same for you locally as they are on PROD or CODE (whichever you're pointing to)

**Comment by sammorrisdesign** [comment]
Good idea. I have compared a few and played around with both existing dynamic containers they look the same on code as they do locally.

**Pull request merged**
