### PR TITLE
Actually fix [select all] button in consents

### PR DESCRIPTION
**Pull request by walaura**
## What does this change?
#19210 fixed [select all] causing race conditions by faking one click each 100 ms, reaching a very horrible goofy compromise to fix most issues. This PR actually goes back and fixes it for good by debouncing click handlers in all the respective input fields and eventually sending 1 single ajax request with all the changes.

This solution is extremely over-engineered but it lets the [Select all] button still quite literally select all checkboxes in the page while leaving the handling of what to do when a lot of checkboxes are pressed to the individual checkbox components. (This means less duplicate code!)

### CODE REVIEW

**Comment by jfsoul** [comment]
I think this is great, but we need to be super cautious about these kind of changes at the moment.  We'll need to do plenty of testing on this.

**Comment by walaura** [comment]
@jfsoul doing browser testing at the moment but in principle this should actually _improve_ browser support for older browsers

**Comment by SiAdcock** [comment]
Thanks @walaura. I think I'd be inclined to go with a third party library for the debounce promise. It would mean less code for us to maintain and a [library like this one](https://github.com/bjoerge/debounce-promise) actually has tests, is more likely to catch edge cases, can be tested for security vulnerabilities, etc.

What do you think?

**Comment by walaura** [comment]
@SiAdcock absolutely agree. Can we have a chat tomorrow on how to bundle it in our code? That's (well, and sheer stubbornness) mostly what kept me from putting it in there in the first place!

**Review by SiAdcock — APPROVED** [review]
Thanks for this @walaura! 💎

**Pull request merged**
