### PR TITLE
Update capi and fapi dependencies.

### PR DESCRIPTION
**Pull request by LATaylor-guardian**
## What does this change?
Update CAPI and FAPI dependencies.

## What is the value of this and can you measure success?
N/A

## Does this affect other platforms - Amp, Apps, etc?
N/A

## Screenshots
N/A

### CODE REVIEW

**Comment by gidsg** [comment]
>What is the value of this

There is value! As it exposes new fields to frontend and facia.

**Review by gidsg — APPROVED** [review]
Looks good to me, but if you don't want to test pressing locally, please deploy to CODE and check that updating a managed front works before merging.
You should also update the version in https://github.com/guardian/facia-tool to keep them in sync.
CC @Reettaphant

**Review by jfsoul — APPROVED** [review]

**Comment by LATaylor-guardian** [comment]
@gidsg Yup, I'll test on CODE first and update that repo also.

**Comment by LATaylor-guardian** [comment]
Tested with @gidsg on CODE and looks fine. Merging.

**Pull request merged**
