### PR TITLE
Remove structured data pages.

### PR DESCRIPTION
**Pull request by LATaylor-guardian**
## What does this change?
This changes removes the recently added structured data pages from Frontend.

## What is the value of this and can you measure success?
After testing this for a number of weeks its been decided that they haven't had the impact and value add we would have liked so they are now being cleaned up and removed.

## Does this affect other platforms - Amp, Apps, etc?
No.

## Screenshots
No.

## Tested in CODE?

Note: Please do not merge until the links to these pages have also been removed. I will add a note back in here once this has happened.

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
@jfsoul @NataliaLKB

**Review by NataliaLKB — APPROVED** [review]

**Comment by NataliaLKB** [comment]
Thanks for cleaning up!

**Comment by LATaylor-guardian** [comment]
@NataliaLKB You're most welcome :)

**Comment by regiskuckaertz** [comment]
Are these the recipes fronts @mchv told me about? Dammit, I thought that was a great idea.

**Comment by LATaylor-guardian** [comment]
@regiskuckaertz Yes they are.

**Comment by LATaylor-guardian** [comment]
@chriswilk maybe you can provide some explanation around what you saw as for your reasons for wanting them removed for others?

**Pull request merged**
