### PR TITLE
Adjust crossword controls

### PR DESCRIPTION
**Pull request by sndrs**
before
screen shot 2015-04-10 at 11 44 58

after
screen shot 2015-04-10 at 11 48 37

cc @Pearson82 @crifmulholland

### CODE REVIEW

**Comment by Pearson82** [comment]
Looks better. The blue type on blue button might struggle with accessibility, so might be worth darkening it. @sndrs

**Comment by sndrs** [comment]
@Pearson82 good point.

darkened to this:

screen shot 2015-04-10 at 12 57 43

**Comment by Pearson82** [comment]
I'm out of office now, but looks good on my phone

On Friday, April 10, 2015, Alex Sanders <notifications@github.com> wrote:

> @Pearson82 <https://github.com/Pearson82> good point.
>
> darkened to this:
>
> [image: screen shot 2015-04-10 at 12 57 43]
> <https://cloud.githubusercontent.com/assets/867233/7087261/52b6a7ee-df81-11e4-8c80-9fdacda25a87.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/8821#issuecomment-91532417>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by robertberry** [comment]
Cool. :+1:

**Pull request merged**
