### PR TITLE
Add preconnect link for DFP library

### PR DESCRIPTION
**Pull request by regiskuckaertz**
@rich-nguyen @JonNorman

### CODE REVIEW

**Comment by piuccio** [comment]
`Configuration.googletag.jsLocation` suggest a javascript file location. `preconnect` works with origins, not with specific files. Well maybe browser are smart enough to extract the origin out of any path, is that the case?
If that's an actual file maybe you can use [prefetch](http://caniuse.com/#feat=link-rel-prefetch) that seems to have better support than [preconnect](http://caniuse.com/#feat=link-rel-preconnect)

**Comment by regiskuckaertz** [comment]
you can put a fully qualified URL there, the browser will figure out the domain

**Comment by piuccio** [comment]
I didn't think browsers were that smart 👅

**Comment by regiskuckaertz** [comment]
😆 

`prefetch` is just a hint, the browser decides whether or not to follow it—`preconnect` is an order.

**Comment by piuccio** [comment]
go for the order 👍

**Comment by rich-nguyen** [comment]
👍

**Pull request merged**
