### PR TITLE
Cc fix css promise

### PR DESCRIPTION
**Pull request by Calum-Campbell**
## What does this change?
- Second go at ES6 update of LoadCssPromise. 
- This time round deconstruct the object imported into the javascript legacy files that have not been upgraded to ES6 yet. 
- When these files are upgraded the deconstruction will need to be removed.
- This method continues the pattern of not using default exports

## What is the value of this and can you measure success?
- ES6
## Does this affect other platforms - Amp, Apps, etc?
- Shouldn't do

## Tested in CODE?
- No

### CODE REVIEW

**Review by lps88 — COMMENTED** [review]
Have you made the change for all the usages of this module? e.g.

`static/src/javascripts-legacy/projects/common/modules/ui/smartAppBanner.js`

**Comment by Calum-Campbell** [comment]
@lps88 Ah no missed that one, will update, thanks.

**Review by lps88 — APPROVED** [review]
Looks good 👍

**Review by sndrs — APPROVED** [review]
nice

**Pull request merged**
