### PR TITLE
Remove all references to config lib from commercial bundle

### PR DESCRIPTION
**Pull request by Jakeii**
## What does this change?
Remove all references to config lib from commercial bundle with the power of regex, to simplify eventual migration to commercial-core.

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by arelra — APPROVED** [review]
Epic 🚀 

As long as everything is functionally equivalent it _should_ be a straightforward update.

Where we've touched some shared code (assuming its still used) it might be worth letting the teams involved know - identity and supporter revenue?

**Comment by SiAdcock** [comment]
Thanks @Jakeii. It's pretty cool that as part of this, you have made the type definition for `PageConfig` even more complete 🎉

**Review by chrislomaxjones — APPROVED** [review]
This is such a big improvement! 👏

Now it shouldn't be much work to figure out which subset of the `window` properties we're using in the commercial bundle.

**Comment by Jakeii** [comment]
Hey @guardian/identity and @guardian/conversions-developers just letting you know I've a moved a couple instances of `config.get` to `window.config` in a few shared libs, they're functionally identical, so shouldn't affect anything.

**Comment by ashishpuliyel** [comment]
I'm coming in late, but this is great, and I wanted to say that.

**Pull request merged**
