### PR TITLE
Use ES2020 CMP

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

- updates webpack config to put all `@guardian` scope npm packages through babel pipeline (as per https://github.com/guardian/dotcom-rendering/pull/1919 and https://github.com/guardian/recommendations/blob/master/client-side.md#guardian-packages)
  - expcept `@guardian/automat-modules` (see comments below)
- bumps all `babel` deps to latest

this allows for:

- updates CMP to ES2020 version

### CODE REVIEW

**Review by tjmw — APPROVED** [review]
:+1: Nice! I'd got as far as updating the regexp and opening a draft PR (#23006) but I was getting some errors from `make watch` which I'd not gotten to the bottom of (see thread in Client Side chat). I'm guessing you weren't seeing them? Maybe the bumps to various babel packages fixed things?

**Comment by sndrs** [comment]
>  I'm guessing you weren't seeing them? Maybe the bumps to various babel packages fixed things?

yeah i think so – i needed to bump them for compile to work, so i guess they were the same thing? does this branch look ok to you?

**Comment by tjmw** [comment]
Hi @sndrs I'm still seeing a few errors (on this branch locally) when I run `make watch`. For each instance in frontend where we call `mountDynamic` I see:

```
"export 'mountDynamic' was not found in '@guardian/automat-modules'
```

Though I'm not seeing the CMP error which I was before which was:

```
"export 'ConsentManagementPlatform' was not found in '@guardian/old-cmp/dist/ConsentManagementPlatform'
```

Though I see now that's probably gone away since removing old-cmp in #23008. Perhaps it's something in the config of `@guardian/automat-modules` which is causing the issue?

Really interesting if you're not getting that locally though. I wonder what the difference in our dev envs could be? Happy to pair on this if it'd be useful!

**Comment by sndrs** [comment]
@tjmw i think the issue was that `@guardian/automat-modules` is only published as a cjs module. for the moment i've updated the webpack config to not include `@guardian/automat-modules`, but i think if you update it to publish a `module` version too, you can remove that here

**Comment by tjmw** [comment]
Ah thanks @sndrs, that makes sense. Yeah `cjs` is specified [here](https://github.com/guardian/automat-client-v2/blob/master/src/modules/rollup.config.js#L19). I'm not sure of the Rollup API, perhaps that can be switched to `module` (or we output `module` as well as `cjs`). Still omitting this from transpilation seems like a good way to go for the time being (and matches what we're doing already on `main` I think. /cc @nicl

**Comment by sndrs** [comment]
@tjmw here's an example dual format config if it helps https://github.com/guardian/consent-management-platform/blob/main/src/rollup.config.js

**Pull request merged**
