### PR TITLE
Es6: bootstraps/youtube_embed

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

very little, but no longer exporting an `init` method, just calling it. @regiskuckaertz does that look ok to you? only ref I could find to this is https://github.com/guardian/frontend/blob/5d8ab10f0599683b1b723e67fc36b91ed2dd7561/common/app/model/meta.scala#L417
is `init` called somewhere else?

### CODE REVIEW

**Comment by GHaberis** [comment]
@sndrs if you rebase with `master` this will hopefully fix the checks

**Comment by sndrs** [comment]
cheers @GHaberis

**Review by regiskuckaertz — APPROVED** [review]
Yep, all good. The module is inserted [here](https://github.com/guardian/frontend/blob/master/applications/app/views/fragments/atomPageHead.scala.html#L13) so it's perfectly fine.

**Comment by sndrs** [comment]
thanks @regiskuckaertz

btw, https://github.com/guardian/frontend/search?utf8=✓&q=page.javascriptModule suggests its inlined anyway? no need to preload?

**Comment by regiskuckaertz** [comment]
Oh yeah you're right 😮  Thanks, I'll get rid of that line

**Pull request merged**
