### PR TITLE
Fix logical fallacy to detect wider columns for comments in articles

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Currently a `.discussion__ad-wrapper-wider` class is added to the container of the comments MPU in all cases except when the page is both a liveblog and a minute article—i.e. always.

Here is what happens:
picture 1

### CODE REVIEW

**Comment by jbreckmckye** [comment]
One step at a time...

:+1:

**Comment by regiskuckaertz** [comment]
I wish one day there won't be an expired switch coming in the way :sob:

**Comment by gtrufitt** [comment]
Whoops, my bad :+1:

**Comment by sndrs** [comment]
:dizzy: :dizzy_face:

**Comment by regiskuckaertz** [comment]
http://giphy.com/gifs/fcK30LKXjG6Tm

**Pull request merged**
