### PR TITLE
background colour added, illustration extended

### PR DESCRIPTION
**Pull request by superfrank**
White BG is displaying so image looks broken at largest breakpoints

image

@katebee

### CODE REVIEW

**Comment by katebee** [comment]
Can't spot the change in the SVG 😂 😭  Do you have an 'after' pic?

**Comment by superfrank** [comment]
It's exactly the same! Just twice the width so SVG is now 5200, rather than 2600.

**Comment by superfrank** [comment]
image

**Review by katebee — APPROVED** [review]
Woop! 👍

**Pull request merged**
