### PR TITLE
Reinstate dreamsnap kickers

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

This is the simplest possible change to make Dreamsnaps cards look like non-Dreamsnap cards when Garnett is switched on. 

## What is the value of this and can you measure success?

Dreamsnap kickers are displayed

### Before

picture_78

### After

picture 449

## Tested in CODE?

Noes

### CODE REVIEW

**Review by sndrs — APPROVED** [review]
🔋

**Comment by SiAdcock** [comment]
After some discussion with @blongden73 I'm going to do a little bit more work to move the kicker inline with the headline and make the font size / weight consistent.

**Comment by blongden73** [comment]
All good from me.

**Comment by blongden73** [comment]
👍🏻

**Review by sndrs — APPROVED** [review]

**Pull request merged**
