### PR TITLE
Improve FaciaControllerTest (mf2.json rendering)

### PR DESCRIPTION
**Pull request by TBonnin**
## What does this change?

Instead of checking if response is not of JsUndefined type,
tests are now checking that response contains an `items` array
with the correct size
## Request for comment

@rich-nguyen

### CODE REVIEW

**Comment by rich-nguyen** [comment]
cool :+1:

**Comment by rich-nguyen** [comment]
do you need to change the test so that it tests a non-default editionalised section, eg `au/sport`?

**Comment by TBonnin** [comment]
Good point @rich-nguyen. I'll do that

**Comment by TBonnin** [comment]
@rich-nguyen Done :smile: https://github.com/guardian/frontend/commit/501c36e618ed09a7068cb227423d647cb741e44b

**Comment by NataliaLKB** [comment]
:+1:

**Pull request merged**
