### PR TITLE
Enable preview of DCR

### PR DESCRIPTION
**Pull request by jfsoul**
## What does this change?
The aim of this PR is to enable articles in preview to be rendered by DCR. The current restrictions on that are:

1. The generic `renderItem` method used as a catch-all by preview for articles uses a block restriction in its CAPI lookup. This is fine for frontend which uses the main block, but DCR requires the blocks (which are not present in the expected place when a restriction is added).
2. In dotcom rendering data model creation, we filter out blocks that are not `published` according to CAPI. That is seemingly always false in preview, so the blocks are all filtered out.

The changes to address this are:

1. renderItem uses a new `BlockRange` called `GenericFallback` which is only used by preview and the `PublicationController`. It includes `body` blocks so we still have the expected `body` property in the response to utilise. `PublicationController` probably doesn't need to use the `GenericFallback`, and we could do a bit of extra refactoring to stop that (but I have left it out for now, as there's not much downside apart from a larger CAPI response for these low traffic articles). I've also renamed `Canonical` because it is now only used for liveblogs.
2. We ignore `published` property of blocks if we're in preview.

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## Screenshots

Before
image

After
image

-->

## What is the value of this and can you measure success?
This provides the ability to preview on DCR, and with #23278 I expect it to actually turn it on 100% of the time. The value of this is that composer users see the same platform as most of our users.

### Does this affect other platforms?

- [x] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [x] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by shtukas — APPROVED** [review]

**Comment by AWare** [comment]
How will preview determine whether to use DCR or classic dotcom™️?

**Comment by jfsoul** [comment]
@AWare the intention is that the same `ArticlePicker` rules will be applied to `preview` as they are to `article`. So only articles we support on DCR will be shown by preview (based on many many rules) - but for those articles everyone will see DCR, which I think makes sense as it will be what 90% of our users see.

**Comment by paperboyo** [comment]
Sorry for ignorant question: huge majority of users use Viewer in Composer instead of naked Preview. I’m not familiar in how they are related, but would like to know if users will be seeing DCR-rendered content in Viewer.

**Comment by jfsoul** [comment]
@paperboyo viewer uses our `preview` service so they are the same thing effectively. This change needs some testing through viewer specifically though to ensure everything works as expected.

**Pull request merged**
