### PR TITLE
 Make Spacefinder play nice with the after-article and match report pages

### PR DESCRIPTION
**Pull request by katebee**
#### 👉Bump the `minbelow` on the spacefinder rules
To accomadate the part of the submeta that exists in the padding.

#### 👉Delete the `float: right` on football tables
It used to be possible for tables to be part width and appear next to a paragraph and to do this we used to float them right (https://github.com/guardian/frontend/pull/3697). However, currently these tables all have a width of 100% therefore the `margin-left` and `float` are no longer doing anything useful.

#### 👉Remove the `clear: both` from the `after-article` and submeta
Now that football tables are not floating right, they no longer have collision issues with the match stats (https://github.com/guardian/frontend/pull/19462), therefore using `clear: both` should be unnecessary! 🎉 

This also solves an issue where floating items added by Spacefinder were pushing down the `after-article` and submeta:

spacefinder-issue

#### 👉Bonus fix to timestamps on legacy match reports
Layout issue where `block-time.published-time` were seen overlaying the paragraph while testing the above changes:

picture 9

## What is the value of this and can you measure success?

Spacefinder will correctly calculate the hight of the `js-article-body` and the secondary column. Items placed by spacefinder that offset into the secondary column do not have collision issues with the various components added to the `after-article` section (epic, match stats, etc).

## Does this affect other platforms - Amp, Apps, etc?

Nope

###### after-article and DMPU before (right) and after (left) :

picture 17

https://www.theguardian.com/football/2017/nov/01/tottenham-real-madrid-champions-league-match-report

###### No visual change to current liveblog match reports:

picture 14

https://www.theguardian.com/football/live/2017/nov/01/tottenham-hotspur-v-real-madrid-champions-league-live

###### No visual change to current match reports:

picture 15

https://www.theguardian.com/football/2018/apr/16/pep-guardiola-make-manchester-city-better-premier-league-title-champions-league

###### Legacy match reports before (right) and after (left) with fixed timestamps:

picture 16

https://www.theguardian.com/football/2014/mar/25/manchester-united-manchester-city-live 

## Tested in CODE?

Nope

### CODE REVIEW

**Comment by paperboyo** [comment]
💎 Fixes: a bunch of over-optimistically closed issues 😄

**Review by jeteve — APPROVED** [review]

**Comment by sammorrisdesign** [comment]
Removing the `clear: both;` on the `after-article` might cause issues with bad embed placement though. If a supporting, thumbnail or rich link embed is placed towards the end of the article, it could clash with the match stats.

**Comment by katebee** [comment]
@sammorrisdesign I think the clash would have been caused by the `float: right` that was on the first match stat. Taking the `float: right` off these `div` elements allows them to assert their personal space without needing to use `clear: both`

**Comment by katebee** [comment]
More test articles welcome! I am going to have a poke around one last time to hunt for any oddities. Admittedly, I am far less familiar with our football section...

it-crowd-football

**Comment by katebee** [comment]
Removing either the `clear: both` or the `float: right` would not give the desired behaviour. However, removing `clear: both` from the after-article means that toggling `float: right` gets you this:

matchstats

So I am pretty certain at this point that removing `float: right` from the element-table will allow me to remove the `clear: both` from the after-article, which will allow me to restore the desired spacefinder behaviour. 🎉

**Comment by katebee** [comment]
Embeds. Richlinks. Spacefinder. Match Reports.

As pointed out by @sammorrisdesign, there is always another edge case (good catch)! 🙇
Therefore the match report component will still have to `clear: left` to [accommodate any manual rich-links](https://github.com/guardian/frontend/pull/19523/files#diff-5deda805ea705d0a06ca07606a75e350R289) added at the end of the article.. :headdesk:

picture 19

https://www.theguardian.com/football/2018/jan/13/watford-southampton-premier-league-report

Moving the `clear: both` off the `.after-article` and specifically onto the `.match-stats__container` as a `clear: left` hopefully lets spacefinder mostly still do what it is supposed to do.

**Pull request merged**
