### PR TITLE
Facia: update trendind-topics to the new tags style

### PR DESCRIPTION
**Pull request by gu-stav**
## What does this change?

Updates trending-topics tags on facia pages to the new style used in articles.

## What is the value of this and can you measure success?

More consistent design.

## Does this affect other platforms - Amp, Apps, etc?

No.

## Screenshots

** Before **

screen shot 2017-03-07 at 11 32 46

screen shot 2017-03-07 at 11 33 11

** After **

screen shot 2017-03-07 at 11 32 35

screen shot 2017-03-07 at 11 32 58

## Tested in CODE?

No.

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
👍 👍 👍

**Comment by gustavpursche** [comment]
@zeftilldeath Although Simon already approved this one, I'd like to hear yur opinion on the combination with the "More ..." Button and the increased space below the element.

**Comment by zeftilldeath** [comment]
Increased space below the element looks great. With regards to the more button, I don't feel like our lozenge button style works inline with text links like that. I feel just the word 'more...' after the final trailing slash will be sufficient.

**Comment by zeftilldeath** [comment]
Also, while we're looking at this bit. Could we standardise this section with the rest of the home page? A blue border at the top edge to edge and blue lowercase heading. No reason to have a new style here (no idea why it was like that originally)

screen shot 2017-03-07 at 16 30 31

**Comment by paperboyo** [comment]
Isn't this huge "Topics" text some regression? I don't remember it being like that until very recently. Apologies if I just name-called someone's design a regression 😜

**Comment by gustavpursche** [comment]
@paperboyo Interesting - thanks for pointing this out. 👍  I'll have a chat with Zef about this.

**Comment by gustavpursche** [comment]
@zeftilldeath 

> I feel just the word 'more...' after the final trailing slash will be sufficient.

I'll try it out, but my feeling is somehow, that it would be confusing, if it just looks like the other links, since it's a different functionality.

> Also, while we're looking at this bit. Could we standardise this section with the rest of the home page? A blue border at the top edge to edge and blue lowercase heading. No reason to have a new style here (no idea why it was like that originally)

Will have a look 👍

**Comment by gustavpursche** [comment]
After a f2f chat we decided to remove the previously hidden tags at all.

**Comment by paperboyo** [comment]
> After a f2f chat we decided to remove the previously hidden tags at all

The ones behind More..? 😱 As I understand, they dynamically indicate the composition of tags on a front. We have so little of this kind of structure discoverability mechanisms... it seems a pity to reduce them even more. Just my 2 cents, obviously...

**Review by SiAdcock — APPROVED** [review]

**Pull request merged**
