### PR TITLE
Update the main README

### PR DESCRIPTION
**Pull request by TBonnin**
## What does this change?

Update the main README https://github.com/guardian/frontend/blob/tbonnin-revamp-main-readme/README.md
## What is the value of this and can you measure success?

Focusing on the most important info, mostly link to more detailed document.

=> Less to read, more efficient 🎯 
## Does this affect other platforms - Amp, Apps, etc?

No
## Request for comment

@gareth @jfsoul @johnduffell @sndrs @SiAdcock @stephanfowler @dominickendrick

### CODE REVIEW

**Comment by jfsoul** [comment]
Very nice! There's something strangely exciting about docs updates 👍

**Comment by SiAdcock** [comment]
Nice refactor 👍

**Comment by akash1810** [comment]
👍

**Comment by stephanfowler** [comment]
👍 much saner

**Comment by gareth** [comment]
I don't think I'm the Gareth you meant to tag in this request - letting you know in case you need to tell the correct one.

**Comment by TBonnin** [comment]
My apology @gareth. Thanks for pointing this out, I was actually trying to ping @gtrufitt

**Comment by gtrufitt** [comment]
😆 Cheers @TBonnin - looks good!

**Pull request merged**
