### PR TITLE
Revert changes to longer caching comments.

### PR DESCRIPTION
**Pull request by gklopper**
I don't have time to complete this. If someone else wants to do it I will walk them through what I think needs to be done...

### CODE REVIEW

**Comment by dominickendrick** [comment]
I'm happy to pick this up

**Comment by nicl** [comment]
@dominickendrick let me know if you want to hand it over to us - we're happy to look after things like this.

**Comment by NataliaLKB** [comment]
@dominickendrick @nicl are either of you guys picking up this work? Shall we close this PR?

**Comment by nicl** [comment]
@NataliaLKB realistically we are not going to do this before Christmas so let's close this and pick it up again in the new year. Thanks :)

**Pull request closed without merging**
