### PR TITLE
Add link to applications wiki page

### PR DESCRIPTION
**Pull request by TBonnin**
## What does this change?

As an ongoing effort to provide better documentation for the frontend codebase, I have created a wiki page to describe what each Play app is responsible for: https://github.com/guardian/frontend/wiki/Applications-architecture

This PR is actually more about this wiki page than adding a link to it.
This is a work in progress obviously but I would really appreciate if as much people as possible could review the wiki page, add any missing information, fix any typo and correct my broken English. Thank you
## What is the value of this and can you measure success?

Make it easier for developers from other teams to grasp the complexity of the frontend codebase.
Hopefully this will reduce the number of times the question "What is this app doing?" is asked 😁 
## Does this affect other platforms - Amp, Apps, etc?

No
## Request for comment

@sndrs @dominickendrick @stephanfowler @johnduffell @jfsoul @NataliaLKB @JustinPinner @paulbrown1982 @SiAdcock @sihil @philwills @alexduf

### CODE REVIEW

**Comment by NataliaLKB** [comment]
👍

**Comment by ScottPainterGNM** [comment]
What a guy!

**Comment by philwills** [comment]
It would be really useful to have some reference to where the Nginx config for the router lives. I've tried to find this a number of times and always struggled.

**Comment by philwills** [comment]
The `Facia-press` description explains what that app does, but not why you'd want to do that, which I'm unsure of.

**Comment by rich-nguyen** [comment]
@philwills added some [rationale](https://github.com/guardian/frontend/wiki/Applications-architecture#facia-press) to facia-press

**Comment by philwills** [comment]
This is really helpful, thank you. 🀄

**Comment by TBonnin** [comment]
Thanks a lot @rich-nguyen

**Comment by TBonnin** [comment]
@philwills added a link to the nginx config 😎

**Comment by johnduffell** [comment]
this is fantastic! 👍 🚤

**Comment by stephanfowler** [comment]
👍 nice. Added some links to the existing facia docs.

**Comment by jamespamplin** [comment]
thanks loads for this @TBonnin - great stuff! :tada:

**Pull request merged**
