### PR TITLE
Add `fixed/thrasher` in the set of supported collections in `FaciaPicker`

### PR DESCRIPTION
**Pull request by ioannakok**
## What does this change?
We now have a list of `UNSUPPORTED_THRASHERS` (https://github.com/guardian/frontend/pull/26126). If a front contains thrashers that are not there, we can render it via DCR 🎉 

This PR also removes some unnecessary spaces from `UNSUPPORTED_THRASHERS` urls.

We'll be monitoring these graphs in the Fronts dashboard after this gets merged:

image

image

## Does this change need to be reproduced in dotcom-rendering ?

- [X] No
- [ ] Yes (please indicate your plans for DCR Implementation)

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [x] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [x] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by OllysCoding — APPROVED** [review]
+111111111 Wooooo

**Review by AshCorr — APPROVED** [review]
Wohoo!

**Review by ParisaTork — APPROVED** [review]

**Comment by ioannakok** [comment]
Deployed on the 9th of May at 12:27: https://riffraff.gutools.co.uk/deployment/view/07d0ce62-b443-4543-ac7c-058a548b8fbe

**Comment by ioannakok** [comment]
After https://github.com/guardian/frontend/pull/26138 we start supporting thrashers! There was an extra check for them which wasn't removed in the current PR

**Comment by ioannakok** [comment]
After #26138 we do see an increase in numbers!

image

**Comment by ioannakok** [comment]
Latency looks okay but we'll keep an eye
image

**Pull request merged**
