### PR TITLE
Removes default NewsArticle schema type on AMP articles

### PR DESCRIPTION
**Pull request by tsop14**
## What does this change?
Google now [supports schema types](https://github.com/ampproject/amphtml/tree/master/examples/metadata-examples) in their amp carousel; it no longer needs to default to 'NewsArticle'. https://www.ampproject.org/docs/guides/discovery

## What is the value of this and can you measure success?
More accurate description of content. 

## Does this affect other platforms - Amp, Apps, etc?
It only effects AMP. 

## Tested in CODE?
No

Spotted by @NataliaLKB on separate [PR](https://github.com/guardian/frontend/pull/16001) which copied this code.

### CODE REVIEW

**Review by NataliaLKB — APPROVED** [review]
Thanks so much for doing this @tsop14 !!! 💯 

Before merging, would you be able to check that a recipe (no atom obviously) and a review page validate on AMP?

Just to make sure 100% that this is okay.

**Comment by tsop14** [comment]
> Before merging, would you be able to check that a recipe (no atom obviously) and a review page validate on AMP?

An article with recipes (with or without recipe atoms) is type `NewsArticle` so will be the same. 
A review page passes validation on https://ampbench.appspot.com but all `make validate-amp` tests are failing (on master and this branch).

@NataliaLKB

**Comment by NataliaLKB** [comment]
@tsop14 great! Thanks for testing. 

If you look into our [AMP docs](https://github.com/guardian/frontend/blob/master/docs/03-dev-howtos/17-working-with-amp.md) at the bottom we have this:
image

[Here is the file](https://github.com/guardian/frontend/blob/master/common/app/views/fragments/amp/customStyles.scala.html#L31)

I haven't gotten around to doing what I would like to do with this. I want to make sure that if we run the tests, it ignores this particular error. It is on my list, but until it is implemented best to just do as the comment suggests and comment out the link tag while you run the tests.

Sorry about that 😞

**Comment by NataliaLKB** [comment]
Great work though! Definitely good to merge

**Pull request merged**
