### PR TITLE
Extend discussion switch

### PR DESCRIPTION
**Pull request by markjamesbutler**
## What does this change?

Extend switch to ensure no disruption for the election tonight.

## What is the value of this and can you measure success?

None its a functional change.

## Does this affect other platforms - Amp, Apps, etc?

No

### CODE REVIEW

**Comment by markjamesbutler** [comment]
@nicl Are you happy with this change?

**Comment by DiegoVazquezNanini** [comment]
:+1:

**Review by DiegoVazquezNanini — APPROVED** [review]

**Comment by nicl** [comment]
👍 yes sorry would be good to extend and then we'll sort out what to do with this! Thanks.

**Comment by nicl** [comment]
@markjamesbutler only comment would be that it would be helpful to extend the switch perhaps a week rather than 2 days.

**Pull request merged**
