### PR TITLE
update message for older browsers in discussion

### PR DESCRIPTION
**Pull request by johnduffell**
Everyone (who has contacted tech-feedback) is shocked because ipad non retina don't cut the mustard any more hence no discussion.

This is a big size problem in terms of amount of time to fix it properly.

However at least we can be clear about what's the situation, at the moment we're just telling them their browser is too old which seems strange to them as they didn't downgrade anything.

I'm going to update the linked article to reflect the current situation too.

Edit: updated to wording suggested by Theresa:
image

### CODE REVIEW

**Comment by rich-nguyen** [comment]
Quite wordy, have you asked someone to go through the copy?

**Comment by uplne** [comment]
I agree with @rich-nguyen. If it is difficult to explain in short (which it is) should we rather create a link "Why am I getting basic discussion experience?" linking to, for example, the recommended browsers section where you can explain everything in detail.

It is self explanatory that everyone should understand very fast that he/she is viewing the basic experience and if they want to know more they can simply click on it.

**Comment by johnduffell** [comment]
@uplne I should have pointed out, the link in there (and still in the edited version) goes to the page explaining why we have recommended browsers and what they are. http://www.theguardian.com/help/recommended-browsers

**Comment by gklopper** [comment]
But the supported browsers article says...

>iOS 7+ Safari

Which no longer cuts the mustard (as far as I know).

It would be something like `iOS 8 on Retina iPhones/ iPads` or something.

**Comment by johnduffell** [comment]
@gklopper dreaming about iPads at 5am?
actually in the updated version it says "iPad 3 or iPhone 4s" as I wasn't sure people will know whether it's retina or not.  However suggestions would be good to improve the clarity.

**Comment by rich-nguyen** [comment]
:+1:

**Comment by sndrs** [comment]
> It would be something like iOS 8 on Retina iPhones/ iPads or something.

iOS 7 must cut the mustard? ios 8 only came out 10 months ago...

**Pull request merged**
