### PR TITLE
Fix hosted video in the standalone bundle

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

For `youtube-player.ts`, adds to existing `window.onYouTubeIframeAPIReady` callback instead of replacing it.

Small changes:
- Converted a function to `async` in order to use `await`.
- Use of HTML `dataset` directly, which camelCases automatically: `.attr('data-media-id')` &rarr; `.dataset.mediaId`

## Does this change need to be reproduced in dotcom-rendering ?

- [X] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## Screenshots

| Before      | After      |
|-------------|------------|
| ![before][] | ![after][] |

[before]: https://user-images.githubusercontent.com/76776/135273549-c526ebe7-83ec-459b-8bc6-8ae181c1773e.png
[after]: https://user-images.githubusercontent.com/76776/135273518-2a9d15f0-4cce-4b9a-9a28-836e5744c7fb.png

## What is the value of this and can you measure success?

Hosted videos work for everyone!

### Tested

- [X] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by arelra — COMMENTED** [review]
> This happens with the standalone commercial bundle

Do we know why this happens?

**Comment by mxdvl** [comment]
> > This happens with the standalone commercial bundle
> 
> Do we know why this happens?

Yes, because both bundles are being loaded and executed by webpack. IIUC, this is due to how the chunking is done and I’m not sure how we could prevent it from running twice 🤷

image

**Comment by arelra** [comment]
> Yes, because both bundles are being loaded and executed by webpack. IIUC, this is due to how the chunking is done and I’m not sure how we could prevent it from running twice 🤷

Ah okay. Is it possible for another race condition where `previousApiLoadCallback` has already been called by the first `onYouTubeIframeAPIReady` ?

**Comment by mxdvl** [comment]
Yes, exactly, it’s a race condition. Locally it almost always works. In PROD, almost never.

**Comment by MarSavar** [comment]
Thanks for fixing! 

Just a small note: when I converted this module to TypeScript I didn't use `dataset` because of its slower performance compared to `getAttribute` (ran a test and `dataset` is 45-50% slower: https://jsbench.me/5wku5obaj4/1).
It turns out that `dataset` pulls ahead when you have lots of data attributes that you want to collect into a map of strings, but for individual data attribute retrievals, `getAttribute` is more performance-friendly.

We're talking microseconds so the difference really isn't noticeable at all, and it's 100% fine to go ahead with `dataset` here, but it's an interesting fact to know (I think!)

**Comment by arelra** [comment]
> Yes, exactly, it’s a race condition. Locally it almost always works. In PROD, almost never.

Ouch :)

Not for this PR but fyi [YoutubeAtom.tsx](https://github.com/guardian/atoms-rendering/blob/5db298b9f1b1674ddfe7049dc1434adb1a64abec/src/YoutubeAtom.tsx) uses [youtube-player ](https://github.com/gajus/youtube-player)which abstracts the waiting for the player to initialise.

Introduced here: [#149](https://github.com/guardian/atoms-rendering/pull/149)

Might be worth switching if this continues to cause problems.

**Review by arelra — APPROVED** [review]

**Pull request merged**
