### PR TITLE
improve discussion CORS errors

### PR DESCRIPTION
**Pull request by johnduffell**
when discussion is running through an http 1.0 proxy it's impossible to post due to CORS.  Noone should be using an http/1.0 proxy, but it happens, and people complain about it, so I've improved the error message.

I've also tidied up some other messages that included email addresses etc, because we don't include error messages in the cookie any more for privacy reasons.

image

### CODE REVIEW

**Comment by rich-nguyen** [comment]
Excellent find, how did you discover this?

:+1:

**Comment by phamann** [comment]
:+1: Love this!

**Comment by johnduffell** [comment]
@rich-nguyen people were complaining they couldn't post and I managed to get a HAR archive from one of them.  It showed a 400 bad request from an OPTIONS request (as CORS does) - the crucial clue there was that it was an HTTP/1.0 response rather than 1.1.
The tough bit is we can't really solve this ourselves, other than perhaps going HTTPS, but I thought a better message albeit with a weak suggested action would help users more in future.

Related, I'm not sure if we should collect stats for failed commenting - or do we do that already?

**Comment by rich-nguyen** [comment]
Great, that seems like the next piece of the puzzle, because we were previously not routing OPTIONS requests at all, but I didn't see an uptick in reliability when I introduced them.

**Comment by gklopper** [comment]
:+1: good detective work...

Please run the message past UX - I'm not sure its easily understandable across the board

**Comment by johnduffell** [comment]
Cheers, I've sent a message UX's way so hopefully I can get a better message in there some time soon!

**Pull request merged**
