### PR TITLE
Crosswords: grouped entries (navigation and highlighting)

### PR DESCRIPTION
**Pull request by OliverJAsh**
Still to do with groups:
- [ ] 'Clear/reveal' should clear/reveal all entries in group? This is the R2 behaviour

I suspect I could improve this by calculating the data format I need upfront. /cc @desbo @janua 

image

### CODE REVIEW

**Comment by ScottPainterGNM** [comment]
I would vote yes to the question you asked above, I think that the clear/reveal should apply to the whole group as per R2

**Comment by OliverJAsh** [comment]
@janua Do you want to do that when you implement the clear button, @janua?

**Comment by ScottPainterGNM** [comment]
Also the group needs to apply to the anagram solver, comments from users in the beta comments section about this.

**Comment by ScottPainterGNM** [comment]
Raised #10138 for the anagram issue

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
