### PR TITLE
Get rid of no thrashers test for ipads.

### PR DESCRIPTION
**Pull request by gklopper**
This was always temp, Core should be managing these things

### CODE REVIEW

**Comment by JustinPinner** [comment]
With the proviso that core is defaulted for ~50% of retina iPads and all older iPads: :+1:

**Comment by johnduffell** [comment]
yes yes ship it :+1:

**Comment by gklopper** [comment]
Its already been switched off for a while (expired switch)

**Comment by gklopper** [comment]
Its already been switched off for a while (expired switch)

**Comment by gklopper** [comment]
Its already been switched off for a while (expired switch)

**Pull request merged**
