### PR TITLE
Fluid 250 v4 with animation on the right

### PR DESCRIPTION
**Pull request by tijanamiletic**
New version of the fluid 250 advert with the option for right hand side animation:

screen shot 2015-08-14 at 11 29 37

The rest of the template closely matches previous version 3.

Example: bottom banner on /uk/environment?adtest=tm6

### CODE REVIEW

**Comment by Calanthe** [comment]
If it closely matches version 3, can't we use the same template?

Also, screenshot would be nice ;)

**Comment by tijanamiletic** [comment]
Here is the screenshot of the test:

screen shot 2015-08-14 at 11 47 02

The only reason this is not an amendment to existing template is that the existing template is used a lot on live for current campaigns and it's too risky making changes to it.

**Comment by Calanthe** [comment]
I still would prefer to use one template but if you don't want to risk it, thats fine.

During your absence we had an issue with fps in one of the scrollable MPU (https://github.com/guardian/frontend/pull/9973). It was related to the 'background-attachment: fixed;'. I know that you do not use this style here, but maybe it would be worth checking and comparing fps of the page with and without your adtest.

**Comment by Calanthe** [comment]
:+1:

**Pull request merged**
