### PR TITLE
Don't forward requests for /favicon.ico to CAPI

### PR DESCRIPTION
**Pull request by cb372**
Intercept requests for `/favicon.ico` and return a 404 instead of forwarding the request to CAPI. It's a 404 on the CAPI side, and we get quite a lot of these requests, which screws with our CloudWatch monitoring.

On live, requests to this path never hit the frontend machines anyway, because they are handled by the router. So this change will only affect preview.

### CODE REVIEW

**Comment by robertberry** [comment]
Not even sure what that standalone app is ... you probably need to put this in `applications`. CC @gklopper

**Comment by robertberry** [comment]
:+1: (given our conversation)

**Comment by gklopper** [comment]
Nope...

This needs to go into the router so we serve a proper icon...

This will just result in 404 errors

**Comment by gklopper** [comment]
My bad, Rob tells me this is for preview.

Still we have ways of serving a static file, so maybe do that.

see https://github.com/guardian/frontend/blob/master/facia/conf/routes#L14

**Comment by cb372** [comment]
Is the static file available somewhere in the Play app?

btw the current behaviour is a 404 error, so this wouldn't be any worse :)

**Comment by gklopper** [comment]
I'm not sure it is in the app, but I'm pretty sure it is at the end of this URL http://www.theguardian.com/favicon.ico :smile: and then just follow the pattern for humans.txt

**Comment by cb372** [comment]
Could somebody merge this please? I don't have permissions.

**Pull request merged**
