### PR TITLE
Remove unused module parameter

### PR DESCRIPTION
**Pull request by jbreckmckye**
This is just a little change to remove an 'options' parameter in dfp-api.js that isn't actually set by anything - either in production or in test code.

### CODE REVIEW

**Comment by kelvin-chappell** [comment]
Could it be being set by a DFP template?

**Comment by jbreckmckye** [comment]
@kelvin-chappell Is that possible? How would I check?

**Comment by uplne** [comment]
@kelvin-chappell what do you mean by that? DFP templates shouldn't have access to DFP init

**Comment by kelvin-chappell** [comment]
That's true.  :+1:

**Pull request merged**
