### PR TITLE
Common Module - move more packages

### PR DESCRIPTION
**Pull request by MatthewJWalls**
## What does this change?

* Moves cricket_pa package into conf
* Moves newspaper_books package into conf
* moves cards into layout 
* moves slices into layout

## What is the value of this and can you measure success?

Collapsing more packages down a bit

### CODE REVIEW

**Comment by TBonnin** [comment]
Should we have a `cricket` or `sport.cricket` module in common?

**Review by DiegoVazquezNanini — APPROVED** [review]
LGTM :+1: apart from the failing test.

**Comment by MatthewJWalls** [comment]
@DiegoVazquezNanini I've rebased this and solved any merge conflicts. Can you give this a quick skim to make sure I haven't done anything dumb? Hoping to merge this in quick before any more conflicts come up

**Review by DiegoVazquezNanini — APPROVED** [review]
Looks good

**Pull request merged**
