### PR TITLE
Flashing elements

### PR DESCRIPTION
**Pull request by nicl**
## What does this change?

If 'flashing-elements' accessibility pref is disabled:

* hide thrashers
* prevents video autoplay

Note, this does not cover commercial videos or ads.

(Pre-existing) code which actually toggles display is here: https://github.com/guardian/frontend/blob/master/static/src/stylesheets/module/_accessibility.scss

## What is the value of this and can you measure success?

Better UX/accessibility.

## Does this affect other platforms - Amp, Apps, etc?

-
## Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

No.

## Tested in CODE?

Yes

### CODE REVIEW

**Comment by paperboyo** [comment]
> hide thrashers

Do we want to hide them or just freeze them?

freeze

**Comment by nicl** [comment]
@paperboyo I guess freeze and then, only those which actually need it. *BUT* hiding is likely to be much simpler and less error-prone so I think that is a better option unless I head strong arguments against.

**Comment by gtrufitt** [comment]
> Do we want to hide them or just freeze (and silence) them?

This would require every thrasher to have the behaviour to handle that built in which is... unlikely. So, I agree with Nic's approach here.  ❤️

**Comment by paperboyo** [comment]
> which is... unlikely

Sure-sure (also affects small amount of readers). I assumed thrashers are all built from one template and it could be easily amended. “Could“ and “easily” are my usual mistakes 😜

**Comment by gtrufitt** [comment]
> I assumed thrashers are all built from one template and it could be easily amended.

They do, I think, but they quickly diverge in their behaviour and have custom JS, CSS animations etc.

**Comment by blongden73** [comment]
@gtrufitt @nicl - I'm not sure hiding all thrashers is the right approach here. I'm happy to make sure when thrashers are built that we make sure they adhere to this. This seems like a pretty extreme option - when we haven't even had a chance to defend ourselves.

**Comment by gtrufitt** [comment]
@blongden73 Do thrashers have a standard approach to animations that can be built in to the template? 

Note that this affects a really small proportion of the audience that have accessibility problems with moving imagery (the flashing dot on the live blog, for example, causes them pain) - hence avoiding the risk of a thrashers being forgotten. After seeing this problem a couple of times, the a11y working group suggested this as a better-safe-than-sorry approach. 

Anyway... I don't even work on platform any more so...

giphy 7

**Comment by paperboyo** [comment]
> I don't even work on platform

I never did and can’t see a problem (other than @nicl not getting proper reviews, but ‘improper’ discussions):

lru

**Comment by nicl** [comment]
@blongden73 @gtrufitt okay chatted with Ben IRL and on the assumption the numbers here are low, we're going to take the approach above. Turns out we do track clicks on the accessibility pref but it's broken so we'll fix that separately and re-evaluate if the numbers turn out larger than expected.

**Review by NataliaLKB — APPROVED** [review]
Yay! 🎉

**Pull request merged**
