### PR TITLE
participation tests - extend and blat

### PR DESCRIPTION
**Pull request by NathanielBennett**
## What does this change?

Extends the expiry date of one expired, incomplete test, and takes down and expired complete test
## What is the value of this and can you measure success?

Fixes the build
## Does this affect other platforms - Amp, Apps, etc?

N/A
## Screenshots

N/A
## Request for comment

@rtyley @katebee @NataliaLKB

### CODE REVIEW

**Comment by katebee** [comment]
LGTM 👍

**Comment by NataliaLKB** [comment]
👍

**Comment by regiskuckaertz** [comment]
There are two expired tests, the other is `ABParticipationDiscussionOrderingNonLive`

**Comment by NathanielBennett** [comment]
@regiskuckaertz Yeah I've deleted that one. So it should work, right?

**Comment by regiskuckaertz** [comment]
yes

**Pull request merged**
