### PR TITLE
Remove "sign-in CTA on banner" test

### PR DESCRIPTION
**Pull request by Mullefa**
## What does this change?

Removes the test introduced in #21458.

### CODE REVIEW

**Review by gtrufitt — APPROVED** [review]
👍

**Comment by lmath** [comment]
https://github.com/guardian/frontend/pull/21458/files#diff-d81c9da19a1532b5d566982d6e015e38R22 
⬆️ is that parameter being used elsewhere now?

**Review by jlieb10 — APPROVED** [review]
nice work

**Comment by Mullefa** [comment]
Good question @lmath ! I thought I'd keep it in. A nod to further tests we might do in the future 😅;)

**Comment by jlieb10** [comment]
yes I think you should keep it there @Mullefa - one of our teams will definitely want to use it in the not too distant future.

**Pull request merged**
