### PR TITLE
Membership promintent engagement messaging adjustments

### PR DESCRIPTION
**Pull request by JustinPinner**
## What does this change?

Some modifications to the prominent messaging AB test;
_Functional:_
We don't want to track button clicks separately from link clicks anymore.
We only want to test one button caption, so we only need two AB groups: "control" and "become"
Use GA tracking codes

_Visual:_
Flows the button inline with the link text
Use smaller font on tablet breakpoint
Adjustments to padding and button heights to accommodate in-lining of button and changes to font
## What is the value of this and can you measure success?

See https://github.com/guardian/frontend/pull/14746
## Does this affect other platforms - Amp, Apps, etc?

No.
## Screenshots

_In the test ("become" group)_
## screen shot 2016-10-24 at 17 33 15 become

screen shot 2016-10-24 at 17 33 47 become

_In the test ("control" group)_
## screen shot 2016-10-24 at 17 38 28 control

screen shot 2016-10-24 at 17 38 58 control
## Request for comment

@benwuersching @rtyley

### CODE REVIEW

**Comment by johnduffell** [comment]
the button and its writing looks disconcertingly small compared with the rest of the text, not sure if it's designed like that?

**Comment by JustinPinner** [comment]
Yes, it's an intentionally smaller font.

**Comment by rtyley** [comment]
So far as I can tell, this looks all good to me, though I've got very limited CSS skills, so perhaps @svillafe would like to take a look at it for our team? Feel free to get other people on our team to review PRs, I know it's awkward waiting for me given I'm not around on Mondays.

**Comment by JustinPinner** [comment]
@Ap0c would you take a look too? Cheers.

**Comment by svillafe** [comment]
I have just the css with @SiAdcock and it is ok. 👍

**Comment by JustinPinner** [comment]
Thanks @svillafe and @SiAdcock - merging now :)

**Pull request merged**
