### PR TITLE
update hiring message

### PR DESCRIPTION
**Pull request by sndrs**
move the hiring message below the charset, for older browsers.
- uses fewer chars
- bolder too

screen shot 2016-02-05 at 11 05 11

### CODE REVIEW

**Comment by jbreckmckye** [comment]
:+1:  and :100: for funky drop shadow.

**Comment by rich-nguyen** [comment]
ohh

**Comment by rich-nguyen** [comment]
https://github.com/guardian/frontend/pull/11865

**Comment by sndrs** [comment]
oop!

**Pull request merged**
