### PR TITLE
Remove variant for new liveblog ab test

### PR DESCRIPTION
**Pull request by michaelbjacobson**
## What does this change?

• removes `v1` variant from list of variants in 'contributions-epic-liveblog-design-test.js'
• removes redundant import of `lastSentenceTemplateButtonAndSubscribe`

## Does this change need to be reproduced in dotcom-rendering ?

- [ ] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## Screenshots

Screenshot 2020-04-16 at 11 35 00

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/master/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by michaelbjacobson** [comment]
@tomrf1 I've had a look through numerous closed PRs and can't find anything conclusive about actually removing dead A/B tests. In addition to removing the variant, should I also remove the test files and templates in their entirety, along with references to it in switches etc?

**Comment by tomrf1** [comment]
@michaelbjacobson yes, the test file etc can also be removed. Happy to pair on this - it's quite a big codebase!
The original PR that introduced the test is [here](https://github.com/guardian/frontend/pull/22449/files)

**Comment by michaelbjacobson** [comment]
@tomrf1 thanks for such a quick response, and for the offer of help! I've had a go at tackling the cleanup solo this morning though as I'm keen to see if I'm starting to get the hang of the Guardian codebase! 

I've now reverted all changes from your original PR, except for in the following files:

- `static/src/javascripts/__flow__/types/ab-tests.js`
- `static/src/javascripts/projects/common/modules/commercial/contributions-utilities.js`

These seemed to be valuable to retain, but I may be mistaken!

**Review by tomrf1 — APPROVED** [review]
great work!
A screenshot of the epic in the PR description would be helpful, as a record of the design that we ended up with

**Comment by michaelbjacobson** [comment]
> great work!
> A screenshot of the epic in the PR description would be helpful, as a record of the design that we ended up with

Thanks @tomrf1 for your help! I've added a screenshot to the PR description, per your suggestion.

**Pull request merged**
