### PR TITLE
Make the series onward journey above the non-series

### PR DESCRIPTION
**Pull request by johnduffell**
This puts the series container above the container that shows more of the same media type in the same section but not in the series.  Otherwise it didn't really make sense so I think it's been regressed at some point.

I've not gathered the stats or AB tested, but people noticed if the only media of that type in that section was in one series, the [non-series content just looked really out of date](https://www.theguardian.com/football/blog/audio/2016/apr/28/after-27-years-justice-for-hillsborough-victims-football-weekly-extra).

before:
image
after:
image

### CODE REVIEW

**Comment by jamesgorrie** [comment]
I know there was definitely some tests done that were contrary to common-sense - so it might be worth (like the most popular being better performing than series' in some instances).

It might be worth chasing this up - @stephanfowler or @crifmulholland - do you know anything about this?

**Comment by johnduffell** [comment]
stephan said (in person) he doesn't have objections

**Comment by jamesgorrie** [comment]
Do we have any insight into the insight they had?

**Comment by stephanfowler** [comment]
We didn't do any tests on series content. Of the tests we did on regular articles, the only thing that had meaningful impact was the addition of section front containers. So this PR is not meaningfully informed by that. I think this PR just makes sense - for the reasons stated by John.

**Comment by stephanfowler** [comment]
:+1:

**Comment by jamesgorrie** [comment]
Yea, sorry, I wasn't trying to block - just super interested in past research / tests as I don't want to be the new kid on the block with fancy shiny ideas undoing work-well-done.

**Comment by johnduffell** [comment]
that's fine @jamesgorrie it's best to ask - better to say what you're thinking than keep quiet and something gets broken!
I'll merge this monday due to fixing conflicts - @jamesgorrie will you be updating in your next refactoring this naming or have I made an error? my comments on https://github.com/guardian/frontend/pull/12905/files

**Pull request merged**
