### PR TITLE
Social toggle removal

### PR DESCRIPTION
**Pull request by zeftilldeath**
Continuing my social media buttons rampage. This PR removes the show/hide toggle at the top of articles. Usage of Google +, Pinterest and Linkedin shares are very small, and getting rid of this complexity allows for things to be a lot tidier, and a lot of tonal specific code to be removed. 

## Does this affect other platforms - Amp, Apps, etc?
Yep AMP follows suit.

## Screenshots
# Before
screen shot 2018-04-19 at 14 25 13

# After
screen shot 2018-04-19 at 14 25 04

# Next steps
Making what remains, look a lot neater.

### CODE REVIEW

**Comment by paperboyo** [comment]
💎 !

Long overdue. Since about... the very inception 😜. [This a thing yet?](https://developers.google.com/web/updates/2016/09/navigator-share)

**Comment by ScottPainterGNM** [comment]
YESSSSSSSSS, Better Meta reaches its beautiful conclusion.

**Review by sndrs — APPROVED** [review]
Cor lovely!

**Comment by zeftilldeath** [comment]
@ScottPainterGNM We played the long game!

**Pull request merged**
