### PR TITLE
Print stylesheet tweaks

### PR DESCRIPTION
**Pull request by holder-josh**
Received a couple of emails from central prod and userhelp regarding bugs with the print stylesheet. 
This PR hides some of the newer content page elements (like rich links) and fixes some overlapping.

### CODE REVIEW

**Comment by paperboyo** [comment]
related to: https://github.com/guardian/frontend/issues/7107 (some useful screenshots?)

Live print style emulation (sorry, if known :panda_face: ):
06aks

**Comment by Jholder112233** [comment]
Thanks for the screenshots @paperboyo, turns out there was a lot of problems with icons displaying badly in the print view. I've updated the PR with some more fixes and it displays pretty cleanly now across Chrome, Firefox and Safari.

**Comment by paperboyo** [comment]
Thanks, @Jholder112233!

**Comment by phamann** [comment]
:+1: 

Maybe in the future we should consider inverting this logic. I.e. hide everything by default and have a whitelist of things we want to show, rather than a blacklist of things to hide.

**Pull request merged**
