### PR TITLE
Email preferences: correct the example URLs

### PR DESCRIPTION
**Pull request by rrees**
## What does this change?

Some of the url structures seem to have changed and the redirects were not working properly. I think I have now corrected Poverty Matters and added the right URL for the Fiver.
## What is the value of this and can you measure success?

Bugfix
## Does this affect other platforms - Amp, Apps, etc?

No
## Request for comment

I'm not involved in the new onsite emails so if anyone can review the url structure that would be great.

### CODE REVIEW

**Comment by rrees** [comment]
@rich-nguyen how do I get an account for the dotcom CI?

**Comment by rich-nguyen** [comment]
👍  you can self-register for dotcom CI. The build looks to have failed because of expired switches, a merge from master should do the trick.

**Comment by johnduffell** [comment]
great, this one's getting old, need any help shipping?

**Comment by rrees** [comment]
Yep I'm happy to merge but obvie can't :shipit:

**Pull request merged**
