### PR TITLE
Use Webpack Bundle Analyzer Plugin

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

Installs [`bundle-analyzer-plugin`](https://www.npmjs.com/package/webpack-bundle-analyzer) for Webpack, that generates a visual report of the content of our JavaScript bundles. 

## What is the value of this and can you measure success?

This report will make it easier to identify libs that are duplicated across chunks, so that they can, for example, be extracted into commons chunks.

## Does this affect other platforms - Amp, Apps, etc?

No

## Screenshots

c7jseuxx0aanapd

## Tested in CODE?

No

### CODE REVIEW

**Comment by gustavpursche** [comment]
How is this different from `webpack-visualizer-plugin`? I gues we could remove the old one, if they are identical :)

**Comment by sndrs** [comment]
maybe add a link on admin?

**Comment by sndrs** [comment]
> How is this different from webpack-visualizer-plugin? I gues we could remove the old one, if they are identical :)

be nice to compare for a bit? easy enough to kill which ever is less useful?

**Review by sndrs — APPROVED** [review]

**Comment by SiAdcock** [comment]
I think this visualizer presents the information in a way that makes it easier to compare the contents of bundles. Happy to run both side by side, and yes, I'll add a link in Admin!

**Pull request merged**
