### PR TITLE
Fix twitter selection sharing #11241 #12615

### PR DESCRIPTION
**Pull request by katebee**
## What does this change?
- Sharing highlighted text via twitter no longer slices a section that is 141 characters, it now only takes the 140 required for a valid tweet.
- Sharing text containing semicolons no longer truncates the text; encodeURIComponent will convert the semicolon to UTF-8 (encodeURI does not cover all special characters).
## What is the value of this and can you measure success?

e6da9c9 fixes issue #11241 (too many characters being passed to a tweet)
1deb267 fixes issue #12615 (semicolons in selected text cause truncation of tweet)
## Screenshots

**141 char issue BEFORE:**
tweetbefore

**141 char issue AFTER:**
tweetafter

**Semicolon issue BEFORE:**
semicolons missing

**Semicolon issue AFTER:**

semicolons present
## Request for comment

@gtrufitt

### CODE REVIEW

**Comment by katebee** [comment]
While I was checking #e6da9c9 I found another bug (#12615), this PR fixes both issues

**Comment by gtrufitt** [comment]
🆒 👍 Just for reference, why did it reduce a character?

**Comment by katebee** [comment]
Why it reduced a character:

> twitterMessageLimit = 114, // 140 - t.co length - 3 chars for quotes and url spacing

The limit of 115 didn't account for the ellipsis character added to the tweet when the selected text exceeds 140 characters.

**Comment by gtrufitt** [comment]
Hmm, interesting, it was definitely right at some point! 😄 Maybe the url length changed or something.

**Comment by gtrufitt** [comment]
Actually, the comment says t.co url and your screenshot has a gu.com url so probably that

**Comment by katebee** [comment]
Ah, yep! I assumed it was the ellipsis throwing it off, missed the change of the url length...

Any potential issues with the change to using `encodeURIComponent` instead of `encodeURI`? Otherwise I will merge tomorrow morning.

**Comment by gtrufitt** [comment]
I don't think so off the top of my head, I made a similar change (but from urlEncoded) myself a while back: https://github.com/guardian/frontend/commit/7a2cba628f251afa3885cd494cc59d839aa63e39

**Pull request merged**
