### PR TITLE
Block asking for contributions on Leonard Cohen pieces

### PR DESCRIPTION
**Pull request by philwills**
## What does this change?

Ensures we don't ask for contributions/membership on any Cohen pieces. I don't think we are, but this seems a sensible precaution.

## Does this affect other platforms - Amp, Apps, etc?
No

## Request for comment

@jranks123

### CODE REVIEW

**Comment by jranks123** [comment]
👍

**Comment by LATaylor-guardian** [comment]
Just chipping in here, but this seems like something we most certainly don't want to do for a specific subset of articles. Is there a way to do this in a more automatic way?

**Comment by philwills** [comment]
@LATaylor-guardian It's what the targeting tool is supposed to fix generally, I believe, but my understanding is that that's not yet ready.

**Comment by LATaylor-guardian** [comment]
@philwills Ah yes, good point, I forgot about that! Thanks.

**Comment by jranks123** [comment]
I also think a better solution than included and excluded hard coded lists is in order...Maybe using the Google Sheets API?

**Comment by philwills** [comment]
This is failing at the moment because @JustinPinner has an expired test.

**Comment by rupertbates** [comment]
@philwills I'm about to merge a PR which will fix that

**Comment by dominickendrick** [comment]
👍 Hallelujah!

**Pull request merged**
