### PR TITLE
Add supporting to lite.json

### PR DESCRIPTION
**Pull request by janua**
The data team need data from the fronts and `lite.json` almost fulfills their requirements. All that is missing is `supporting` content on items.

This adds a `supporting` key to the `lite.json` files with supporting items. If there are no supporting items then no supporting key gets added.

This also cleans up at collection level **null**s that may exist, a common one being `href`.
## Risk

In the spirit of M and M, what risk does this have? Low

In the past, changing this has broken shuttlerun from indexing. This then stopped `editorsPicks` from working. This was due to the parser not being able to handle nulls.

I would say this change is low because it just adds a new key to the `json` and removes some **nulls**.

@stephanfowler @rich-nguyen @mchv 

---

supportingitems
#### Href Null

collectionlevelnull

### CODE REVIEW

**Comment by mchv** [comment]
:+1: it should not break not our side

**Comment by obrienm** [comment]
:+1: 

Ophan *may* be interested in this change too, instead of using the FAPI client.

**Comment by janua** [comment]
@obrienm Do you have everything you need from this feed? If so, great! It's a much better alternative to using the full *facia-scala-client*.

**Comment by kelvin-chappell** [comment]
Looks good to me :+1:

**Pull request merged**
