### PR TITLE
The Campaign Minute. Version 1, desktop styling

### PR DESCRIPTION
**Pull request by gtrufitt**
The Campaign starts today - this converts the current [mobile-on-desktop](http://www.theguardian.com/us-news/live/2016/jan/28/trump-dumps-debate) styling into nearer to the desktop view. 

v1_wide_scroll

v1_breakpoints

cc/ @superfrank @desbo @crifmulholland

### CODE REVIEW

**Comment by paperboyo** [comment]
Are these images lightboxable into an ad hoc gallery? Just asking (earlier design included a button)...

**Comment by gtrufitt** [comment]
@paperboyo Not currently a part of the design, no, but will talk to the designer-types and see whether that's something we can add later on.

**Comment by paperboyo** [comment]
Thanks, @gtrufitt. It doesn't work in Liveblogs either... Not sure if it would be easy to add. Apparently, in-article Lightbox is quite popular.

**Comment by gtrufitt** [comment]
@paperboyo It's easy enough to add functionally but don't know whether we would want a different design treatment for it in minute articles/us-election :)

**Comment by desbo** [comment]
:+1:

**Comment by paperboyo** [comment]
Sure thing. My take on this - not that it matters - is that it should be available on all article types. If, what I think may be the case sometimes, it isn't because "no, i don't want all these gray buttons on images", we could decide to show them only on hover in these situations.

**Pull request merged**
