### PR TITLE
[Do not merge] AMP Cleaning Correction

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

This PR reverts two reverts. 

1: https://github.com/guardian/frontend/commit/cd0dae0f80d85c6fa96ff79695328183e516514a
and 
2: https://github.com/guardian/frontend/commit/15ccdac651062ca7d32e2506ddaa84348adaaa9b

Which were done a bit earlier today as part of trying to correct a problem with disappearing hosted contents. 

Then introduces a fix. A piece of code that was incorrectly deleted is re-introduced (something that neither the Scala compiler nor the tests picked up, for strange reasons).

### CODE REVIEW

**Comment by shtukas** [comment]
Recovered content:

Screenshot 2019-06-14 at 13 47 40

**Review by MatthewJWalls — CHANGES_REQUESTED** [review]
Unfortunately, I think we still need to resurrect the amp version of the hosted pages. 

on a build from two days ago, running locally with ?amp param:

image

on this branch:

image

**Comment by kelvin-chappell** [comment]
Hosted content (anything with a `/advertiser-content/...` path) is all currently served from the Commercial servers.  If you wanted to serve amp pages in the same way as other articles I think you'd need to do some rewiring in the nginx config as well.

**Comment by shtukas** [comment]
@kelvin-chappell Many thanks Kelvin, this is like super useful information for us :)
@MatthewJWalls @nicl @gtrufitt @philmcmahon @jeteve

**Comment by shtukas** [comment]
I am going to close this as we are doing a full revert of all the changes.

**Pull request closed without merging**
