### PR TITLE
Use npm in webpack, not checked in bower packages

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

- directs webpack to npm, rather than bower

## What is the value of this and can you measure success?

- will mean require/bower can go as one, when the time is right. there's no need to use bower

## Does this affect other platforms - Amp, Apps, etc?

no

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
👍  Amazing

**Comment by sndrs** [comment]
hit a blocker: 

currently we serve `videojs@5.4.6` and `videojs-ima@0.3.0` (both checked in), but `videojs-ima@0.3.0` specifies a dependency of `videojs@~5.3`. webpack therefore is bundling both, adding 200k to the bundle... trying to work out how to handle it

**Comment by sndrs** [comment]
raised an issue https://github.com/googleads/videojs-ima/issues/333

**Comment by sndrs** [comment]
tempted to downgrade our version till ima updates - seems like it might be a while, and we're running (potentially) incompatible versions as it is. 

we'll mainly miss out on https://github.com/videojs/video.js/pull/2638.

any feelings either way @SiAdcock @akash1810?

**Comment by akash1810** [comment]
> tempted to downgrade our version till ima updates - seems like it might be a while

@sndrs 👍 but could we do this in a test to be sure there isn't a detrimental loss of video consumption as a result?

**Comment by sndrs** [comment]
how long would we have to run it for? according to https://github.com/guardian/frontend/pull/11821, it was only to bring it inline with contribs anyway?

**Comment by akash1810** [comment]
Ah, I wasn't aware of that! In that case, I'm all for downgrading.

**Pull request merged**
