### PR TITLE
Change Google logo on /reauthenticate

### PR DESCRIPTION
**Pull request by laurenemms**
## What does this change?
Updates the logos on /reauthenticate for Google and Facebook as the first step to making the buttons look like the buttons on the new sign in flow.

## Screenshots

Before
screen shot 2019-01-15 at 14 42 53

After
screen shot 2019-01-15 at 16 49 36

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by walaura** [comment]
Hi! Confirm with @rcrphillips but I think we need to use the 4 colour google logo :(

**Comment by walaura** [comment]
Also! this is outside of the scope of the PR but can we pretty please make these buttons match the rest of buttons? they are taller and the font is bold and bigger, can pair if you wanna.

**Comment by laurenemms** [comment]
> Also! this is outside of the scope of the PR but can we pretty please make these buttons match the rest of buttons? they should be taller and the font is bold and bigger, can pair if you wanna!

Coincidentally, I've actually been working on that this morning. It looked a bit strange with the blue background and blue in the google icon. You mean to make them the same as the new ones on sign in right?

**Comment by walaura** [comment]
> > Also! this is outside of the scope of the PR but can we pretty please make these buttons match the rest of buttons? they should be taller and the font is bold and bigger, can pair if you wanna!
> 
> Coincidentally, I've actually been working on that this morning. It looked a bit strange with the blue background and blue in the google icon. You mean to make them the same as the new ones on sign in right?

yep!

**Review by jfsoul — APPROVED** [review]
lgtm!

**Review by walaura — APPROVED** [review]
😻

**Pull request merged**
