### PR TITLE
Reduce number of containers before lazy load to 5

### PR DESCRIPTION
**Pull request by robertberry-zz**
As iPad crashes with more than this 

CC @gklopper

### CODE REVIEW

**Comment by gklopper** [comment]
:+1:

**Comment by michaelwmcnamara** [comment]
can't expand image in page http://localhost:9000/world/picture/2015/feb/21/eyewitness-new-york-city-usa#img-1 to fullscreen
Seems to be related to the code on this branch as when I checked out master and tried the same thing it worked fine

**Comment by michaelwmcnamara** [comment]
Deleting previous comment as after I tried pulling latest master then checked out branch and ran a clean/compile in sbt - the problem went away - suspect was a result of some old crud from a different build. My sbt does get around.
Other than this couldn't see any issues.

**Comment by johnduffell** [comment]
no idea why your build failed, but maybe try a respin. then ship it! :+1:

**Comment by robertberry** [comment]
Not sure if we'll need this once we've sorted out the CSS so closing for now

**Pull request closed without merging**
