### PR TITLE
AB: Remove social share and rich link AB tests

### PR DESCRIPTION
**Pull request by gtrufitt**
## What does this change?

Removes the AB tests.
## What is the value of this and can you measure success?

They are complete.

### CODE REVIEW

**Comment by gtrufitt** [comment]
@guardian/dotcom-platform

**Comment by TBonnin** [comment]
😿

**Comment by johnduffell** [comment]
I hope you won't keep us in suspense about the results!

**Comment by johnduffell** [comment]
👍

**Comment by gtrufitt** [comment]
@johnduffell Make sure you ⭐ subscribe ⭐ to our newsletter for all the juicy gossip!

**Pull request merged**
