### PR TITLE
Moving alumni to the correct section, and adding myself to the team :)

### PR DESCRIPTION
**Pull request by NataliaLKB**
Simply moving some Alumni from the `TEAM` section to `ALUMNI and COLLEAGUES`.

Also, I added myself to the team. :smile:

### CODE REVIEW

**Comment by rich-nguyen** [comment]
:+1:

**Comment by gklopper** [comment]
:+1: - some people in dire need of demotion :smile: cc @robertberry @phamann

**Comment by NataliaLKB** [comment]
Added another commit to this PR. @jennysivapalan has been moved to `TEAM`.

**Comment by jennysivapalan** [comment]
Great thanks! :+1:

**Comment by phamann** [comment]
WTF?%^&! I demand to know whom said this was OK? I hope that Snowden, Viner and Cordey where all consulted before making such drastic move...

**Comment by phamann** [comment]
p.s. hopefully see you all tonight.. :smile:

**Pull request merged**
