### PR TITLE
Update grunt-jscs to 1.8.0

### PR DESCRIPTION
**Pull request by OliverJAsh**
The new version automatically traverses the file tree and reads `.jscsrc` files. This is good because these files can also be read by the JSCS plugin for various IDEs, e.g. SublimeLinter-jscs.

### CODE REVIEW

**Comment by davidrapson** [comment]
Might be missing the point here, but is it worth upgrading if you are about to replace / deprecate this with `eslint`? https://github.com/guardian/frontend/pull/9502

**Comment by OliverJAsh** [comment]
I wanted to get the newest versions of ESLint+jscs in place before reviewing features. I've read that ESLint supports most of the rules provided by jscs. On the other hand, jscs has a nice "auto format" option.

**Comment by davidrapson** [comment]
Thought you'd have a plan here, carry on.

**Comment by OliverJAsh** [comment]
:+1: anyone?

**Pull request merged**
