### PR TITLE
Fix crossword input validation

### PR DESCRIPTION
**Pull request by zetter**
## What does this change?

This improves how accented characters and numbers are handled in crosswords by:
+ allowing numbers to be inputted
+ marking clues as answered when they contain numbers or accented characters

## What is the value of this and can you measure success?

Currently certain crosswords are uncompletable. This can be unfulfilling for anyone trying to solve them. Others have seen this too, for example, [there's a few comments about it on a recent weekend crossword](https://www.theguardian.com/crosswords/weekend/410#comment-122353358).

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

I've worked on [extracting the crossword component](https://github.com/zetter/frontend) which has made it easier for me to work on these fixes independently of the rest of the frontend codebase. I've been able to run tests & linters for the isolated component and test it in browser to give me the confidence that this fixes the issue.

—-

I've read that certain contributions require a signed CLA as I'm an external contributor. Please let me know if this is required since I'm happy to do this.

### CODE REVIEW

**Comment by AWare** [comment]
Hey @zetter this is great. 

Our CLA is https://github.com/guardian/frontend/blob/88cfa609c73545085c3e5f3921631ec344a3eb83/cla-individual.txt here. 

We're really happy that you've also taken the time to extract the component into its own codebase. I guess we should probably consider whether it should have its own codebase and package instead of living in the frontend repo.

**Comment by mchv** [comment]
@zetter Thanks a lot for your contribution!

**Comment by zetter** [comment]
Thanks for taking a look at this, I have since submitted a signed CLA.

**Review by AWare — APPROVED** [review]
Thanks for taking the time to make our crosswords better.

**Comment by mchv** [comment]
@zetter in the name of all @guardian/all I would like today to express today once again our gratitude for this contribution, which has been truly appreciated by guardian users each time there is accented letters  in our crosswords!  

You may not know this, but your are a legend!

Screenshot 2021-11-19 at 14 48 29

**Pull request merged**
