### PR TITLE
Set Up New Commercial Integration Test Configuration

### PR DESCRIPTION
**Pull request by kelvin-chappell**
This enables a new SBT command: `commercial-integration:test`
which will be used in the new Teamcity build configuration.

Also:
- webdriver uses ChromeDriver in local mode
- packages have been put under an integration package

/cc @rich-nguyen

### CODE REVIEW

**Comment by johnduffell** [comment]
is the idea they will be more reliable because there are less tests, or is the idea to take out the unreliability of saucelabs?
Because I think getting rid of saucelabs would be great if someone here is maintaining a machine with chrome on.  Saucelabs is only really useful to save maintenance and give us access to a million different browsers.

**Comment by gklopper** [comment]
Yes, why?

**Comment by kelvin-chappell** [comment]
The idea of having a local non-saucelabs option for running tests is to make it easier to run them on a dev machine, especially when you're building a new test.

Perhaps a better general approach is to have one suite of integration tests and get rid of any that repeatedly fail without being fixed.  That would leave us with a set of tests that are valuable.

**Comment by kelvin-chappell** [comment]
Another incarnation of this coming up soon.

**Pull request closed without merging**
