### PR TITLE
Update CAPI & FAPI clients to latest versions (also remove hack required for Lightbox)

### PR DESCRIPTION
**Pull request by ioannakok**
## What does this change?

The latest version of the CAPI client (v19) includes https://github.com/guardian/content-api-scala-client/pull/359, which we can use to replace the pagination code based on [`play-iteratees`](https://github.com/playframework/play-iteratees) (introduced in July 2014 with https://github.com/guardian/frontend/pull/5199), currently blocking the [Scala 2.13 upgrade for Frontend](https://github.com/guardian/frontend/issues/24817).

The updated CAPI client is binary-incompatible with previous versions of the CAPI client, meaning we also need to update the FAPI client - as it also uses CAPI, and needs to be compiled against the same CAPI version. A similar PR, updating FAPI & CAPI in Ophan is at https://github.com/guardian/ophan/pull/4719, and has been successfully deployed. Like there, we're adding a `FaciaClientTest` that will break at build time rather than runtime if our versions of the FAPI & CAPI clients are incompatible.

The updates to the CAPI client also support `previous`/`next` search functionality, as used by the Lightbox, meaning that the small `ContentApiNavQuery` hack for the Lightbox (introduced here: https://github.com/guardian/frontend/pull/20462) can now be removed.

## Screenshots

The next/previous functionality in lightboxes (eg on [this article](https://www.theguardian.com/commentisfree/picture/2022/may/22/brian-adcock-on-the-looming-sue-gray-report-cartoon)) from https://github.com/guardian/frontend/pull/20462 continues to work:

https://user-images.githubusercontent.com/52038/176659959-1bba3f4e-cea7-4c75-8927-42b06a209da3.mov

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [x] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Tested

- [ ] Locally
- [x] On CODE (optional)

### CODE REVIEW

**Comment by ioannakok** [comment]
Deployment to CODE succeeded almost everywhere except for facia-press. We should release a beta version of facia-client: https://logs.gutools.co.uk/s/dotcom/goto/02ce2d00-f24e-11ec-9ed0-71515ea686c5

**Comment by ioannakok** [comment]
We compared and they were the same:

https://m.code.dev-theguardian.com/getprev/commentisfree/series/guardian-comment-cartoon/commentisfree/picture/2022/may/22/brian-adcock-on-the-looming-sue-gray-report-cartoon

https://theguardian.com/getprev/commentisfree/series/guardian-comment-cartoon/commentisfree/picture/2022/may/22/brian-adcock-on-the-looming-sue-gray-report-cartoon

**Comment by rtyley** [comment]
[Deploying](https://riffraff.gutools.co.uk/deployment/view/c2750520-bf14-44bc-a966-a48755992bdc) build 43804 (https://github.com/guardian/frontend/commit/71b241d28dacd0ebfa7a8c14eed3e8febb1b7746 - which has the FAPI client updated to use the same CAPI client with https://github.com/guardian/facia-scala-client/pull/271) to CODE has completed - happily, there are no further `java.lang.NoSuchMethodError` errors showing up in the [logs](https://logs.gutools.co.uk/s/dotcom/goto/08f30dc0-f863-11ec-8bc5-a5ef3755e21d):

image

The lightbox functionality from https://github.com/guardian/frontend/pull/20462 is also working

https://user-images.githubusercontent.com/52038/176659959-1bba3f4e-cea7-4c75-8927-42b06a209da3.mov

**Review by jfsoul — APPROVED** [review]
💯

**Comment by rtyley** [comment]
Deployed on PROD, and the lightbox still works!

https://user-images.githubusercontent.com/52038/176927036-77372a17-7a05-4b49-88ad-3cc24b5dd464.mov

**Pull request merged**
