### PR TITLE
Update DCR rendering logic

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

Update the DCR Rendering logic to match the following logic: 

pic

### CODE REVIEW

**Comment by MatthewJWalls** [comment]
Does this logic change essentially reduce to => "Never use DCR if you're in the ab test control group" ?

**Comment by shtukas** [comment]
@MatthewJWalls Yep

**Review by MatthewJWalls — APPROVED** [review]
I'm going to approve this for now in the name of getting this into production, but *that being said* if you want to you can probably implement this code more cleanly in the picker rather than the controller by adding ```val isCommercialBetaControl = ActiveExperiments.isParticipating(DotcomRenderingAdvertisements)```

and adding a new boolean to the logic for it.

**Review by MatthewJWalls — APPROVED** [review]

**Comment by MatthewJWalls** [comment]
+1 again

**Comment by shtukas** [comment]
@MatthewJWalls @nicl 
I am closing this, after discovering that I don't need, since what I wanted has already been implemented.

**Pull request closed without merging**
