### PR TITLE
Improve our hiring messages

### PR DESCRIPTION
**Pull request by adamnfish**

### CODE REVIEW

**Comment by mattandrews** [comment]
Classic Adam.

**Comment by janua** [comment]
:eyes:

**Comment by johnduffell** [comment]
:hand:

**Comment by mattandrews** [comment]
:money_with_wings:

**Comment by janua** [comment]
:facepunch:

**Comment by uplne** [comment]
:anchor:

**Comment by robertberry** [comment]
LOL.

But no. :-1:

**Pull request closed without merging**
