### PR TITLE
Sticky nav scenario with adblock

### PR DESCRIPTION
**Pull request by Calanthe**
Sticky nav scenario with adblock turned on.

stickynavadblock

### CODE REVIEW

**Comment by paperboyo** [comment]
giphy

**Comment by sndrs** [comment]
:+1: great, but i'm still unhappy about how all those styles are set inline and not by class...

**Comment by uplne** [comment]
@sndrs totally agree. As we discussed I am going to look at it today

**Comment by uplne** [comment]
@Calanthe is it fixed for mobile too? We have a few complaints about it having a blank space.

**Comment by sndrs** [comment]
>As we discussed I am going to look at it today
:nail_care: :smiley:

**Comment by Calanthe** [comment]
@uplne I din't look at mobile. Didn't even know that we have problems there.

Maybe we can do it as a separate pull request? Because I doubt it is related to adblock.

**Comment by uplne** [comment]
@Calanthe lol yeah true, I was too fast. We have a little bit different problem there so it should be another PR. :+1:

**Comment by paperboyo** [comment]
Not working for me :sadpanda: Still broken in latest releases of FF and CH on 10.9.3 with AdBlock Plus 2.6.9.1 and 1.9.1 respectively (updated subscriptions). Totally for testing, obviously :palm_tree:

**Comment by Calanthe** [comment]
It works fine on newest Chrome (43.0.2357.134) and Adblock Plus (1.9.1). I am not sure if we have an easy solution to detect adblocks in other browsers.

**Comment by paperboyo** [comment]
?? Do we have to be able to detect it? Could we not brake the site in the first place instead of then having to be able to detect an extension in order to fix the broken site just for the users of that extension?

Seems almost as convoluted as the above sentence, no?

**Comment by Calanthe** [comment]
You should talk with different people. Not with a simple developer like me. That wasn't my decision.

**Comment by paperboyo** [comment]
I may have been to quick to report (2hrs seemed like enough of a wait). Seems to be working correctly in both browsers now. Apologies!

Still think that above comment holds true, though...

Regards
The Simplest

**Comment by paperboyo** [comment]
Came back. But just in FF. Maybe recent changes around FF adblock sniffing caused the comeback? (like e.g. https://github.com/guardian/frontend/pull/10152).

**Comment by Calanthe** [comment]
I investigated it and it seems that on FF (mainly with Adblock Plus) we can't distinguish if users whitelisted us or not. We can only detect if Adblock Plus add-on is installed. I was told to leave it as it is right now because in this situation we have to assume that we are whitelisted. Of course, the new sticky banner AB test won't work on FF (with Adblock Plus) either.

**Comment by paperboyo** [comment]
Thanks for looking into it, @Calanthe. I do not understand the reasoning at all, though. If we are assuming to be whitelisted, why we treat readers that whitelist us to a sudden appearance of a huge empty space (that does not go away until reload and then reappears as soon as one scrolls)?

crap-space

My above comment (https://github.com/guardian/frontend/pull/9789#issuecomment-121989836) still very much applies, IMHO :sadpanda:

**Pull request merged**
