### PR TITLE
Set inline logo size for slim header without SVG

### PR DESCRIPTION
**Pull request by marchibbins**
Sass ampersands twisting my melon, can't see a way to combine this with the rule above it?

### CODE REVIEW

**Comment by marchibbins** [comment]
Before fix screengrab: 

image

**Comment by davidrapson** [comment]
```
.no-svg .l-header--is-slim & {
    .inline-logo {
        width: 160px;
        height: 30px;
    }
}
```

This selector is going to generate the following `.no-svg .l-header--is-slim .logo-wrapper .inline-logo`. That may or may not be what you want…

FWIW I'm not a fan of `&` selectors for exactly this reason; can lead to accidental specificity issues and non-obvious selectors. Is it an option to write out the selector longhand?

**Comment by marchibbins** [comment]
@davidrapson correct, that's the order I'm after. Previous rule is selecting `.no-svg .logo-wrapper .inline-logo`, the slim header modifier is above the wrapper but after `.no-svg` on the `html` element.

**Comment by davidrapson** [comment]
Hmm, your original selector should give you that, but I'd still suggest writing the selector out long-hand to get (without nesting) to get what you want, then you could probably strip back the selector to the bare minimum.

**Comment by marchibbins** [comment]
With fresh eyes I can see a better place for this, so moved it up into the existing `.l-header--is-slim` block. I'm also not a big fan of the `&` use but it's the de facto in this file and elsewhere so in favour of consistency it should match. Think it's still clear what the (full) selector is without writing it out long-hand.

**Comment by davidrapson** [comment]
:+1: Great. Yeah agree it's better to follow the existing style.

**Pull request merged**
