### PR TITLE
Fix issue with thin black line appearing above youtube atom overlay

### PR DESCRIPTION
**Pull request by GHaberis**
## What does this change?

Fixes issue in Chrome where when you use "background-size: cover", if the position of background-image isn't less than 50% then you sometimes see a 1px 'line' at the top of the overlay, setting position to 49%  instead will fix this problem.

## What is the value of this and can you measure success?

Fixes bug

## Does this affect other platforms - Amp, Apps, etc?

No

## Screenshots

Before...

picture 34

After...

picture 33

## Tested in CODE?

No

@akash1810

### CODE REVIEW

**Comment by akash1810** [comment]
Oh wow! This feels a bit magic to me. Is this a general bug in Chrome's implementation of `background-size: cover` or ours?

**Comment by GHaberis** [comment]
@akash1810 it is magic, I found a handful of people reporting the same issue online although no official bug report, this solution seemed the best as it matched closely to the original rules (background-size: cover; background-position: 50% 50%) were derived from youtube's implementation.

I've done a little testing and I could remove background-position completely to remove this bug on youtube-atoms. If I do it'll default the position to 0% 0%. This means that an image which doesn't match the aspect ratio of the container would be partially 'cut off' from one side only (eg. bottom side) rather than the cut off area being equally spread (eg. between top and bottom) - this is not necessarily a problem for youtube-atoms however as the image aspect ratio always matches the container size (16:9)?

**Comment by akash1810** [comment]
Interesting. Could we add a comment for future generations? Then 👍 

> this is not necessarily a problem for youtube-atoms however as the image aspect ratio always matches the container size (16:9)?

We don't enforce this rule (but it has been added to the [project](https://github.com/guardian/media-atom-maker/projects/2#card-1329735)) so we probably can't rely on this being true yet.

**Review by NataliaLKB — APPROVED** [review]
lgtm! But definitely agree with @akash1810 that a comment is really needed. Maybe a link to where you found the hack?

**Comment by GHaberis** [comment]
I've added a little info as suggested!

**Pull request merged**
