### PR TITLE
Remove `localStorage` font loading code

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

removes the old `localStorage` font loading code, now that #24094 seems to be settled in.

font files themselves are removed in #24161 (merge that after this)

### CODE REVIEW

**Comment by jamie-lynch** [comment]
> The diff you're trying to view is too large. We only load the first 3000 changed files.

😨

**Comment by sndrs** [comment]
the deletions are almost all in https://github.com/guardian/frontend/tree/main/static/src/fonts. maybe i'll do a second PR for that lot, since they're just static assets that aren't published.

**Comment by sndrs** [comment]
font file removal is now in #24161

**Review by SiAdcock — APPROVED** [review]
LGTM 👍

**Pull request merged**
