### PR TITLE
add commit hook to ensure npm-shrinkwrap.json is added with package.json

### PR DESCRIPTION
**Pull request by desbo**
also change git-hooks/update-message.js to support different messages

@sndrs @rich-nguyen @OliverJAsh :eyes:

### CODE REVIEW

**Comment by sndrs** [comment]
:+1: looks great :lips:

**Comment by OliverJAsh** [comment]
I like this idea! However, what if a change is made to `package.json` because a jspm dependency was changed—or—more unlikely—some other metadata was changed?

**Comment by desbo** [comment]
@OliverJAsh afaik `npm-shrinkwrap.json` includes everything (name, version, jspm deps) so any change should be reflected

**Comment by OliverJAsh** [comment]
@desbo I don't think npm shrinkwraps any of the jspm dependencies?

**Comment by desbo** [comment]
is it not this? https://github.com/guardian/frontend/blob/master/npm-shrinkwrap.json#L12187

**Comment by desbo** [comment]
ohh, that's jspm itself :sob:

**Comment by OliverJAsh** [comment]
You could read the JSON to see if there's changes to the value of `dependencies`? Or, pass if there are changes to `systemjs-config.js` (the shrinkwrap equivalent for npm). In cases where we change our stuff (metadata), we could just force commit.

**Comment by desbo** [comment]
hmm, to get the changes we'd need to read the output of `git diff`, which has no notion of it being JSON. I've added an extra check that will allow the commit to go through if `systemjs-config.js` is staged. 

metadata should be fine - I tested changing the name (and nothing else) in `package.json` and it was shrinkwrapped.

**Comment by OliverJAsh** [comment]
:+1:

**Comment by rich-nguyen** [comment]
:+1: super

**Pull request merged**
