### PR TITLE
Upgrade jspm to 0.16.2 (out of beta!)

### PR DESCRIPTION
**Pull request by OliverJAsh**
This has version locking which will stop the build from breaking unexpectedly.

### CODE REVIEW

**Comment by sndrs** [comment]
:dancer: :+1: :8ball:

**Comment by desbo** [comment]
`dl-loader` still overwrites the babel versions in package.json though 8(

**Comment by OliverJAsh** [comment]
@desbo, you're right. Still tracking https://github.com/jspm/jspm-cli/issues/947. At least this will stop SystemJS from auto updating.

**Comment by sndrs** [comment]
> :kiss:

:kiss:

**Comment by desbo** [comment]
the fix for `dl-loader` has gone in, propose we close this and wait until the next version

**Comment by desbo** [comment]
they just released 0.16.1 so that's it upgraded and babel locked down :point_up: :lock:

**Comment by rich-nguyen** [comment]
:+1:

**Comment by OliverJAsh** [comment]
Ah, 0.16.1 conflicts with the text plugin. Waiting on https://github.com/systemjs/plugin-text/issues/16

**Comment by OliverJAsh** [comment]
0.16.2 is good to go. Will ship this today.

**Pull request merged**
