### PR TITLE
Adds the standfirst and byline on mobile

### PR DESCRIPTION
**Pull request by blongden73**
Adds the byline to the photo essay on mobile

picture 455

### CODE REVIEW

**Review by NataliaLKB — APPROVED** [review]
lgtm! 👍

**Comment by sndrs** [comment]
this means the standfirst will exist twice right?

**Comment by NataliaLKB** [comment]
@sndrs Its the same as the immersive template, the standfirst and byline do exist twice because they are in different places as the design changes between mobile and desktop. 

If we want to only have them exist in one place, i think we would need design approval (last time Sam Morris didn't want either the mobile or desktop experience to change)

**Comment by sndrs** [comment]
if ever there was a code smell that a design was too complex then surely needing to duplicate the dom must be it?

sounds like it's broader than the scope of this PR though

**Comment by NataliaLKB** [comment]
I agree with both those statements. Lets chat @blongden73 @sndrs tomorrow? Surely there is a situation which would work for both.

**Comment by sndrs** [comment]
in the meantime this look 👍

**Comment by paperboyo** [comment]
> didn't want either the mobile or desktop experience to change

I always abhorred this out-of-place solid gray patch appearing only on mobile:

a shade too much

And now it's gonna spread further... Out of scope of this PR, obv, but you've mentioned a possible  discussion...

**Pull request merged**
