### PR TITLE
Having a little moment in the header     

### PR DESCRIPTION
**Pull request by zeftilldeath**
An orange one. 

screen shot 2019-02-18 at 15 56 23

### CODE REVIEW

**Comment by SiAdcock** [comment]
It's worth considering that the contrast / font size for the buttons would [fail WCAG AAA](https://webaim.org/resources/contrastchecker/) for colour contrast. Currently these buttons pass AAA, so this would be an accessibility regression.

screen shot 2019-02-18 at 17 55 47

**Comment by walaura** [comment]
> It's worth considering that the contrast / font size for the buttons would [fail WCAG AAA](https://webaim.org/resources/contrastchecker/) for colour contrast. Currently these buttons pass AAA, so this would be an accessibility regression.

@SiAdcock wouldnt these buttons count as 'large text'? as they are bold and around 17px? I realize this is clutching at straws which is why

@zeftilldeath @blongden73 would `#121212` be acceptable? that one passes all four checks and follows the [pattern from the yellow contributions banner](https://github.com/guardian/frontend/pull/21086) where buttons are a "solid" object rather than letting the background be seen through them like the roundel does

**Comment by SiAdcock** [comment]
@walaura

From the WebAIM website:

> Large text is defined as 14 point (typically 18.66px) and bold or larger, or 18 point (typically 24px) or larger.

I think the button font size is `16px`. Can we make the font size larger, or use a `$opinion-pastel` (`#F9B376`) for the colour?

**Comment by zeftilldeath** [comment]
When I tested this I was under the impression that reaching AA standard was acceptable especially for non essential information, and that triple AAA was "ideal". Given that this is a promotional element I figured that it being harmonious with the campaign and reaching AA would be acceptable. Laura's suggestion was what I previously had, but we wen't overlay happy with the way the black looks on the orange in that context, but I agree it's the best way of achieving AAA.

I can push up that change this morning.

As a side note, [W3C concedes](https://www.w3.org/TR/WCAG20/#conformance-reqs) that achieving AAA across the board is unlikely to be possible in most cases:

```Note 2: It is not recommended that Level AAA conformance be required as a general policy for entire sites because it is not possible to satisfy all Level AAA Success Criteria for some content.```

Which is why I assume the "Pass" labels on the tool you used to check the contrast aren't AAA compliant. I recognise that this sounds petty - but if WebAIM have picked a colour ratio that doesn't conform to AAA it does imply that they are taking in other considerations rather than blanketly saying AAA must be reached across the board.

The .gov [design system](https://design-system.service.gov.uk/styles/colour/) states:
```You must make sure that the contrast ratio of text and interactive elements in your service meets level AA of the Web Content Accessibility Guidelines (WCAG 2.0).```

What is out stance on this? Currently the majority of our none greyscale text colour ratios are AA and not AAA, just look at the cards on fronts.

**Comment by walaura** [comment]
@zeftilldeath I agree with your points! Would love to have more specific guidance on adherence to AA/AAA in the future but this being a temporary campaign rather than a permanent fixture I'm happy to leave the text colour for you to decide

**Comment by SiAdcock** [comment]
Excellent points, @zeftilldeath. I'm going to update our [guidelines on colour contrast](https://accessibility.gutools.co.uk/testing/web/colour-contrast/) because they are very strict and arguably unachievable across the site!

**Review by SiAdcock — APPROVED** [review]
👍 from a code / accessibility point of view

**Pull request merged**
