### PR TITLE
Replace the existing SVG adblock banner with a new one

### PR DESCRIPTION
**Pull request by philwills**
## What does this change?

Replaces the existing adblock banner advertising membership with a new one
## What is the value of this and can you measure success?

Uptick in membership signups from the associated campaign code
## Does this affect other platforms - Amp, Apps, etc?

No
## Screenshots

image
## Request for comment

The images need to be finalised, but I wanted to get feedback on whether this was an appropriate approach sooner, rather than later, as it's a long time since I last did anything in frontend.

### CODE REVIEW

**Comment by tomverran** [comment]
The new banner design looks great!
Are we losing anything by using an image as opposed to HTML / CSS?

**Comment by paperboyo** [comment]
> Are we losing anything by using an image as opposed to HTML / CSS?

Judging by above design, they would probably be smaller in HTML/CSS/SVG. PNGs will look bad on HiDPI devices. The fonts will look fuzzy/different. If it’s compatibility, then we may just not mix vector and raster elements within an SVG. It’s obviously still possible to have a fallback in PNG...

And these PNGs could be much smaller.

But most importantly it’s gonna be a mojor PITA to replace £ with $ and ¥ and ֏ and ؋ and ৳ and ૱ and ௹ and ฿ and ៛ and € and ₭ and ₮ and ₲ and ₽ and ﷼ and all the rest. And to adjust the amount...

**Comment by sndrs** [comment]
yeah curious about why it's a png? not sure why it was ever a png embedded in an svg, but an svgs for the whole thing seems appropriate?

**Comment by philwills** [comment]
Primarily because that's what I was given, but I can go back and ask when Akemi is next in the office.

**Comment by philwills** [comment]
Given that we only target by edition, the currency symbol issue isn't as much of a problem as it might otherwise be.

**Comment by jbreckmckye** [comment]
One issue with the old SVGs was that we inlined them into the bundle, which added quite a bit of weight to them IIRC. Perhaps we could just place an SVG image in the static directory - taking advantage of the retina-friendliness of vectors, but also the long-term caching and lazier loading of a static file.

**Comment by sndrs** [comment]
you could always `require` it at runtime?

**Comment by jbreckmckye** [comment]
@sndrs Does that end up much different to just loading it through an `img` tag?

**Comment by sndrs** [comment]
use the platform you mean? rather than delivering a complicated dependency management system to conditionally load an asset via a plugin? intriguing... :)

yes, that's a much better idea :) 

but a couple svgs should give a much nicer display, as you say

**Comment by paperboyo** [comment]
Not necessarily for these as at least some of the fonts we do not serve on dotcom, but would it be possible for the SVGs to use dotcom fonts in similar circumstances? That would mean better readability, rendering and much smaller filesize.

Also these different breakpoint designs look awfully like it could be just one responsive graphic... maybe.

**Comment by philwills** [comment]
I asked Akemi nicely and she's given me some shiny SVGs at double resolution as suggested by @paperboyo 

I've also checked what images are desired for all editions, so I think this is now ready to go.

**Comment by paperboyo** [comment]
Thanks, Akemi, @philwills!

BTW, these are at twice the resolution to better swallow optimisations, if that creates problems when placing them (shouldn't), then you can edit `width` and `height` in them to be half of what it is...

**Comment by johnduffell** [comment]
looks great! really smart.  interesting reviewing those massive files, but 👍 
might be worth running it through webpage test or something just to check no obvious CS perf gremlins

**Comment by paperboyo** [comment]
AFAIK they were run through SVGO(MG).

**Comment by johnduffell** [comment]
is this going out soon?

**Comment by philwills** [comment]
If everyone is happy then it's ready to go as far as I'm concerned, but I'm
out of the office till Tuesday.

Phil

On Thu, 2 Jun 2016 13:57 John Duffell, <notifications@github.com> wrote:

> is this going out soon?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/guardian/frontend/pull/13072#issuecomment-223283208>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEK6ToE9Kg5bB3JmMqHQ93IyGZCFWcuks5qHtNOgaJpZM4ImxAs>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by JonNorman** [comment]
Is this ready for the old :ship:?

**Comment by philwills** [comment]
No, the images got vetoed, so we're waiting on sign off of the new ones. 

Apologies for this hanging around.

**Comment by philwills** [comment]
This doesn't appear to be going anywhere at the moment, so I'll close and revive it if and when something is agreed.

**Comment by tomverran** [comment]
Have you considered releasing the new banners for the UK only? I made it possible to tailor banners by region in response to previous vetoes

**Comment by philwills** [comment]
@tomverran I did talk about it briefly with Nick M, but I think we both thought it would have been fully sorted by now.

**Pull request closed without merging**
