### PR TITLE
Add new climate change snap case

### PR DESCRIPTION
**Pull request by sammorrisdesign-zz**
Just another snappable treat. Would be good now that FAPI is nearly refactored to get this in properly @stephanfowler @janua, let me know if I can help out with this.

### CODE REVIEW

**Comment by janua** [comment]
@sammorrisdesign This entirely depends on the path, so should be fine! And `fapi` is already merged!

**Comment by sammorrisdesign** [comment]
@janua But we would also need the work to add the right classes if the path is a snap, right? Also to add the snap url attribute to the correct node.

Here I'm manually adding bits.

**Comment by robertberry** [comment]
:+1:

**Comment by janua** [comment]
@sammorrisdesign The path will never be a snap?

**Pull request merged**
