### PR TITLE
Vertical priority

### PR DESCRIPTION
**Pull request by uplne**
Changing z-index based on our vertical priority style guide

screen shot 2015-07-14 at 16 47 18

### CODE REVIEW

**Comment by davidrapson** [comment]
:+1: Nice!

**Comment by sndrs** [comment]
does this image correlate to the z-indexs? i've not seen it before but it looks great, but they look different?

**Comment by uplne** [comment]
@sndrs no. The image is showing theoretical layers on our website from 0 to 6 but these numbers doesn't correlate with actual z-indexes.

However it is a good point and we can make it more in line with the style guide. It can be 1010 - 1050.

**Comment by gklopper** [comment]
:+1:

**Pull request merged**
