### PR TITLE
New Header: Show users avatar

### PR DESCRIPTION
**Pull request by gu-stav**
## What does this change?

Implements the user avatar on the new header. Idea is: we always show the fallback SVG until the user opens the header. In case the avatar wasn't requested already, the SVG gets replaced with the avatar.

## What is the value of this and can you measure success?

Header feature completeness.

## Does this affect other platforms - Amp, Apps, etc?

No.

#### leftCol

screen shot 2017-06-20 at 13 02 45

#### desktop

screen shot 2017-06-20 at 13 03 47

#### Tablet

screen shot 2017-06-20 at 13 04 14

#### leftCol

screen shot 2017-06-22 at 17 16 42

#### Desktop

screen shot 2017-06-22 at 17 16 06

#### Mobile

screen shot 2017-06-22 at 17 16 15

## Tested in CODE?

Done.

### CODE REVIEW

**Comment by paperboyo** [comment]
Circle seems to have a 0,5-1px cutoff from the right hand side in the desktop screenshot above.

**Comment by gustavpursche** [comment]
@SiAdcock @NataliaLKB I think this is ready for a review now.

**Comment by NataliaLKB** [comment]
@gustavpursche can you update the images in the description?

**Comment by gustavpursche** [comment]
@NataliaLKB Done. Look at this beautiful Avatar!

**Review by NataliaLKB — APPROVED** [review]
<3 Love it.

**Pull request merged**
