### PR TITLE
Add logos to multiple-campaign commercial container

### PR DESCRIPTION
**Pull request by kelvin-chappell**
It looks like this at the moment:

image

So more styling will be required.

/cc @Calanthe

### CODE REVIEW

**Comment by kelvin-chappell** [comment]
@kenlim has looked at this code and I've refactored some of it as a result.

**Comment by paperboyo** [comment]
Looking at the Woodland one particularly... Where are they? Who manages them? Are they optimised (could call _via_ imgIX to force optimisation)?

**Comment by kelvin-chappell** [comment]
@paperboyo The logos are stored in the ad server at the moment.  They're managed by Ad Ops. I don't know if they're optimised.

**Comment by paperboyo** [comment]
Thanks, @kelvin-chappell, will try to have a closer look...

**Pull request merged**
