### PR TITLE
Add ability to specify a module to convert to es6

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

adds a `file` option to `make es6`, e.g. 

```bash
make es6 file=lib/ajax.js
```

## What is the value of this and can you measure success?

several people have wanted to swap files or convert another file before merging another. this should make that easier

### CODE REVIEW

**Comment by rich-nguyen** [comment]
👍  it looks like you may have to add logic around the `git status` command to avoid being frozen out of the conversion? Unless the intent is to make 1 branch per file convert.

**Review by rich-nguyen — APPROVED** [review]

**Comment by rich-nguyen** [comment]
Also somewhat related, I noticed the `Commit the content tranform`[sic] step doesn't include `--no-verify`, I assume that's intended for the user to see the lint errors before the final commit. I've been making fixes in a separate commit to the `lebab` conversion, for clarity. not sure what you'd prefer, @sndrs ?

**Comment by sndrs** [comment]
> 1 branch per file convert

yeah i htink so, the easier they are to PR the better

**Comment by sndrs** [comment]
> I assume that's intended for the user to see the lint errors before the final commit

yeah that's correct. once we moved linting+fixing to the commit hook, there was no need for an extra step, but we knew earlier steps would fail the linter. on a good day, everything will be fixed by lint/fix and there's nothing manual to do. manually fixing before the last commit is totally fine.

**Pull request merged**
