### PR TITLE
hide save for later button label on mobile breakpoints

### LINKED ISSUE #9778: Date line crashes into headline on mobile breakpoint
Reported by: Alex Breuer

Screenshots:
image1

image2

### PR DESCRIPTION
**Pull request by desbo**
Unfortunately there's no way to fit the full date, comments and save for later icon on related content containers. 
Fixes #9778.

### CODE REVIEW

**Comment by crifmulholland** [comment]
This affects tag pages too - http://www.theguardian.com/us-news/bernie-sanders
Only those where we list on a monthly basis, but will be more of a problem soon once Olly ads dates to more areas.

**Comment by desbo** [comment]
@crifmulholland have updated the change to hide the "save" / "saved" labels on mobile breakpoints

**Comment by crifmulholland** [comment]
I presume this is only when timestamps appear?

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
