### PR TITLE
add test to show controls on main media video

### PR DESCRIPTION
**Pull request by jamesgorrie**
## What does this change?

Adding the test to show media controls on main media video.
## What is the value of this and can you measure success?

Either people will notice this more and watch more video, in which case success = success - or they won't, in which case failure = success.
## Does this affect other platforms - Amp, Apps, etc?

No
## Screenshots

definitely-a-video
## Request for comment

@akash1810 @harrysalmon

### CODE REVIEW

**Comment by ScottPainterGNM** [comment]
Nice!

**Comment by akash1810** [comment]
bit sad the visibility of the controls are controlled by css rather than at the time the videojs is instantiated - but as its a test 👍

**Comment by jamesgorrie** [comment]
You can definitely control via JS. I might have a go if it proves profitable.

**Comment by harrysalmon** [comment]
Here's the SQL for analysis once the test is finished https://github.com/guardian/data-science/blob/master/mvt/video_starts_on_main_media.sql

**Pull request merged**
