### PR TITLE
Rename internal and ophan events for video quartiles

### PR DESCRIPTION
**Pull request by rich-nguyen**
A tidy up so that quartile events sent to Ophan appear as 'video:content:25' rather than 'video:play:25'. This is more consistent and allows us to name any future preroll quartile events in the same way.

I don't think this should cause a problem to [Ophan](https://github.com/guardian/ophan/blob/79aa04ae478e4456aa5ae6b492146b0903d52101/the-slab/app/lib/MediaPlaybackExtractor.scala#L17) @tackley ?

### CODE REVIEW

**Comment by tackley** [comment]
Should be just fine for ophan real time: see https://github.com/guardian/ophan/blob/master/the-slab/app/lib/MediaPlaybackExtractor.scala#L28, the only thing we care about in the middle position of the event is if the word is "preroll".

However, the data warehouse has not yet transitioned to using the output of the slab, so @tomseddon may need to update his current import scripts off the raw data accordingly. Please check with him!

**Comment by tackley** [comment]
Oh. Just noticed you'd linked to the appropriate bit of code in the slab already ;)

**Comment by rich-nguyen** [comment]
thanks @tackley . will close this until @tomseddon is back from hols.

**Comment by rich-nguyen** [comment]
Any update on this, @tomseddon ?

**Comment by tomseddon** [comment]
Hi,

Sorry for the delay, I've modified the ETL code to handle this now, so you can go ahead with the changes.

Cheers,

Tom

**Comment by rich-nguyen** [comment]
Great, no worries at all. Thanks for updating the ETL.

**Pull request merged**
