### PR TITLE
Click to grid

### PR DESCRIPTION
**Pull request by piuccio**
In the fronts tool, if an image exists in the grid, click on the thumbnail to open the image's page.

### CODE REVIEW

**Comment by paperboyo** [comment]
Cool! How hard would it be to open Grid in modal state instead (so that any click on suitable crop would automatically close the modal Grid and replace the source picture with the clicked crop)? Unless, I misunderstood and it already works like that...

**Comment by piuccio** [comment]
Interesting use case @paperboyo.

This PR opens the grid in a new tab. I'm trying to address a different use case; if you want to use one article's picture in another one, you can now click on the first thumb and from the grid drag into the second article.

What you describe is more like an image picker. It might require some work from the grid, cc @theefer.

**Comment by paperboyo** [comment]
> if you want to use one article's picture in another one, you can now click on the first thumb and from the grid drag into the second article

That functionality, useful as well, is currently provided by @theefer's great Gustaf extension's extension (long press on any pic on the live site, not preview, unfortunately, incl. a front). Maybe extending it to work within fronts tool as well would be more consistent and then a simple click could realise the image replacement scenario?

**Comment by piuccio** [comment]
Gustaf is brilliant, but we also need to make the experience easy in the tool itself, for people who don't use the extension or cannot access to it for whatever reason.

**Comment by theefer** [comment]
> What you describe is more like an image picker. It might require some work from the grid

I think in theory you could make it all work without any extra work on the Grid. Come and talk to me if you're interested.

**Comment by paperboyo** [comment]
How I see it (completely and purposefully disregarding pitfalls of implementation):

These two actions should be common to all images (eventually to all atomicised assets) - replacing in situ and finding the source. They should work on live site, on preview and in all tools. The interface/UX to realise them should be consistent (unless we decide that it should be consistent within the tools, but different to live/preview for some unknown reason).

Gustaf currently works only on the live site (it doesn't work on imagery within Composer or fronts tool, for example). I would have thought it best to just extend it so that it works - and works consistently - everywhere (unless: [INTERNAL ASSET]: https://github.com/guardian/teleporter/issues/22#issuecomment-114113013 :-). Then, if we decide it should not be long press, but eg. two icons, we would just have to change it in one place.

But if it's more realistic to rebuild the above functionality in every single tool separately - I couldn't care less (as far as it looks/behaves the same) :stuck_out_tongue_winking_eye:

**Comment by theefer** [comment]
> it doesn't work on imagery within Composer

I thought it worked somewhat on Composer but there are issues with many of the images that already have click handlers. But in short it doesn't work reliably, so it doesn't really work. It could, and should.

**Comment by piuccio** [comment]
closing this, will work on your suggestions

**Pull request closed without merging**
