### PR TITLE
Reduce number of layers in the nav

### PR DESCRIPTION
**Pull request by sndrs**
At tablet and below, a combination of `overflow: scroll` and `position` (for the weird `:after` elements on links – anyone know why they were done like that?) forced almost all elements in the nav into their own layer. This undoes that.
## before

screen shot 2015-08-07 at 15 09 07
screen shot 2015-08-07 at 15 07 57
screen shot 2015-08-07 at 15 07 25

screen shot 2015-08-07 at 15 28 34
## now

screen shot 2015-08-07 at 15 09 13
screen shot 2015-08-07 at 15 08 14
screen shot 2015-08-07 at 15 07 31
screen shot 2015-08-07 at 15 28 03
## testing

confirm across all browsers:
- [x] no visible changes to nav, compared to prod
- [x] 'click/touchability' of items in the nav is no different to prod

/cc @johnduffell 
/fyi @robertberry

### CODE REVIEW

**Comment by kaelig** [comment]
> for the weird :after elements on links – anyone know why they were done like that?

There was a lot of cross-browser weirdness going on when we coded this nav.

e.g. at the time Firefox did not even support positioning into `display: table-cell`.

`:after` was probably here to increase the hit zone in a controlled way.

If the browser support level has changed and browsers have gotten better, I'd totally recommend this change.

**Comment by johnduffell** [comment]
awesome, I agree with the requires testing, but once you're happy, go for it :+1:

**Comment by ScottPainterGNM** [comment]
I've run the branch across browsers and devices and all appears to be working without issue, the nav is just as clickable/touchable as before and no new errors appeared. 

QA :+1:

**Comment by kaelig** [comment]
In case it helps, I remember having troubles in Windows phones and old iOS. Old Firefox and IE were also really annoying regarding `display: table-cell`.

**Pull request merged**
