### PR TITLE
Adding assets frequency graph into admin

### PR DESCRIPTION
**Pull request by uplne**
screen shot 2015-02-05 at 15 29 44

screen shot 2015-02-05 at 15 26 05

### CODE REVIEW

**Comment by robertberry** [comment]
:+1: You are a Scala wiz

**Comment by phamann** [comment]
Why does the page have loads of horizontal padding in the screenshot?

**Comment by phamann** [comment]
:+1:

**Comment by uplne** [comment]
@phamann it's the part of the generated HTML/CSS. We are already removing it.

**Pull request merged**
