### PR TITLE
Fastdom commercial creatives

### PR DESCRIPTION
**Pull request by robertberry-zz**
Lots of nasty stuff in here!
- [ ] - Windows8 phone only top banner ad loads - other ad slots remain empty
  also seen on iphone 4S
- [ ] - Chrome on windows of roughly 738' width are showing mobile banner ads in mpu slots - seems to only happen when window size is close to threshold of mobile breakpoint but not reproduceable in CODE environment.

### CODE REVIEW

**Comment by johnduffell** [comment]
just interested in what difference you find in forced relayouts when you make these changes?

**Comment by phamann** [comment]
:+1:

**Comment by samdesborough** [comment]
:+1: 

looked for a gif of an "approved" stamp, I could only find this so here you go
sharonrubber

**Comment by robertberry** [comment]
@michaelwmcnamara Please could you help me test this? Basically need to make sure ads are all still appearing on all breakpoints on all devices.

**Comment by michaelwmcnamara** [comment]
ipad 2 - display of mpu on network front is not aligned with its actual slot - result is that only the bottom quarter of the mpu  is actually visible

**Comment by robertberry** [comment]
@michaelwmcnamara That was bug recently fixed in master I think. I'll merge master in so we can see if that fixes it.

**Comment by robertberry** [comment]
@michaelwmcnamara OK, master is now merged in.

**Comment by michaelwmcnamara** [comment]
Ah thats fixed it - much better :-)

**Comment by michaelwmcnamara** [comment]
Chrome on windows of roughly 738' width are showing mobile banner ads in mpu slots - seems to only happen when window size is close to threshold of mobile breakpoint but not reproduceable in CODE environment.

**Comment by michaelwmcnamara** [comment]
windows8 phone banner ad below sport container on network front does not load

**Comment by gklopper** [comment]
15 days and counting

**Comment by gklopper** [comment]
This needs to be Berried &trade; - SHIP or SHUT

**Comment by robertberry** [comment]
I really doubt you want me to merge this bug bomb while I'm drunk up a
mountain in the Alps! Feel free to close it and I'll resurrect it when I'm
back.
On 25 Mar 2015 14:54, "Grant Klopper" <notifications@github.com> wrote:

> This needs to be Berried ™ - SHIP or SHUT
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/8502#issuecomment-86037649>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by michaelwmcnamara** [comment]
Closing pull request until the prophecied return of Lord Berry.

tumblr_m69815oznm1r331r3o3_250

**Comment by sndrs** [comment]
"merge this bug bomb while I'm drunk up a mountain" - the ultimate Berrial

On Wed, Mar 25, 2015 at 3:44 PM Michael McNamara <notifications@github.com>
wrote:

> Closed #8502 <https://github.com/guardian/frontend/pull/8502>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/8502#event-264860566>.
>
> ------------------------------
> Visit theguardian.com. On your mobile and tablet, download the Guardian
> iPhone and Android apps theguardian.com/guardianapp and our tablet
> editions theguardian.com/editions.  Save up to 57% by subscribing to the
> Guardian and Observer - choose the papers you want and get full digital
> access.  Visit subscribe.theguardian.com
>
> This e-mail and all attachments are confidential and may also be
> privileged. If you are not the named recipient, please notify the sender
> and delete the e-mail and all attachments immediately. Do not disclose the
> contents to another person. You may not use the information for any
> purpose, or store, or copy, it in any way.  Guardian News & Media Limited
> is not liable for any computer viruses or other material transmitted with
> or as part of this e-mail. You should employ virus checking software.
>
> Guardian News & Media Limited is a member of Guardian Media Group plc. Registered
> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered
> in England Number 908396
>
>
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request closed without merging**
