### PR TITLE
Add to Homescreen: use proper roundel

### PR DESCRIPTION
**Pull request by OliverJAsh**
It's me again!

When one adds dotcom to their homescreen, the browser will use the square icon as per the manifest. This looks really bad against other icons which are not square!

Could we use the pure roundel instead, like the native app does?

Also I'm intrigued to know why we serve a 114px version?
# Before

image
# After

image

### CODE REVIEW

**Comment by jamesgorrie** [comment]
> why we serve a 114px version?

[According to this, retina iPad](http://www.kylejlarson.com/blog/creating-retina-images-for-your-website/).

**Comment by jbreckmckye** [comment]
👍 

This seems a reasonable change to me. Oliver, do you still have merge permissions?

**Comment by OliverJAsh** [comment]
Looks like I do, but of course I won't be able to see it out :-(

**Comment by sndrs** [comment]
nice one!

**Pull request merged**
