### PR TITLE
Add github docs to admin app view

### PR DESCRIPTION
**Pull request by MatthewJWalls**
## What does this change?

Quick PR to add links to the docs to the admin app so they show up on the frontend gutools 
## What is the value of this and can you measure success?

We said back in the tech time planning that this might be helpful so the gutools area can act as a portal to the frontend stuff.
## Does this affect other platforms - Amp, Apps, etc?

No

## Screenshots

N/A

### CODE REVIEW

**Comment by jfsoul** [comment]
I can definitely see the facia link being broken when somebody moves the documentation around in the future.  Can we just have the top level docs link?

**Review by TBonnin — APPROVED** [review]
❤️

**Comment by jfsoul** [comment]
Thanks! 👍

**Comment by MatthewJWalls** [comment]
Cool np, I just added it since the solitary link looked a little lonely!

**Comment by rich-nguyen** [comment]
Are there many people who know what the link is to the admin dashboard, but don't know how to get to the Frontend project on github?

**Comment by jfsoul** [comment]
I would say people don't automatically think to go to the docs.  The more places we can add references to them, the better?

**Comment by rich-nguyen** [comment]
@jfsoul I don't think we need to add it everywhere, especially given the area of concern usually associated with Admin. The docs link is already prominent on the project readme.

**Comment by dominickendrick** [comment]
@jfsoul @rich-nguyen So what is the conclusion ? Should we merge this ?

**Comment by jfsoul** [comment]
I am thinking this can be closed, I take @rich-nguyen's point and keeping the admin dashboard lean is a good thing.

**Pull request closed without merging**
