### PR TITLE
Smooth-scroll the new nav

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

makes the new nav scroll touch-style if possible

## What is the value of this and can you measure success?

smoothness

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
segue: another small improvement to the global user experience on mobile would be to disable the 300ms delay for clicks events on links and buttons: `a, button { touch-action: manipulation; }`

**Comment by NataliaLKB** [comment]
@sndrs When googling this, I found:
image

Should we be using this?

**Comment by sndrs** [comment]
https://github.com/guardian/frontend/search?utf8=✓&q=-webkit-overflow-scrolling

yeah, it's fine :)

isn't that warning just saying it's only webkit (basically)?

**Review by NataliaLKB — APPROVED** [review]
If we are already using it, I guess it shouldn't hurt.

**Pull request merged**
