### PR TITLE
Redisplay membership banners

### PR DESCRIPTION
**Pull request by paulbrown1982**
## What does this change?

This change triggers a re-display of the membership supporter banners (to people who have previously closed it). These appear on the footer of articles for any non-member who visits at least 10 different articles.

The Membership marketing team ask us to do this approximately twice per quarter.
## What is the value of this and can you measure success?

There is usually an uplift of supporter signups when this is done.
## Does this affect other platforms - Amp, Apps, etc?

No, only theguardian.com web users.
## Screenshots

picture 87

### CODE REVIEW

**Comment by adamnfish** [comment]
Would it be clearer to use a date string (e.g. 2016-05) instead of a number? Means you'd be able to see at a glance when it was changed and it would better show if some regions have been changed at different times (at the moment it looks like UK is newer because its increment is higher).

**Comment by paulbrown1982** [comment]
That's a good idea, I've submitted a change to include that.

**Comment by jamespamplin** [comment]
:+1: code changes look fine to me

**Comment by rtyley** [comment]
:+1:

**Pull request merged**
