### PR TITLE
Add structured bylineElements

### PR DESCRIPTION
**Pull request by philmcmahon**
## What does this change?
Adds a thing called bylineElements that looks like this:
screen shot 2018-11-14 at 17 07 12

Which should significantly simplify the logic in dotcom rendering for rendering the byline. I've not been able to remove the existing crazy `ContributorLinks` logic as it's used all over the place in dotcom  - not just `byline.scala.html` - and there doesn't seem  much point as eventually the templates it's used in will be replaced by dotcom rendering.

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by paperboyo** [comment]
Just a comment from a clueless completist: seems wasteful to repeat this logic on all frontends (most recently here and Daily Edition) when Composer is well placed to emit this as separated fields (yeah: and CAPI…)?

**Comment by philmcmahon** [comment]
You're completely right. This is actually the third time I've rewritten this logic - twice in dotcom rendering, once in dotcom, and this is probably the worst implementation so far (splitting on random made up characters) but I'm not sure I can take redoing it a 4th time. At least with this setup if I ever get round to putting the data in capi there won't be any changes to the dotcom api needed

**Comment by paperboyo** [comment]
Sak was rewriting it for the other thing just yesterday, too. Let me do my usual schtick in these instances: @franziskas, @LATaylor-guardian (CAPI part?), @gtrufitt 
[I don’t actually count on anything happening, but you never know :-)]

**Comment by philmcmahon** [comment]
It's not a tools problem - composer has the structure already - it's CAPI https://composer.gutools.co.uk/api/content/5b99d7d6e4b0be10064984df/preview

**Comment by SiAdcock** [comment]
Looks like something for one of @shtukas' coding challenges...

**Comment by AWare** [comment]
@philmcmahon as we're going to be making some changes for pullquote, do we want to look at whether we should fix this in CAPI and go for two birds with one stone?

**Comment by philmcmahon** [comment]
@paperboyo wins. this is going into capi.

**Pull request closed without merging**
