### PR TITLE
Fix image sizes for `ImageContent` type pages

### LINKED ISSUE #10467: Images on cartoon/picture type pages requested at too low a resolution
Hello,

Example URL: http://www.theguardian.com/commentisfree/picture/2015/sep/09/happy-twonyversary-prime-minister

The images on Cartoon/Picture type pages are requested at 700px max while they are shown at 940px wide on widest breakpoint resulting in crappy quality highlighted by Autrialia's picture editors. There are higher res mastercrops available, we just need to add a correct `src` size.

cc/ @JonnyWeeks

Related to https://github.com/guardian/frontend/issues/9482 (and, possibly, more...).

Regards
Mateusz

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes #10467

This was broken by #10266. /cc @johnduffell

### CODE REVIEW

**Comment by johnduffell** [comment]
:+1: thanks :grinning:

**Comment by OliverJAsh** [comment]
@johnduffell OK to :+1: the rename?

**Comment by paperboyo** [comment]
:sparkles:

**Comment by johnduffell** [comment]
@OliverJAsh I'm still waiting the the helpful comment on the object ;)
but it's definitely better than before :+1:

**Comment by OliverJAsh** [comment]
@johnduffell 7976d28aad8800efe56a046aaf8879c7ca11d970

**Comment by paperboyo** [comment]
In the best tradition of me sticking unrelated (slightly) stuff into people’s work, `isMainMediaLightboxable` is misbehaving sometimes. Check this out http://www.theguardian.com/world/picture/2014/may/07/sony-world-photography-awards.

**Comment by OliverJAsh** [comment]
@paperboyo Is there an issue for that, with expected and actual outcomes?

**Comment by OliverJAsh** [comment]
Merged this locally but for some reason GitHub hasn't recognised it: 7c8ddef7795e94e0a71f5500235797b6abced649

**Comment by paperboyo** [comment]
Yeah, sorry @OliverJAsh, no issue yet (I may open one later). Actual: there is no Lightbox icon, expected - there should be as the image is of enough resolution: http://static.guim.co.uk/sys-images/Guardian/Pix/pictures/2014/5/7/1399448330678/Michael-Nordqvist-winner--012.jpg.

**Pull request closed without merging**
