### PR TITLE
split out the switches into sensible files

### PR DESCRIPTION
**Pull request by johnduffell**
It keeps annoying me that the switches file is so big.  On one hand perhaps we have too many switches, but either way it doesn't make sense to have one long file for them all.

This PR splits them into files by category.  Things seem to compile and work ok locally, but any pointers to gotchas would be good.

### CODE REVIEW

**Comment by piuccio** [comment]
The previous implementation create a single output file in `/ENV/config/switches.properties`, is this still the case?

I'm asking because `facia-tool` has it's own stack now and reads from that file. If you change the format it'll stop working.

**Comment by johnduffell** [comment]
@piuccio nothing should have changed about the properties file, this change is just for the code that references it

**Comment by jennysivapalan** [comment]
Perhaps we could split this into a few PRs to make it manageable to deploy and check. For example just taking the Monitoring switches to it's own file, deploy that and check it's okay before doing the next set?

**Comment by johnduffell** [comment]
@jennysivapalan it would be possible but I'm not sure whether or not it's worth going through the whole deploy cycle for something so minor. anyone else have opinions either way on that?

**Comment by piuccio** [comment]
I like @jennysivapalan's idea. After this PR you'll have to check all apps to check whether they work properly. You can test them one at a time.
And keep facia-tool as last because I'll delete it in the coming weeks..

**Comment by jbreckmckye** [comment]
Do we have any rules for how long a switches' shelf life is? Some places I've worked use ninety days as a benchmark, but perhaps that's too generous?

**Comment by johnduffell** [comment]
@jbreckmckye I think it's hard to make a standard, it's just down to the developer to decide what makes sense for that switch.  Some things might just be needed for a week, but sometimes you want to run something for a few months to see how things go.

**Comment by jbreckmckye** [comment]
@johnduffell Yeah, makes sense. I guess it's just up to code review for us to keep them fairly reasonable.

**Comment by janua** [comment]
What's going on with this?

Not really that bothered by the massive switches file, but I think this PR is fine too, it's just changing name spacing really.

:+1:

**Comment by kelvin-chappell** [comment]
Bold move! But I think it's a good idea.

**Pull request merged**
