### PR TITLE
Update prettier

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

latest prettier

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
Much Prettier™️

**Comment by sndrs** [comment]
it's a shame you lose it (or add noise), but the benefits are pretty big i think

**Comment by SiAdcock** [comment]
Perhaps we can split the difference and only make minor version upgrades to `prettier`, no patch upgrades? As an amateur GitHub detective, it's difficult sometimes to trace the history of a particular line of code if the blame gives you noise like this.

**Comment by SiAdcock** [comment]
By the way, if we're upgrading prettier, ought there be a change to `package.json` in this PR?

**Comment by sndrs** [comment]
still in the range of package, only bumped in the lock file

**Comment by nicl** [comment]
@sndrs @SiAdcock okay thanks for the feedback. Agree it's worth prioritising the code today and readability while recognising the cost.

**Comment by SiAdcock** [comment]
We need to remember to rebase before merging as there have been JS changes since master was last merged

**Pull request merged**
