### PR TITLE
Resolve explicitely in adfree test

### PR DESCRIPTION
**Pull request by regiskuckaertz**

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
🙇  Thanks man

**Comment by SiAdcock** [comment]
cc @JustinPinner @Ap0c

**Comment by JustinPinner** [comment]
Nice, thanks!
🏁

**Comment by regiskuckaertz** [comment]
😅

**Comment by Ap0c** [comment]
Nice! 🌴

**Pull request merged**
