### PR TITLE
Extending to banner position test extra month

### PR DESCRIPTION
**Pull request by uplne**
We have sufficient data for this test and it seems that odds are against this amazing feature. However the user experience gain is great so I would like to wait for product owner (on holiday) to go through data one more time and possibly setup some process so it won't be lost in the abyss of the past.

### CODE REVIEW

**Comment by rich-nguyen** [comment]
:+1:  maybe up the traffic to, by adding another variant to the variant list? gets you some more data.

**Comment by paperboyo** [comment]
> user experience gain is great

Skew the data, then. Fake it. Where do I have to click? How many times? I’ve got loads of friends, you know... This data thing will bury us all. :pouting_cat: :bar_chart: 

https://www.youtube.com/watch?v=GAXLHM-1Psk

*all views mine, whose else, right?!

**Comment by uplne** [comment]
We have enough data :disappointed: It is really only :money_with_wings: talking in this case. But I am idealist so I want to push for it more.

**Comment by rich-nguyen** [comment]
@uplne good stuff. For me, that's not idealism. That's just doing the right thing.

**Comment by paperboyo** [comment]
> That's just doing the right thing

+1!

**Pull request merged**
