### PR TITLE
[WIP] Cache assets using service worker

### PR DESCRIPTION
**Pull request by GHaberis**
## What does this change?

This PR creates a named cache in our service worker for cacheing responses to requests for assets served from `assets.guim.co.uk`.

Why? After debugging the service worker running for the www.theguardian.com I came to the conclusion that the fetch requests intercepted by the service worker were always falling back to network requests rather than returning cached responses. The screen shots below demonstrate this. Note I turned off the browser cache for these tests...

**Prod / 1st load / No service worker running / assets retrieved from network**

prod-1st-load
 
**Prod / 2nd load / Service worker active / assets retrieved from network via service worker**

The service worker is active and now intercepts requests for assets, however if they don't exist in the cache it fallback to a network request. We'd expect to see this happening on 2nd load as this is the first time the service worker has intercepted the `fetch` requests so no assets will be cached yet. Network requests via the service worker are denoted by the gear icon in the network panel.

prod-2nd-load

**Prod / 3rd load / Service worker active / assets should be retrieved from service worker cache**

Assets requests intercepted in the 2nd load should now be cached and the service worker should return this cached response rather than going to the network. **The problem is the requests still go to the network via the service worker, as denoted by the gear icon in the network panel.**

prod-3rd-load

To address this issue I have created a named cache, in which I explicitly add responses when they have been retrieved from the network. This appears to fix the issue as show in the screen shots below... 

**gh-service-worker-cache / 1st load / No service worker running / assets retrieved from network**

As expected asset requests go to the network on first load as the service worker has not activated...

pr-1st-load

**gh-service-worker-cache / 2nd load / Service worker active / assets retrieved from network via service worker**

The service worker is now running and the cache has been set-up. Requests go to the network via the service worker but now the service worker is explicitly adding responses to the cache.

pr-2nd-load

**gh-service-worker-cache / 3rd load / Service worker active / assets retrieved from service worker cache**

pr-3rd-load

Now the service worker intercepts requests and returns the cached response. **The gear icon is no longer visible on 3rd load and the response times are much less than on the Prod 3rd load eg. 36ms for `graun.enhanced.js compared to 525ms.**

## What is the value of this and can you measure success?

This should speed up response time for assets served from `assets.guim.co.uk`.

## Does this affect other platforms - Amp, Apps, etc?

No

## Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

No

## Screenshots

N/A

## Tested in CODE?

Yes

### CODE REVIEW

**Comment by GHaberis** [comment]
There are a few things I need to clarify around the service worker lifecycle and best practise around clearing the cache. Currently I'm clearing the cache every time the service worker activates.

**Comment by sndrs** [comment]
i would imagine the cache can be filled as much as you like? my guess is it will chuck out old stuff as necessary?

**Comment by GHaberis** [comment]
> if the amount of cached data exceeds the browser's storage limit, the browser will begin evicting all data associated with an origin, one origin at a time, until the storage amount goes under the limit again.

https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker#removing_outdated_caches

I'm not sure if there's any method to what it chooses to discard of from storage: eg. older caches first. 

The activate event is triggered when a new service worker activates (becoming the active worker). A service worker is considered _new_ by the browser if there is a byte's difference in the service worker file compared to what it currently has. 

So assuming service-worker.js doesn't change between releases it will persist across releases. meaning a new group of hashed assets will be cached, on top of the old cached assets, which are no longer required. 

One solution would be to force the service-worker to be considered new by ensuring the bytes differ per release.

**Comment by SiAdcock** [comment]
> We'd expect to see this happening on 2nd load as this is the first time the service worker has intercepted the fetch requests so no assets will be cached yet. 

Interesting. If we registered the service worker inline, rather than in [enhanced/main.js](https://github.com/guardian/frontend/blob/master/static/src/javascripts/bootstraps/enhanced/main.js#L291-L301), could we get the service work to serve assets from the cache on the 2nd load rather than the 3rd?

> One solution would be to force the service-worker to be considered new by ensuring the bytes differ per release.

Is that what [this](https://github.com/guardian/frontend/blob/master/applications/app/templates/serviceWorker.scala.js#L14) is for?

**Comment by GHaberis** [comment]
> If we registered the service worker inline, rather than in enhanced/main.js, could we get the service work to serve assets from the cache on the 2nd load rather than the 3rd?

This [article](https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/registration) suggests that registering the service worker in the head could lead to performance hit for users, especially those on underpowered devices. 

You could ensure the assets are cached on a user's 2nd visit by cacheing the assets upfront when the service-worker first initialises rather than cacheing them in an ad-hoc manner when intercepting requests on the 2nd visit. You could do this using `[Cache.addAll](https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll)`, we'd need to pass this a list of assets to cache though.

**Comment by GHaberis** [comment]
@SiAdcock hmm yeah I guess [this](https://github.com/guardian/frontend/blob/master/applications/app/templates/serviceWorker.scala.js#L14) was put in to force an update, it doesn't look like it's ever been used though!

**Comment by SiAdcock** [comment]
> You could ensure the assets are cached on a user's 2nd visit by cacheing the assets upfront when the service-worker first initialises rather than cacheing them in an ad-hoc manner when intercepting requests on the 2nd visit. You could do this using [Cache.addAll](https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll), we'd need to pass this a list of assets to cache though.

But I guess this would lead to a performance hit?

**Comment by sndrs** [comment]
yeah `// version 1` was added incase you need to force it.

**Comment by sndrs** [comment]
> You could do this using Cache.addAll, we'd need to pass this a list of assets to cache though.

maybe we could pick some we know we'd want, esp fonts? at the point the SW registers they'd be in the HTTP cache anyway?

**Comment by sndrs** [comment]
is this mergeable? be really good to have in

**Comment by sndrs** [comment]
gah

**Comment by mchv** [comment]
@GHaberis you mentioned that you turned off the browser cache for these tests. With the browser cache turned on, on the second load assets requests should be returned `304` (if they have not changes, thanks to `ETag` I believe). Therefore how much do you think response time will improve in practice for assets served from `assets.guim.co.uk`?

**Comment by GHaberis** [comment]
@mchv interesting point. Assets served from `assets.guim.co.uk` have a long max-age (1 year) `cache-control:public, max-age=315360000` so the browser won't consult the server to see if the asset has changed on second request. When assets change we cache bust the URL. 

I do wonder how the service worker affects cacheing with the browser cache enabled. I've just run some initial tests on PROD and enabling browser cache as you suggested and disabling the service worker lead to very fast response times when the assets were served from the disk cache, however enabling the service worker alongside the browser cache (as most users would) lead to slower response times due to the latency of making the request to the service worker, so maybe having the service worker slows things down? I'll look into this further today.

**Pull request closed without merging**
