### PR TITLE
Remove javascript-legacy

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

removes refs to the now empty `javascript-legacy` files.

## What is the value of this and can you measure success?

less legacy

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
⬇️  with legacy

**Comment by gustavpursche** [comment]
@sndrs I think we can also remove a couple of dependencies, needed for the conversion (e.g. `lebab`) ...

**Comment by sndrs** [comment]
@gustavpursche excellent point

**Comment by SiAdcock** [comment]
Separately we can kill the "So you want to ES6?" wiki entry

**Pull request merged**
