### PR TITLE
Crosswords: normalize separators for grouped entries 

### PR DESCRIPTION
**Pull request by OliverJAsh**
Take all of these entries in the same group (taken from http://www.theguardian.com/crosswords/cryptic/26666):

``` json
[
  {
    "id": "10-across",
    "separatorLocations": {},
    "length": 9,
    "group": ["2-down", "10-across", "23-down", "21-across"]
  },
  {
    "id": "21-across",
    "separatorLocations": {},
    "length": 9,
    "group": ["2-down", "10-across", "23-down", "21-across"]
  },
  {
    "id": "2-down",
    "separatorLocations": {
      ",": [
        4, 8,
        11, 17,
        21, 25, 28
      ]
    },
    "length": 8,
    "group": ["2-down", "10-across", "23-down", "21-across"]
  },
  {
    "id": "23-down",
    "separatorLocations": {},
    "length": 4,
    "group": ["2-down", "10-across", "23-down", "21-across"]
  }
]
```

All of the separator locations are stored on the first entry in the group, `2-down`. This meant that other entries in the group did not have their separators rendered correctly:

image

This change normalizes the data to store the separators on the corresponding entries.

After:

image

And for comparison with R2 which does render the separators correctly:

image

For context, here is how we render separators on the client-side: https://github.com/guardian/frontend/pull/10126

/cc @janua

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Thanks @janua for your help with the transformation bits. :smile:

**Comment by janua** [comment]
Looks good. It's quite clever and a bit complicated, but I think the fact that it's split into `val`s all over the place makes it much easier to follow what's going on rather than nested madness.
Maybe someone else should look at it aswell? I'm :+1: if you're happy it covers all the cases correctly.

**Comment by OliverJAsh** [comment]
Ping @rich-nguyen, you might also like to check this.

**Comment by rich-nguyen** [comment]
Test needed, cool :+1:

**Comment by OliverJAsh** [comment]
FYI I have informed CAPI.

**Comment by jennysivapalan** [comment]
I agree I think a test is needed, @OliverJAsh I'm happy to help write one with you.

**Comment by OliverJAsh** [comment]
Ping @jennysivapalan and @rich-nguyen, here's my test: 656da0ef1fc507a9e6d993ab1ecca4e57da92778

**Comment by jennysivapalan** [comment]
:+1: 
:black_medium_square: :white_medium_small_square: :black_medium_square:
:black_medium_square: :white_medium_small_square: :black_medium_square:
:black_medium_square: :white_medium_small_square: :black_medium_square:

**Pull request merged**
