### PR TITLE
Fix Paid Content MPU size

### PR DESCRIPTION
**Pull request by janua**
This surrounds the anchors of a `paidContent` `card` with a `div` to give it a minimum height of `140px`.

The paid for explainer has a current height of `140px`, which in some cases can expand beyond the bottom of the MPU.

I have not made the height of the MPU depend on the height of the explainer as it is currently out of the document flow using `absolute`.

This changes the height of the adverts, changing the design by creating extra whitespace.
The alternative to this is to decrease the font or the size of the explainer text somehow, keeping the original designed height.

@ScottPainterGNM @regiskuckaertz 
## Broken

brokenhidden
brokenshown
## Fixed

fixedhidden
fixedshown

### CODE REVIEW

**Comment by janua** [comment]
[GLabs - Explainer Component Cut Off](https://trello.com/c/NBXh2nOe/67-glabs-explainer-component-cut-off)

**Comment by regiskuckaertz** [comment]
Q: do we want the logo to stick to the bottom of the creative?

**Comment by janua** [comment]
@regiskuckaertz Yes, that's what I was wondering aswell. If we stick with this sizing we probably want to do that.

**Comment by regiskuckaertz** [comment]
(we do it for the cards in containers, that's why I asked)

**Comment by regiskuckaertz** [comment]
otherwise, LGTM 👍

**Comment by janua** [comment]
fixedlogo

@regiskuckaertz

**Comment by regiskuckaertz** [comment]
tchooo tchooo 🚂

**Pull request merged**
