### PR TITLE
Replace link to Apps with tracking link

### LINKED ISSUE #26683: Replace the link for 'The Guardian app' in the main nav bar
From [email](https://groups.google.com/a/guardian.co.uk/g/dotcom.platform/c/T8ue0dIL21g): Replace the link for 'The Guardian app' in the main nav bar with this tracked link: https://app.adjust.com/16xt6hai

<br>

### PR DESCRIPTION
**Pull request by sunnyclimber456**
As requested by CP. Closes #26683

## Screenshot
image

### CODE REVIEW

**Review by mxdvl — APPROVED** [review]
Note: to reduce the reference diff I used the `cp` command without opening the file in an IDE to prevent formatting differences.

**Review by abeddow91 — APPROVED** [review]

**Comment by abeddow91** [comment]
Looks good!
@mxdvl you can also use the settings to hide whitespace 
Screenshot 2023-11-15 at 08 21 29

**Comment by mxdvl** [comment]
> @mxdvl you can also use the settings to hide whitespace 

True, but I was hinting that in this case we are creating useless diffs. Formatting should be deterministic. I'm not sure why this file is not consistently formatted, but I've found different IDEs trying to format it differently each time. Maybe we want to automatically apply Prettier to the file? There seems to be a basic formatting applied in the generated file, which is why I went with a straight copy initially.

**Comment by georgeblahblah** [comment]
@mxdvl as far as I remember (1 hour ago 🙈...) I did just `cp` the `json` file over. I don't think I opened / formatted it!

**Pull request merged**
