### PR TITLE
add lodash-node for Jest

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

adds `lodash-node` to use in jest, instead of `lodash-amd` which jest does not understand

## What is the value of this and can you measure success?

karma tests that use lodash can be more easily ported to jest

### CODE REVIEW

**Comment by philwills** [comment]
Along with the changes to the `package.json` that @desbo makes in the AB test PR, this does allow my tests to run properly. Does seem to blow up the eslint plugin tests though.

**Comment by sndrs** [comment]
>  Does seem to blow up the eslint plugin tests though.

yeah does! hopefully just pushed a fix for that

**Review by philwills — APPROVED** [review]
Great. That does the job for me.

**Comment by desbo** [comment]
After this change I also had to add this mapping (earlier in the list than the one you added)

```"^lodash\/functions/(.*)$": "lodash-node/compat/function/$1"```

This is apparntly because `lodash-amd` calls it `functions` but `lodash-node` calls it `function.

**Pull request merged**
