### PR TITLE
Fix amp inline caption margins

### PR DESCRIPTION
**Pull request by Pearson82**
Getting rid of additional margins on inline images and videos...

Before
screen shot 2015-09-28 at 16 54 24

After
screen shot 2015-09-28 at 16 53 48

### CODE REVIEW

**Comment by paperboyo** [comment]
Oops that may have been me suggesting to @NataliaLKB that some margins look better than none, based on the screenshot she provided in above PR:

0f61f88a-5df4-11e5-8cfc-5abf5b6c7d99

Yours look like there are margins there already, @Pearson82...

**Comment by NataliaLKB** [comment]
@Pearson82 I think we want images in the body not to have any margins. What do you think @stephanfowler ?


I realise that your PR is directly to this, but if possible can we fix this in this PR and that way you don't need to remove the margin in the `figcaption`

**Comment by stephanfowler** [comment]
:+1:  I think basic rule is: whatever we do for mobile breakpoints on the main site, let's so that on AMP. We need to minimise layout shifts as the user navigates from an AMP to our site. 

So here, the caption text should get the same margin as the body text. And images shouldn't bleed to the edge. (Unless we make it do that on the main site too - because it looks great ;-)

**Comment by Pearson82** [comment]
From a design / consistency point of view we should just match styles as
much as possible to the article layout of .com. ie. main media at the top
bleeds to 100% of the browser width, an all inline embeds align to the
column width, (including captions).



On 29 September 2015 at 10:06, Stephan Fowler <notifications@github.com>
wrote:

> [image: :+1:] I think basic rule is: whatever we do for mobile
> breakpoints on the main site, let's so that on AMP. We need to minimise
> layout shifts as the user navigates from an AMP to our site.
>
> So here, the caption text should get the same margin as the body text. And
> images shouldn't bleed to the edge. (Unless we make it do that on the main
> site too - because it looks great ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/10681#issuecomment-143998092>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by Pearson82** [comment]
The reason being there is some hierarchy of main image over inline embeds
@stephanfowler <https://github.com/stephanfowler>.



On 29 September 2015 at 10:12, Chris Pearson <chris.pearson@theguardian.com>
wrote:

> From a design / consistency point of view we should just match styles as
> much as possible to the article layout of .com. ie. main media at the top
> bleeds to 100% of the browser width, an all inline embeds align to the
> column width, (including captions).
>
>
>
> On 29 September 2015 at 10:06, Stephan Fowler <notifications@github.com>
> wrote:
>
>> [image: :+1:] I think basic rule is: whatever we do for mobile
>> breakpoints on the main site, let's so that on AMP. We need to minimise
>> layout shifts as the user navigates from an AMP to our site.
>>
>> So here, the caption text should get the same margin as the body text.
>> And images shouldn't bleed to the edge. (Unless we make it do that on the
>> main site too - because it looks great ;-)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/guardian/frontend/pull/10681#issuecomment-143998092>.
>>
>
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by stephanfowler** [comment]
@Pearson82  - OK yes - see your point

**Comment by NataliaLKB** [comment]
Makes sense! :+1: 

Please merge with master :smile:

**Comment by Pearson82** [comment]
Should I be worried about the 'Checks failing'? @NataliaLKB @stephanfowler

**Comment by NataliaLKB** [comment]
@Pearson82 yes, you needed to merge with master first before merging your pull request. Just remember for next time!

**Comment by Pearson82** [comment]
OK thanks! @NataliaLKB

**Pull request merged**
