### PR TITLE
Refactor inline components to use the new styles

### PR DESCRIPTION
**Pull request by JonNorman**
## What does this change?

Reworking the last two inline components - books and live events - to use the new styles.
## What is the value of this and can you measure success?

We can get rid of a load of the old templates and styles.
## Does this affect other platforms - Amp, Apps, etc?

No
## Screenshots

No point - looks the same.

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
Let's not deploy this until #13286 is fixed.

**Comment by rich-nguyen** [comment]
hopefully fixed now

**Comment by JonNorman** [comment]
Yep, just checked:

image
image

**Comment by regiskuckaertz** [comment]
Yep, I just added some emphasis in live events when there's not much space left. I would give you a +1 but as we worked on this together, let's have someone else review it.

**Comment by kelvin-chappell** [comment]
👍

**Pull request merged**
