### PR TITLE
Authenticate users by calling back to identity

### PR DESCRIPTION
**Pull request by Mullefa**
## What does this change?

Authenticates users by calling back to identity API.

This is currently a draft PR which I'm raising since I will be off for the next 4 weeks. Things to do/consider when working on this PR to get it to a state where it can be merged:

- [x] import a new version of `identity-cookie` to get an implementation of the `IdentityCookieService` stubbed in this PR
- [x] import release and import the [new version](https://github.com/guardian/identity/pull/1627) of `identity-auth-play`
- [x] decide whether we want to keep the return type of `fullyAuthenticateUser` as an `Option[User]` or whether we can make this method asynchronous (since it involves an HTTP request); if we do keep it as is, then use a dedicated thread pool for blocking IO
- [x] wire up compile time dependencies
- [x] get the tests to pass 
- [ ] (optional) assess whether the SC_GU_RP cookie is still required (I know it was used for GDPR related re-permissioning)

I will try and address as many of these as I can before I take leave.

### CODE REVIEW

**Comment by coldlink** [comment]
Switching to async/futures seems to involve quite a few changes, so sticking to thread-pooling.

Think I've implemented ThreadPooling correctly, let me know if it looks off, whats the best way to measure the number of threads that we'll need?

**Comment by coldlink** [comment]
Once https://github.com/guardian/identity/pull/1638 is approved and merged, we have to bump identity lib version to 3.189  (currently 3.189-M1 for testing).

**Comment by coldlink** [comment]
Noticed some issues when navigating to certain pages e.g.  https://profile.thegulocal.com/account/edit where we get stuck in a redirect login loop. Will investigate further.

**Review by dominickendrick — APPROVED** [review]

**Comment by philmcmahon** [comment]
Hey, I've had a look through this and am happy with these changes (they're all isolated to just the identity app which is encouraging!). 

I remember talking to Guy about the potential increased traffic this could cause. There's a cloudwatch dashboard [here](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#dashboards:name=xIdentity) for the identity service which could be useful for monitoring post deploy.

**Pull request merged**
