### PR TITLE
remove deep linking for apps

### PR DESCRIPTION
**Pull request by johnduffell**
Depp linking is causing a lot of problems with hitting the app for things that aren't supported and not giving the user a choice between the web and the app.
So we should remove it for the time being until we have a better user experience.
@crifmulholland @ScottPainterGNM @PetrK-GNM @michaelwmcnamara

### CODE REVIEW

**Comment by PetrK-GNM** [comment]
Does this completely disable deep linking?

**Comment by johnduffell** [comment]
@PetrK-GNM yes, seems like there are a few issues, I don't have time to implement it again at the moment but someone probably needs to go through and do it properly.  if it's not a big problem in the end, we don't need to merge this one, but it's there if we need to.

**Comment by crifmulholland** [comment]
There's definitely an issue with Crosswords. The other problem is chrome
browser on iOS - this mechanism is designed to be an app-to-app user
journey. But chrome don't really give you a choice so visitors are going
from browser-app without being told. Definitely needs some more testing and
logic around it.


On 5 October 2015 at 16:37, John Duffell <notifications@github.com> wrote:

> @PetrK-GNM <https://github.com/PetrK-GNM> yes, seems like there are a few
> issues, I don't have time to implement it again at the moment but someone
> probably needs to go through and do it properly. if it's not a big problem
> in the end, we don't need to merge this one, but it's there if we need to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/10772#issuecomment-145573392>.
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by JustinPinner** [comment]
Presumably iosId is the mechanism that triggers deep linking, and the removal of any iosType values prevent that from ever getting set? (Just checking my understanding here). If so: :+1:

**Comment by PetrK-GNM** [comment]
Can you guys just make sure you don't merge/release this before consulting with us to make a decision?

**Comment by johnduffell** [comment]
sure, no problem Petr, I just wanted to get the code out there in case it needs shipping

**Comment by johnduffell** [comment]
@NathanielBennett is looking at this properly

**Pull request closed without merging**
