### PR TITLE
Fix missing subnav cartoons

### PR DESCRIPTION
**Pull request by alinaboghiu**
## What does this change?

This ensures the subnav appears on the Cartoons tag page

## Checklist

- [ ] Tested locally, and on CODE if necessary
- [ ] Will not break dotcom-rendering
- [ ] Will not break our database – if updating CAPI, [updated and committed the database files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)
- [ ] Meets our accessibility [standards](https://github.com/guardian/recommendations/blob/e647ef695199ea3116ea20d827ef0f1364270a39/accessibility.md)
  - [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
  - [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#Keyboard)
  - [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#colour)

### CODE REVIEW

**Review by mxdvl — APPROVED** [review]
Looks good! Just missing a PR description.

PS. These massive json diffs really annoy me…

**Review by DanielCliftonGuardian — APPROVED** [review]
✅

**Comment by alinaboghiu** [comment]
Thanks both. And I agree Max, hiding whitespace in the GH diff helps a bit.

**Comment by alinaboghiu** [comment]
@mxdvl sorry I completely forgot about description, have added some now

**Pull request merged**
