### PR TITLE
Deps: Upgrade fastdom to 1.0.6

### PR DESCRIPTION
**Pull request by gu-stav**
## What does this change?

Upgrades `fastdom` to 1.0.6. Tests are all passing - I want to do some more click around testing to see if anything else goes wrong.

Breaking changes:

- `.read()` is now `.measure()`
- `.write()` is now `.mutate()`
- `.defer()` does not exist anymore

In theory we could now make use out of the included [`fastdom-promised`](https://github.com/wilsonpage/fastdom/compare/v0.8.5...master#diff-647abe7331d0b11a05b598484f061ac7) instead of having our own. ✨ 

It also cleans up some tests, where `fastdom` was used for code flow control. Buuuh!

## What is the value of this and can you measure success?

Up to date dependencies.

## Does this affect other platforms - Amp, Apps, etc?

No.

## Screenshots

No.

## Tested in CODE?

No.

### CODE REVIEW

**Comment by SiAdcock** [comment]
First of all: **awesome work, @gustavpursche!** 🎉 🔥 🎉  This upgrade is long overdue!

We can probably deprecate `lib/fastdom-promise` if it provides the same functionality as the built-in API `fastdom-promised`. Maybe add a deprecation warning to `lib/fastdom-promise`?

I am very sad, by not that surprised, by the revelation that `fastdom.defer` is occasionally being used as an async delay for tests. Replacing it with `setTimeout` may mask the problem in the short term, but it could introduce some of the mysterious intermittent failures that the codebase has been plagued with over the last couple of years.

A better approach would be to use `fastdom-promised` to provide a more deterministic way of waiting for DOM mutation to finish. There are not too many places where refactoring would be required. The question is whether to do that as part of this PR or a separate PR. If we do it separately, we should do it sooner rather than later, to minimise the risk of intermittent failures breaking the build. We should also add magic comments to the tests that need refactoring so we can easily find them again.

Again, great job, dude!

**Comment by sndrs** [comment]
yes!!! 💫

nice one @gustavpursche. I agree with simon – i think i'd remove our promised version at the same time, or maybe prep the PR branched from this ready to open immediately this merges. the changes here are many but simple, i think we could handle the promise in there too? your call, but i reckon very deliberately batching up the changes (fastdom-style) for the upgrade would be a great idea...

**Comment by gustavpursche** [comment]
@SiAdcock @sndrs Thanks for all the 🎉! I discussed the PR with Simon and we agreed on:
- right after this is merged, I'll open up another PR, where we deprecate our `fastdom-promise` and prove a nice way to use the internal `fastdom-promised`
- I'll keep an eye on the introduced `setTimeout`s to see if they cause any test failures. In the very soon future, maybe as part of the ES6 conversion, we'll refactor this code so that methods are returning `Promises`

Yeah, some more click testing and then LGTM (lets get this merged) 🚢 .

**Comment by gustavpursche** [comment]
@SiAdcock @sndrs Could one of you give me your approval so I can merge this tomorrow morning?

**Comment by SiAdcock** [comment]
@gustavpursche do you agree with @sndrs's suggestion to batch up all the PRs, so they are all ready to merge, and then merge them one at a time?

**Comment by gustavpursche** [comment]
After a quick chat:

> 1

👍 

> 2. PR to replace lib/fastdom-promise with fastdom-promised
> PR to refactor code to use fastdom-promised, reducing our reliance on arbitrary async delays in our tests?

I'd prefer to keep this separate and have some time in between, so in case there are problems we can isolate them a bit more.

Also I have to think and play around a bit with their idea of having [it as an extension](https://github.com/wilsonpage/fastdom#using-an-extension). Not sure about this. Maybe it makes sense to talk about it and see if we should raise a PR to make it more compatible with our codebase.

4. Enhance tests and interfaces or methods, which are now dependent on `setTimeout`, so they return promises.

**Comment by sndrs** [comment]
is there a reason we wouldn't want to only provide `fastdom-promised` as our `fastdom` import? so any call to its methods are thenable if you want it?

**Comment by gustavpursche** [comment]
@sndrs Good question: So you mean making `fastom` an alias for `fastdom-promised`?

**Comment by sndrs** [comment]
@gustavpursche yeah – if you don't use the `then` that's ok? it's just there if you want it?

**Comment by sndrs** [comment]
pretty sure the only reason we have promise and non-promise versions available currently is evolution, not intelligent design

**Comment by gustavpursche** [comment]
Closing this because of the growing number of conflicts. Don't have the time currently to update the tests.

**Pull request closed without merging**
