### PR TITLE
Temporarily disable sticky nav on mobile

### PR DESCRIPTION
**Pull request by sndrs**
temporarily mitigates #10220.

that this doesn't improve the mega nav bugs on breakpoints _above_ mobile :(
### Before

screen recording 2015-08-25 at 11 01 am
### After

screen recording 2015-08-25 at 10 59 am

### CODE REVIEW

**Comment by davidrapson** [comment]
:+1:

**Comment by rich-nguyen** [comment]
:+1:

**Comment by OliverJAsh** [comment]
Viewability doesn't need to be tied to the sticky nav. Can we correct the
switch to wrap just the sticky nav and then disable it, until all these
issues are fixed?

On Tue, 25 Aug 2015 11:47 Richard Nguyen <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/10259#issuecomment-134548742>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by paperboyo** [comment]
:gem:

**Pull request merged**
