### PR TITLE
onward most-read api update for DCR

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

This PR updates the answer of `onward`'s `/most-read/*path.json` in the case of DCR. This is an answer to https://trello.com/c/NnisWuAi/1014-enhance-most-popular-api-response

We move away from `OnwardCollectionResponse` to `OnwardCollectionForDCRv2`

```
case class OnwardCollectionForDCRv2(
  tabs: Seq[OnwardCollectionResponse],
  mostCommented: Option[OnwardItemMost],
  mostShared: Option[OnwardItemMost]
)
``` 

Note the introduction of `OnwardItemMost` which is designed to be compatible with DCR's `TrailType`.

Note that we do not need to update DCR because the new return type has already been implemented. 

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No

### CODE REVIEW

**Comment by shtukas** [comment]
API answer

Screenshot 2020-01-22 at 14 12 24

**Comment by shtukas** [comment]
The choice of the image might be to be improved in a further PR

**Review by oliverlloyd — APPROVED** [review]
We worked on this together and my Scala is... yeah, so someone else might want to check that side of things but these changes look to solve the missing data problem I have in DCR

👍 👍

**Comment by shtukas** [comment]
@oliverlloyd Tested on CODE. Merging

Screenshot 2020-01-23 at 16 17 36

**Pull request merged**
