### PR TITLE
Nice underlines everywhere

### PR DESCRIPTION
**Pull request by zeftilldeath**
## What does this change?
Underlines across the website will no longer overlap descenders. Using a nifty new(ish) css rule. If it's not supported we get the same underline we had before, so nothing is lost. 

Changes:
- On supported browsers underlines will skip descenders
- Body underlines will no longer have a transition animation on hover
- On IE and unsupported browsers, body articles will have standard underlines for links

The result is easier on the eye and much more accessible to those with cognitive disablities. ([Here's why.](https://medium.com/@iamhiwelo/improving-text-readability-for-dyslexic-users-with-skip-ink-underlines-bf52a2f3426b))

[Browser compatibility](https://caniuse.com/#search=text-decoration-skip)

# Before
screen shot 2018-01-03 at 14 49 22

# After
screen shot 2018-01-03 at 14 50 32

# Before
screen shot 2018-01-04 at 10 42 49

# After
screen shot 2018-01-04 at 10 42 32

NB: Garnett crew - there will be some hover rules you need to change to match this, but I don't think they should be in this PR. CC @Joshua-David @superfrank

### CODE REVIEW

**Review by NataliaLKB — APPROVED** [review]
😻

**Comment by ScottPainterGNM** [comment]
Lovely stuff! Thanks Zef ❤️

**Comment by paperboyo** [comment]
@zeftilldeath 

Seeing double underline in Firefox:
double underline

> Body underlines will no longer have a transition animation on hover

Hmm, so they will look worse on unsupported browsers, as the border trick was also nicely lighter :-(

Also, this is not needed on latest Chrome as `ink` is on by default, so...

**Comment by paperboyo** [comment]
Also, it looks like the property introduced here is getting deprecated: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/47BHtmz0jVY

**Comment by zeftilldeath** [comment]
Thanks so much @paperboyo PR following up our conversation.

**Comment by hiwelo** [comment]
Just spotted you tried to implement skip-ink underlines. Yay! 🎉 Thanks for this try 👍 

And thank you @paperboyo for this resource. I'll update my article with this information.
I'm looking forward to seeing this as a default behaviour in Chrome!

**Pull request merged**
