### PR TITLE
Limit number of video players on tag pages

### PR DESCRIPTION
**Pull request by robertberry-zz**
CC @gklopper 

To stop terrible performance on pages like Telly Addict:

screen shot 2015-01-07 at 17 40 42

### CODE REVIEW

**Comment by sammorrisdesign** [comment]
I know this is just for tag pages, but aren't we allowing for playables on smaller items all on fronts soon? Which will leave us with even more embedded videos on our pages.

Is there any reason that we include the video object in the page from load? Couldn't we inject once a user has decided to play the video? (I'm sure there's a reason for this, but just curious)

**Comment by crifmulholland** [comment]
I agree with @sammorrisdesign - the issue is we're using exactly the same player setup as the article / video pages. These should load the video asset immediately, whereas on fronts we shouldn't. The fallback on fronts should be to link to the video page, rather than having the default html5 video fallback. 

We'll look into this as part of the upcoming playables piece of work.

**Comment by robertberry** [comment]
In the meantime, should I ship this as an intermediate fix? The performance issues are pretty bad.

**Comment by crifmulholland** [comment]
Yes please!!

**Pull request merged**
