### PR TITLE
Imgix images now respect "height" parameter.

### PR DESCRIPTION
**Pull request by gklopper**
We managed to "lose" this along the way...

Also fixed up some instances where we were doing escaping incorrectly (i.e. `&` and `&amp;`)

### CODE REVIEW

**Comment by rich-nguyen** [comment]
why is the `Html` needed? Is it because of the & characters?

**Comment by gklopper** [comment]
Yes, I had a chat with @sndrs about it. I should probably measure how much smaller the page size is, there was a lot of these on fronts :smile:

**Comment by johnduffell** [comment]
is this a cheat to save bytes or were we ending up with &amp;amp; in the html source?

**Comment by gklopper** [comment]
Hmmm, it seems I have been lied to :scream: - someone will make a good manager, they are supposed to be `&amp;`

**Comment by gklopper** [comment]
There we go, gimme a :+1:

**Comment by johnduffell** [comment]
:+1: ship it!

**Pull request merged**
