### PR TITLE
Remove FastClick

### LINKED ISSUE #9947: Frustrating scrolling behaviour with fast click on fronts
When strolling a front on an iPad, it's really easy to accidentally click to go into an article. The problem is particularly annoying if a *flick*–*scroll*–*tap-to-stop* action is performed, as Fast Click (http://labs.ft.com/2011/08/fastclick-native-like-tapping-for-touch-apps/) interprets the *tap-to-stop* as a click on an article, which it isn't.

Please consider switching off Fast Click on fronts (https://github.com/guardian/frontend/blob/8053d50a1bb4287625d5d139139ad1452c445677/static/src/javascripts/bootstraps/common.js#L106)

Very happy to demo. I could even video the frustration when I enter an unexpected article for the 4th time over my morning granola.

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes #9947

### CODE REVIEW

**Comment by uplne** [comment]
:+1: I was looking forward to this day

**Comment by piuccio** [comment]
:heart_eyes: :+1:

**Comment by piuccio** [comment]
@robertberry would be proud of your delete ratio!

**Comment by sndrs** [comment]
yeah why not, let's see what it's like :+1:

**Pull request merged**
