### PR TITLE
User history - count fronts & articles seperately

### PR DESCRIPTION
**Pull request by stephanfowler**
For each tag, count front hits and article hits separately. Allows different rankings to be tried out later. Uses a more compact format:

```
   "artanddesign": [
        "Art and design",
        "1...5...1...3.2....2",                  // fronts hits
        "..1..1.1.........2.....6..........1"    // article hits
    ]
```

Where `1...5...` means one hit today, five hits three days ago, etc.

// @crifmulholland

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
hard to validate the js. tests?

**Comment by robertberry** [comment]
What's with the compact format? Are we running out of space?

**Comment by stephanfowler** [comment]
@ironsidevsquincy  Ah, yes, will fix tests.

@robertberry no, it's just easier to read.

**Comment by robertberry** [comment]
Say whaaaaat

**Comment by stephanfowler** [comment]
I'm rethinking this.

**Pull request closed without merging**
