### PR TITLE
Discussion: make relative dates optional

### LINKED ISSUE #10139: Add timestamp to comments
This was an R2 feature missing in NGW, the crosswords community have probably complained about this being missing in the beta version more then any part of the actual crosswords functionality.

Can this be added, are there any blockers to this change? Seems a shame to cause issues to a very loyal and engaged comments community on our page by losing this.

### PR DESCRIPTION
**Pull request by OliverJAsh**
Lots of users were asking for absolute dates, especially those in our crossword community, who race to completion when a crossword is released at midnight.

Fixes #10139

Relative (default):
image

Absolute:
foo

/cc @crifmulholland

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Updated UI:

image

Also only going to run this in crosswords sections.

**Comment by crifmulholland** [comment]
The Crosswords community will go crazy for this!

**Comment by gtrufitt** [comment]
:+1: Nice!

**Comment by rich-nguyen** [comment]
:+1:

**Comment by paperboyo** [comment]
Just my, completely personal, opinion. This is much too niche a preference to surface it like that. I would make it a part of (bury it in) user preferences (maybe, later?).

**Comment by crifmulholland** [comment]
@paperboyo - we're specifically scoping this to crosswords users. The reason being, it's by far the biggest issue the community is asking for. 

We'll see if the other commenters decide to go into crosswords to change it, but for the time being, it will just sit there. 

I do agree, we should have a better prefs page to hold these!

**Comment by paperboyo** [comment]
@crifmulholland Oh, cool, I didn't know it's only visible there. All happy!

More central, clear, Gu-wide user/site preferences, that readers are used to look into when checking if something is possible: +1.

**Pull request merged**
