### PR TITLE
Refactor engagement banner and tests

### PR DESCRIPTION
**Pull request by rtyley**
## What does this change?

Refactors the Membership/Contributions engagement banner code to make to make the expression of the A/B tests more concise and clear.

## What is the value of this and can you measure success?

Hopefully this should lead to smaller diffs as we add and remove engagement banner tests, allowing us to iterate our tests more rapidly.

## Does this affect other platforms - Amp, Apps, etc?

No only web.

## Screenshots

image

This is kind of a rehash of PR #14244, which had a similar refactoring.

cc @JustinPinner

### CODE REVIEW

**Comment by JustinPinner** [comment]
Have we lost the test control variants? Also, the currently active AU test ID can't change or we'll be restarting the test (I think the switch is left intact but the test has been refactored).

**Comment by JustinPinner** [comment]
LGTM 👍

**Comment by rtyley** [comment]
Looks to be working in PROD in all editions.

Australia
----
I'm able to successfully switch test variants:

image
image

UK
---
image

US
---
image

International
---
image

**Comment by rtyley** [comment]
The first time this newly refactored code base has been used is with PR #15429 - I'm calling this a win:

image

The size for a similar PR in the past, eg #14976 - 7x bigger :

image

**Pull request merged**
