### PR TITLE
Add new size for outstream ads in inline slots

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Currently, outstream video ads like Teads Inreads break out of the ad slot. This is not desirable at all, for obvious reasons, but most importantly because we can't measure viewability. In this chance, we introduce a new ad size Teads said could allow them to run _in situ_. As a bonus, they will also be pushing towards delivering SafeFrame enabled creatives.

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
[Create a new size for Teads](https://trello.com/c/JDjN6pof/142-create-a-new-size-for-teads)

**Comment by ScottPainterGNM** [comment]
Out of curiosity, why are we removing inline2 and 3 in this PR?

**Comment by regiskuckaertz** [comment]
@ScottPainterGNM because they're all similar, I should've gotten rid of them long ago.

**Comment by ScottPainterGNM** [comment]
Cool - can/have you confirmed with adops they aren't doing any specific targeting to this slot?

**Review by scottp719 — APPROVED** [review]
👍 Apart from one query

**Pull request merged**
