### PR TITLE
Rich links (flyers): don't show tag-targeted rich links on "sensitive content"

### PR DESCRIPTION
**Pull request by OliverJAsh**
"sensitive content" = `shouldHideAdverts || !showRelatedContent`

/cc @cantlin

### CODE REVIEW

**Comment by OliverJAsh** [comment]
A quick note on the JSCS config: I think code is more readable with a space after prefix unary operators, e.g. `! true` instead of `!true`. Could we discuss changing our style guide?

**Comment by rich-nguyen** [comment]
:+1:

**Comment by OliverJAsh** [comment]
Sadly it looks like we have no tests for the Flyers module. Worth me adding some, @rich-nguyen?

**Comment by OliverJAsh** [comment]
@rich-nguyen I've added some tests. Would you mind taking a look?

The tests are not linted by JSCS, so please point out if there's any styling errors.

/cc @phamann

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
