### PR TITLE
Toggle playable live blog

### PR DESCRIPTION
**Pull request by piuccio**
Default is off. The toggle is only visible on live blogs

@stephanfowler

### CODE REVIEW

**Comment by stephanfowler** [comment]
:+1: (nice to see my ol' option definition syntax has survived your refactoring!)

**Comment by piuccio** [comment]
I'm never going to refactor that file :tongue:

**Comment by stephanfowler** [comment]
Don't merge until we've done the frontend bit..!

**Comment by gklopper** [comment]
This is getting a bit old...

**Comment by stephanfowler** [comment]
Yes - but should get picked up v soon.

**Comment by jennysivapalan** [comment]
I've updated facia to only display the live updates if `showLivePlayable` is set to true.

I won't look at merging this till Monday as we'll need to let central prod (and other teams?) know as we'll need to let them know to start checking the field in facia-tool.

cc/ @stephanfowler @janua

**Comment by stephanfowler** [comment]
:+1: perfect

**Comment by janua** [comment]
Great! :+1:

**Comment by stephanfowler** [comment]
Hold on, you need to remove all the `LiveblogFrontUpdates*` switches from:
* [common/app/conf/switches.scala](https://github.com/guardian/frontend/blob/facia-tool-playable/common/app/conf/switches.scala) 
* [static/src/javascripts/bootstraps/facia.js](https://github.com/guardian/frontend/blob/facia-tool-playable/static/src/javascripts/bootstraps/facia.js#L95)

**Comment by stephanfowler** [comment]
:+1: and again

**Pull request merged**
