### PR TITLE
Football snaps

### PR DESCRIPTION
**Pull request by phamann**
Fixes the styling of football snaps components. After discussing with @sndrs and @stephanfowler we've also refactored the styles into their own encapsulated css file which then gets inlined into the components payload. I.e. we will only load the styles if the components are actually visible on the page rather than on every facia page regardless like before. Web Components anybody???
### Before

google chrome
### After

google chrome

### CODE REVIEW

**Comment by uplne** [comment]
Nice. Should we remove imports of those files from global.scss?

**Comment by phamann** [comment]
@uplne Good shout, i've now done that, but sadly can only remove the snaps specific file :cry:

**Comment by phamann** [comment]
@sndrs Have now refactored the 'base/table' file to remove all vars and mixins.

**Comment by sndrs** [comment]
yeah nice catch @uplne 

:+1:

**Pull request merged**
