### PR TITLE
Add KnockoutSpider.ordering data for Women World Cup 2019

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

Add the missing `KnockoutSpider.ordering` dates for the coming Women World Cup 2019.

### CODE REVIEW

**Review by vlbee — APPROVED** [review]
Thanks for explaining this to me! 👍

**Comment by shtukas** [comment]
You're welcome @vlbee :)

**Comment by adamnfish** [comment]
Make sure you test it out and ensure that each phase of the knockout feeds into the correct branch of the next phase. It's a bit of a fiddle to get it right because PA don't give us any data to automatically link stages together.

**Comment by shtukas** [comment]
@adamnfish Will do :)

**Comment by nicl** [comment]
@adamnfish @shtukas yeah, for the last world cup, I definitely had to rejig the ordering during the tournament which wasn't great. (Although it wasn't hard to do.)

**Pull request merged**
