### PR TITLE
Remove article inserted email forms

### PR DESCRIPTION
**Pull request by gtrufitt**
## What does this change?

Removes the Article Email Signup code as it is no longer in use.

This wasn't working due to a bug which was then fixed and all the signups appeared. They've been asked to be removed and with the move to dotcom-rendering this is likely to be impelemented another way if we want to bring them back in the future.

So long and thanks for all the (signups).

Tested on CODE. Email signup pages and footer still sign users up.

*Common.js bootstrap* - remove email article boot
*check-mediator-checks* - Removing all email related checks
*check-dispatcher* - sets up the tests for whether emails that are added to articles can be added and run
*Run-checks* - checks a whole load of things for all the in-article email checks
*Email-article.js* - runs all checks and then adds the lists to the page
*iframe.html* - the js template used to add the list
*submission-response.html* - unused

*Routes* - edit out the article email type
*emailSignUp.scala.html* - remove article type related checks

Update docs
Remove feature switches

### CODE REVIEW

**Review by rcrphillips — APPROVED** [review]

**Comment by jfsoul** [comment]
My understanding was that `article` type signups didn't work on apps, so we stopped embedding them in favour of plaintone.  I assume those are still going to work within articles?

**Comment by gtrufitt** [comment]
> My understanding was that article type signups didn't work on apps, so we stopped embedding them in favour of plaintone. I assume those are still going to work within articles?

Yup, this just affects the automated (JS) article insertions - plaintone routes and the iframe and templates that render them still exist :)

**Review by nicl — APPROVED** [review]
Great to remove so much code :) 👍

**Comment by gtrufitt** [comment]
> Great to remove so much code :) 👍

ALL ABOUT THEM RATIOS.

**Pull request merged**
