### PR TITLE
videojs refactor

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

- Removes some of the complexity around supporting VideoJS in an AMD environment and Webpack
- Cleans up some comments
- Removes another alias from Webpack config 

## What is the value of this and can you measure success?

Makes our code more maintainable

## Does this affect other platforms - Amp, Apps, etc?

No

## Tested in CODE?

No

### CODE REVIEW

**Comment by sndrs** [comment]
love it

**Review by sndrs — APPROVED** [review]
if @akash1810 is happy i def am, nice one

**Comment by SiAdcock** [comment]
w00t! I'll fix that switch-related fail then merge

**Review by akash1810 — COMMENTED** [review]
I'm late to the party, but 👍

**Pull request merged**
