### PR TITLE
Remove RSS server switch

### PR DESCRIPTION
**Pull request by robertberry-zz**
CC @gklopper

### CODE REVIEW

**Comment by phamann** [comment]
:+1:

**Comment by janua** [comment]
Is `RSS` gone from `applications`?

**Comment by robertberry** [comment]
@janua I've removed the routes, but a lot of the code is still common. In a refactor I can sort some of it out.

**Comment by janua** [comment]
Ah I see :+1:

**Comment by phamann** [comment]
Ship me.

**Comment by gklopper** [comment]
SHIPPPPPPIT - expiring tomorrow

**Pull request merged**
