### PR TITLE
Polyfill `Promise.AllSettled`

### PR DESCRIPTION
**Pull request by chrislomaxjones**
## What does this change?

Add `Promise.allSettled` to the frontend polyfill.io bundle.

## Does this change need to be reproduced in dotcom-rendering ?

- [X] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## What is the value of this and can you measure success?

We have a number of errors being [logged by Sentry](https://sentry.io/organizations/the-guardian/issues/?project=35463&query=is%3Aunresolved+feature%3Acommercial+promise.allSettled&statsPeriod=14d) (non-public URL) that arise from `promise.AllSettled` not being a function. These all seem related to older browsers that [do not support](https://caniuse.com/mdn-javascript_builtins_promise_allsettled) this function.

To resolve these errors, we can polyfill the function.

### Tested

- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by simonbyford — APPROVED** [review]
Makes sense!

Do we need to make the change in DCR also?

https://github.com/guardian/dotcom-rendering/blob/main/dotcom-rendering/src/web/server/document.tsx#L185

**Review by mxdvl — COMMENTED** [review]
What’s the size of that polyfill for older browsers?

**Comment by chrislomaxjones** [comment]
> What’s the size of that polyfill for older browsers?

Good question that I should've checked and included in the original description.

There may be a better method to do this, but setting `ua=ie10` to see what an older browser receives, I'm comparing:


With `Promise.AllSettled`: 168.2KB / gzipped 46.5KB

```
https://assets.guim.co.uk/polyfill.io/v3/polyfill.min.js?rum=0&features=es6,es7,es2017,default-3.6,HTMLPictureElement,IntersectionObserver,IntersectionObserverEntry,fetch,navigator.sendBeacon,performance.now,Object.fromEntries,Promise.allSettled&flags=gated&callback=guardianPolyfilled&unknown=polyfill&clearCache=5&ua=ie10
```


and without: 167.4KB / gizipped 46.28KB



```
https://assets.guim.co.uk/polyfill.io/v3/polyfill.min.js?rum=0&features=es6,es7,es2017,default-3.6,HTMLPictureElement,IntersectionObserver,IntersectionObserverEntry,fetch,navigator.sendBeacon,performance.now,Object.fromEntries,Promise.allSettled&flags=gated&callback=guardianPolyfilled&unknown=polyfill&clearCache=5&ua=ie10
```

Does that seem like a reasonable calculation? On its own the polyfill weighs about 16KB unzipped, but I suppose some of that gets factored out when you're pollyfilling more than one function?

**Review by mxdvl — APPROVED** [review]

**Comment by chrislomaxjones** [comment]
> Do we need to make the change in DCR also?

Hadn't realised this was handled separately, I'll raise a PR!

**Comment by oliverlloyd** [comment]
There's an argument to be made against adding more and more polyfills. It's easy to see them as a quick solution but they come with a cost (the output from some polyfills is wild!) and I think we need to have a solid use case and justification for adding more. Ideally, if there is another way to solve your problem (write more basic code?) then that would - I think - be preferable and a better long term solution

Note also, that support for IE11 is in flux so if that is the only motivation we could perhaps revisit this?

**Pull request merged**
