### PR TITLE
Filter browser support errors

### PR DESCRIPTION
**Pull request by OliverJAsh**
I'm trying to bring some sanity to [Sentry](https://app.getsentry.com/the-guardian/client-side-prod/).

When we try to run the video player on an unsupported browser, we throw an error, which in turn displays a user to the message on screen. We don't care about sending these errors to Sentry, however.

The origin of these errors will always be a browser that doesn't support source maps. This leads to having a single Sentry entry for this one error every time we redeploy, because the hashed asset file name will be unique:

image

Hacky, I know.

### CODE REVIEW

**Comment by piuccio** [comment]
Can we use something like [ignore_errors](https://raven-js.readthedocs.org/en/latest/config/index.html#ignoreerrors) or [shouldsendcallback](https://raven-js.readthedocs.org/en/latest/config/index.html#shouldsendcallback)?

**Comment by rich-nguyen** [comment]
I think there is more work to do. You're trying to clean up Sentry, but now we do not know how many clients are playing videos on unsupported browsers. This is useful information that we'd be losing.

**Comment by OliverJAsh** [comment]
@piuccio Good spot.

@rich-nguyen I don't think Sentry is the right way to track that information. Is anyone currently using this information? If it's needed we can add some sort of tracking for it, but it shouldn't pollute our error tracking.

**Comment by OliverJAsh** [comment]
@rich-nguyen I can't remember what your reply to my comment above was?

> I don't think Sentry is the right way to track that information. Is anyone currently using this information? If it's needed we can add some sort of tracking for it, but it shouldn't pollute our error tracking.

I want to re-open this because we are reporting too many errors to Sentry than our plan can cope with, and this error is the biggest offender. (500k reports in the last 24 hours.)

**Comment by piuccio** [comment]
you can always rate limit it until you put in place a better tracking. Send only 10% of the errors

**Comment by OliverJAsh** [comment]
We currently rate limit errors by filtering `Math.random() < 0.2`. We could also filter these errors too.

Would people be happy if I didn't implement replacement tracking, because to my knowledge we haven't ever looked at this data? If someone needs to track it, they can.

**Comment by piuccio** [comment]
I'd be happy

**Comment by rich-nguyen** [comment]
I think we need to know how many people are requesting video content that isn't supported by their browser/ our video player. If that's not available in Sentry, and it's not the right place for that kind of data (it is an exception, after all), then it should be beaconed somewhere else.

**Comment by jbreckmckye** [comment]
Should browser support issues even throw errors? Exceptions are very dramatic things which abort the entire event. They are quite destructive and quite hard to reason about. If we're expecting something to fail in certain clients, I reckon having an if statement around a feature check would more explicit and save us from having to do any filtering in sentry (which always seems very risky - what happens if the exception is raised on a page which doesn't tell the user what's wrong?).

**Comment by OliverJAsh** [comment]
@jbreckmckye I was wondering the same. The video player has an error state that it only displays when you throw an error, so we've little choice there.

@rich-nguyen I'm not sure I would agree that alternative tracking is necessary given no-one I know has needed this data, but maybe I'm just being lazy. I'll figure something out and re-open when that's done. :smile:

**Pull request closed without merging**
