### PR TITLE
Add a custom selection colour

### PR DESCRIPTION
**Pull request by zeftilldeath**
screen shot 2015-11-06 at 13 59 16

### CODE REVIEW

**Comment by rich-nguyen** [comment]
whilst you're in the area, do you think you could fix those share icons? They used to be centered...

**Comment by zeftilldeath** [comment]
@rich-nguyen Was next on my list :dancer: Should I do it on a seperate branch though?

**Comment by rich-nguyen** [comment]
sure

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
