### PR TITLE
Commercial metrics start and end times

### PR DESCRIPTION
**Pull request by janua**
## What does this change?

This changes the `Baseline` type for commercial performance reports to include a `startTime` and an `endTime`. This will measure the start and end times of both baselines; `primary` and `secondary`.
## What is the value of this and can you measure success?

This will allow us to accurately measure the two main parts of the client side commercial application.
## Does this affect other platforms - Amp, Apps, etc?

No.

## Request for comment

@rich-nguyen

### CODE REVIEW

**Review by rich-nguyen — CHANGES_REQUESTED** [review]
Can you update `commercial-browser-performance.js` too?

**Review by rich-nguyen — CHANGES_REQUESTED** [review]
Can you add a label to this pr?

**Review by rich-nguyen — CHANGES_REQUESTED** [review]
Can you make me a cup of tea?

**Comment by janua** [comment]
DONE! :tea:

**Comment by rich-nguyen** [comment]
👍

**Review by rich-nguyen — APPROVED** [review]

**Review by rich-nguyen — APPROVED** [review]

**Review by rich-nguyen — APPROVED** [review]

**Pull request merged**
