### PR TITLE
remove qwery

### PR DESCRIPTION
**Pull request by arelra**
## What does this change?
 
Master PR for removing [qwery](https://github.com/ded/qwery) from commercial code.

This PR is a placeholder for us to manage the removal in smaller more focussed PRs.

References to `qwery`:

- [x] /projects/commercial/modules/article-aside-adverts.spec.js (Mario - [PR merged](https://github.com/guardian/frontend/pull/23813))
- [x] /projects/commercial/modules/hosted/onward-journey-carousel.js (Ravi - [PR merged](https://github.com/guardian/frontend/pull/23745))
- [x] /projects/commercial/modules/hosted/gallery.js (Ravi - [PR merged](https://github.com/guardian/frontend/pull/23793))
- [x] /projects/commercial/modules/paid-containers.js (Ed - [PR merged](https://github.com/guardian/frontend/pull/23744))
- [x] /projects/commercial/modules/dfp/fill-advert-slots.js (Ed - [PR merged](https://github.com/guardian/frontend/pull/23741))
- [x] /projects/commercial/modules/dfp/prepare-googletag.js (Ed - [PR merged](https://github.com/guardian/frontend/pull/23747))
- [x] /projects/commercial/modules/dfp/render-advert.js (Ed - [PR merged](https://github.com/guardian/frontend/pull/23755/files))

References to `$` which uses `qwery` internally:

- [x] /projects/commercial/modules/article-aside-adverts.js (Mario - [PR merged](https://github.com/guardian/frontend/pull/23813))
- [x] /projects/commercial/modules/comment-adverts.js (Ravi - [PR merged](https://github.com/guardian/frontend/pull/23832))
- [x] /projects/commercial/modules/comment-adverts.spec.js (Ravi - [PR merged](https://github.com/guardian/frontend/pull/23832))
- [x] /projects/commercial/modules/dfp/dfp-api.spec.js (Ed - [PR merged](https://github.com/guardian/frontend/pull/23863/))
- [x] /projects/commercial/modules/hosted/about.js (Ravi - [PR merged](https://github.com/guardian/frontend/pull/23754))
- [x] /projects/commercial/modules/hosted/gallery.js (Ravi - [PR merged](https://github.com/guardian/frontend/pull/23793))
- [x] /projects/commercial/modules/hosted/next-video-autoplay.js (Ed - [PR merged](https://github.com/guardian/frontend/pull/23840))
- [x] /projects/commercial/modules/hosted/onward-journey-carousel.js (Ravi - [PR merged](https://github.com/guardian/frontend/pull/23745))

## Does this change need to be reproduced in dotcom-rendering ?

- [X] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## What is the value of this and can you measure success?

Reduce bundle size, remove dependency on old libraries, improve performance, aid migration

### Tested

- [X] Locally
- [ ] On CODE (optional)

---

Non-commercial:

We won't tackle these but left here for reference:

References to `qwery`:

- [ ] /bootstraps/videojs-embed.js
- [ ] /bootstraps/enhanced/trail.js
- [ ] /bootstraps/enhanced/gallery.js
- [ ] /bootstraps/enhanced/main.js
- [ ] /bootstraps/enhanced/article.js
- [ ] /projects/facia/modules/onwards/geo-most-popular-front-extended.js
- [ ] /projects/facia/modules/onwards/geo-most-popular-front.js
- [ ] /projects/facia/modules/ui/container-show-more.spec.js
- [ ] /projects/facia/modules/ui/container-show-more.js
- [ ] /projects/facia/modules/ui/lazy-load-containers.js
- [ ] /projects/common/modules/ui/autoupdate.js
- [ ] /projects/common/modules/spacefinder.js
- [ ] /projects/common/modules/gallery/lightbox.js
- [ ] /projects/common/modules/component.js
- [ ] /projects/common/modules/discussion/comments.js
- [ ] /projects/common/modules/discussion/loader.js
- [ ] /projects/common/modules/onward/popular.js
- [ ] /projects/common/modules/onward/geo-most-popular.js
- [ ] /lib/$.js

References to `$()` which uses `qwery` internally:

- [ ] /bootstraps/videojs-embed.js
- [ ] /bootstraps/enhanced/article-liveblog-common.js
- [ ] /bootstraps/enhanced/article.js
- [ ] /bootstraps/enhanced/facia.js
- [ ] /bootstraps/enhanced/football.js
- [ ] /bootstraps/enhanced/main.js
- [ ] /bootstraps/enhanced/media-player.js
- [ ] /bootstraps/enhanced/newsletters.js
- [ ] /bootstraps/enhanced/sport.js
- [ ] /bootstraps/enhanced/trail.js
- [ ] /bootstraps/enhanced/video-player.js
- [ ] /lib/formInlineLabels.js
- [ ] /lib/page.js
- [ ] /projects/common/modules/analytics/discussion.js
- [ ] /projects/common/modules/article/membership-events.js
- [ ] /projects/common/modules/atoms/youtube-player.js
- [ ] /projects/common/modules/atoms/youtube.js
- [ ] /projects/common/modules/business/stocks.js
- [ ] /projects/common/modules/charts/table-doughnut.js
- [ ] /projects/common/modules/commercial/adblock-ask.js
- [ ] /projects/common/modules/crosswords/crossword.js
- [ ] /projects/common/modules/crosswords/main.js
- [ ] /projects/common/modules/discussion/activity-stream.js
- [ ] /projects/common/modules/discussion/comments.js
- [ ] /projects/common/modules/discussion/loader.js
- [ ] /projects/common/modules/discussion/whole-discussion.js
- [ ] /projects/common/modules/gallery/lightbox.js
- [ ] /projects/common/modules/identity/account-profile.js
- [ ] /projects/common/modules/identity/delete-account.js
- [ ] /projects/common/modules/identity/modules/button.js
- [ ] /projects/common/modules/identity/modules/switch.spec.js
- [ ] /projects/common/modules/navigation/navigation.js
- [ ] /projects/common/modules/navigation/search.js
- [ ] /projects/common/modules/onward/history.js
- [ ] /projects/common/modules/social/share-count.js
- [ ] /projects/common/modules/sport/score-board.js
- [ ] /projects/common/modules/sport/football/match-list-live.js
- [ ] /projects/common/modules/ui/autoupdate.js
- [ ] /projects/common/modules/ui/expandable.spec.js
- [ ] /projects/common/modules/ui/full-height.js
- [ ] /projects/common/modules/ui/message.js
- [ ] /projects/common/modules/ui/message.spec.js
- [ ] /projects/common/modules/ui/relativedates.js
- [ ] /projects/common/modules/ui/rhc.js
- [ ] /projects/common/modules/ui/rhc.spec.js
- [ ] /projects/common/modules/ui/selection-sharing.js
- [ ] /projects/common/modules/ui/selection-sharing.spec.js
- [ ] /projects/common/modules/ui/smartAppBanner.js
- [ ] /projects/common/modules/video/events.js
- [ ] /projects/common/modules/video/video-container.js
- [ ] /projects/facia/modules/onwards/geo-most-popular-front-extended.js
- [ ] /projects/facia/modules/onwards/geo-most-popular-front.js
- [ ] /projects/facia/modules/onwards/search-tool.js
- [ ] /projects/facia/modules/onwards/search-tool.spec.js
- [ ] /projects/facia/modules/onwards/weather.js
- [ ] /projects/facia/modules/ui/container-show-more.js
- [ ] /projects/facia/modules/ui/container-toggle.js
- [ ] /projects/facia/modules/ui/container-toggle.spec.js
- [ ] /projects/facia/modules/ui/live-blog-updates.js
- [ ] /projects/facia/modules/ui/snaps.js

### CODE REVIEW

**Comment by mxdvl** [comment]
I think this it's worthwhile tackling the `/projects/commercial/*` ones, but probably best to leave out the rest.

Maybe it's worth spinning this into an Issue (remove Qwery) and only keep the commercial ones here?

The real benefit of this is if we can remove `qwery` from the commercial bundle so it's not served to DCR, and we don't rely on it when we move things over to `commercial-core`!

**Comment by arelra** [comment]
> I think this it's worthwhile tackling the `/projects/commercial/*` ones, but probably best to leave out the rest.

Yes I agree.

The other modules were a low priority stretch goal.

But given the effort we've encountered so far I'll remove non-commercial.

The problem is going to be the use of `$` in `/common` modules which means we probably won't remove qwery from the bundle but it will help future migration.

**Review by ashishpuliyel — APPROVED** [review]
What a neat little PR following weeks of work!

**Review by mxdvl — APPROVED** [review]
Ma-hoo-sive!

**Pull request closed without merging**
