### PR TITLE
Remove dead opt-in controller

### PR DESCRIPTION
**Pull request by jfsoul**
## What does this change?
~Starts a discussion over whether we can kill this "feature".  This won't build for now, as I need to remove more references - but wanted to see if anyone knows why this feature might still be needed.~

This feature is no longer needed (see comments).

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by philmcmahon** [comment]
Any idea what it was originally used for? Was it garnett or next gen web?

**Comment by jfsoul** [comment]
> Any idea what it was originally used for? Was it garnett or next gen web?

My current guess would be something to do with r2 -> next-gen-web.  Hasn't been touched meaningfully since 2014 looking at the history.

**Comment by jfsoul** [comment]
I think this is very safe to delete judging by this PR: https://github.com/guardian/fastly-edge-cache/pull/186.  There's also no reference anywhere to the cookie name that this controller sets.

**Comment by NataliaLKB** [comment]
Definitely this has been preceded by: https://github.com/guardian/frontend/blob/master/applications/app/controllers/OptInController.scala

**Comment by NataliaLKB** [comment]
This should be all good to delete!

**Review by nicl — APPROVED** [review]
Okay trusting the other comments which say this is no longer needed! 👍

**Pull request merged**
