### PR TITLE
Uprade to Play 2.5.10

### PR DESCRIPTION
**Pull request by TBonnin**
We are almost there.
This is the final branch for Play 2.5 upgrade

## What is the value of this and can you measure success?
You can measure my blood pressure. Should be taken down a notch after this is merged

I might have messed up the merge because some commits appears twice. Anyway we will do a squash merge when merging with master 😄

### CODE REVIEW

**Comment by TBonnin** [comment]
@guardian/dotcom-platform @DiegoVazquezNanini @alexduf @jfsoul 

🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 
It is all green. 💚💚💚💚💚💚💚💚💚💚💚💚💚💚
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

We will deploy it tomorrow morning since I am leaving in a few minutes

**Comment by dominickendrick** [comment]
👏

**Comment by jfsoul** [comment]
AND we're saving 32 lines of code!

**Comment by alexduf** [comment]
giphy

**Review by alexduf — COMMENTED** [review]
I had a look, all good!

**Pull request merged**
