### PR TITLE
Fix weather healthcheck

### PR DESCRIPTION
**Pull request by robertberry-zz**
CC @janua @gklopper

### CODE REVIEW

**Comment by janua** [comment]
:+1:

**Comment by phamann** [comment]
Ship me!

**Comment by robertberry** [comment]
@phamann I can't until websys put the weather api key on TeamCity - see the test I added

**Comment by janua** [comment]
What on earth is going on with this? It surely doesn't take that long to add an API key!
TeamCity really is one of the last things out of our reach, seeing as we operate devops style, what's wrong with giving us access I wonder.

**Comment by robertberry** [comment]
I completely agree with this. That we don't own Team City causes us many problems. CC @gklopper Can we prioritise sorting this out?

In this case Grant pointed out I shouldn't be calling out to the weather API from Team City. I thought my last commit fixed it but obviously not ...

**Pull request merged**
