### PR TITLE
don't transition the height of the top banner, ever

### PR DESCRIPTION
**Pull request by sndrs**
makes #11622 permanent.

it didn't affect crashes, but it definitely makes page load feel quieter

cc @Calanthe @uplne

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Could you post a recording of before/after? So instead of a transition, the page just jumps?

**Comment by sndrs** [comment]
you can view exactly what it does by opting in to the temporary pref i added in #11622 http://www.theguardian.com/uk#gu.prefs.no-banner-transition=true

**Comment by uplne** [comment]
As I remember the whole purpose of the transition (UX/product decision) was to make it a little bit less painful for the user. That is the only reason why we haven't removed it months ago.

**Comment by sndrs** [comment]
@uplne i've updated it to set a min-height on the iframe. this should mean there's nothing to transition when a 90px ad loads, but if it's a larger one, the page will still slide to accommodate it

screen recording 2016-01-20 at 04 48 pm
screen recording 2016-01-20 at 04 50 pm

**Comment by OliverJAsh** [comment]
I think this is fine :+1:

**Pull request merged**
