### PR TITLE
Add standfirst titles to items

### PR DESCRIPTION
**Pull request by sammorrisdesign-zz**
I saw a few people in the comments mention this. Something that we should probably do.

screen recording 2015-02-04 at 05 56 pm

### CODE REVIEW

**Comment by robertberry** [comment]
I like this, but you should measure what the increased weight is on a couple of pages. (Set your facia stage in frontend.properties to PROD, and load the same page on theguardian.com and local, and look in your Network tab.)

**Comment by gklopper** [comment]
I take it that `@HTML.noHtml(...)` strips out any links that might be in the standfirst?

**Comment by robertberry** [comment]
Yeah, it turns HTML into plain text

**Comment by michaelwmcnamara** [comment]
What does it do on phones and touch screens?

**Comment by robertberry** [comment]
Pretty much nothing. It's a feature that's only really useful on desktop.

**Comment by michaelwmcnamara** [comment]
Ah ok, can you tell me is it loaded for phones at all? (Thinking of our iPad/iPhone 4 page size/crashing issue)

**Comment by michaelwmcnamara** [comment]
On android phone
 - page weight for culture front on prod is 97.8 kb compressed / 845 kb uncompressed
- page weight for culture front on local is 109 kb compressed / 898 kb uncompressed
(using the culture front as uk front in prod had a whole lot of .gif entries that were not present on local)

@Rob is this a significant enough increase to be a problem?
if so can we limit this to just serve to desktop - especially given it is not of any use on mobiles?

**Comment by robertberry** [comment]
@michaelwmcnamara What was the equivalent page weight with it turned off? Page weight changes depending on how many stories are on the page.

Also you don't need to do it on a device - page weight is the same across desktop & mobile.

**Comment by sammorrisdesign** [comment]
@michaelwmcnamara Are you talking about the prod/local content or actual site?

If it's the actual sites, then local would have the changes and prod wouldn't. Which would mean for 12KB increase, which probably isn't worth it. Can you confirm this @michaelwmcnamara ?

**Comment by phamann** [comment]
8 days. Make a decision.

**Comment by robertberry** [comment]
I say no for now. Once we've sorted perf issues we could try introducing them, and seeing whether it has a negative effect.

**Comment by sammorrisdesign** [comment]
Yeah I'd agree with this. Unfortunately.

**Pull request closed without merging**
