### PR TITLE
Check validity of participation(s) prior to accessing property

### PR DESCRIPTION
**Pull request by JustinPinner**
## What does this change?
We see errors in Sentry when we attempt to reference instances of AB participations without checking that we were able to retrieve them first.

The cause of the error is somewhat opaque, and for specific devices, but points to attempts to access the variant property of a non-existent participation.

## What is the value of this and can you measure success?
Fewer errors reported in Sentry. Less likely to cause failures on user's devices.

## Does this affect other platforms - Amp, Apps, etc?
Anything that uses the AB system. But the change should have no visible effect.

## Screenshots
N/A

## Request for comment
@NataliaLKB @regiskuckaertz

### CODE REVIEW

**Comment by NataliaLKB** [comment]
One comment, but otherwise great 👍 . Thanks so much for doing this!

**Comment by dominickendrick** [comment]
Can this be shipped ?

**Comment by sndrs** [comment]
can this be closed @JustinPinner?

**Comment by JustinPinner** [comment]
@sndrs @dominickendrick Oops - this slipped through, I'll ship it today / tomorrow.

**Comment by TBonnin** [comment]
@JustinPinner any update on this PR?

**Comment by NataliaLKB** [comment]
@JustinPinner I am closing this PR. Please reopen and ship when you can.

**Pull request closed without merging**
