### PR TITLE
Force sending of Commercial metrics

### PR DESCRIPTION
**Pull request by domlander**
## What does this change?

This allows the user to forcefully send commercial metrics by adjusting the URL.

## Does this change need to be reproduced in dotcom-rendering ?

- [X] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## What is the value of this and can you measure success?

Allows us to check what commercial metrics are sent on production frontend

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by arelra — COMMENTED** [review]
Wondering (I'm not sure 100%) if we should add this to the list of allowed dev parameters. I think it would be okay to only allow this client-side as the comments suggest?

https://github.com/guardian/frontend/blob/edde50a39fd5b4beea4d0a69c49ee246ba68bd7f/common/app/dev/DevParametersHttpRequestHandler.scala#L59

https://github.com/guardian/frontend/blob/edde50a39fd5b4beea4d0a69c49ee246ba68bd7f/common/app/dev/DevParametersHttpRequestHandler.scala#L23-L28

**Comment by domlander** [comment]
> Wondering (I'm not sure 100%) if we should add this to the list of allowed dev parameters. I think it would be okay to only allow this client-side as the comments suggest?

Thanks Ravi, that seems like a good idea. Will update.

**Comment by chrislomaxjones** [comment]
Does the allowlist of dev parameters include hashes like `#forceSendMetrics`? Or does it just apply to e.g. `?adtest`?

**Comment by arelra** [comment]
> Does the allowlist of dev parameters include hashes like `#forceSendMetrics`? Or does it just apply to e.g. `?adtest`?

Ah good catch!

The list is for request parameters and not hashes.

Perhaps it should be a request param though? Using a hash seems a bit overloaded.

**Comment by chrislomaxjones** [comment]
> Perhaps it should be a request param though? Using a hash seems a bit overloaded.

Equally happy with that, especially since we've added it to the allow-list already! FYI @domlander `getUrlVars()` is a handy lib function we have for this.

**Comment by domlander** [comment]
> > Perhaps it should be a request param though? Using a hash seems a bit overloaded.
> 
> Equally happy with that, especially since we've added it to the allow-list already! FYI @domlander `getUrlVars()` is a handy lib function we have for this.

Yep, that seems like a good idea to me. I will make the change.

**Review by arelra — APPROVED** [review]
👍

**Review by chrislomaxjones — APPROVED** [review]
Nice!

**Pull request merged**
