### PR TITLE
Move huge images out of SVGs

### PR DESCRIPTION
**Pull request by regiskuckaertz**
The size of the commercial JS is in large part due to inlined assets, notably the adblock coins:

picture 1
picture 2
picture 3
picture 4

Let's move those suckers into static PNGs instead (thanks @SiAdcock for the insight of using `javascriptConfig`). People from the @guardian/membership-and-subscriptions team, so you're aware.

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
Real nice, man ❤️

**Comment by regiskuckaertz** [comment]
Why are tests failing? 😭

**Comment by philwills** [comment]
@regiskuckaertz think those images need to go in `static/public`, not `static/src`

**Comment by regiskuckaertz** [comment]
Thanks @philwills 😃

**Pull request merged**
