### PR TITLE
[PlatformFuture] Initial commit.

### PR DESCRIPTION
**Pull request by gtrufitt**
In the interest of small PRs, here is a `package.json` and a `readme` for static-future as a start to creating a sandbox (and fairly rapidly production build) for the future of our client side architecture.

### CODE REVIEW

**Comment by gtrufitt** [comment]
@guardian/dotcom-platform

**Comment by jfsoul** [comment]
Get that ball rolling 👍  ⚽️  🎾  🎱

**Comment by sndrs** [comment]
one thing that came up in a discussion with @rich-nguyen about this kind of thing before was the value of making sure that everyone knows their environment

(appreciate this is a slightly different case and also not a final PR, so only mean this as a point of discussion more than anything else...)

but rich's thought, with which he persuaded me, was that there's a lot of overhead in needing to find out, for example, which version of lodash is installed for this file i'm working on. more than the value of being able to move forward more quickly in some areas of the codebase than in others

by having one set of packages, you can just _know_ 'we're using lodash 3' or 'we can now use `async`/`await` etc...

**Comment by rjmk** [comment]
I'm not sure how to use the `static-future` folder. What's your vision for it?

**Pull request merged**
