### PR TITLE
Developer lines in the sand

### PR DESCRIPTION
**Pull request by johnduffell**
There are certain must-have's that are fundamental to doing our job effectively.

We have never written them down as far as I know (or possibly just not somewhere obvious enough for me), except in emails from time to time.  This isn't totally useful especially when we're expecting to get new people into the team in future.

Also writing them down will help if we need to convince people outside that we need to invest in things in order to stick to our principles - if we are modest and realistic in our list, it would seem unkind not to let us keep to them.

The list I've made is completely off the top of my head.  We should probably think harder than I just did about what should go in there but I wanted to make a start.

@janua @gklopper

### CODE REVIEW

**Comment by gklopper** [comment]
Here is my initial run at it...

* We develop and release in small chunks. If we cannot figure out how to do that we ask our team for help.
* The team is our conscience, the team always knows what we are doing, and "the team" is not only other engineers.
* For any task we understand who we need to communicate with and we communicate accurately and with empathy.
* No job is done till we have seen it working properly in production. In particular we deploy and check our own software, we do not leave it for someone else to do.

**Comment by gklopper** [comment]
Just for interest sake, here is a list from the very early days of NGW (its too long, people need to be able to remember it):

* It's not discovery unless it contains user and A/B testing.
* We are an evidence-based decision making outfit. We do not believe in superstition and we don't deal in witchcraft.
* We release early and often. We continuously deploy.
* Personalisation is a core function, we cannot add it later.
* Our environments are swimlaned.
* We build asynchronous applications. Request blocking is an unpardonable offence.
* We reduce the future cost of change. We pay the cost of software development upfront and don't cut corners.
* Our software is source controlled, tested, instrumented, documented, performant, robust, multi platform, asynchronous, distributed, trivial to run locally, well logged, continuously integrated, continuously deployed and compliant with WebSys Web Application Specifications.
* We utilise the identity, user and content platforms fundamentally in our pages.
* We are transparent. Our scorecard is on the radiator screen.
* We know how live our pages need to be and they are that live.
* We are multiplatform from the start.
* We instrument extensively. We know what our applications are doing. Our numbers are dashboarded.
* We are not led by the legacy.
* We believe the secret to failure is trying to please everybody.
* We are fast. Our performance test results are outstanding.
* We write code we assume will be made public.
* We let it fail.
* All pages should have a sensible and coherent rendering with just a single Content API call.
* If users don't care about it, it goes, or is moved, or is rethought.
* We are not in the business of writing another rules engine or trailblock editor. Because we are the UI. Not the data layer. Or the business rules. Or the API.

**Comment by johnduffell** [comment]
This is a good one
> If users don't care about it, it goes, or is moved, or is rethought.

**Comment by rich-nguyen** [comment]
Are all these lines in the sand, or principles? I've always thought of a line as something measurably non-negotiable. A principle is less measurable, important nonetheless, but subjective in it's application.

**Comment by gklopper** [comment]
The 2nd lot I put in were just for interest sake from the good old days. I think any list needs to be short to work.

How about the heading...

## How we work

**Comment by jennysivapalan** [comment]
How about something along the lines of developers knowing how to back their changes out quickly? e.g. using switches or knowing the roll back process.

**Comment by johnduffell** [comment]
@gklopper or how about 
# Five things the team cares about above all else
@jennysivapalan that's definitely a good one - know how to get yourself out of any situation

From chatting with some people it seems like there could be an additional document expanding on the core points, which would be useful for new starters especially.  Just to be a bit more specific about all the things you should know to be a confident member of the team.

**Comment by gklopper** [comment]
How about something like...

We believe we can make a difference. We understand we are empowered to do that.

**Comment by johnduffell** [comment]
@gklopper I like that, like you said in the gifs meeting we should make a career out of subverting things

**Comment by gklopper** [comment]
I said "***I***" made a good career out of it.

**Comment by janua** [comment]
> We instrument extensively. We know what our applications are doing. Our numbers are dashboarded.

I like this one, but I don't think "extensive" is no longer the case and there is more we could do. (And I personally do this by exposing some part of an application because it annoys me that it's wrapped away failing silently)

> Personalisation is a core function, we cannot add it later.

Hmmmm.

Maybe 4 or 5 to start with would be good. (The contents of the PR), but there are still some good ones in the old principles.

**Comment by johnduffell** [comment]
@janua (and all) I've opened a doc for collaborating on these, we should discuss this at the next team meeting https://docs.google.com/document/d/1_ELZGwpjhUhOSNt4dKAQxazQabQjZZLC6OOl-CiWdlY/edit (there are more than 4 but we can refine and vote on them)

**Comment by rich-nguyen** [comment]
@johnduffell ok to close this one now?

**Comment by OliverJAsh** [comment]
@johnduffell I've added a comment and a suggestion.

**Comment by johnduffell** [comment]
we will discuss these soon

**Pull request closed without merging**
