### PR TITLE
Removing the 2017 facia election container

### PR DESCRIPTION
**Pull request by NataliaLKB**
## What does this change?
Reverting https://github.com/guardian/frontend/pull/16847, https://github.com/guardian/frontend/pull/16822 and  https://github.com/guardian/frontend/pull/16806

The election container was created just for the election which has now passed. Removing the code.

_Note:_ There has been talk of elements of this container to be reimplemented in the future. Until that is decided though its best to revert this change to avoid dead code lying around.

**TODO:**
- [x] Changes were made to the facia tool/config tool that also have to be reverted: https://github.com/guardian/facia-tool/pull/242

cc @stephanfowler @guardian/dotcom-platform

## What is the value of this and can you measure success?
Less code! Less container options! 

## Does this affect other platforms - Amp, Apps, etc?
Nope

## Screenshots
N/A

## Tested in CODE?
Nope

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]
💅 !

**Comment by stephanfowler** [comment]
There's also a change to Facia Tool that'll need to be reverted.

**Comment by NataliaLKB** [comment]
@stephanfowler yes! I have it in the **TODO** in the description 😄

**Comment by NataliaLKB** [comment]
Facia tool PR: https://github.com/guardian/facia-tool/pull/242

**Pull request merged**
