### PR TITLE
Lazy load images on fronts

### PR DESCRIPTION
**Pull request by robertberry-zz**
Wonder if this saves us any money, too ... 
- [x] Images not loaded on IE8 
- [x] On article pages, images aren't loading for recommended content containers at bottom of page
- [x] On video pages - "more on this story" and "more sport videos"/"more football videos" and similar  
     containers don't display images.
- [x] For firefox and IE on windows machines, images on fronts are only loaded for items that are visible at time of loading - when you scroll down the page, images for lower containers do not load.

### CODE REVIEW

**Comment by robertberry** [comment]
CC @sndrs @gklopper @stephanfowler @phamann 

I think this is nearly there. I don't want to merge it until Alex has merged his picturefill fix, though, as this will end up calling picturefill more frequently after initial load.

I'm not sure whether to add some kind of fade-in effect for the images, or something to indicate they're loading before they do, as there's no visual feedback at the moment. I could easily add a CSS transition for them to fade in, but as that's opacity, it could be heavy on the GPU.

**Comment by uplne** [comment]
As this is a really nice thing to play and learn about the Chrome timeline I did this out of the interest on how this will affect the page.

Testing approach:
1. I just tried to scroll in the same speed from top to bottom
2. checked for animation frame fire events
3. counted the number of reflows
4. try 1-3 few times

Using Chrome.

What we have now (Live):
screen shot 2015-02-23 at 15 49 07

As expected there is not much happening. Pretty steady FPS.
No of reflows: 0

Lazy load without Fastdom:
screen shot 2015-02-23 at 15 35 33

This is of course different but again, as expected. We have few spikes now.
No of reflows: 12 (whole document)

Lazy load with Fastdom:
screen shot 2015-02-23 at 15 21 50

The amount of spikes is similar.
No of reflows: 12 (whole document)

Conclusion:
For me, in this case, Fastdom is not making any difference. But it might be just because the Chrome should be smart about reflows/repaints and it may be totally different in other browsers or I just didn't have enough data.

The spikes are below 30 fps in few cases which may be seen as lags (this was done on shiny mac...)

**Comment by robertberry** [comment]
It might not be making much of a difference - depends whether anything else is executing in the JavaScript at the time. The point is, if you queue up all the reads to happen in the read cycle, and all the writes in the write cycle, you don't get layout thrashing caused by multiple modules doing reads and writes at random times (rather than batching all the reads within an animation frame to happen before all the writes) ... if that makes sense.

**Comment by michaelwmcnamara** [comment]
Meant to add this earlier - sorry - 
2 issues:
1) on article pages, images aren't loading for recommended content containers at bottom of page
2) For firefox and IE on windows machines, images on fronts are only loaded for items that are visible at time of loading - when you scroll down the page, images for lower containers do not load.

**Comment by robertberry** [comment]
@phamann Hmm kind of stumped with this - how can we reconcile it with non-modern browsers?

**Comment by michaelwmcnamara** [comment]
Update:
Fronts display correctly but articles still not loading images for "related content" and "recommended" containers below article body - also seen on video pages.

**Comment by robertberry** [comment]
@michaelwmcnamara I've changed a bunch of stuff. Ran it locally and was seeing images on related content and recommended.

We should thoroughly test this on a bunch of browsers & devices. Grab me when you're in and we'll go through it

**Comment by michaelwmcnamara** [comment]
http://localhost:9000/sport/video/2014/nov/28/phillip-hughes-cricket-australia-cricket-continue-when-ready-video

"more on this story"
and
"more sport videos"

containers don't display images.

**Comment by michaelwmcnamara** [comment]
Also IE8 isn't showing any images

**Comment by robertberry** [comment]
@michaelwmcnamara The more stuff should be fixed now. Looking at IE8.

**Comment by robertberry** [comment]
@michaelwmcnamara IE8 should be fixed, too.

**Pull request merged**
