### PR TITLE
Reinstate Correct Blog ID

### PR DESCRIPTION
**Pull request by kelvin-chappell**
Was taking last character, rather than last part of blog ID.

@ironsidevsquincy

### CODE REVIEW

**Comment by robertberry** [comment]
:+1:

**Comment by robertberry** [comment]
Although is this not now taking the whole id?

**Comment by kelvin-chappell** [comment]
Yes, that's the idea.  After discussing with @ironsidevsquincy It changed from a reinstatement to a complete change that's more semantically correct, but will hopefully not break anything.

**Comment by robertberry** [comment]
Cool, looks good then :+1:

**Pull request merged**
