### PR TITLE
Ignore ensime config files

### PR DESCRIPTION
**Pull request by kelvin-chappell**

### CODE REVIEW

**Review by JonNorman — APPROVED** [review]
Are you now using Atom to develop frontend with?

**Comment by kelvin-chappell** [comment]
I'm going to keep an eye on it.

**Comment by desbo** [comment]
Should `.ensime` be ignored? What if I want to try it?

**Comment by kelvin-chappell** [comment]
It seems to be full of directory names etc so it's very machine and user-specific.  You'll have to generate your own!

**Comment by JonNorman** [comment]
I managed to get mine to work (before my mac got nuked), it took a bit of faffing about but eventually I got go-to functionality in Atom with it.

**Pull request merged**
