### PR TITLE
Adds penalty tries to the rugby scoreboard. 

### PR DESCRIPTION
**Pull request by jennysivapalan**
Penalty tries come through as a different score event from the Opta feed (it's not documented :disappointed: )
`
<Event minute="12" period="First Half" player_id="0" second="11" team_id="550" type="Penalty Try"/>
`

Note the player_id=0 which is not a player on a team. This seems to be the standard on the events feed that events not assigned to a player. However our code assumes every score event is assigned to a player. In the penalty try case I have created a fake player with the name `Penalty` and wrapped this up with the Try events.

Before:
screen shot 2015-09-21 at 11 53 08

After:
screen shot 2015-09-21 at 11 23 42

cc @mchv @rich-nguyen

### CODE REVIEW

**Comment by mchv** [comment]
@jenny I get the idea of the implementation, but I am not a big fan on fake player, which I find complicates quite a big the parsing. I think that displaying `Penalty Tries` on a separated line in the UI when there is one of them clearer and easier to implement.

**Comment by jennysivapalan** [comment]
@mchv so I tried this to start but we do two things quite early on in the parsing. First we filter the events we care about (e.g. Tries, Conversions) so adding Penalty Try was easy. However in the second part we map the player_id to the a player listed in the `TeamDetail`. In this case we don't have a player so we lose the event. We have to alter the parsing in any case and probably more code further up in the controller. So I thought this was the simplest route for now. I assume if we have more cases of this we can refactor the code. The other thing with a separate UI line is how do we distinguish between the two teams as we won't have a player name to list. We would need some kind of icon? The sports desk seem happy to list Penalty Tries with the Tries.

**Comment by jennysivapalan** [comment]
Seems like adding `Half time` was a simple fix so I've added it to this PR: https://github.com/guardian/frontend/commit/5e0ddb26cae0a27001e5bc1c69800b864246e79c

**Comment by mchv** [comment]
@jennysivapalan this all makes sense, Thanks
:+1:

**Comment by jennysivapalan** [comment]
Grat thanks

**Pull request merged**
