### PR TITLE
fix show more button spacing

### PR DESCRIPTION
**Pull request by sndrs**
# before

screen shot 2015-02-13 at 11 25 41
# after
### tablet+

screen shot 2015-02-13 at 11 21 57
screen shot 2015-02-13 at 11 22 05
### mobile

screen shot 2015-02-13 at 11 22 20
screen shot 2015-02-13 at 11 22 35

### CODE REVIEW

**Comment by robertberry** [comment]
Does this fix all the spacing issues? I was also seeing it between slices on mobile

**Comment by robertberry** [comment]
(as in you'd get the last card from one slice up against the first card from another)

**Comment by sndrs** [comment]
yeah sorry, the slightly narrower ones (bottom 2) are mobile bp - will update description

**Comment by robertberry** [comment]
:+1:

**Pull request merged**
