### PR TITLE
Bump faciaVersion to 3.0.20

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

Bump faciaVersion from 3.0.11 to 3.0.20.

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No

### CODE REVIEW

**Comment by tjmw** [comment]
Hi @shtukas there was a conversation on another PR about this upgrade: https://github.com/guardian/facia-tool/pull/1111#issuecomment-557589872 Anna's comment:

>NB: if you need to jump from a version of facia-scala-client below 3.0.12 - a big change has been added in .12-.14 updating to a new version of capi models. So you will need to make sure you are on the same version of capi models as facia-scala-client.

made me think the changes would be more far reaching on our side. Great if they're not, but just want to make sure we're not missing something!

**Comment by shtukas** [comment]
@tomrf1 Looks like things are ok for us. Obviously it would be great if @philmcmahon or @jonathonherbert could approve :)

**Comment by philmcmahon** [comment]
@shtukas to play it safe I suggest bumping capiVersion to 15.4

**Comment by shtukas** [comment]
@philmcmahon capiVersion is 15.6

**Review by philmcmahon — APPROVED** [review]

**Pull request merged**
