### PR TITLE
add tone to video info endpoint

### PR DESCRIPTION
**Pull request by jamesgorrie**
## What does this change?

Adding the tone to the video endpoint.
This should help us push info to Ophan allowing us to see what type of video is doing well.
## What is the value of this and can you measure success?

We can measure success 
## Does this affect other platforms - Amp, Apps, etc?

No (not for now)
## Request for comment

@akash1810

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@paulmr - might be something we need to add to the video Artom.

**Comment by akash1810** [comment]
👍

**Comment by gtrufitt** [comment]
⏳ Is this one waiting for anything? 😃

**Comment by jamesgorrie** [comment]
Closing until we're 100% sure what we need.

**Pull request closed without merging**
