### PR TITLE
archive - Update http link to https for not found page

### PR DESCRIPTION
**Pull request by mchv**
## What does this change?

Update archive not found page links to https so no error is reported

### CODE REVIEW

**Comment by JustinPinner** [comment]
Will this be a problem?
screen shot 2016-06-02 at 11 53 56

**Comment by mchv** [comment]
@JustinPinner not sure on long term but it will be good to find if we use `image.guardian.co.uk` for any other files

**Comment by humaislam** [comment]
What next for this PR?

**Comment by sndrs** [comment]
33 days

**Comment by JustinPinner** [comment]
Looks like we need an SSL cert over image.guardian.co.uk before this can be merged.

**Comment by humaislam** [comment]
status: in conversation with fastly and @adamnfish re certs. Will unblock this soon.

**Comment by johnduffell** [comment]
any updates on this? it's been a very very long time!

**Comment by humaislam** [comment]
Isn't this now unblocked @mchv

**Comment by mchv** [comment]
I think image.guardian.co.uk simply need to be configured with the correct SSL provider and an email  being sent to fastly

**Comment by adamnfish** [comment]
Fastly has a wildcard cert so as @mchv says, `image.guardian.co.uk` just needs to be configured and have its DNS updated.

**Comment by mchv** [comment]
I am going to merge this as the configuration is on going and will be fixed soon

**Comment by gidsg** [comment]
Hi @mchv you can just use `https://static.guim.co.uk` which is an alias for the same host, I am happy to update the file.

**Comment by mchv** [comment]
@gidsg please do

**Comment by humaislam** [comment]
was this done?

**Comment by gidsg** [comment]
@humaislam we fixed this another way by changing the host.

**Pull request merged**
