### PR TITLE
Move Grant to "Former Members" section

### PR DESCRIPTION
**Pull request by gklopper**
## What does this change?

Makes Grant a "Former" member

### CODE REVIEW

**Comment by NataliaLKB** [comment]
Sad days 😞

**Comment by gklopper** [comment]
@daithiocrualaoich I can only ignore the style guide a week from today...

https://www.theguardian.com/guardian-observer-style-guide-j

lc

**Review by sndrs — CHANGES_REQUESTED** [review]
there's a nasty code smell in here

**Review by sndrs — APPROVED** [review]

**Comment by TBonnin** [comment]
I am merging this. Sad day 😢

**Pull request merged**
