### PR TITLE
Upgrade Fastclick to 1.0.6

### PR DESCRIPTION
**Pull request by robertberry-zz**

### CODE REVIEW

**Comment by sndrs** [comment]
:+1:

**Comment by sndrs** [comment]
though i'm more game for nuking it

**Comment by ironsidevsquincy** [comment]
JS are defined https://github.com/guardian/frontend/blob/master/static/src/javascripts/bower.json. That needs updating

Also note we're using a fork because the official version was broken - is this not the case anymore?

**Comment by robertberry** [comment]
https://github.com/ftlabs/fastclick/pull/293

**Comment by ironsidevsquincy** [comment]
cool, just need to tell bower to use v1.0.6

**Comment by sndrs** [comment]
@ironsidevsquincy gah, last night lasted too long. i'm staying off here till tomorrow

**Comment by robertberry** [comment]
Ok I updated it and ran bower-installer and it changed loads of stuff :cry:

**Pull request merged**
