### PR TITLE
Add CSS Selectors report endpoint for all days

### PR DESCRIPTION
**Pull request by robertberry-zz**
Aggregates everything in the DB.

CC @stephanfowler @sndrs

### CODE REVIEW

**Comment by stephanfowler** [comment]
Nice. Hold before merging - I'll add an option to use this.

**Comment by sndrs** [comment]
:wine_glass:

**Comment by robertberry** [comment]
Stop wining

**Comment by sndrs** [comment]
:beetle:

**Comment by robertberry** [comment]
the "lady" "bird" - most feminine of insects (& half Liverpudlian)

**Comment by stephanfowler** [comment]
:+1: ok done, go, yeh

**Pull request merged**
