### PR TITLE
Invert mvt flag on new header

### PR DESCRIPTION
**Pull request by gu-stav**
## What does this change?

This inverts the MVT flag on the new header, which indicates, somebody is participating in the test. With this approach, we could prefix the desktop CSS with `new-header--mvt-desktop`.

```css
.new-header---mvt-desktop {
    @include mq(desktop) {
        display: block;
    }
}
```

## What is the value of this and can you measure success?

Going forward (or something else generic).

## Does this affect other platforms - Amp, Apps, etc?

No.

## Screenshots

No.

## Tested in CODE?

No.

### CODE REVIEW

**Review by NataliaLKB — CHANGES_REQUESTED** [review]
Not clear how this prevents it from being mobile only when you are not in the test.

Also:
> With this approach, we could prefix the desktop CSS with new-header--mvt-desktop

We can still do that without removing the mobile-only class. Not sure how "inverting" the test changes that.

**Comment by gustavpursche** [comment]
@NataliaLKB The `mobile-only` class get's in the way with the tablet extension which will happen first. Basically it inverts the mindset: show the new navigation everywhere, but the desktop.

**Comment by NataliaLKB** [comment]
Lets get the tablet extension out first then. Is that PR ready for review?

**Comment by NataliaLKB** [comment]
I suppose I am not clear on how this works making this change in isolation of the tablet extension. But regardless, why don't you do this: 

``` 
<header class="@RenderClasses(Map(
    "mobile-only" -> !mvt.ABNewDesktopHeader.isParticipating
    "new-header--mvt-desktop" -> mvt.ABNewDesktopHeader.isParticipating
), "new-header")"
```

And then remove the `mobile-only` class in the tablet extension?

**Comment by NataliaLKB** [comment]
Unless you mean that the `mobile-only` class is redundant since the rewrite (it was needed before) In which case you can definitely remove it - but then you need some css in this change to extend the desktop when you are in the test.

**Comment by NataliaLKB** [comment]
Unless you mean that the `mobile-only` class is redundant since the rewrite (it was needed before) In which case you can definitely remove it - but then you need some css in this change to extend the desktop when you in the test.

**Review by NataliaLKB — APPROVED** [review]
👍

**Pull request merged**
