### PR TITLE
Remove youtube endslate related code

### PR DESCRIPTION
**Pull request by nicl**
## What does this change?

Cleanup of endslate related code for youtube videos. See also: https://github.com/guardian/frontend/pull/21693

@SiAdcock @akash1810 there is a load of endslate-related stuff still around for non-youtube videos. I think this is still needed but do you know if this is the case?

### CODE REVIEW

**Comment by SiAdcock** [comment]
> there is a load of endslate-related stuff still around for non-youtube videos

Gosh, that's a good point. I think @rcrphillips is investigating removing VideoJS, without which the end slate will not work on old videos. Maybe you can hook up with him, and if VideoJS is to be ditched, delete all the end slate code at the same time as the VideoJS code?

**Comment by nicl** [comment]
@SiAdcock okay might have caught the bulk of it now. Videojs is going to be a separate discussion - sounds like we will remove, but the decision hasn't been made yet apparently.

**Review by gtrufitt — APPROVED** [review]
Bit hard to review a code deletion PR really, but it looks reasonable to me! Are there tests for the new stuff? Wondering because it was added as a switch they might have been missed so maybe worth adding as a separate PR.

**Review by SiAdcock — APPROVED** [review]

**Comment by nicl** [comment]
@gtrufitt hmm good point. Looks like there is a single test of the atom markup but that's it for Youtube stuff that I can see. I am not sure how easy it is to test this as we'd probably have to do a full browser test to load youtube and check. The alternatve is a test that just checks the related boolean on youtube markup is set and true but that seems too low-value a test to bother with.

**Comment by gtrufitt** [comment]
Yeah, sure, maybe this is something that the data team should be tracking as a metric somewhere, I imagine there's a GA ping fired off. We should think about these kind of 'canary' metrics on things we can't test that tell us if the data doesn't line up with expectations.

**Pull request merged**
