### PR TITLE
Integer timestamps for newsletter tracking

### PR DESCRIPTION
**Pull request by dblatcher**
## What does this change?
Uses integer timestamps on component events for newsletter sign-up components, instead of formatting into a custom date format.
After a point raised in https://github.com/guardian/dotcom-rendering/pull/5440, which originally implemented the custom data format on a DCR component, it was realised that the formatting can be by the data team as their end, reducing  the amount of client side code required.

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

## What is the value of this and can you measure success?
 - reduces JS payload for all newsletters page and sign-up iframes
 - will make the tracking format consistent with the new DCR component.

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [x] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [x] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by oliverlloyd — APPROVED** [review]
Less code 🎉

**Comment by mxdvl** [comment]
This seems valuable, will you be merging it, @dblatcher?

**Comment by dblatcher** [comment]
> This seems valuable, will you be merging it, @dblatcher?

Yes, sorry. I was going to double check with the data team to make sure they were ready for the change

**Comment by dblatcher** [comment]
As of 30th August, the data team wanted to do some more checks on their end to make sure this won't break any reporting.

**Pull request merged**
