### PR TITLE
Add clearer form guides and badges to football fixtures and tables

### PR DESCRIPTION
**Pull request by sammorrisdesign-zz**
The form guide's readability seems to come up as a problem fairly frequently, so this fixes that. It also adds team badges to the fixtures, results and table pages too.

**Fixtures and results**
Before: 
screen shot 2015-09-29 at 14 17 36

After:
screen shot 2015-09-29 at 14 17 13

**Tables**
Before:
screen shot 2015-09-29 at 14 18 01

After:
screen shot 2015-09-29 at 14 17 48

### CODE REVIEW

**Comment by paperboyo** [comment]
That’s a lot of crests... are there that many football teams in the world?!

Anyway, AFAIK, every single one of them is an unoptimised PNG24 of 500x500 px (one I’ve checked weighted 50KB). Maybe it would be wise to put them through imgIX, specifying `w=` and adding `fm=png8` to our usual set of arguments, so that the first table in the above screenshots won’t add almost 1MB to the page weight?

**Comment by rich-nguyen** [comment]
love the form guide ! super accessible

**Comment by sammorrisdesign** [comment]
For the badges I've created https://github.com/guardian/football-assets which will rescale and upload the assets automatically. This should make it easier to maintain and resize the badges (very designer friendly @rich-nguyen :smile:).

I'm also using the new size badges, so this is good to go on my end.

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
