### PR TITLE
Video play button alignment issues

### PR DESCRIPTION
**Pull request by zeftilldeath**
Video play buttons were not center aligned on smaller container size. 

Red colour illustrated where the play icon/circle should be. 

off-center

off-center_2

Result:
screen shot 2015-12-09 at 12 18 23

### CODE REVIEW

**Comment by sndrs** [comment]
lgtm - is it ok across all breakpoints?

**Comment by paperboyo** [comment]
Hush-hush. Maybe that's the time when we can drop opacity of the play button dark oval just a tad, so that the below does not look so terrible (there is one like that every day on the site. Trying to educate people to crop off-center will **never** work)?

picture 11

You won't tell anybody, I won't tell anybody, reviewers won't tell anybody, nobody will notice, everything's gonna be fine. Just fine. Only a bit better.

Regards
Mateusz

**Comment by zeftilldeath** [comment]
Cheers @sndrs, yep looks good on all breakpoints. Snuck in a 20% opacity drop @paperboyo. Or did I?

**Comment by paperboyo** [comment]
:gem: Don't know what you're talking about, @zeftilldeath :innocent: In case any designers ask, I always mistake opacity for transparency and vice versa.

giphy

**Comment by sammorrisdesign** [comment]
:+1:

**Pull request merged**
