### PR TITLE
Test whether not running our main javascript improves iphone 4 crash rates

### PR DESCRIPTION
**Pull request by gklopper**
Only to be merged after we test removing some containers.

### CODE REVIEW

**Comment by robertberry** [comment]
:+1:

**Comment by commuterjoy** [comment]
BTW, I have a crappy old iPhone 4 / iOS 6 and the front page crashes daily in Safari (not Chrome). Typically the page will load/render, then 2-3 seconds later just shut down the browser. Unscientifically it feels like a lot going on - fonts, js, ads etc. - and it just gets overwhelmed. I need a new phone.

**Comment by crifmulholland** [comment]
Hi Matt! Do you think you could retry this morning - we've released something that *should* have fixed that!

**Comment by commuterjoy** [comment]
@crifmulholland It didn't crash yesterday.

**Pull request closed without merging**
