### PR TITLE
Remove grunt uglify

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

- removes grunt uglify
- moves es5-shim, htmlshiv and json2 to npm, from bower
- uglifies during bundling, instead of as a separate task

## What is the value of this and can you measure success?

one more grunt dep down, and reduces bower deps too

## Does this affect other platforms - Amp, Apps, etc?

no

## Screenshots

slight diffs with master:

- diff vars in uglified otuput
screen shot 2016-11-15 at 13 14 19

- json2 is UMD
screen shot 2016-11-15 at 13 14 27 

## Request for comment

@SiAdcock @gtrufitt @NataliaLKB

### CODE REVIEW

**Review by NataliaLKB — APPROVED** [review]
lgtm 👍

**Comment by paperboyo** [comment]
🎆 Happy 15k, Frontend! 🎆 

still kickin

**Comment by sndrs** [comment]
WOO I DIDN'T EVEN NOTICE!

**Comment by sndrs** [comment]
look who got #5000? :)

**Pull request merged**
