### PR TITLE
Unit test membership JS

### PR DESCRIPTION
**Pull request by jbreckmckye**
Let's cover the functionality of `user-features.js` with some unit tests.

### CODE REVIEW

**Comment by kelvin-chappell** [comment]
:+1: 

Though still think it would be nice to separate out user features that are membership features from those that are features from being logged in or a subscriber, for example.  I know there aren't any at the moment.

**Comment by jbreckmckye** [comment]
@kelvin-chappell - so, you mean making `user-features` just `membership-features`? I'm not sure I understand the difference between being a member and a subscriber.

**Comment by kelvin-chappell** [comment]
Or just `membership`, but it doesn't need to be done in this PR.  This is fine to go.

**Comment by piuccio** [comment]
:heart_eyes:

**Pull request merged**
