### PR TITLE
Npm: update `sass-mq` to a valid version

### PR DESCRIPTION
**Pull request by gu-stav**
## What does this change?

Updates `sass-mq` dependency. The listed version `3.0.0` never was published on npm and so throw an error, when running certain npm/ yarn commands.

According to the [changelog](https://github.com/sass-mq/sass-mq/releases) there shouldn't be any changes at all.

Edit: Turns out, the linter didn't run since end of January. I'll raise another issue, that we need a check, if our linters are actually running during the validate step :)

## What is the value of this and can you measure success?

Proper toolchain.

## Does this affect other platforms - Amp, Apps, etc?

No.

### CODE REVIEW

**Comment by gustavpursche** [comment]
@sndrs Adding you as reviewer, because you initialised the `package.json` change for `sass-mq` - just in case it was intentional.

**Review by SiAdcock — APPROVED** [review]
Looks good, although `yarn.lock` seems to have gone a bit mental and updated hundreds of dependencies! Otherwise 👌

**Comment by gustavpursche** [comment]
@SiAdcock Thanks for pointing this out. Should be fixed now - could you have a look again, if this looks right to you?

**Comment by SiAdcock** [comment]
Much healthier! @gustavpursche 💎 👍 💎

**Comment by sndrs** [comment]
ha – nice one!

**Pull request merged**
