### PR TITLE
Updated old article message

### PR DESCRIPTION
**Pull request by zeftilldeath**
Tidied up the old article message.

screen shot 2016-01-21 at 17 44 03

screen shot 2016-01-21 at 17 43 54

screen shot 2016-01-21 at 17 43 36

### CODE REVIEW

**Comment by JustinPinner** [comment]
Will this work on non-white backgrounds? Also, the original designs specified the clock icon I think.

**Comment by zeftilldeath** [comment]
@JustinPinner Great point with the dark backgrounds, have added a variant. Reverted to clock too. Have updated screenshots.

**Comment by JustinPinner** [comment]
Looking good :+1:

**Comment by paperboyo** [comment]
Better typography + clock without the hole = win!
Q: “isn’t it too small now?”; A: “no, it was too big before”

**Pull request merged**
