### PR TITLE
AMP, meet Guardian Egyptian

### PR DESCRIPTION
**Pull request by zeftilldeath**
Added one cut of Guardian Egyptian Web to AMP (Regular). Also slightly tightened up the letter spacing on instances of Georgia that are bold, to make the visual contrast between the two typefaces slightly less jarring.

Have opted for using Egyptian Regular (When it should be a heavier weight) rather than Georgia in instances where colour or scale provide enough visual contrast.

Linked through from pasteup.guim.co.uk, lemme know if that's an issue. 

screen shot 2015-10-05 at 15 31 21

screen shot 2015-10-05 at 15 32 13

screen shot 2015-10-05 at 15 32 02

### CODE REVIEW

**Comment by stephanfowler** [comment]
Out of interest (because it might happen on Wednesday!), what happens to first paint when a font fails to load because of missing CORS permissions?

**Comment by davidrapson** [comment]
@stephanfowler You will get missing text for however long the browser timeout is and then it will fallback to the default. Most browsers is ~3s. Safari is 30s.

I thought I saw a good table of the different timeouts recently, but I can't find it. This contains a section with a decent overview https://dev.opera.com/articles/better-font-face/

**Comment by stephanfowler** [comment]
Hmm, thinking we need to be very careful here. Hard to test this until were on a Google domain on Wednesday.

**Comment by sndrs** [comment]
yeah this will result in a FOIT until the font arrives, which obviously if it's not white-listed it never will.

(@davidrapson – I think safari is 60s then give up regardless of what arrives?)

this also means on slow connection, even whitelisted, nothing will be readable until the fonts arrive. given the state of mobile caches and the environments this is designed to work under, i'm not sure the standard (extremely frustrating) way of declaring web fonts is going to work here...

**Comment by sndrs** [comment]
:-1: sorry @zeftilldeath :)

**Comment by davidrapson** [comment]
Yep, dunno why I said ~30s, even says 60s the in the link I mentioned.

**Comment by paperboyo** [comment]
There is that [INTERNAL RESOURCE](https://github.com/ampproject/amphtml/issues/136)

**Pull request closed without merging**
