### PR TITLE
Soulmates logo color fix

### PR DESCRIPTION
**Pull request by uplne**
Soulmates header have different html structure. I will look at it in the separate PR. If we can make it in sync with other components.

screen shot 2016-02-05 at 15 33 59

@regiskuckaertz

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
:+1: are you confident it won't break the whole site? (it's Friday)

**Comment by uplne** [comment]
I am not confident to release it in the same deploy with your changes

**Comment by regiskuckaertz** [comment]
:santa:

**Comment by uplne** [comment]
conan-titanic

**Comment by paperboyo** [comment]
Probably nothing we can do about it (the correct font file is not served), but that’s a horrible faux italic that is (“worth”).

Worth-y of a GIF:

faux

**Pull request merged**
