### PR TITLE
Liveblog playables: styling

### PR DESCRIPTION
**Pull request by stephanfowler**
- font 
- capilatisation

liveblog

### CODE REVIEW

**Comment by Pearson82** [comment]
Does this still hold up alright at narrow mobile view in serif ie. at 14px stil fitting enough characters per line, and lines of text in each block?

**Comment by Pearson82** [comment]
@stephanfowler

**Comment by johnduffell** [comment]
looks good :+1:

**Comment by paperboyo** [comment]
@stephanfowler Have you seen https://github.com/guardian/frontend/pull/9253#issuecomment-112370118? I love linking to myself...

**Comment by stephanfowler** [comment]
@paperboyo yeah I saw it and checked. Strangely, the font change seemed to fix it on local, but not on prod. Am looking into why.

**Comment by paperboyo** [comment]
Thanks, @stephanfowler! Strange irrespective if you mean next line marginally showing or a shadow around ellipsis... Why would a font matter...

**Pull request merged**
