### PR TITLE
Add to humans.txt

### PR DESCRIPTION
**Pull request by jbreckmckye**
Before I go!

### CODE REVIEW

**Comment by ScottPainterGNM** [comment]
Getting those cheeky commits in to beat Sam?


On Fri, 17 Jun 2016 at 14:53 Jimmy Breck-McKye <notifications@github.com>
wrote:

> Before I go!
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/guardian/frontend/pull/13328
> Commit Summary
>
>    - Ego commit
>
> File Changes
>
>    - *M* facia/public/humans.txt
>    <https://github.com/guardian/frontend/pull/13328/files#diff-0> (5)
>
> Patch Links:
>
>    - https://github.com/guardian/frontend/pull/13328.patch
>    - https://github.com/guardian/frontend/pull/13328.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/guardian/frontend/pull/13328>, or mute the thread
> <https://github.com/notifications/unsubscribe/ALXrTWUtwAeW2KDllWYQZJDDoURYMJ1nks5qMqbAgaJpZM4I4YOl>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by rich-nguyen** [comment]
👍

**Comment by jbreckmckye** [comment]
@ScottPainterGNM - I just need one more...

**Comment by kenlim** [comment]
👍

**Comment by desbo** [comment]
👎

**Comment by gtrufitt** [comment]
file_000

**Pull request merged**
