### PR TITLE
Remove JsonImplicits.scala

### PR DESCRIPTION
**Pull request by ioannakok**
This file was introduced in this PR: https://github.com/guardian/frontend/pull/8059
It became unecessary after this PR: https://github.com/guardian/frontend/pull/10585

Co-authored-by: Roberto Tyley <roberto.tyley@guardian.co.uk>

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [x] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [x] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/main/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by jlieb10 — APPROVED** [review]
nice

**Comment by janua** [comment]
Oopsie! 
Might it be worth adding `-Xlint:unused` to the compiler flags for `frontend`? This would have been picked up immediately if that was in use. Although I'm not even sure if it existed back then 😅

**Review by rtyley — APPROVED** [review]
The JsonImplicits was in use for about 9 months, and then remained unused in the Frontend codebase for ~7 years! See 
https://github.com/guardian/frontend/pull/10585#discussion_r935679134

**Comment by rtyley** [comment]
> Might it be worth adding `-Xlint:unused` to the compiler flags for `frontend`?

Ooh, good tip, we should look into that! Thanks @janua !

**Pull request merged**
