### PR TITLE
Revert "Add trackAd module"

### PR DESCRIPTION
**Pull request by regiskuckaertz**
The Promise in article-body-adverts will not resolve until the inline slot is loaded. Problem is, dfp waits for it before making any ad call... A deadlock.

### CODE REVIEW

**Comment by uplne** [comment]
:+1:

**Comment by uplne** [comment]
giphy 2

**Comment by OliverJAsh** [comment]
Hope this makes it back in? :+1:

**Comment by regiskuckaertz** [comment]
@OliverJAsh yeah I'll do that as soon as I have time. deadlocks are always a fun riddle :)

**Pull request merged**
