### PR TITLE
Use https for old interactives without a body

### PR DESCRIPTION
**Pull request by mchv**
2 years ago @theefer [added some logic to use a prefixed host](https://github.com/guardian/frontend/pull/2935/files) for some interactives. I don't know which interactives go to this code path but the host should be updated. However before merging I need to check that this is not breaking them.

@gklopper @JustinPinner do you know any interactives (or way to find them) I could test with those changes?

### CODE REVIEW

**Comment by mchv** [comment]
Interestingly [the test](https://github.com/guardian/frontend/blob/3ef8f2c450dc0b2896b2cd2dfad79f9f096db237/common/test/assets/javascripts/spec/Interactive.spec.js) which was used to test this feature does not seem to on `master`.

**Comment by JustinPinner** [comment]
It looks like all interactives that are handled by next-gen pass through this code. In terms of testing, I can send you a list of URLs that _shouldn't_ pass through here if that helps?

**Comment by johnduffell** [comment]
@mchv this one's getting on a bit, are you waiting for anything?

**Comment by mchv** [comment]
@johnduffell yes we discussed with @JustinPinner and we think this is only used for r2 interactives that have been archived. So we should only apply the changes when those r2 archives will have been migrated as a last step to make them work.

**Comment by humaislam** [comment]
@mchv @JustinPinner hello - what shall we do with this PR?

**Comment by sndrs** [comment]
47 days…

**Comment by mchv** [comment]
@humaislam @sndrs @JustinPinner I think we simply wait r2 interactives to be ready and when they are we merge. If we don't plan to migrate them, or or don't mind to break those we care while migrating we could merge now.

**Comment by johnduffell** [comment]
any updates? close and reopen when ready?

**Pull request closed without merging**
