### PR TITLE
Review kicker

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Cleans up the kicker stuff by getting rid of the unruly pseudo-elements, favouring a good old border to achieve the same effect. Had to decrease the top padding but Ben's happy with that to go ahead.

### CODE REVIEW

**Review by GHaberis — APPROVED** [review]
Simpler and hopefully more resilient, looks good 👍

**Comment by sndrs** [comment]
wonder if we can use a pseudo element or maybe border image gradient to align the border with the text bottom?

**Comment by sndrs** [comment]
yeah looks like something like `border-image: linear-gradient(to top, transparent, transparent .25em, $lines .25em) 1;` might do that?

**Comment by regiskuckaertz** [comment]
oh nice! I always forget about `border-image`. Thanks!

**Comment by sndrs** [comment]
think it's the first time i've ever typed it out!

**Pull request merged**
