### PR TITLE
Remove flow

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

removes flow from frontend, as part 1 of [the process of swapping flow out for typescript](https://trello.com/c/Qr86e5k7/1225-epic-convert-frontend-from-flow-to-typescript):

**1. Remove flow and convert flow-typed `*.js` to vanilla, untyped `*.js`.**

- remove all flow type checking
- archive existing flow-typed `*.js` files in `static/src/javascripts.flow.archive` to preserve existing type information for future reference (in stage 4)
- strip all flow type syntax from `static/src/javascripts`

_Next steps_
2. Convert flow declaration files and the 4 current `**/types.js` files to `.d.ts` files.
3. Add support for `*.ts` files.
4. Require converting `.js` files to `.ts` on first edit, adding a commit hook disallowing editing/adding `.js` files.

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No

## What is the value of this and can you measure success?

- A lot of the flow types are no use. Many have been added to keep flow quiet (`any`) rather than add type safety.
- This is also the last codebase at the guardian that uses it (rather than Typescript), so anything we install from elsewhere in the organisation does not get type safety in this project. 
- The plan is convert files to typescript as-needed. Once the 4 stages are complete, developers will need to change any `*.js` files they work on to `*.ts`, using the flow archive as a guide, where useful.
  - New files in `static/src/javascripts` will also need to be `*.ts`, not `*.js`.
  - Any files that don't get changed will stay as `*.js`, i.e. in their current state

## Reviewing notes

I know this is a BIG pr, sorry...

In the hope it makes this easier to review, most of the changes were automated and are contained in the following 2 commits:

- create archive of flow-typed `static/src/javascripts` 6165f83
  - i.e. copy files to `static/src/javascripts.flow.archive` and add explainer header comment
- remove flow types from `static/src/javascripts` 60a4950 (using [flow-remove-types](https://flow.org/en/docs/tools/flow-remove-types/))

The following commits contain manual changes:

- remove flow and all flow checks fb63342
- remove flow-typed definitions 1fc5758
- prepare eslint for converted files c54b4d7
- remove unused type imports 2423595
- post conversion lint fixes b70dd51

It _should_ be possible to review changes by commit...

_Depends on #23378 for the build to pass._

### CODE REVIEW

**Review by mxdvl — APPROVED** [review]
Looking at commits for manual edits, it looks like a good first step.

**Review by shtukas — APPROVED** [review]

**Comment by mchv** [comment]
💎

**Comment by gustavpursche** [comment]
@sndrs All that precious work : 😭 Excited to see what comes next too.

♥️

**Comment by SiAdcock** [comment]
Amazing effort @sndrs! 💯 🥇  Brings back memories of the `make es6` days 😭

**Pull request merged**
