### PR TITLE
Flagship: scrub like there's no tomorrow

### PR DESCRIPTION
**Pull request by regiskuckaertz**
## What does this change?

- Fix a missing border in the headline
- Remove volume controls on Android
- Reduce vertical white-space on mobile
- Make the component initialisation more react-idiomatic
- Update current time on seek/scrub
- Scrubbing works perfectly now ✨

### CODE REVIEW

**Review by tomrf1 — APPROVED** [review]
looks good!

**Comment by ajwl** [comment]
Yes - seems to be all working. Only issue is a usability one with being able to grab a small 4px wide bar. But perhaps we can do a usability cleanup with Nancy after launch

**Review by ajwl — APPROVED** [review]

**Comment by regiskuckaertz** [comment]
@ajwl yes, the whole player area is used to track the mouse cursor when grabbing, but as soon as you leave it (e.g. 1px above the track), then it does not work anymore. I probably should handle that with `onmouseleave`.

I agree for the 4px bar, on desktop it's easy for me to `scale` it horizontally, but it is just a visual cue. Ideally there should be an invisible padding around it, so that using your thumb would not be cumbersome.

**Comment by regiskuckaertz** [comment]
There is also the matter of accessibility, but we have done nothing on that front yet.

**Pull request merged**
