### PR TITLE
make sure preload is set appropriately

### PR DESCRIPTION
**Pull request by jamesgorrie**
# Video preload strategy

Make sure we never preload on unenhanced mode, preload metadata universally across video placings on enhanced, and never preload content until we know have the `gimmeallthedataIdontcare` client hint (thanks @paperboyo).
## What is the value of this and can you measure success?

People stop asking us not to download content without their explicit decision.

@akash1810 @sndrs 
## 

_Does this PR meet the [contributing guidelines](https://github.com/guardian/frontend/blob/issue_pr_templates/.github/CONTRIBUTING.md#submission)?_

### CODE REVIEW

**Comment by jamespamplin** [comment]
:+1: code looks good to me

**Comment by akash1810** [comment]
branch needs to be brought up to date with master, but :+1:

**Comment by sndrs** [comment]
:+1: great! was never clear why we did

**Comment by johnduffell** [comment]
good idea! actually makes sense a lot more sense to do it that way :+1:

**Pull request merged**
