### PR TITLE
dont auto focus search

### PR DESCRIPTION
**Pull request by AWare**
## What does this change?
No longer auto focuses the search box's input field, to ensure the google custom search branding is shown- and fixes the padding.
## Screenshots
image
image

## What is the value of this and can you measure success?
🐝bugfix🐞
### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [X] No
- [ ] Yes (please give details)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [X] [Navigable with keyboard]*(https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

* This introduces one more interaction to use the custom search in chrome. I couldn't use custom search with the keyboard only in firefox at all.

### Tested

- [X] Locally
- [x] On CODE (optional)

### CODE REVIEW

**Review by NataliaLKB — APPROVED** [review]
LGTM 🚢

**Comment by paperboyo** [comment]
More clicks: :sadpanda:. Compliance: loaded panda. Padding: :happypanda:.

**Comment by SiAdcock** [comment]
Have Google stipulated that the branding must be visible and there’s nowhere else it can go? This seems like a loss for accessibility to me.

**Comment by AWare** [comment]
Aside from major redesign and rework on this component, I'm not sure how to make it obviously a google product and to retain auto-focus. 

And this whole thing is a great case of why to not use placeholder elements.

**Comment by paperboyo** [comment]
> Aside from major redesign and rework on this component

That would be getting rid of this worst-search-on-earth and introducing what we used to have in R2: a custom search with filters by contributors, tones, content types, dates etc rendering results as a dynamic front.

But before this, maybe we could just move the logo and whatever txt we are required to have to the right, reduce opacity and make it stay there even when the field is focussed/text being entered?

**Comment by AWare** [comment]
Let's pick it up when you get back.

**Pull request merged**
