### PR TITLE
Facia tool visible stories

### PR DESCRIPTION
**Pull request by piuccio**
Show how many stories are visible for a container.

It looks like this

visible stories

@robertberry I've cherry-picked your commits and rebased on latest master

### CODE REVIEW

**Comment by robertberry** [comment]
Neat!

**Comment by stephanfowler** [comment]
:+1: really nice. Test with some real data...

**Comment by piuccio** [comment]
topstories

Here is `au` front, it has groups. Numbers match the articles displayed in facia.

**Comment by stephanfowler** [comment]
The editors will love this.

On 5 January 2015 at 18:13, Fabio Crisci <notifications@github.com> wrote:

> [image: topstories]
> <https://cloud.githubusercontent.com/assets/680284/5617395/447feb1a-9506-11e4-97bc-15f2a155885a.png>
>
> Here is au front, it has groups. Numbers match the articles displayed in
> facia.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/7655#issuecomment-68749669>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by crifmulholland** [comment]
This is nice - I like the interface for it.

As an alternative / enhancement to this do you think we could look at using the colour as and indication of click through rates on items... this would / *should* display where the visible point is on the page as a by-product. E.g. the more opaque the colour, the higher the click through. We would then see the colours fading as you go down and see the jump in transparency at the visible point. 

Lets have a chat as this probably isn't the place to discuss!

**Comment by piuccio** [comment]
Bars are now green, less in your face

green bars

**Comment by robertberry** [comment]
That's much nicer

**Comment by stephanfowler** [comment]
:+1:

**Comment by robertberry** [comment]
AWESOME SHIP IT :dancer:

**Pull request merged**
