### PR TITLE
Add channel to Omniture media event props

### PR DESCRIPTION
**Pull request by robertberry-zz**
CC @mkopka @gklopper

### CODE REVIEW

**Comment by johnduffell** [comment]
what does this mean! :confused:

**Comment by robertberry** [comment]
Only those versed in the arcane lore of Omniture know that. I am just a humble acolyte, attending the data priests

**Comment by mkopka** [comment]
In this omniture media library
*https://github.com/guardian/frontend/blob/a7b51fa5b7216e91386b100cb16920a5295b73a3/static/src/javascripts/projects/common/modules/analytics/omnitureMedia.js
<https://github.com/guardian/frontend/blob/a7b51fa5b7216e91386b100cb16920a5295b73a3/static/src/javascripts/projects/common/modules/analytics/omnitureMedia.js>*

theres this line of code

.linkTrackVars = 'events,eVar11,prop41,eVar43,prop43,eVar44,prop44,prop9';

This defines the omniture varaibles that get passed through with all of our
video milestones events.

We would like the 'channel' variable added to this line please

On 27 May 2015 at 11:04, Rob Berry <notifications@github.com> wrote:

> Only those versed in the arcane lore of Omniture know that. I am just a
> humble acolyte, attending the data priests
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9276#issuecomment-105850394>.
>



-- 
Thanks - Matt


(L)  0203 35 (33044)
(M) 07508 589 888

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by robertberry** [comment]
This does that @mkopka

**Comment by johnduffell** [comment]
now I am wise :pray:

**Comment by mkopka** [comment]
wiser

On 27 May 2015 at 11:22, John Duffell <notifications@github.com> wrote:

> now I am wise [image: :pray:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9276#issuecomment-105854511>.
>



-- 
Thanks - Matt


(L)  0203 35 (33044)
(M) 07508 589 888

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by robertberry** [comment]
why does GitHub not have a like button for comments?

**Comment by johnduffell** [comment]
if I was truly wise, I'd be able to answer that question :cry:

**Pull request merged**
