### PR TITLE
Media tone icon bug in *drumroll* IE

### PR DESCRIPTION
**Pull request by zeftilldeath**
@blongden73 It's your fault for spotting this bug so you have to plus one it.

This is how cool it looked:
screen shot 2016-09-02 at 16 22 42

### CODE REVIEW

**Comment by gtrufitt** [comment]
Can we have an after screenshot please Zef?

**Comment by gtrufitt** [comment]
😀

**Comment by gtrufitt** [comment]
👍

**Comment by zeftilldeath** [comment]
@gtrufitt 
screen shot 2016-09-02 at 16 28 29

**Comment by gtrufitt** [comment]
brilliant

**Pull request merged**
