### PR TITLE
extend switch for quiz score service

### PR DESCRIPTION
**Pull request by johnduffell**
the tools team will take this over by the end of the quarter

### CODE REVIEW

**Comment by uplne** [comment]
:+1 but it will haunt you again in the future

**Comment by gklopper** [comment]
>the tools team will take this over by the end of the quarter

:laughing: :laughing: :laughing: :scream: 

:+1:

**Comment by johnduffell** [comment]
is that a real thumbs up or are you teasing me @uplne ? ;)

**Comment by rich-nguyen** [comment]
Are we unable to delete this feature? @johnduffell 

I'm happy to do this if you want.

**Comment by gklopper** [comment]
I agreed with the tools team we will keep it running to end of the quarter.

**Pull request merged**
