### PR TITLE
Add garnet styles for articles

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

- adds a garnett version of `head.content` for use in articles
- duplicates existing partials (where relevant) in `module/content-garnett` ready for editing/deleting garnett-only styles (no partial is new CSS, just content of duplicated partials from pre-garnett stuff)
- doesn't add classes to articles themselves, because I need some help with that

### CODE REVIEW

**Comment by SiAdcock** [comment]
Good start! To help the reviewer, can you call out the substantive changes that require reviewing? 😄

**Comment by sndrs** [comment]
is that any more helpful?

**Comment by SiAdcock** [comment]
@sndrs very much, thanks!

**Review by SiAdcock — APPROVED** [review]
Lovely

**Pull request merged**
