### PR TITLE
Move Liveblog block styles into the head

### PR DESCRIPTION
**Pull request by GHaberis**
## What does this change?

Styles for below the fold Liveblog elements (such as blocks) were previously loaded in asynchronously in content.css. Users can however follow links directly to below the fold blocks, and if they do so they'd see a significant jump as the styles are applied to blocks. This branch moves the liveblog block element styles into the head so they are applied earlier. There's still a jump but it's an improvement.   

## What is the value of this and can you measure success?

Styles applied earlier to liveblog blocks, better user experience.

## Does this affect other platforms - Amp, Apps, etc?

No

## Screenshots

Before...

blog-before

After...

blog-after

## Tested in CODE?

Yes

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]
giphy-tumblr

👍

**Comment by sndrs** [comment]
do you know how much weight this adds to the head? 

my gut says we have to accept some things require the second CSS load (mainly below the fold), and i wonder how often these blocks are actually seen by people to repaint (i.e. count as above the fold)?

**Comment by GHaberis** [comment]
@sndrs I'll get this on CODE today to get some numbers out, hopefully I can get enough out to let us weigh up the costs/benefits.

**Comment by GHaberis** [comment]
@sndrs I revisited this and ran a comparison on PROD and CODE on the same liveblog at the same point in time and the headline stats are below.

**PROD**
First meaningful paint from lighthouse: 1,080 ms 
Consistently Interactive from lighthouse: 11,780 ms
Document weight from dev tools: 89.5 KB

**CODE**
First meaningful paint from lighthouse: 1,060 ms
Consistently Interactive from lighthouse: 9,910 ms
Document weight from dev tools: 97.5 KB

** Document weight on CODE consistently appears to be 6K more than PROD even when comparing like-for-like builds.

**Comment by gustavpursche** [comment]
@GHaberis Is this something you still work on?

**Comment by GHaberis** [comment]
@gustavpursche I was actually discussing with @SiAdcock yesterday whether to close this. We decided I'd get some comparisons off Code (using master) and Code (using this branch) to account for the discrepancies between Code and Prod. I'll do this at some point in the next day or two, so consider it alive for now.

**Comment by GHaberis** [comment]
Back from the grave.. time to resurrect or finally kill this PR. 

Using the following [blog](https://www.theguardian.com/politics/blog/live/2017/sep/20/keeping-1-public-sector-pay-cap-could-damage-public-services-says-ifs-politics-live) I've ran some tests on code...

**master**
First meaningful paint from lighthouse: 1,060 ms
Consistently Interactive from lighthouse: 11,550 ms
Document weight from dev tools: 527 KB

**gh-faster-liveblog-styles**
First meaningful paint from lighthouse: 930 ms
Consistently Interactive from lighthouse: 10970 ms
Document weight from dev tools: 543 kb

Updated screen grabs below. @SiAdcock the jump in styles is more noticeable in these grabs as they are both taken from code. I actually believe the difference between the before/after screen grabs before was less pronounced as they were taken from my local build which doesn't actually add the styles in the head :sweat_smile: ... :weary:

Before...

blog-old

After...

blog-new

**Review by SiAdcock — APPROVED** [review]
Looks good to me, @GHaberis! The FOUC is less pronounced and the timings slightly better. Page weight is only a secondary concern after time to first paint / interactive, so this change is 🥇 👌  💎

**Review by gu-stav — APPROVED** [review]
What @SiAdcock ⬆️  said!

**Pull request merged**
