### PR TITLE
Force protocol relative on older IE.

### PR DESCRIPTION
**Pull request by gklopper**
http://blogs.msdn.com/b/ieinternals/archive/2010/05/13/xdomainrequest-restrictions-limitations-and-workarounds.aspx

### CODE REVIEW

**Comment by OliverJAsh** [comment]
I had given this patch to @janua because I was too lazy… oh well :smile:

**Comment by OliverJAsh** [comment]
:+1:

**Comment by sndrs** [comment]
:+1:

**Comment by janua** [comment]
:+1:

**Comment by gklopper** [comment]
@OliverJAsh yeah, @janua then passed it on to me...

**Comment by OliverJAsh** [comment]
Did this fix the problem? Can you confirm by looking at the error in sentry?

**Comment by janua** [comment]
Did we get the error in sentry? I never verified that. But I will check now if this has fixed it in IE 9.

**Comment by janua** [comment]
Comments now seem to be loading in IE 9 :+1:

**Comment by OliverJAsh** [comment]
@janua That's good. I want to see the error dropping in Sentry though.

**Comment by OliverJAsh** [comment]
Here we go: https://app.getsentry.com/the-guardian/client-side-prod/group/49311746/events/3708860297/

For some reason Sentry thinks the error occured in facia.js, but if you look at the stacktrace it was core.js. The error message and browser stats make me believe this was the error. You can see the drop from our release :smile: 

When we fix errors like this we should make sure to track them in Sentry, and mark them as resolved afterwards.

**Comment by janua** [comment]
Yeah true (about marking as resolved). Don't they do that naturally anyway?

I think sentry is seriously useful, I'm always in there floating around now. Yes, you can float around a web app before you ask.

**Pull request merged**
