### PR TITLE
Reduce email size

### PR DESCRIPTION
**Pull request by joelochlann**
## What does this change?
Ditch the Zurb Foundation For Emails framework for front-generated emails (same to follow for article emails in a separate PR, at which point we can remove a LOT of dead code). This has been replaced with handcrafted styles plus a few fragments based on the Zurb code.

## What is the value of this and can you measure success?

- Email size reduced from **155.61K** to **77.03K** locally for [this example](https://www.theguardian.com/email/joe-test) (**50% reduction**). All emails should be reduced by roughly the same proportion (the more cards, the greater the reduction is likely to be)
- Longstanding rendering bugs fixed (particularly in Outlook)
- Moving towards using exclusively classes as selectors (still a bit more to do on that) which may eventually allows us to stop inlining styles altogether for Gmail

## Does this affect other platforms - Amp, Apps, etc?
Just email

### Outlook Before
picture 497

### Outlook After
picture 498

## Tested in CODE?
No

@guardian/dotcom-platform

### CODE REVIEW

**Comment by joelochlann** [comment]
also @superfrank cos he loves this stuff

**Comment by joelochlann** [comment]
Another headline: Guardian Today UK has gone from **221.37K** to **87.87KB**, i.e. a **60%** reduction

**Comment by joelochlann** [comment]
which takes it well under the 102KB limit imposed by Gmail

**Comment by superfrank** [comment]
As always,  you've knocked it out of the park

**Pull request merged**
