### PR TITLE
Revert "Pass event emitter to ophan so it can use throttledScroll"

### PR DESCRIPTION
**Pull request by philwills**
Reverts guardian/frontend#13525

### CODE REVIEW

**Comment by philwills** [comment]
This doesn't look good:

https://dashboard.ophan.co.uk/graph/breakdown?device=Personal+computer&device=Smartphone&device=Tablet&by=browser

**Comment by dominickendrick** [comment]
👍

**Comment by philwills** [comment]
Actually, on closer inspection, not sure that's the issue. Digging a bit more.

**Comment by philwills** [comment]
False alarm, it weren't me, guv'.

**Pull request closed without merging**
