### PR TITLE
Add isHeroic flag to JS config

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

Add the `isHeroic` flag to the JS config map, for debugging purposes
## Request for comment

@NataliaLKB @sndrs

### CODE REVIEW

**Comment by NataliaLKB** [comment]
👍

**Comment by NataliaLKB** [comment]
Hey @SiAdcock ! Make sure you wait for the tests to pass in Teamcity before you merge. The tests are still running: http://teamcity.gu-web.net:8111/viewLog.html?buildId=13026&tab=buildResultsDiv&buildTypeId=dotcom_pullrequests

**Comment by SiAdcock** [comment]
Argh, sorry!

**Comment by NataliaLKB** [comment]
No worries :). Even though it is unlikely this PR would cause the tests to fail, it is still good practise

**Comment by SiAdcock** [comment]
Wouldn't you know it, it looks like they have failed. One of the Switches has expired. Is this going to cause problems further down the pipeline?

**Comment by NataliaLKB** [comment]
In this case the answer would have been to rebase/merge with Master. Just monitor the master tests. If the pass then you are all good.

**Comment by SiAdcock** [comment]
Makes sense. Thanks for your help @NataliaLKB , I'll continue to keep an eye on them

**Pull request merged**
