### PR TITLE
ES6: Convert modules/discussion/comments

### PR DESCRIPTION
**Pull request by gu-stav**
## What does this change?

Converts `modules/discussion/comments` to ES6. [A previous PR](https://github.com/guardian/frontend/pull/17668) was reverted because it broke `pickComment()`.

This PR is basically a clone of the previous one, but improves the type definitions and tries to fix the problem.

### CODE REVIEW

**Comment by gustavpursche** [comment]
@SiAdcock @GHaberis This is ready to go, I believe. You don't have to go through a full review again, because most of it was copied over (see description). Only the last 4 commits differ ...

**Comment by SiAdcock** [comment]
The changes look good. Have you been able to recreate the issue on CODE or locally, to make sure it is fixed?

**Comment by gustavpursche** [comment]
@SiAdcock Calumn gave me moderator permissions on CODE today, so I was able to test the functionality locally.

**Review by GHaberis — APPROVED** [review]
Looks good, makes sense 👍

**Pull request merged**
