### PR TITLE
Remove expired bounce test

### PR DESCRIPTION
**Pull request by rich-nguyen**
This switch has now expired. We should still be measuring this, we need more detail about the time when the page view has registered.

### CODE REVIEW

**Comment by JustinPinner** [comment]
Code changes look :+1: How will we make sure to revisit this in more / better detail?

**Comment by rich-nguyen** [comment]
@sndrs is currently looking at ways to implement good omniture reporting without embedding the script. So we'll need to know about bounce rate as a related metric of this work

**Comment by NataliaLKB** [comment]
:+1: :ship:

**Comment by gklopper** [comment]
thanks Rich

**Pull request merged**
