### PR TITLE
Content API upgrade (7.12)

### PR DESCRIPTION
**Pull request by OliverJAsh**
This is needed so we can consume content atoms so we can do quizzes.

/cc @rich-nguyen

### CODE REVIEW

**Comment by piuccio** [comment]
:heart_eyes:

**Comment by jennysivapalan** [comment]
A big diff but the changes look relatively sane to me :+1: :up: :a:

**Comment by johnduffell** [comment]
the proof of the coding is in the testing I suspect :+1:

**Comment by piuccio** [comment]
just to scare you with random unrelated facts. Last time I tried to upgrade CAPI in fronts tool, live blog started appearing as dead. Once you start testing this it might be a good idea to keep an eye on live blogs as well, just in case...

**Comment by johnduffell** [comment]
@piuccio if this PR doesn't break live blogs, mine will :fearful:

**Pull request merged**
