### PR TITLE
Revert "Merge branch 'oja-revert-lodash-v3'"

### PR DESCRIPTION
**Pull request by OliverJAsh**
This reverts commit ec8062450479426212197e5900f04c476e8c6fd4, reversing
changes made to c5d1360a6ad271173e48b65e201e7adbe25e64d6.

To do:
- [x] Test with ads (when they work in DEV again…)
- [x] Resolve errors captured by Sentry at https://app.getsentry.com/the-guardian/client-side-prod/?sort=freq&df=2015-07-21&tt=&cursor=1437478935%3A0%3A0&tf=11%3A00+AM&dt=&date_type=first_seen&df=2015-07-21&tf=10%3A00+AM&dt=&tt=&date_type=first_seen, if different from above

### CODE REVIEW

**Comment by sndrs** [comment]
I'd get QA to give this a thorough tire kick, across browsers

**Comment by piuccio** [comment]
10k lines added? Are you sure?

**Comment by OliverJAsh** [comment]
@piuccio That's because with Bower we have to commit our dependencies. :unamused:

**Comment by piuccio** [comment]
looks better after you commit few seconds ago. At least now there are 7k lines removed...

**Comment by piuccio** [comment]
Although I don't see the point of updating our dependencies before we get rid of bower.

**Comment by OliverJAsh** [comment]
Yep, forgot to purge the old, now unused, dependency files.

On Tue, 21 Jul 2015 at 15:45 Fabio Crisci <notifications@github.com> wrote:

> looks better after you commit few seconds ago. At least now there are 7k
> lines removed...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9882#issuecomment-123350483>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by OliverJAsh** [comment]
We don't know when we will be ready to switch off Bower.

On Tue, 21 Jul 2015 at 15:45 Fabio Crisci <notifications@github.com> wrote:

> Although I don't see the point of updating our dependencies before we get
> rid of bower.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9882#issuecomment-123350978>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by piuccio** [comment]
and what's the point of updating lodash?

**Comment by OliverJAsh** [comment]
As detailed in https://github.com/guardian/frontend/pull/9863, it might fix one of our most frequently occuring errors in Sentry.

It's also 20-40% faster.

See https://github.com/lodash/lodash/releases/tag/3.0.0 for more.

**Comment by OliverJAsh** [comment]
This is ready for QA time!

**Comment by sndrs** [comment]
what's the status of this?

**Comment by OliverJAsh** [comment]
I haven't had the chance to do some more testing with it. I'll ask the QAs if they can spend some time on it for us this week.

**Comment by ScottPainterGNM** [comment]
@OliverJAsh ran through some light testing on Chrome and Firefox, I have shared the issues doc with you

**Comment by OliverJAsh** [comment]
Nice one!

On Mon, 10 Aug 2015 at 13:54 Scott Painter <notifications@github.com> wrote:

> @OliverJAsh <https://github.com/OliverJAsh> ran through some light
> testing on Chrome and Firefox, I have shared the issues doc with you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/9882#issuecomment-129431323>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by OliverJAsh** [comment]
I won't have the time to do this for awhile, but feel free to pick it up!

**Comment by sndrs** [comment]
:crying_cat_face:

**Pull request closed without merging**
