### PR TITLE
Fix unbounded parallelism in Facia Press

### PR DESCRIPTION
**Pull request by robertberry-zz**
I noticed this on hack day. Press is supposed to serially process messages but in reality it pulls off as much as possible as quickly as possible, which probably means it has more errors than it ought to.

### CODE REVIEW

**Comment by robertberry** [comment]
CC @stephanfowler @janua

**Comment by janua** [comment]
`FaciaPress` doesn't get many errors.

Even though I see what you did with the `flatMap`, I can't see how this fixes it. I don't think there is anything to fix, it looks serial to me.

Aaand I see it now.

:+1:

**Comment by johnduffell** [comment]
cool!! :+1: flatmap-tastic!

**Comment by janua** [comment]
@johnduffell Yes true. Funny thing would be it may have gotten worse if the boxes became bigger.

We have our own custom execution context for `facia-press`.

It's currently:

```
      front-press = {
        fork-join-executor {
          parallelism-factor = 1.0
          parallelism-max = 4
        }
      }
```

**Comment by robertberry** [comment]
@johnduffell @janua Not exactly true, as almost everything it's doing is IO, not CPU. IO is event-based, so essentially unbounded, meaning we're pummelling CAPI with requests, which is more likely to cause one of them to fail. Then we put the thing back on the queue and pull it off again and send another burst and fail, etc., etc.

**Comment by janua** [comment]
Well it also depends on the type of dispatcher underneath. The default is `fork-join` I believe, which would mean it is event based. You can make work thread bound!

**Pull request merged**
