### PR TITLE
Remove server side test of Liveblogs

### PR DESCRIPTION
**Pull request by nitro-marky**
## What does this change?

[Based on this card](https://trello.com/c/FFJQV9Yo/354-remove-server-side-test-for-dcr-liveblogs)

It removes the server side testing of Liveblogs to allow DCR to run tests independently of Frontend. 

This means adding `?dcr` and `?dcr=false` flags to the end of the liveblog URL.

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by DavidLawes — APPROVED** [review]
Nice! 👍

**Review by idrise — APPROVED** [review]
Nice one!

**Comment by nitro-marky** [comment]
[remove server side test for DCR liveblogs](https://trello.com/c/FFJQV9Yo/354-remove-server-side-test-for-dcr-liveblogs)

**Comment by nitro-marky** [comment]
Closing as not needed

**Pull request closed without merging**
