### PR TITLE
Fix broken links to builds from radiator

### PR DESCRIPTION
**Pull request by kelvin-chappell**
Links from radiator to riff-raff builds seem to have got broken in #13864 

/cc @piuccio

### CODE REVIEW

**Comment by piuccio** [comment]
funny

`target` is a `ul`
`link` is a `a`
`li` is a `li`

The generated markup is
```html
<ul>
   <a><li></li></a>
   <a><li></li></a>
</ul>
```

which feels wrong, but if that works 👍

**Comment by gtrufitt** [comment]
It'll work but it's not valid, do with that what you will :)

**Comment by kelvin-chappell** [comment]
I see what you mean.  I think the problem is the clickable area is empty and therefore unclickable.  I'll see if I can make it valid and working.

**Comment by gtrufitt** [comment]
Not entirely sure what is happening, but could you just do ` link.innerHTML = nameAbbreviation + ' ' + d.build;` and append that to the li instead?

**Comment by kelvin-chappell** [comment]
@gtrufitt I've taken your advice

**Pull request merged**
