### PR TITLE
Match Nav endpoint for DCR

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What does this change?
Adds a DCR (json only) version for the `match-nav` endpoint

http://localhost:9000/football/api/match-nav/2020/03/11/26305/9.json?page=football%2F2020%2Fmar%2F11%2Fliverpool-atlletico-madrid-champions-league-last-16-second-leg-match-report&dcr returns:

```typescript
{
	homeTeam: {
		name: "Liverpool",
		id: "9",
		score: 2,
		crest: "https://sport.guim.co.uk/football/crests/120/9.png",
		scorers: [
			"Georginio Wijnaldum 43",
			"Roberto Firmino 94"
		]
	},
	isResult: true,
	awayTeam: {
		name: "Atlético",
		id: "26305",
		score: 3,
		crest: "https://sport.guim.co.uk/football/crests/120/26305.png",
		scorers: [
			"Marcos Llorente 97",
			"Marcos Llorente 105 +0:02",
			"Alvaro Morata 120 +0:16"
		]
	},
	id: "4188140",
	refreshStatus: true,
	competition: {
		fullName: "Champions League"
	},
	isLive: false,
	venue: "Anfield",
	comments: "Club Atletico de Madrid win 4-2 on aggregate"
}
```
Screenshot 2020-05-20 at 09 26 38

## Why?
We want to support Match Reports in DCR. To do this we need to render the Match Nav component at the top of the page. On frontend this uses a special endpoint that returns the html to put in the page. For DCR, we're taking the approach of the api returning json and using react to render it to html. For this we need an endpoint that gives us the data we need in json format.

### CODE REVIEW

**Comment by oliverlloyd** [comment]
[JSON endpoint for match nav](https://trello.com/c/4M0FzkZD/1685-json-endpoint-for-match-nav)

**Review by shtukas — COMMENTED** [review]
Look great. I would make a function to render the team structure (which is identical for both `homeTeam` and `awayTeam`) but other than that it's fine.

**Comment by oliverlloyd** [comment]
> Look great. I would make a function to render the team structure (which is identical for both `homeTeam` and `awayTeam`) but other than that it's fine.

Personally, I question abstractions like this. I thought I'd take this chance to talk about why, hope you don't mind, it's not a rant, more just a way to put this down for posterity!

I'm a fan of thinking twice before extracting repeated code and perhaps accepting the repetition. I realise this approach is contrary to the generally accepted opinion (which is that repeated code should be moved into functions - DRY) but in my experience this can make future maintenance and overall readability harder.

It's not that I _always_ avoid abstractions. Instead I try to apply some vague rules:

1. Does the abstraction make the code more readable? Hugely subjective, but it's clear that in some cases abstracting something feels like a breath of fresh air and in other cases it can feel like the you suddenly don't know what's happening and need to open 5 different files to understand things

2. Will any of the use cases I'm abstracting change in future? Again, hard to know, but in the event they do, then the abstraction will make that work _much_ harder so should be avoided.

**Review by shtukas — APPROVED** [review]

**Comment by shtukas** [comment]
Perfect. And as promised I will refactor with types, feel free to merge though.

**Pull request merged**
