### PR TITLE
Fix broken call to CSS.supports on Safari 9

### PR DESCRIPTION
**Pull request by regiskuckaertz**
It turns out the [`window.CSS` interface](https://developer.mozilla.org/en-US/docs/Web/API/CSS) is an instance on Safari 9 and thus `supports` **must** be called using `CSS.supports`

### CODE REVIEW

**Review by scottp719 — APPROVED** [review]

**Review by gtrufitt — APPROVED** [review]
👍

**Comment by regiskuckaertz** [comment]
Expired switches 😩

**Comment by jfsoul** [comment]
@regiskuckaertz - just merged to master the switch extension 😞

**Comment by regiskuckaertz** [comment]
@jfsoul thank you 😃

**Pull request merged**
