### PR TITLE
Upgrade Zurb version

### PR DESCRIPTION
**Pull request by joelochlann**
## What does this change?
Upgrades the Zurb email CSS framework

## What is the value of this and can you measure success?
- Styles now in Sass rather than raw CSS
- Fixed a few visual bugs in some clients (see screenshots below)

Most importantly, though, it's reduced the weight of the email HTML, which we care about because Gmail clips messages at 102KB and requires you to click a "View full email" link to see the whole thing.

For instance, for the Guardian Today US:

Original size: **118KB**, New Size: **98KB**, Savings: **20KB (16.9%)**

This brings it under the 102KB limit imposed by Gmail - but only just. The nested tables and inlined styles which we need for compatibility with certain clients lead to very wasteful markup. More optimisation is needed before we can be sure that the email will never be clipped.

Main things to focus on next would be:
- Seeing if we can avoid inlining styles. Supposedly Gmail [now allows inline styles](https://www.emailonacid.com/blog/article/industry-news/gmail-announces-style-and-media-query-support-what-this-means-for-you), but there are a whole [load of conditions](https://www.emailonacid.com/blog/article/email-development/12_things_you_must_know_when_developing_for_gmail_and_gmail_mobile_apps) which the Zurb framework doesn't meet. So we'd need another significant refactor
- More aggressive HTML minification. @guardian/dotcom-platform may have some thoughts on how to achieve this. I know in prod we have some basic whitespace stripping from the `pagespeed` nginx module, but with https://kangax.github.io/html-minifier I was able to get these further reductions on https://www.theguardian.com/email/the-flyer (**95K -> 78K**)

## Does this affect other platforms - Amp, Apps, etc?
Just email rendering

### iPhone before
old-iphone-7

### iPhone after
picture 494

### Outlook before
old-outlook
old-outlook-bottom

### Outlook after
new-outlook
new-outlook-bottom

## Tested in CODE?
No

### CODE REVIEW

**Comment by superfrank** [comment]
Damn, Mr Outlook really knows how to put together a high quality rendering. I'm guessing there's no easy fix for this padding/margin issue: 
image

**Comment by jfsoul** [comment]
>I know in prod we have some basic whitespace stripping from the pagespeed nginx module, but with https://kangax.github.io/html-minifier I was able to get these further reductions on https://www.theguardian.com/email/the-flyer (95K -> 78K)

Might be interesting to see if we can update the settings we use in pagespeed to achieve similar.  I imagine they've probably released some new features since we last took a look at our settings as well.

**Review by davidfurey — APPROVED** [review]
Great work

**Comment by joelochlann** [comment]
Thanks @davidfurey. But I found a mistake in the Sass build process which leads to the email stylesheets being compiled twice, once remified and once not, and the two versions overwriting each other. I've got a fix but I'm not going to deploy til Monday

**Pull request merged**
