### PR TITLE
Garnett header case change

### PR DESCRIPTION
**Pull request by zeftilldeath**
It's almost as if nothing changed...

I've changed the case of everything in the new header to Sentence case (or title case where brand appropriate). Then hidden those changes from the test with css.

ALL capitalisation will now be missing from the secondary (in the new header test) - which isn't ideal but is the only clean way we can prepare for garnett. UK wasn't capitalised in the expanded menu anyway. 

screen shot 2017-12-28 at 15 54 25

screen shot 2017-12-28 at 15 54 42

Also deleted `_menu-user.scss` as we don't have user info in the expanded menu anymore.

### CODE REVIEW

**Comment by NataliaLKB** [comment]
Thanks for doing this! Two things:
1. This affects AMP too. Have you checked that? 
2. The tests are failing. Do you want help fixing them?

**Comment by zeftilldeath** [comment]
Let's pick this up next year 🛩  And I'll check AMP

**Comment by zeftilldeath** [comment]
Ok I've resolved the issue (Thanks @NataliaLKB) and now it should be good to go.

**Comment by NataliaLKB** [comment]
@zeftilldeath looks like there are still some tests failing. Let me know if you need help fixing these! This also looks like it needs to be rebased with master

**Review by NataliaLKB — APPROVED** [review]
👍

**Pull request merged**
