### PR TITLE
Added fullscreen icon to gallery images on interaction

### PR DESCRIPTION
**Pull request by zeftilldeath**
Picture the scene...

You're sat on your favourite office chair
You're 'surfing the web'
You're on the Guardian
You're in a gallery
You hover an image
You see a fullscreen icon

hover

Happy 🎄  @paperboyo

### CODE REVIEW

**Comment by paperboyo** [comment]
Woohoo! Thanks, @zeftilldeath! Yellow state is just a flash on click, then, before a Lightbox opens?

Happy 🎯!

**Comment by paperboyo** [comment]
Oh, I would love to know if there is a way to track the (possible) uplift in Lightbox opens on Gallery pages in GA after this goes out...

**Comment by zeftilldeath** [comment]
@paperboyo The yellow flash is when you hover your cursor directly over the icon

**Review by NataliaLKB — APPROVED** [review]
Looks good! 👍

**Pull request merged**
