### PR TITLE
Extending expired tests

### PR DESCRIPTION
**Pull request by NataliaLKB**
Extends some tests that have expired @akash1810 @jamesgorrie

### CODE REVIEW

**Comment by Calum-Campbell** [comment]
👍  Looks all good!

**Comment by jamesgorrie** [comment]
Apologies - I just got in to do those - but you beat me to it.

**Comment by NataliaLKB** [comment]
@jamesgorrie it happens!

**Comment by akash1810** [comment]
argh! sorry all was meant to take these out yesterday! 😢

**Pull request merged**
