### PR TITLE
Remove border between content and header

### PR DESCRIPTION
**Pull request by OliverJAsh**
I consulted @sammorrisdesign and @zeftilldeath on this one. They said we don't need it :smile: 
# Before

image
# After

image

### CODE REVIEW

**Comment by sammorrisdesign** [comment]
:+1:

**Comment by jbreckmckye** [comment]
Looks much better :+1:

**Comment by sammorrisdesign** [comment]
:+1:

**Comment by NataliaLKB** [comment]
:+1:

**Comment by sammorrisdesign** [comment]
:+1:

**Comment by zeftilldeath** [comment]
:+1:

**Comment by zeftilldeath** [comment]
:+1:

**Comment by zeftilldeath** [comment]
:+1:

**Comment by zeftilldeath** [comment]
:+1:

**Comment by zeftilldeath** [comment]
:+1:

**Comment by jbreckmckye** [comment]
:zap:

**Comment by OliverJAsh** [comment]
:+1:

**Comment by sammorrisdesign** [comment]
:+1:

**Pull request merged**
