### PR TITLE
Removes Skiing from UK, US, AU, INT editions navs

### PR DESCRIPTION
**Pull request by DiegoVazquezNanini**
@jfsoul @stephanfowler

### CODE REVIEW

**Comment by jfsoul** [comment]
Will this work for the tertiary (new) nav? cc: @NataliaLKB @gustavpursche

**Comment by DiegoVazquezNanini** [comment]
Thanks, @jfsoul I also removed it from the newNav. 
@NataliaLKB @gustavpursche should I also change it somewhere else?

**Comment by gustavpursche** [comment]
@jfsoul I don't see a problem in removing it for the new navigation.

screen shot 2017-04-28 at 13 29 33

**Review by NataliaLKB — APPROVED** [review]
lgtm

**Pull request merged**
