### PR TITLE
add entry for charlotte emms to humans.txt

### PR DESCRIPTION
**Pull request by cemms1**
## What does this change?

Added Charlotte Emms to `humans.txt` file only

### CODE REVIEW

**Review by bryophyta — APPROVED** [review]
Welcome! 🎉

**Review by oliverlloyd — APPROVED** [review]
Welcome 🎉 

(Also, so many PRs!)

**Review by mxdvl — APPROVED** [review]
Welcome! 🎉

**Review by OllysCoding — APPROVED** [review]
Welcome!

**Pull request merged**
