### PR TITLE
Amp list overflow element

### PR DESCRIPTION
**Pull request by NataliaLKB**
#### How it looks:

image
#### Behaviour:

If the amp-list component is within 600px, or 75%, from the top of the screen only one list item will show. This is to ensure that there is no page jank for the user. Alongside this an overflow element will appear. When clicked the overflow element disappears and the rest of the stories show. 

If the amp-list component isn't in view, it will resize as normal and no overflow element will show.

@zeftilldeath is currently working on improving the styling :raised_hands:

### CODE REVIEW

**Comment by zeftilldeath** [comment]
Latest:

screen shot 2016-01-19 at 16 05 27

**Comment by NataliaLKB** [comment]
Looks great @zeftilldeath

**Comment by stephanfowler** [comment]
:+1: like

**Comment by johnduffell** [comment]
code looks great! however one tiny point on the sytling @zeftilldeath - the button seems a bit unbalanced in terms of size, it seems to dominate the size of the picture
also in future maybe we can consider changing it to say "more headlines" or "more highlights" etc

**Comment by zeftilldeath** [comment]
@johnduffell Good point John have switched to medium sized button (screenshot now reflects this). Stefan had suggested that labeling too.

**Comment by johnduffell** [comment]
looks better now

**Comment by NataliaLKB** [comment]
@johnduffell though I agree that labelling like that would be clearer to the user, unfortunately there isn't a nice way of doing that with amp-list. The list itself doesn't know what stories are going to load before it happens, and so I would have to hard code the sections. 

It is best to leave it as is for now, as "More stories" is fine.

**Pull request merged**
