### PR TITLE
Add the lodash webpack plugin

### PR DESCRIPTION
**Pull request by AWare**
…might break things.

## What does this change?
This adds https://github.com/lodash/lodash-webpack-plugin to our webpack config. 
Which removes the following:
image
The tests still pass with this enabled, but this will need a lot more testing.

## Screenshots
image
=>
image

This drops total combined bundles size from 2.39  to 2.35

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Does this change update the version of CAPI we're using?

- [ ] No, all the existing database files are just fine
- [ ] Yes, and I have [re-run all the tests locally and checked in all the updated data/database/xyz files](https://github.com/guardian/frontend/blob/master/docs/03-dev-howtos/15-updating-test-database.md)

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested

- [ ] Locally
- [x] On CODE (optional)

### CODE REVIEW

**Comment by SiAdcock** [comment]
The impact on bundle size looks very promising, so thanks for putting this together @AWare! It will be important to get the balance right between:

1) bundle size
2) developer expectation
3) the effort required to fix the things that break when removing features

If we disable everything at once, debugging could be a nightmare, and it'll be harder to make a call on which features are worth keeping. It would be safer to remove features one by one, starting with those that have the greatest impact. We can then assess what breaks, and make a call on whether it's worth fixing. 

> The tests still pass with this enabled

Do the tests go through Webpack? I'm not so sure.

I'm a bit concerned that removing features that developers would expect to be there would produce unexpected results in production that won't be caught by unit tests.

Is there a way of notifying developers that certain features will not be available at runtime? Perhaps we can add unavailable features to this list of [restricted imports](https://github.com/guardian/frontend/blob/master/static/src/javascripts/.eslintrc.js#L44)

> but this will need a lot more testing

Too right! I was very methodical when I upgraded lodash to v4 (#20475) but still errors slipped through into production. Just something to be aware of.

**Comment by AWare** [comment]
I think some of the things can be restricted, but this seems mostly about forbidding lodash use on slightly arcane types. I'll try and come up with a strategy for getting this validated.

**Comment by AWare** [comment]
I had a look through our lodash calls, and I'm fairly confident that nothing would use these. Also tested on code (inc. crosswords). I'd like to merge this tomorrow and then keep an eye on raven.

**Comment by SiAdcock** [comment]
Thanks @AWare for checking out the safety of this plugin.

There's still a question around developer expectation, but it's hard to get the balance right. Adding something to our documentation is probably not going to save anyone, as nobody would ever find it. I think we should [explicitly disallow the use](https://github.com/guardian/frontend/blob/master/static/src/javascripts/.eslintrc.js#L44) of any [publicly-exposed `lodash` methods](https://github.com/lodash/lodash-webpack-plugin/blob/master/src/mapping.js) that are replaced by stub or identity functions. There's a bunch of internal stuff that this plugin also changes, and it's a lot harder to assess the impact of these changes. This is where the risk lies, but as long as developers test their code, it should be fine (_famous last words_)

Finally, I notice with interest that the code for [v5 of `lodash`](https://github.com/lodash/lodash/) is on GitHub, although it's not yet published. It looks a lot more tree-shakeable, that might negate the need for this plugin in the near future.

**Comment by SiAdcock** [comment]
Is it likely we'll ever get around to completing this, @AWare? Or perhaps we can wait for [lodash v5](https://github.com/lodash/lodash/wiki/Roadmap#v500-2019)?

**Comment by AWare** [comment]
Unlikely, but is still low hanging fruit

**Comment by AWare** [comment]
I don't think this remains useful and am no longer on the team.

**Pull request closed without merging**
