### PR TITLE
Rename all "flyer" references to "rich links"

### PR DESCRIPTION
**Pull request by OliverJAsh**
This was rather brave of me to try. All seems to be working in DEV. Can someone check the Scala changes (including my new file mappings), please?

### CODE REVIEW

**Comment by OliverJAsh** [comment]
@rich-nguyen Checked the styling in DEV:

image

**Comment by johnduffell** [comment]
haha, my test gets around ;)

**Comment by johnduffell** [comment]
looks great :+1:  however something I wonder is how much did our CSS/JS increase in size?

**Comment by OliverJAsh** [comment]
Cheers @johnduffell. How do you mean? I've only renamed references of "flyers", so there should be no big impact on file sizes.

**Comment by johnduffell** [comment]
flyers is only 6 characters, wheras rich-links is 8 or 9 depending if it's hyphenated.  It just struck me as something that can't be minified in all cases so I was wondering what the end impact of this would be.  I'd guess small but it got me wondering!

**Comment by phamann** [comment]
:+1: Ship it.

**Pull request merged**
