### PR TITLE
update node version reference in readme

### PR DESCRIPTION
**Pull request by dskamiotis**
## What does this change?

Currently the readme does a good job of suggesting using a node version manager (`nvm use`)

The current version suggested is not in line with the node version in the `.nvmrc` file.
Also a pointer towards other node version managers which may be used in the department.

## Does this change need to be reproduced in dotcom-rendering ?

- [x] No
- [ ] Yes (please indicate your plans for DCR Implementation)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by abeddow91 — APPROVED** [review]
Looks good, thanks @dskamiotis !

**Review by DanielCliftonGuardian — APPROVED** [review]
👍

**Comment by georgeblahblah** [comment]
Is this a duplicate of https://github.com/guardian/frontend/pull/26293/files?

**Comment by dskamiotis** [comment]
> Is this a duplicate of #26293?

Hey @georgeblahblah yes sorry has some `pull` issues on Friday which I resolved and therefore opened PR, apologies I should have closed this one!

**Pull request closed without merging**
