### PR TITLE
Private collections

### PR DESCRIPTION
**Pull request by janua**
This adds a switch to change the read access of `collection.json` files to `private`.

The only consumer of these collections should be `facia-scala-client`, which _CAPI_, _MAPI_ and _Ophan_ use, each with their own key.

`facia-tool` also reads these but not through the client.

@robertberry @piuccio @DiegoVazquezNanini @mchv @obrienm

### CODE REVIEW

**Comment by mchv** [comment]
@janua we (CAPI) did not have a key yet!

**Comment by robertberry** [comment]
:+1: 

Obviously we need to make sure everyone is able to read private collections already. Might be worthwhile making a front on some unlinked to URL on PROD, make the file private, then make sure all those services can access it

**Comment by piuccio** [comment]
`facia-tool-node-api` is also reading those, but it has its key.

:+1: 

How about the `config.json`?

**Comment by janua** [comment]
I'm less worried about `config.json`. I think we really would break a lot of things if we made that private. But I still think we should do it eventually.

**Comment by johnduffell** [comment]
better security makes me very happy! :+1:

**Comment by mchv** [comment]
@janua Content has been updated so it is safe from us :+1:

**Comment by janua** [comment]
Merging this, will not switch on until I till everyone when it will happen and when I'm ready.

**Pull request merged**
