### PR TITLE
Permutive implementation behind a 0% AB test

### PR DESCRIPTION
**Pull request by faresite**
## What does this change?
Adds permutive code into our `<head>` and in the commercial bundle. I have created a 0% AB test as well to verify with Permutive.

## Trello card
https://trello.com/c/0SLsTKkO/568-permutive-schema

## Does this change need to be reproduced in dotcom-rendering ?

- [ ] No
- [x] Yes (please indicate your plans for DCR Implementation)

As far as I know, DCR ships with the commercial, however there will be some permutive code to run in the <head> tag. Will create a card for it once permutive is tested and working on `frontend`.

## What is the value of this and can you measure success?
We are replacing Krux with Permutive. We can measure success by confirming with Permutive and the commercial team that the implementation is fit for purpose and no bad side effects occurring.

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by ripecosta — APPROVED** [review]
Looks good 👍 

Suggestion for the future: When it goes live we should have a feature switch (default on) to control running permutive. That way if anything goes wrong with permutive for whatever reason we can switch it off instead of having to take more drastic measures (such as switching off the entire commercial stack)

**Comment by faresite** [comment]
> Looks good 👍
> 
> Suggestion for the future: When it goes live we should have a feature switch (default on) to control running permutive. That way if anything goes wrong with permutive for whatever reason we can switch it off instead of having to take more drastic measures (such as switching off the entire commercial stack)

Thanks for the review @ripecosta , It does exist as it's standalone switch and you can turn it off or an just for permutive .. maybe I'm misunderstanding something?

**Review by ripecosta — APPROVED** [review]
👍 All good

**Comment by katebee** [comment]
> When it goes live we should have a feature switch (default on) to control running permutive. 
> That way if anything goes wrong with permutive for whatever reason we can switch it off instead of having to take more drastic measures (such as switching off the entire commercial stack)

Agree, but would suggest `default off` since you would only need to turn it on once and it would stay on, but the `SafeState` is useful to central prod and 24/7 to infer what actions can be taken 😸

**Pull request merged**
