### PR TITLE
update Shaun Dillon's GH username

### PR DESCRIPTION
**Pull request by shaundillon**
## What does this change?
Shaun Dillon's username from ShaunYearStrong to shaundillon

## What is the value of this and can you measure success?
The `make es6` and `make fix` scripts will work correctly for me.

## Does this affect other platforms - Amp, Apps, etc?
Nope

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]

**Comment by paperboyo** [comment]
giphy

**Comment by sndrs** [comment]
@shaundillon ping

**Comment by shaundillon** [comment]
@sndrs - I don't have write access :(

**Comment by sndrs** [comment]
ah right! ill merge it

**Comment by shaundillon** [comment]
@sndrs Cheers!

**Pull request merged**
