### PR TITLE
Make visibility of timestamps configurable at container level

### PR DESCRIPTION
**Pull request by robertberry-zz**

### CODE REVIEW

**Comment by gklopper** [comment]
Annoy your valued colleagues for a review, don't just wait for them...

**Comment by phamann** [comment]
:+1: LGTM

**Comment by phamann** [comment]
9 days!

**Comment by gklopper** [comment]
SHIP or SHUT...

**Comment by robertberry** [comment]
I've been distracted by all this perf stuff! But fine, I'll close it in the meantime.

**Pull request closed without merging**
