### PR TITLE
JSCS: allow multiple var statements

### PR DESCRIPTION
**Pull request by OliverJAsh**
I would like to propose that we allow multiple var statements per function scope. The code is much more readable when variables are defined beside the code you are reading. Anyone authoring JavaScript should have a good understanding of hoisting, removing the need to manually hoist variable declarations.

Thoughts?

E.g.

Before:

``` js
var car = new Car(),
    isBlueCar;

if (car.colour === 'blue') {
    isBlueCar = true;
}
```

``` js
var car = new Car();

if (car.colour === 'blue') {
    var isBlueCar = true;
}
```

http://jscs.info/rules.html#requiremultiplevardecl

### CODE REVIEW

**Comment by robertberry** [comment]
I agree ... had the same argument a few months ago.

**Comment by samdesborough** [comment]
I'm on the single var team: it's a better representation of how hoisting works, so there's less chance of confusion about scope, and it looks less noisy to me.

**Comment by OliverJAsh** [comment]
@samdesborough Developers should not need a reminder of how hoisting works in JS. I favour readability over the very tiny edge case where a developer has misunderstanding of hoisting.

**Comment by samdesborough** [comment]
That's true, but readability is subjective, and I don't find it much of an improvement. I'd still go for the option that's less likely to confuse people, however small that set of people may be.

Whichever style we go for, we should be consistent, so there's the cost of refactoring existing code to consider too.

**Comment by piuccio** [comment]
In my projects I prefer multiple var, especially in cases like this where the var is only used in a given block. It's closer to how you would use let instead of var.

However on this project I would use the established guidelines for consistencies. Moreover the var is declared just two lines above it's use. I don't see any readability problem.

**Comment by phamann** [comment]
Can we reach a general consensus on this?

**Comment by robertberry** [comment]
I completely agree with @OliverJAsh that multiple var declarations is more readable. We all know how hoisting works, but having the var declared in the block where you're going to confine its use to helps me, at least, understand programmer's intent.

But if we're about to move to ES6 features, maybe we should just start doing that and use `let`.

**Comment by sndrs** [comment]
highly unlikely :)

one possible thing to consider - in ES6, `let` is not hoisted, and in the above example, you'd probably use a `let`. if you wouldn't, and you want a `var`, there's a good argument to say it should be declared at the top, so it's 'public'

**Comment by samdesborough** [comment]
google just proposed "strong mode", a beefed up strict mode, and they're considering settling this by banning ```var``` altogether: see scoping [here](https://docs.google.com/a/guardian.co.uk/document/d/1Qk0qC4s_XNCLemj42FqfsRLp49nDQMZ1y7fwf5YjaI4/view#)

**Comment by robertberry** [comment]
The scoping of var is pretty much the stupidest thing ever.

On 11 March 2015 at 11:13, Sam Desborough <notifications@github.com> wrote:

> google just proposed "strong mode", a beefed up strict mode, and they're
> considering settling this by banning var altogether: see scoping here
> <https://docs.google.com/a/guardian.co.uk/document/d/1Qk0qC4s_XNCLemj42FqfsRLp49nDQMZ1y7fwf5YjaI4/view#>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/8493#issuecomment-78244535>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by OliverJAsh** [comment]
Indeed, @sndrs, but I don't want to hang my code's readability on the migration to ES6.

We haven't heard from everyone, but I can vouch for @rich-nguyen who is also on the "multiple var" side.

**Comment by rich-nguyen** [comment]
Yep, that's my opinion. Not understanding hoisting doesn't mean we should write all our code in an unreadable way.

This isn't the best place to discuss this. If we want to reach a conclusion, then i'd suggest a quick meeting between interested developers, strictly time boxed to 10 minutes. Even that seems like too long.

**Comment by uplne** [comment]
So what is happening with this?

Readability is subjective thus not a valid argument in this stage of the project. I don't think changing it now will add to the readability.

**Comment by OliverJAsh** [comment]
I'm going to organise a quick 10 minute meeting for us to settle this, once
the storm of work has passed.

On 13 March 2015 at 10:40, Steve Vadocz <notifications@github.com> wrote:

> So what is happening with this?
>
> Readability is subjective thus not a valid argument in this stage of the
> project. I don't think changing it now will add to the readability.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/pull/8493#issuecomment-78910814>.
>



-- 
Oliver Ash (Olly)
Software Engineer

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by rich-nguyen** [comment]
"Readability is subjective thus not a valid argument " @uplne are you sure about that?!

Just because something is subjective, doesn't imply it is invalid. It is of course opinion, as stated, but if we agree on things as a team, we should do them, even if the codebase is big. And that includes the potential for agreeing on subjective things. Let's not forget that those rules were added relatively recently, and at the whim of a single developer, no one really bothered to go through them in detail. Let's challenge everything, and avoid doing something simply because we thought it was a good idea once upon a time.

**Comment by OliverJAsh** [comment]
Re-opening this. If anyone is opposed please shout now.

**Comment by robertberry** [comment]
Ship it

**Pull request merged**
