### PR TITLE
Bump Thrift-related libraries

### PR DESCRIPTION
**Pull request by regiskuckaertz**
A transitive dependency introduced a version mismatch for the thrift library. This went undetected for a long time as we almost never change the model of existing types. However yesterday the `Tag` type was changed in Concierge with a new field and it ended up breaking the site. This has been [fixed](https://github.com/guardian/content-atom/pull/128) and all downstream libraries are being updated too.

TODO
- [x] [Upgrade the FAPI client](https://github.com/guardian/facia-scala-client/pull/214)
- [x] Update database
- [x] Test on CODE

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
I don't have access to Snyk 🤔 What are these vulnerabilities about?

**Comment by regiskuckaertz** [comment]
Okay ... I'm in a bit of a pickle as moving away from libthrift@0.9.1 is a huge effort that will require a fair amount of time, testing and team coordination.

**Comment by regiskuckaertz** [comment]
This is live in MAPI since yesterday, are you ok to go live with this @nicl @philmcmahon ? We're working on bringing all libraries up to date with the latest version of scrooge, but this will take some time.

**Comment by regiskuckaertz** [comment]
YAY @nicl Tested in CODE too.

**Comment by philmcmahon** [comment]
👍

**Pull request merged**
