### PR TITLE
Inline refresh

### PR DESCRIPTION
**Pull request by janua**
## What does this change?

This removes the restriction of ad refresh for the slot `inline1`. This ad slot is used to serve inline Outstream videos, which is the reason we have excluded the ad slot from ad refresh.

Not all calls to our Outstream video provider (Unruly) return a video, and in this case we passback to DFP in order to serve a standard MPU.
When this happens, which I believe is up to 40% of calls, the standard MPU is not refreshed even though it is now eligible.

After this change, ALL ad slots will be eligible for refresh; this will exclude fluids, specific line items such as sponsorships and page skins.

### How do we stop Unruly getting refreshed inventory?

We need to negatively target all Outstream line items to not ever serve on a refreshed impression as Unruly don't want refreshed inventory.

### How do we stop refreshing if there is a video?

We also need to Unruly to update the script they use to send us for direct campaigns, and also update the creatives in the current programmatic line items. This change includes sending a message via the messaging system that will disable refresh for the ad slot when a video gets served.

## What is the value of this and can you measure success?

More impressions measured via DFP reporting

### Before merge:
- [x] Line items negatively targeted
- [x] Unruly script updated on their CDN 

### Does this affect other platforms?

No

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [x] No
- [ ] Yes (please give details)

### Accessibility test checklist

Not applicable

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by jeteve — APPROVED** [review]
Looks legit to me.

**Comment by JonNorman** [comment]
So if a video _is_ returned by Unruly, what is going to stop the slot from refreshing after 30 seconds?

**Comment by janua** [comment]
@JonNorman Aren't you on another team now? :laughing: 
Good question. I have updated the creative script for Unruly that uses the messenger system to send a `disable-refresh` for the ad slot when one gets served!

**Comment by JonNorman** [comment]
I'm planning to make my millions off the commission of ad-refresh, got to make sure it gets out unharmed.

But also, great news!

**Pull request merged**
