### PR TITLE
Switch on/off comment adverts in commercial-features.js

### PR DESCRIPTION
**Pull request by jbreckmckye**
This is a switchable commercial feature I neglected to add to commercial-features.js in my original pull request.

Comment adverts now hang off a 'commentAdverts' boolean value.

I've also slightly rearranged the commercial feature policy unit tests so that they group together the effects of particular switches.

### CODE REVIEW

**Comment by jbreckmckye** [comment]
This is blocked and waiting for #10719 to re-add commercial-features.js after its reversion on Tuesday.

**Comment by jbreckmckye** [comment]
Could someone take a look at this, now it's no longer blocked?

@Calanthe @uplne

**Comment by Calanthe** [comment]
It looks fine to me :+1:

**Comment by jbreckmckye** [comment]
This branch had a bug - it was trying to lookup the switch on the wrong object. I've changed that in a5efcd9.

**Comment by jbreckmckye** [comment]
@Calanthe @uplne - given that there was a bug in the PR itself, I'm going to close this request and re-open it when I have some better unit test coverage.

**Pull request closed without merging**
