### PR TITLE
Sticky navigation small animation fix

### PR DESCRIPTION
**Pull request by Calanthe**
In the situation when there is no top banner (page is sensitive or a paid member uses adblock or we have banner placed after the first container) the animation of slim nav was buggy. Some time ago I added a rule that for sensitive pages there will be no animation of slim nav at all - just a style change from `display: block` to `display: none`. In this PR I added the same functionality for the adblock users and 'the banner below container' scenario.

Before:
slim-navigation-beforr

After:
slim_animation_after

I think that this is the easiest and fastest fix. Maybe in the future there will be a need to refactor the whole animation of the slim nav in js instead of css (`StickyHeader.prototype.showNavigation()` method).

I also fixed the bug when the user wasn't in any test and `config.tests` was an empty object.

### CODE REVIEW

**Comment by paperboyo** [comment]
Super! Sticky>smooth is always a right direction ;)

It's probably known, but just wanted to record current scrolling up<>down behaviour of latest release of Firefox with AdBlock:

firefox with adblock

**Comment by Calanthe** [comment]
If I remember correctly, we don't have a proper method to detect adblocks on Firefox.

**Comment by uplne** [comment]
:+1:

**Comment by paperboyo** [comment]
@Calanthe Oh, that (we know, but can't be sure that we are not whitelisted?): https://github.com/guardian/frontend/pull/10152. Boo.

**Pull request merged**
