### PR TITLE
Upadated EU ref email header to Brexit

### PR DESCRIPTION
**Pull request by zeftilldeath**
Cos it isn't a referendum now. It's a brexit.

### CODE REVIEW

**Comment by desbo** [comment]
👍

**Comment by dominickendrick** [comment]
Nice reuse of the old design! Would have been a little more work if it was remain!

**Comment by zeftilldeath** [comment]
@dominickendrick It's Chris Clarke's design anyway but that's a really good point!

**Comment by paperboyo** [comment]
Wider population always votes for less design-disrupting options. Pragmatism.

**Pull request merged**
