### PR TITLE
Add svg-loader rule to Webpack config

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

Adds a rule to Webpack config, telling Webpack to load SVG files using our custom SVG loader. This saves us from having to specify this in the JS. 

## What is the value of this and can you measure success?

Let the config take care of configuration, let code take care of functionality.

## Does this affect other platforms - Amp, Apps, etc?

No

## Tested in CODE?

No

### CODE REVIEW

**Comment by SiAdcock** [comment]
Oh yeah. Tests.

**Comment by SiAdcock** [comment]
I have fixed the tests. @sndrs @gustavpursche can you take a peek at this?

**Review by sndrs — APPROVED** [review]
lgtm - nice one!

do we need to mock it for jest?

**Comment by SiAdcock** [comment]
Yeah, we probably will need to mock this for Jest. I'll give it a test and address it in a separate PR if necessary

**Pull request merged**
