### PR TITLE
Ab test info is a TC step

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

move AB test info ping to its own TC step

## What is the value of this and can you measure success?

@rich-nguyen and I couldn't find it just now, it's not really an asset thing.

## Does this affect other platforms - Amp, Apps, etc?

will need to update TC build steps when this merges

### CODE REVIEW

**Comment by desbo** [comment]
just out of interest, what uses the output from this?

**Comment by TBonnin** [comment]
Same question: what uses this info?

**Comment by sndrs** [comment]
rich thought it was the data team, but it may be old now?

**Comment by desbo** [comment]
I don't think anyone will be, I'll ask the data people

**Comment by sndrs** [comment]
@desbo oh great - cheers sam

**Comment by desbo** [comment]
@philwills  - do you know anything about the `abtests.json` file generated here: https://github.com/guardian/frontend/blob/master/tools/ab-test-info/ab-test-info.js ? It seems like it's copied to the riff raff artifacts folder (https://github.com/guardian/frontend/blob/00cbe9050b10cb5d1ae11faa3e71b661acc9b5b5/dev/teamcity/dist-publish-assets-tc#L47), is anyone using it?

**Comment by philwills** [comment]
No, I don't know of anything consuming that.

**Comment by desbo** [comment]
I think we can get rid of it, we can always reinstate it if anyone notices.

**Comment by sndrs** [comment]
@desbo updated PR to remove it - cheers for looking into it!

**Comment by desbo** [comment]
nice one, reckon you can remove this line as well: https://github.com/guardian/frontend/blob/00cbe9050b10cb5d1ae11faa3e71b661acc9b5b5/dev/teamcity/dist-publish-assets-tc#L20

**Comment by sndrs** [comment]
ooh good spot

**Comment by rich-nguyen** [comment]
I mean the data team, not data tech. But maybe they don't need it anymore, is that who you spoke to @desbo ?

**Comment by desbo** [comment]
Yep, I've asked Phil and Mahana, neither of them knew of any use of it.

**Comment by rich-nguyen** [comment]
Cool, thanks. Let's get rid of it

**Pull request merged**
