### PR TITLE
Carry force update for facia-tool/facia-press

### PR DESCRIPTION
**Pull request by janua**
### Problem

First of all, on `facia-press`, we hold the `config.json` in memory for quick access as it is used a lot.

When `facia-tool` makes an update to either `config.json` or a `collection.json`, it sends the `paths` that needs updated onto an `SQS` for `facia-press` to pick up.

This is fine for **collection** updates, but for **config** updates, there might be a new container/collection on the front.
We currently have no way of telling the `facia-box` that picks up the press message to update its `config.json`.

This means that when fronts editors change a front, the change they are expecting can take at most **3 minutes** to update the front, when they are expecting a much faster update.

This problem didn't occur when `facia-press` and `facia-tool` were as one, but has reappeared when they were split.
### Fix

This adds `forceConfigUpdate` to both `PressCommand` and `PressJob`.

After this change, it will only be used on updates from the `facia-tool` javascript application asking for a `path` to be updated.

This means that fronts editors will see the update to their front based on their updated `config.json` much faster.

@stephanfowler @piuccio @robertberry

### CODE REVIEW

**Comment by piuccio** [comment]
:+1:  looks good

**Comment by stephanfowler** [comment]
:+1: nice one

**Comment by janua** [comment]
I have added to this so that it updates on creating a new `front` or moving a `collection` in a front.

In it's current state, we have:
 - Upon hitting the endpoint `/press/live/:path`, it forces `facia-press` to update its `config`. Same for `draft`.
 - When we update a front or create a front, it forces `facia-press` to update its `config`.


I'm not sure under what circumstances `facia-tool` JS calls `/press/live/:path` and `/press/draft/:path`.

@stephanfowler @piuccio Would you be able to have a look and let me know? I thought after creating a front or moving a collection it called these but it didn't update for me so that's why I added this.

**Comment by piuccio** [comment]
JS calls `/press/live/:path` when you click the refresh button in the live tab; `/press/draft/:path` when you click refresh or when you change tab from live to draft.

The refresh button is visible only when the presser is stale.

Those endpoints are never called from the config page.

**Pull request merged**
