### PR TITLE
Removing xmlns from weather svgs

### PR DESCRIPTION
**Pull request by uplne**
I've looked into svgmin if this can be done automatically which it can't. It's not really annoying enough to be worth spending time on looking for some other tool or make our own as find and replace is doing a great job.

CC @sndrs

### CODE REVIEW

**Comment by sndrs** [comment]
:+1:

**Comment by phamann** [comment]
Why are you doing this out-of-interest?

**Comment by uplne** [comment]
All modern browsers don't require that if the page is served as text/html. The problem would be on the old IE on which the weather won't be loaded anyway. Se we can save some bytes.

**Comment by gklopper** [comment]
if I view one of those files in master they work fine.

If I view it in the branch it breaks...


https://github.com/guardian/frontend/blob/weather-svgs/static/src/inline-svgs/weather/weather-11.svg

**Comment by uplne** [comment]
My guess is that its loading it by AJAX as image/svg+xml or application/xhtml+xml and in that case you need that xmlns parameter to tell browser that it needs to use XML parser.

**Comment by sndrs** [comment]
@uplne is right, as far as I understand it. 

[HTML 5 parsers ignore xml attributes](https://twitter.com/tabatkins/status/346692274861789185), since the DOCTYPE is HTML, not XML (if I understand correctly), including those on inline `svg` elements. 

IE8, although unable to anything with the svg element, gets completely confused by the presence of the attribute, in totally unpredictable ways. Removing it should cause no harm in browsers that support inline svg, and stop IE8 freaking out. 


more info here: http://stuntbox.com/blog/2013/06/bulletproof-inline-svg

**Comment by robertberry** [comment]
:+1:

**Comment by uplne** [comment]
Tested on:
- [x] Modern browsers
- [x] IE8 - no weather
- [ ] IE9+
- [ ] older smartphones

**Pull request merged**
