### PR TITLE
Show graphs of Prebid bidder performance

### PR DESCRIPTION
**Pull request by kelvin-chappell**
This is intended to give us a basic idea of progress.
It shows charts of winning bid counts by bidder, CPM by bidder and an indication of revenue by bidder over time.
It starts from 21 Jan, the day before we began the A/B test:
image

### CODE REVIEW

**Comment by kelvin-chappell** [comment]
Dates have disappeared! Will add now.

**Comment by kelvin-chappell** [comment]
And now with dates:
image

**Review by rich-nguyen — APPROVED** [review]

**Review by JonNorman — APPROVED** [review]
This looks great 👍

**Comment by ScottPainterGNM** [comment]
Is the indicative revenue pounds or dollars out of curiosity? Likewise with CPM?

**Comment by kelvin-chappell** [comment]
@ScottPainterGNM It's pounds but I'll add a label to the axis.

**Pull request merged**
