### PR TITLE
Facebook overlay everywhere!

### PR DESCRIPTION
**Pull request by dominickendrick**
## What does this change?

This rolls out the Facebook overlay across the entire site.
## Does this affect other platforms - Amp, Apps, etc?

Facebook
## Screenshots

screen shot 2016-06-06 at 11 45 43
## Request for comment

@stephanfowler @katebee

### CODE REVIEW

**Comment by sndrs** [comment]
is the spacing around the text ok? looks a touch tight at the top? cc @zeftilldeath

**Comment by zeftilldeath** [comment]
It's all good, just the way we do it (hang it from the top).
screen shot 2016-06-06 at 14 00 25

**Comment by sndrs** [comment]
👍 ship it then :)

**Comment by katebee** [comment]
Just used the facebook debugger on an older article (23rd May) to force FB to update the cache, using the share button now has made it appear with the overlay on my timeline:

article from last month with overlay

**However,** it appears that, if a user has shared an article before, then the og:image will not update for that user, on the old post or any subsequent post of the same article. Examples on my [demo account](https://www.facebook.com/kate.whalen.982)

**Pull request merged**
