### PR TITLE
Add special report tone

### PR DESCRIPTION
**Pull request by sndrs**
:four_leaf_clover: fingers crossed this catches everything...

screen shot 2015-02-06 at 17 18 41

screen shot 2015-02-06 at 17 19 21

screen shot 2015-02-06 at 17 19 11

screen shot 2015-02-06 at 17 38 43

### CODE REVIEW

**Comment by uplne** [comment]
:+1: seems ok to me. The only thing I don't like is that sometimes we are very very close to or even breaking the sass rule: don't nest more than 3-4 levels (I prefer 3).

**Comment by sndrs** [comment]
i agree  - this is just adding the tone in the current method though. but looking at depth afterwards is no bad idea

**Comment by paperboyo** [comment]
> this catches everything...

Almost :-D

URL: http://www.theguardian.com/business/video/2015/feb/08/hsbc-files-secret-swiss-account-data-misconduct-video

Regards
Mateusz

special report video

**Comment by sndrs** [comment]
@sammorrisdesign picked it up in #8234

**Pull request merged**
