### PR TITLE
Move Outbrain / email checks to module root

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

The intention of the top level `lib` directory is to house self-contained, reusable, composable modules that have no dependencies on other parts of our application. While the `check-dispatcher` and `check-mediator` modules could be made more generic, I have moved them into the module root to signify that they are intended to be generic.

## What is the value of this and can you measure success?

This prepares the way for the ES6 conversion, testing and Flow typing of the `lib` directory.

## Does this affect other platforms - Amp, Apps, etc?

No

## Tested in CODE?

No

### CODE REVIEW

**Comment by gtrufitt** [comment]
I don't think email is the right module for this, it's independent of any particular module (just so happens that the first module to use it is email).

**Review by GHaberis — APPROVED** [review]
👍

**Comment by GHaberis** [comment]
Ok, yes the reasoning behind moving it to email was that it's only used to run email checks right now, it should theoretically be available to any module though, so perhaps common/modules would be a suitable place for these files to live.

**Comment by SiAdcock** [comment]
@GHaberis @gtrufitt I have moved modules into the module root. I have also moved the test spec to mirror this

**Review by gtrufitt — APPROVED** [review]

**Pull request merged**
