### PR TITLE
Improve atoms bootstrap modules compilation

### PR DESCRIPTION
**Pull request by regiskuckaertz**
🎩  @sndrs

### CODE REVIEW

**Comment by sndrs** [comment]
lgtm – do the files get picked up ok in the asset map? might be a good one just to check on code

**Comment by regiskuckaertz** [comment]
I tested locally with `useHashedBundles`; is that what you mean?

**Comment by sndrs** [comment]
@regiskuckaertz yep – sounds good!

**Review by sndrs — APPROVED** [review]
nice

**Pull request merged**
