### PR TITLE
fixing sprite position for pinterest icon #9792

### PR DESCRIPTION
**Pull request by NataliaLKB**
Fixing pinterest icon in ie8 issue #9792.

BEFORE:
￼
image

AFTER:

image

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Nice! :+1: Perhaps leave a comment to say why this icon is special

**Comment by NataliaLKB** [comment]
Tested and all checks are good. Merging :)

**Comment by Jholder112233** [comment]
@NataliaLKB Hey, this appears to have broken the Pinterest icon on modern browsers.

Chrome 44 screenshot:
screen shot 2015-09-01 at 15 09 56

**Comment by NataliaLKB** [comment]
@Jholder112233 thanks! I will push up a fix now.

**Comment by NataliaLKB** [comment]
#10344 will fix this @Jholder112233 . Thanks again!

**Pull request merged**
