### PR TITLE
adds universities email banner

### PR DESCRIPTION
**Pull request by LisaVillani**
## What does this change?
This updates the banner for The Higher Education Network with the new name Guardian Universities (just on the banner)
## Screenshots
universities

### Does this affect other platforms?

- [ ] AMP 
- [ ] Apps
- [ ] Other (please specify)

### Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

- [ ] No
- [ ] Yes (please give details)

### Does this change break ad-free?

- [ ] No
- [ ] It did, but tests caught it and I fixed it
- [ ] It did, but there was no test coverage so I added that then fixed it

### Accessibility test checklist

- [ ] [Tested with screen reader](https://accessibility.gutools.co.uk/testing/web/screen-readers/)
- [ ] [Navigable with keyboard](https://accessibility.gutools.co.uk/testing/web/keyboard-navigation/)
- [ ] [Colour contrast passed](https://accessibility.gutools.co.uk/testing/web/colour-contrast/)

### Tested
NO
- [ ] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Review by QuarpT — APPROVED** [review]

**Comment by SiAdcock** [comment]
Is it safe to now delete the old [`higher-education-network.png`](https://github.com/guardian/frontend/blob/master/static/public/images/email/banners/higher-education-network.png)?

**Review by SiAdcock — APPROVED** [review]
Grand! 👍

**Comment by mchv** [comment]
@LisaVillani I just [applied tinypng](https://tinypng.com/) to reduce the size.
@paperboyo may have or share other tricks.

**Comment by LisaVillani** [comment]
Thanks all! Sorry forgot the tiny bit!

**Comment by paperboyo** [comment]
4KB is fine. I got it 0.5KB smaller, but if it’s in already, I wouldn’t bother:

45681383-48922c00-bb35-11e8-8582-62585e11ec60_opt

**Pull request merged**
