### PR TITLE
enable discussion API proxy for reportAbuse POSTs

### LINKED ISSUE #9897: Discussion Abuse Reports: put through theguardian.com proxy
We have had some reports from legal of abuse reports not being received.
I believe this could be because abuse reports are not currently put through the same domain proxy like Comments so may fail due to lack of CORS support.

Steps to reproduce
===============
Go to: http://www.theguardian.com/science/grrlscientist/2012/aug/07/3
Open Developer Console
Report Abuse on a comment

Actual Results
===========
Posts to: `http://discussion.guardianapis.com/discussion-api/comment/56132192/reportAbuse`

Expected Results
==============
Posts to `http://www.theguardian.com/guardianapis/discussion/discussion-api/comment/56132192/reportAbuse`

CC @guardian/discussion @JustinPinner @OliverJAsh

### PR DESCRIPTION
**Pull request by gidsg**
Fixes #9897. CC @guardian/discussion @johnduffell

### CODE REVIEW

**Comment by gidsg** [comment]
At suggestion of @OliverJAsh I am putting all POSTs through the proxy now. @johnduffell can you review?

**Comment by johnduffell** [comment]
:+1: looks good

**Comment by OliverJAsh** [comment]
If we're doing this for discussion, shouldn't we be doing it for all `POST` requests across the site? Where do you draw the line?

Alternatively we could specify in our browser support description that we cannot support browsers behind HTTP 1 proxies. This would cover our backs in cases like this.

**Comment by johnduffell** [comment]
@OliverJAsh well we don't really support http 1.0 proxies (who actually does?), but people use them anyway, and there's no action we can realistically expect them to take to fix it.  Once we knew about it we could tell people why it was, but if something annoys enough users and they complain enough we'll fix it somehow!

**Comment by OliverJAsh** [comment]
@johnduffell I think the number of complaints justified adding it for comment submission, but now we're slowly adding it to other things without evidence this is a problem. Obviously it is a problem if report fails silently, but is that a [UX issue](https://github.com/guardian/frontend/issues/9898)? Or, if this feature must work, do we have other critical features to fix as well?

**Comment by johnduffell** [comment]
oli I think if we weigh up the pros and cons of adding it to the rest of the discussion endpoints once we added it to one there's probably not much to recommend against it, unless you're aware of a risk I'm missing?  The report feature giving no feedback is definitely a separate problem, and is probably more important to fix (but more work to fix)

**Comment by OliverJAsh** [comment]
Okay :+1:

**Pull request merged**
