### PR TITLE
posh console message

### PR DESCRIPTION
**Pull request by sndrs**
played with the console hiring message on the train last night, came up with this:

screen shot 2016-02-05 at 12 47 45

it's a bit more _brandish_ and will only be shown in the most modern browsers. 

might take a poll of :+1:s against :-1: and merge on that basis...

### CODE REVIEW

**Comment by crifmulholland** [comment]
:+1:

**Comment by jamesgorrie** [comment]
:+1: I was going to suggest it.

**Comment by rich-nguyen** [comment]
:+1: can we also remove `THIS IS ENHANCED`?

**Comment by sndrs** [comment]
> can we also remove THIS IS ENHANCED?

it becomes quite tricky to work out if your enhanced or not without it. i guess it could only show in dev?

**Comment by paperboyo** [comment]
:+1: Now, how you load custom fonts into the Console? ;-)

Also, I would add `font-family: Helvetica Neue, Calibri, sans-serif;`. Calibri exists on all modern Windows machines and it’s way nicer than Arial.

**Comment by rich-nguyen** [comment]
@sndrs that sounds dev only, yep. it would be nice if our production code didn't have to do this kind of logic, but our dev system made it easy to see this kind of thing.

**Comment by sndrs** [comment]
posh it is

**Pull request merged**
