### PR TITLE
Remove useless code from admin

### PR DESCRIPTION
**Pull request by piuccio**
## What does this change?

I was on my quest of deprecating `reqwest` when I realised that some of the admin files are totally useless.

The path `/analytics/browsers` was removed by #4588 while the others by #12745
## What is the value of this and can you measure success?

One fewer `common/utils/ajax` to fix
## Does this affect other platforms - Amp, Apps, etc?

Admin
## Request for comment

@guardian/commercial-dev I'm not quite sure how your admin works, but I couldn't find any reference to the files I deleted. Do you mind double checking you're not using those files?

### CODE REVIEW

**Comment by JonNorman** [comment]
I think that `AdTests.js` is used [here](https://frontend.gutools.co.uk/commercial/adtests), but I think the rest of it can go...

**Comment by piuccio** [comment]
I tried that page but the `init` never gets called

**Comment by JonNorman** [comment]
Ah okay, I think perhaps the code in `Admin` should have been updated when [these changes](https://github.com/guardian/frontend/commit/8527f43b4a0ceb01a2495eb523ab4adf7ce46df1#diff-5ac85536bd706648482d45335031b3faR90) were made to the admin routes file. That said, if the page still works once you've deleted `adTests.js` then my wires may just be crossed and I'll give you a :+1: 😺

**Comment by piuccio** [comment]
I've also removed the button

**Comment by JonNorman** [comment]
C'est magnifique :+1:

**Pull request merged**
