### PR TITLE
Fix for signed in user nav on mobile on core 

### PR DESCRIPTION
**Pull request by holder-josh**
Currently have a problem where you click the hover menu to open it, but the element you click is a link so you go to your profile page.

This brings it back in line with non-core user experience.

Fix for:
prpfiledropdown

cc @sndrs this works in my testing. Safe to do?

### CODE REVIEW

**Comment by rich-nguyen** [comment]
:+1:

**Comment by sndrs** [comment]
would it be better to trap the event and stop it, rather than fiddle with the dom?

**Comment by gtrufitt** [comment]
Agree with @sndrs - also, can you get to that page without the direct link? There is a 'comments activity' link on desktop 
image but not in your gif - should there be a 'Contributions' (or comments activity as per desktop) nav item?

**Comment by Jholder112233** [comment]
@gtrufitt Problem is that the JS for this is inlined so I'm trying to limit the amount of bloat. I can investigate doing that though. I would rather fix this immediate bug first though with this simple PR and tackle that tomorrow.

@sndrs that requites more inline JS though which I'd rather avoid.

**Comment by Jholder112233** [comment]
@gtrufitt sorry for the confusion here. Just checked and the comment activity page doesn't actually work on core, so there's no point linking to it anywhere.

screen shot 2015-10-01 at 16 22 55

**Comment by gtrufitt** [comment]
@Jholder112233 Ah cool, no worries, I guess that's why it isn't in the nav!

**Comment by sndrs** [comment]
(just to keep this conversation in one place) problem with touching the DOM like that is it won't account for any dependencies on it e.g. `a[href=xxx]{…}`. 

it feels cleaner to me to use JS to modify the behaviour than to use it to modify the DOM so that it behaves differently.

the fact that removing the href will minimise inline JS is persuasive, but ultimately I don't think you'd create the resulting DOM if you weren't considering no-JS, which i think is enough of a smell to prefer `preventDefault`...

**Comment by OliverJAsh** [comment]
I think this element should really be a link for no-JS, and then enhanced with JS to a button element (which are automatically added to the tab index). The user agent will read this as a link, but it doesn't have the behaviour of a link (no navigation nor ability to open in a new tab, for example). Lying about these things often leads to unexpected behaviour.

**Pull request merged**
