### PR TITLE
CSS monitoring: admin page

### PR DESCRIPTION
**Pull request by stephanfowler**
css-logger

There's work to do on the sampling end, as some selectors aren't yet getting enough of a chance to... select.

With @robertberry

cc: @rich-nguyen @phamann @sndrs @Calanthe

### CODE REVIEW

**Comment by sndrs** [comment]
:clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap:

**Comment by rich-nguyen** [comment]
brilliant

**Comment by sammorrisdesign** [comment]
This is amazing :tada:

**Comment by robertberry** [comment]
Great work. :+1:

**Pull request merged**
