### PR TITLE
Review atom images

### PR DESCRIPTION
**Pull request by tomrf1**
## What does this change?
Adds images to reviews structured data markup for google.

## What is the value of this and can you measure success?
Reviews will now be rendered (`image` is a required field)

## Does this affect other platforms - Amp, Apps, etc?
No

## Screenshots
N/A

## Tested in CODE?
No

### CODE REVIEW

**Comment by LATaylor-guardian** [comment]
👍  Looks good to me.

**Comment by tomrf1** [comment]
Can someone from @guardian/dotcom-platform review this please?

**Comment by NataliaLKB** [comment]
Hey @tomrf1 this looks fine to me 👍 . But I don't see this affecting AMP at all... isn't it just affecting structured data? Maybe just update the description to `no` if thats the case.

**Comment by LATaylor-guardian** [comment]
@NataliaLKB When we implemented this we were instructed to check it did not break AMP validation, hence the comment.

**Comment by NataliaLKB** [comment]
@LATaylor-guardian sorry, I was not clear. the answer to the questions is that it doesn't affect AMP no? My understanding is that this doesn't affect AMP at all, not just that amp now still passes validation. 

If it does affect AMP, but it still validates then great! I just want to make sure I understand and that the description is accurate.

**Comment by tomrf1** [comment]
thanks @NataliaLKB! I'll merge in the morning

**Pull request merged**
