### PR TITLE
Nauru files

### PR DESCRIPTION
**Pull request by johnduffell**
this shouldn't be a random file in a bucket, so moving it to git - @blongden73 

I've updated the salt logic to reduce the attackability, we shouldn't use the same salt more than once.

@TBonnin

### CODE REVIEW

**Comment by TBonnin** [comment]
Other than the svg 👍

**Comment by johnduffell** [comment]
@gtrufitt @paperboyo do either of you have a suggestion for minifying svgs?

**Comment by paperboyo** [comment]
23KB>6KB. Viewbox was/is crazy, so it moved a little, hopefully won't give problems. Would the SVG be created bigger, it would swallow even more optimisation!

```
<svg xmlns="http://www.w3.org/2000/svg" width="103" height="102.3" viewBox="692 377 103 102.3"><path fill="#333" d="M692 479.3h103V377H692"/><path fill="#FFF" d="M782.7 476l-12-11.8.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.3-.8-1.8l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8l.3.3-11.9 11.8zM770 462.9l-.3.3-.3-.3c-.2-.2-.4-.5-.4-.8s.1-.6.4-.8l.3-.3.3.3c.2.2.4.5.4.8s-.2.6-.4.8zm-1.6 1l.3.3-11.9 11.8-12-11.8.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.3-.8-1.8l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8zm-24.3-1l-.3.3-.3-.3c-.2-.2-.4-.5-.4-.8s.1-.6.4-.8l.3-.3.3.3c.2.2.4.5.4.8s-.2.6-.4.8zm-1.6 1l.3.3-11.9 11.8-12-11.8.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.3-.8-1.8l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8zm-24.3-1l-.3.3-.3-.3c-.2-.2-.4-.5-.4-.8s.1-.6.4-.8l.3-.3.3.3c.2.2.4.5.4.8s-.2.6-.4.8zm-1.6 1l.3.3L705 476l-12-11.8.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.3-.8-1.8l-.3-.3 12-11.8 11.9 11.8-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8zm-11-18.8c0 .3-.1.6-.4.8l-.2.3-.3-.2c-.2-.2-.4-.5-.4-.8 0-.3.1-.6.4-.8l.3-.4.3.3c.2.2.3.5.3.8zM693 430.2l.3-.2c.5-.5.8-1.2.8-1.8 0-.7-.3-1.3-.8-1.8l-.3-.4 12-11.7 11.9 11.7-.3.3c-.5.5-.8 1.2-.8 1.8 0 .7.3 1.3.8 1.8l.3.3L705 442l-12-11.8zm12.6-19.1c0 .3-.1.6-.4.8l-.2.4-.3-.3c-.2-.2-.4-.5-.4-.8s.1-.6.4-.8l.3-.4.3.3c.2.2.3.5.3.8zM693 396.3l.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.3-.8-1.8l-.3-.4 12-11.7 11.9 11.7-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8l.3.3L705 408l-12-11.7zm24.6-3l.3-.3.3.3c.2.2.4.5.4.8 0 .3-.1.6-.4.8l-.3.3-.3-.2c-.2-.2-.4-.5-.4-.8.1-.4.2-.7.4-.9zm1.6-1l-.3-.3 12-11.7 11.9 11.7-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8l.3.3-11.9 11.8-12-11.7.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.4-.8-1.9zm24.3 1l.3-.3.3.3c.2.2.4.5.4.8 0 .3-.1.6-.4.8l-.3.3-.3-.2c-.2-.2-.4-.5-.4-.8.1-.4.2-.7.4-.9zm13.3-13l11.9 11.7-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8l.3.3-11.9 11.8-12-11.7.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.3-.8-1.8l-.3-.4 12-11.7zm12.7 13l.3-.3.3.3c.2.2.4.5.4.8 0 .3-.1.6-.4.8l-.3.3-.3-.2c-.2-.2-.4-.5-.4-.8 0-.4.1-.7.4-.9zm1.5-1l-.3-.3 12-11.7 11.9 11.7-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8l.3.3-11.9 11.8-12-11.7.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.4-.8-1.9zm11.1 18.8c0-.3.1-.6.4-.8l.3-.3.3.3c.2.2.4.5.4.8s-.3.7-.5.9l-.3.3-.3-.3c-.2-.2-.3-.6-.3-.9zm-24 32.2l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8 0 .7.3 1.3.8 1.8l.3.3-12 11.8-11.9-11.8.3-.3c.5-.5.8-1.2.8-1.8-.1-.7-.3-1.3-.8-1.8zm12.3-15.2c0 .3-.1.6-.4.8l-.3.3-.2-.2c-.2-.2-.4-.5-.4-.8 0-.3.1-.6.4-.8l.3-.3.3.3c.1.1.3.4.3.7zm11-15.1l.3.3-12 11.7-11.9-11.7.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.3-.8-1.8l-.3-.4 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.4.8 1.9zm-25.2-1.9c0-.3.1-.6.4-.8l.3-.3.3.3c.2.2.4.5.4.8s-.1.6-.4.8l-.3.3-.4-.2c-.2-.2-.4-.6-.3-.9zm-11.7 17c0 .3-.1.6-.4.8l-.3.3-.3-.2c-.2-.2-.4-.5-.4-.8s.1-.6.4-.8l.3-.3.3.3c.2.1.4.4.4.7zm-12.3-18.8l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8l.3.3-12 11.8-11.9-11.7.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.4-.8-1.9zm-2 1.8c0-.3.1-.6.4-.8l.3-.3.3.3c.2.2.4.5.4.8s-.1.6-.4.8l-.3.3-.3-.2c-.2-.2-.4-.6-.4-.9zm-12.6 16.2l.3-.3.3.3c.2.2.4.5.4.8 0 .3-.1.6-.4.8l-.3.3-.3-.2c-.2-.2-.4-.5-.4-.8s.2-.7.4-.9zm-11.3-18l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8l.3.3-12 11.8-11.9-11.7.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.4-.8-1.9zm23.3 37.7l.3.3-12 11.7-11.9-11.8.3-.3c.5-.5.8-1.2.8-1.8 0-.7-.3-1.3-.8-1.8l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8 0 .7.3 1.3.8 1.9zm1.9-1.9c0 .3-.1.6-.4.8l-.3.3-.2-.2c-.2-.2-.4-.5-.4-.8 0-.3.1-.6.4-.8l.3-.3.3.3c.2.1.3.4.3.7zm-.6-3.1l-12-11.8.3-.3c.5-.5.8-1.2.8-1.8 0-.7-.3-1.3-.8-1.8l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8 0 .7.3 1.3.8 1.8l.3.3-11.9 11.8zm24.6 5l.3.3-12 11.7-11.9-11.8.3-.3c.5-.5.8-1.2.8-1.8 0-.7-.3-1.3-.8-1.8l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8 0 .7.3 1.3.8 1.9zm1.9-1.9c0 .3-.1.6-.4.8l-.3.3-.2-.2c-.2-.2-.4-.5-.4-.8 0-.3.1-.6.4-.8l.3-.3.3.3c.2.1.3.4.3.7zm-.6-3.1l-12-11.8.3-.3c.5-.5.8-1.2.8-1.8 0-.7-.3-1.3-.8-1.8l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8 0 .7.3 1.3.8 1.8l.3.3-11.9 11.8zm26.5 3.1c0 .3-.1.6-.4.8l-.3.3-.2-.2c-.2-.2-.4-.5-.4-.8 0-.3.1-.6.4-.8l.3-.3.3.3c.2.1.3.4.3.7zm11.3-19.1l-.3.3c-.5.5-.8 1.2-.8 1.8 0 .7.3 1.3.8 1.8l.3.3-11.9 11.8-12-11.8.3-.2c.5-.5.8-1.2.8-1.8 0-.7-.3-1.3-.8-1.8l-.3-.4 11.9-11.8 12 11.8zm-10.9 51l11.3-11.2v-7.4l-11.3-11.2.3-.2c.5-.5.8-1.2.8-1.8 0-.7-.3-1.3-.8-1.8l-.3-.4 11.3-11.2v-7.4l-11.3-11.1.3-.3c.5-.5.8-1.2.8-1.8s-.3-1.3-.8-1.8l-.3-.4 11.3-11.1v-7.4l-11.3-11.2.3-.3c.5-.5.8-1.2.8-1.8v-.2h-1.5v.2c0 .3-.1.6-.4.8l-.3.3-.2-.3c-.2-.2-.4-.5-.4-.8v-.2h-1.5v.2c0 .7.3 1.3.8 1.8l.3.3-11.9 11.7-11.9-11.7.3-.3c.5-.5.8-1.2.8-1.8v-.2h-1.5v.2c0 .3-.1.6-.4.8l-.3.3-.2-.3c-.2-.2-.4-.5-.4-.8v-.2h-1.5v.2c0 .7.3 1.3.8 1.8l.3.3-11.9 11.7-11.9-11.7.3-.3c.5-.5.8-1.2.8-1.8v-.2h-1.4v.2c0 .3-.1.6-.4.8l-.3.3-.3-.3c-.2-.2-.4-.5-.4-.8v-.2h-1.5v.2c0 .7.3 1.3.8 1.8l.3.3-11.9 11.7-11.9-11.7.3-.3c.5-.5.7-1.2.7-1.8v-.2h-1.5v.2c0 .3-.1.6-.4.8l-.1.3-.3-.3c-.2-.2-.4-.5-.4-.8v-.2h-1.5v.2c0 .7.3 1.3.8 1.8l.4.3-12 11.7v2l.3.3c.2.2.4.5.4.8 0 .3-.1.6-.4.8l-.3.4v2l12 11.7-.3.3c-.5.5-.8 1.2-.8 1.8s.3 1.3.8 1.8l.3.3-12 11.8v2l.3.3c.2.2.4.5.4.8 0 .3-.1.6-.4.8l-.3.3v2l12 11.8-.3.3c-.5.5-.8 1.2-.8 1.8 0 .7.3 1.3.8 1.8l.3.3-12 11.8v2l.3.3c.2.2.4.5.4.8s-.1.6-.4.8l-.3.3v2l12 11.8-.3.3c-.5.5-.8 1.4-.8 2h1.4c0-.3.1-.8.4-1l.3-.3.3.3c.2.2.4.7.4 1h1.3c0-.7-.3-1.5-.8-2l-.2-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.4-.8 2h1.4c0-.3.1-.8.4-1l.3-.3.3.3c.2.2.4.7.4 1h1.4c0-.7-.3-1.5-.8-2l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.4-.8 2h1.4c0-.3.1-.8.4-1l.3-.3.3.3c.2.2.4.7.4 1h1.4c0-.7-.3-1.5-.8-2l-.3-.3 11.9-11.8 12 11.8-.3.3c-.5.5-.8 1.4-.8 2h1.4c0-.3.1-.8.4-1l.3-.3.3.3c.2.2.4.7.4 1h1.4c0-.7-.3-1.5-.8-2l-.3-.3z"/></svg>
```

**Comment by johnduffell** [comment]
thanks @paperboyo 🎉

**Pull request merged**
