### PR TITLE
lazy load mostpopular component

### PR DESCRIPTION
**Pull request by mattosborn**
@gklopper - not sure if we need tracking for this now... ?

### CODE REVIEW

**Comment by phamann** [comment]
:+1:

**Comment by gklopper** [comment]
:+1: - I like how easy it is to change it to lazy loading.

**Comment by phamann** [comment]
Are we worried about how this is going to affect the component tracking registry? /cc @rich-nguyen ?

**Comment by rich-nguyen** [comment]
worth testing, yes. we need to make sure component views are still being sent. There's a possibility that lazy/proximity loading could actually provide more useful tracking results, because the number of component views could reflect the number of real-life views, rather than the number of application inits. It's analogous to viewability, I guess.

@mattosborn can you make sure that the proximity loader is posting component views correctly?

**Pull request merged**
