### PR TITLE
Create New Module for Commercial Integration Tests

### PR DESCRIPTION
**Pull request by kelvin-chappell**

### CODE REVIEW

**Comment by rich-nguyen** [comment]
there are no tests in the commerical integration folder?

**Comment by kelvin-chappell** [comment]
@rich-nguyen There are now and more on the way.  This is just to test the trigger.

**Comment by rich-nguyen** [comment]
ok. so why split the integration tests? shouldn't they be as important as each other?

**Comment by kelvin-chappell** [comment]
Treating these as high-priority tests as they will affect revenue.  They're going to run on deployment to Code to test presence of elements on ad test pages.  They should be tests that run very quickly and, In principle, if these fail the build shouldn't be deployed to Prod.  But initially they are distinct so that they run fast and we can set different notifications.

**Comment by kelvin-chappell** [comment]
I'm going to take a different approach with this: create a new custom test configuration and leave all the integration tests together.

**Comment by rich-nguyen** [comment]
sounds good

**Pull request closed without merging**
