### PR TITLE
Enable sign in, profile editing and sign out for core users

### PR DESCRIPTION
**Pull request by JustinPinner**
We want to give our core mode users a better signed-in experience.

We'll detect when the user is signed in via the GU_U cookie as usual, and if they are known to us, we'll tweak the signed-in version of the menu bar such that they'll either be directed to their commenting profile page (the preferred route) or to their public profile editing page if we can't detect an ID for some reason.

The footer that appears on these pages has been extended to carry a sign out link, so they should always have a reachable sign out route even if we haven't upgraded their menus with JS (which we don't do in core mode).

Would appreciate some feedback from the frontend team about the proposed changes, and also from identity (@chriswilk?) as I haven't been able to get the identity service running locally yet to see the effects of adding the sign out link to the footer.

Core user signed in (hovering over the user name link):
screen shot 2015-09-04 at 15 44 09

### CODE REVIEW

**Comment by gklopper** [comment]
Does that give a dropdown menu when clicked. If not we should at least lose the dropdown icon

**Comment by JustinPinner** [comment]
Good point. No, we don't get a dropdown in core so I'll look at hiding the icon.

**Comment by NataliaLKB** [comment]
@JustinPinner took a look at identity locally and once you are signed in, it takes you straight to the user's commenting profile. :+1: 

It may be worth doing the dropdown icon in a different PR, unless it is really easy.

**Comment by JustinPinner** [comment]
Nice, thanks @NataliaLKB. I think I have the icon working now so I'll commit that soon, and maybe you could give it another try? Or I will when ID works locally :partly_sunny:

**Comment by NataliaLKB** [comment]
@JustinPinner took another look locally and the dropdown icon still displays on core (at least for me). Lets revisit in the morning.

**Comment by NataliaLKB** [comment]
:+1: great!

**Comment by stephanfowler** [comment]
Dropdowns are actually possible with CSS only (using the "sibling selector / hidden checkbox" method.) Maybe worth a spike... as it'd be good keep core and premium behaviours as undistinguishable as possible.

**Pull request merged**
