### PR TITLE
Prioritise master images during trail image picking

### PR DESCRIPTION
**Pull request by rich-nguyen**
This ensures that we pick master images for trail images, I think that's the main issue causing  https://github.com/guardian/frontend/issues/12214

### CODE REVIEW

**Comment by TBonnin** [comment]
Nitpicking :) : why not looking for the largest image only if a master one doesn't not exist

Otherwise :+1:

**Comment by rich-nguyen** [comment]
@TBonnin I added a lazy for that, thanks

**Comment by paperboyo** [comment]
Great, thanks @rich-nguyen! Will this affect/fix slideshow behaviour or will I have to bother @piuccio for that?

**Comment by rich-nguyen** [comment]
Let's double check, it's not clear if slideshows will be corrected. My belief is yes, because my fix should affect how facia-press picks images for slideshow.

**Comment by paperboyo** [comment]
Just checked (on International front). Slideshow is **not** using `/master/`. Video trails aren't using `/master/`. That would not surprise me (although, I would like it fixed still). But some cards are still **not** using `/master/` (I've checked, there is one). Example: https://i.guim.co.uk/img/media/cdf9df24553f14bddfaedc4ced55ff47aec06d85/0_220_4928_2958/1000.jpg?w=220&q=20&auto=format&usm=12&fit=max&dpr=2&s=0cc7a56c805743cfeaa4561b3932a2fc

no masters
(I don't know how to properly identify a card for you)

Found them by filtering a Network Img filter with `-master`.

**Comment by paperboyo** [comment]
Ok, my bad: so the trail above is a fronts tool's Image Replacement. Others like it, also do not call for `/master/`. So these and slideshow would probably need an intervention from @piuccio? Not sure about trails behind a video play button, though (which, funnily enough, **won't** accept an Image Replacements, but should :wink:)...

**Pull request merged**
