### PR TITLE
Audio AB Test 3: Change image position

### PR DESCRIPTION
**Pull request by ajwl**
## What does this change?

- Removes the old test that hid the image 
- Adds a new test that trials putting the player above the image vs original player.

- 50:50 test that should run for 3 days 

## Screenshots

screen shot 2018-07-27 at 16 01 43

screen shot 2018-07-27 at 16 01 15

### Tested

- [x] Locally
- [x] On CODE (optional)

### CODE REVIEW

**Review by regiskuckaertz — APPROVED** [review]
💯

**Comment by ajwl** [comment]
Thanks! Will test on code and merge on monday...

**Comment by tomrf1** [comment]
👍 so both variants will add the `image` data component, but only one will add `image-below` as well

**Comment by ajwl** [comment]
Code fine 👌

**Comment by ajwl** [comment]
@tomrf1 yes indeed. Seemed simplest way to do it

**Pull request merged**
