### PR TITLE
Move commercial tests

### PR DESCRIPTION
**Pull request by piuccio**
That's the thing I hate about karma, tests don't run in isolation.

To make things slightly more resilient I've moved `commercial` out of `common`. This should avoid some conflicts.

I've also fixed the viewport size for phantom. There's at least one commercial tests expecting the viewport to be that of a desktop. By default Phantom is at mobile breakpoint.

I've checked the number of tests, before and after it's still 546, I haven't lost anything...

@phamann @sndrs @rich-nguyen @someone-else-from-commercial?

### CODE REVIEW

**Comment by rich-nguyen** [comment]
what kind of conflicts?

**Comment by piuccio** [comment]
Well I'm not sure if that's actually happening, but ajax mocks, settimeout, event listeners might cause tests to fail randomly.

I decided to split because it's quite hard to run tests locally.
Try `grunt test:unit:common --no-single-run` and go to `http://localhost:9876/` it's really hard to debug failing tests because there are ~450 tests.
BTW I don't know how do you guys write and run tests. Do you simply run `grunt:test` and hope that it works?
I don't know if you've noticed but some tests fail in the browser but works on Phantom, that means something, I don't know what.

Anyway, this PR can be closed, it's just to better organise tests and make debugging easier.

**Comment by kelvin-chappell** [comment]
It looks good to me but perhaps @Calanthe should comment.

**Comment by rich-nguyen** [comment]
@piuccio you can mark a test with `ddescribe` [sic] to run it exclusively.

**Comment by rich-nguyen** [comment]
I don't have a big preference for either test organisation. At least currently, each folder represents an application, i think that makes sense. If you're going to move commercial, I would say all common subfolders should be moved up one level.

**Comment by Calanthe** [comment]
It's good that @piuccio noticed that ajax mocks, settimeout, event listeners might cause tests to fail randomly. I usually test locally with `grunt test:unit:common` and hope that it will work on Phantom on other machines. Maybe it will also fix an issue which @rich-nguyen had last week with books merchandising.

**Comment by piuccio** [comment]
closing, looks like there's no actual need to do this

**Pull request closed without merging**
