### PR TITLE
crosswords font size adjustments

### PR DESCRIPTION
**Pull request by desbo**
decrease font sizes and tweak button layout to fit everything on one line

before 
screen shot 2015-09-17 at 17 56 16

after
screen shot 2015-09-17 at 17 55 53

### CODE REVIEW

**Comment by gtrufitt** [comment]
:+1:

**Comment by crifmulholland** [comment]
Do you have a before, before shot! It looks like it used to look!

**Comment by crifmulholland** [comment]
Found it! Yeah, looks like it's back to the original.. was there a middle ground?

image

**Comment by desbo** [comment]
@crifmulholland it is bigger than it was, but the screenshots are being scaled differently so it's not very apparent. should be more noticeable here:

old:
screen shot 2015-09-18 at 14 53 53
 
current:
screen shot 2015-09-18 at 14 45 49

this PR:
screen shot 2015-09-18 at 14 43 44

**Comment by crifmulholland** [comment]
Looks great!

**Pull request merged**
