### PR TITLE
Editionalise travel

### PR DESCRIPTION
**Pull request by TBonnin**
## What does this change?

It editionalised the travel section
## Does this affect other platforms - Amp, Apps, etc?

Tools supports it and apps knows about this change
## Request for comment

@rich-nguyen

### CODE REVIEW

**Comment by rich-nguyen** [comment]
Check with editorial tools that this is ready to go :+1:

**Comment by johnduffell** [comment]
is this going? if not we can always close and reopen when it's ready to go

**Comment by rich-nguyen** [comment]
:+1:

**Comment by TBonnin** [comment]
Still waiting for australia green light 😺

**Comment by TBonnin** [comment]
Closing for now. I will reopen when/if decision is finally made to editionalise travel

**Comment by TBonnin** [comment]
We have the green light 🚦 This branch is reborn

:D @johnduffell

**Comment by johnduffell** [comment]
👍

**Pull request closed without merging**
