### PR TITLE
Updated `humans.txt` to give myself a location

### PR DESCRIPTION
**Pull request by oliverlloyd**
## What does this change?
I am adding a location to my entry in Humans

### Why?
So that I can demonstrate how PRs work at the Guardian

### CODE REVIEW

**Review by sndrs — APPROVED** [review]
we really need to update the former list!

**Review by Fatalito — COMMENTED** [review]
nice place

**Review by Fatalito — APPROVED** [review]
good

**Comment by SiAdcock** [comment]
You should probably move yourself out of the content production section. But to echo what @sndrs has said, this whole file is a bit of a mess! Is it supposed to reflect the current and former members of the dotcom platform team, or the wider teams that work on dotcom, or anybody at the Guardian who just wants to be in this file?

**Comment by sndrs** [comment]
i think it began life as just the people working (or who had worked) on the dotcom team, which i think is a nice tradition?

**Comment by oliverlloyd** [comment]
Oh nice, I actually thought it was a way to demonstrate how the PR flow worked + test that everything is up and running - perhaps it's both

**Pull request merged**
