### PR TITLE
bump to play 2.4.8

### PR DESCRIPTION
**Pull request by alexduf**
## What does this change?

This should fix the CSRF problem encountered yesterday with https://github.com/guardian/frontend/pull/13490
## Request for comment

@TBonnin @johnduffell

### CODE REVIEW

**Comment by alexduf** [comment]
@mchv are you aware of any side effect of that upgrade?

**Comment by johnduffell** [comment]
👍

**Comment by alexduf** [comment]
Thanks :)

**Comment by mchv** [comment]
@alexduf do you have a link to the play bug you encountered?
The changelog is full of bug fixes so I think it could only be better!
👍

**Pull request merged**
