### PR TITLE
Load images on fronts regardless of isModern, if possible

### PR DESCRIPTION
**Pull request by sndrs**
- approximately 70% of our non-`isModern` users should now be able to see all images on fronts (from 0%)
- scrolling is much less janky

@janua or @jennysivapalan, any chance you mind look over the scala?
## 1. disables lazy-loading of images
- JS no longer needed to detect your scroll position
- JS _is_ still used to lazy-load non-primary slide-show images
- this improves scrolling performance significantly
### before

screen shot 2015-08-24 at 16 03 05
### after

screen shot 2015-08-24 at 15 58 41
## 2. uses native `srcset` and `sizes` attributes
- ensure that all browsers which can uses them, will
- if you can't, we still polyfill with JS
- if you have no JS, the first 3 are inlined as before 
### before

screen shot 2015-08-25 at 17 41 02
### after

screen shot 2015-08-25 at 17 41 37

### CODE REVIEW

**Comment by jennysivapalan** [comment]
:+1: scala

**Comment by OliverJAsh** [comment]
> approximately 70% of our non-isModern users should now be able to see all images on fronts (from 0%)

Just curious, why 70%?

**Comment by OliverJAsh** [comment]
Do we still need the lazy load images JS, or could we delete that too? I'm not sure where else it's used?

**Comment by sndrs** [comment]
> Just curious, why 70%?

native support for `srcset` and `sizes` (bases on http://caniuse.com/#feat=srcset)

>Do we still need the lazy load images JS

yeah still being used by the slideshows, so we don't load images we won't see on mobile etc

**Comment by OliverJAsh** [comment]
Sorry, I didn't feel comfortable reviewing this, but it's almost entirely Scala and @jennysivapalan gave it a :+1: :smile:

**Pull request merged**
