### PR TITLE
Fapi client

### PR DESCRIPTION
**Pull request by janua**
This changes `facia-press`, `facia` and `facia-tool` to use the new `facia-scala-client` library.

It also touches `applications`, `onward`, `article` and `preview`.

There aren't many deletions yet, as this is more of a change over and a first step rather than a complete piece of work.
I am making this PR to get it out there, I will be doing more cleaning up of some of the code tomorrow when I come in, so it isn't entirely finished yet.

The majority of this work has been making it work exactly as it works now except using the library instead of all the logic inside `frontend`. This is one half, the other being all of [these](https://github.com/guardian/facia-scala-client/pulls?q=is%3Apr+is%3Aclosed).

The main things to look out for:
- Everything is based around the new type `FaciaContent`, which is an ADT. There is an implicit class that gives the functionality that `Content` used to but in a different yet more clear way (Apart from the implicit, ish). I think Diego has copied some of the code in there into `facia-scala-client`, so some of this might get removed.
- There is a new pressed format based on very basic case classes. This is pressed into a different location than the current pressing.
- The pressing and reading are based around a switch, when switched on, it will press to and read from the new location in the new format. When off, it will press to and read from the old location in the old format.
- If something happens in `FaciaController` whilst reading the `json` in the new format, it will fall back to the old `json`. This is to cover the small case of switching over when everything has not pressed yet.
- There are helpers based in `FaciaContentConvert` to get into the correct format for the templates.

There is probably more stuff to know about; come and speak to me tomorrow if you have any questions.

@robertberry @michaelwmcnamara 
@rich-nguyen (I know you wanted to look at this :wink:)

### CODE REVIEW

**Comment by michaelwmcnamara** [comment]
Issues are here: https://docs.google.com/a/guardian.co.uk/document/d/17iR39Inm7VZM3B394KvQyd-AM1FSg4a6yZ0IORagrT8/edit

**Comment by michaelwmcnamara** [comment]
Some work outstanding on this pull request - will need to wait for Francis to return and complete it before it is merged.

**Comment by piuccio** [comment]
Reporting here some comments from #8487 by @michaelwmcnamara 

Effect on fronts using existing format:
 - [ ] - thrashers do not display - they do when I run master branch so this is something related to these      
         changes
 - [ ] - on the uk front, the crosswords icon (treat?) is not displayed on this branch but displays ok when I 
         run master branch
 - [ ] - election poll story in "headlines" container does not display on this branch but displays when I run 
         master
 - [ ] - dream snaps - title should display on a different line to the headline it brings in

**Comment by janua** [comment]
@piuccio Thanks!

**Comment by phamann** [comment]
28 days? Whats going on?

**Comment by michaelwmcnamara** [comment]
- [ ] - articles on editionalised fronts eg /uk/sport have a /uk added to their url which results in a 404 when you try to access them. found on facia-end-to-end - still there as of 6PM 29th April.

**Comment by michaelwmcnamara** [comment]
Outstanding issues for fallback here: https://docs.google.com/a/guardian.co.uk/document/d/18Xa6_IFR3e8KE7PzMpLILSmBH2kS1uIAbAS8h8h0CZ8/edit?usp=sharing

**Comment by robertberry** [comment]
Omfg

**Pull request merged**
