### PR TITLE
Fastdom commercial.js

### PR DESCRIPTION
**Pull request by robertberry-zz**

### CODE REVIEW

**Comment by phamann** [comment]
This is awesome :heart:, you'll also need to update the `dfp.js` file which does the main dom manipulation for normal adverts.

This is the main point at which they write to the dom:
https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/commercial/dfp.js#L158

**Comment by phamann** [comment]
:+1: Other than comments.

**Comment by robertberry** [comment]
@phamann Done dfp too now

**Comment by Calanthe** [comment]
I was hoping to understand it more and do it on my own. But thx @robertberry

**Comment by robertberry** [comment]
sorry @Calanthe, didn't know this was on your radar. If you want me to run you through how it works, come grab me.

**Comment by Calanthe** [comment]
Maybe that's better that you did it. Because of viewability I won't have much time for that any soon. But I am interested in some kind of going through how it works.

**Comment by robertberry** [comment]
@michaelwmcnamara Could you help me test this please? :dancer:

**Comment by robertberry** [comment]
@Calanthe If you like you could fastdom the commercial creatives, as I've not done that yet. If you're too busy let me know and I'll do it

**Pull request merged**
