### PR TITLE
Remove unused files in static/src/stylesheets

### PR DESCRIPTION
**Pull request by shtukas**
## What does this change?

This change removes the .scss files in `static/src/stylesheets` that seem to be not used. 

File "Not used" in this case means

1. Does not appear in the .scss dependency tree.
2. Does not appear in the scala code as an ad-hoc import.
3. Does not break `make compile` when the file is removed. 
4. Does not break the `sbt test`
5. Does not break TeamCity :)

Interestingly, for `i = 1 to 4`, you have have everything from `1 to i` but not `i+1`.

### CODE REVIEW

**Comment by SiAdcock** [comment]
@shtukas 

As discussed, have a look for dynamically-generated filenames in [`assets.scala`](https://github.com/guardian/frontend/blob/master/common/app/assets/assets.scala#L56) before removing those `head.*.scss` files 😄

**Comment by shtukas** [comment]
Thanks @SiAdcock 
`assets.scala` is doing the trick. Interestingly I was putting those files back one by one after looking at the TeamCity build failure logs messages, but didn't know there was a pattern to it :)

**Review by SiAdcock — APPROVED** [review]
I _think_ [`head.rich-links.scss`](https://github.com/guardian/frontend/blob/master/static/src/stylesheets/head.rich-links.scss) might also be safe to delete. However, this PR looks great!

**Comment by shtukas** [comment]
Noted. Will do in a separate PR (there is also a tiny other thing I want to do...)

**Pull request merged**
