### PR TITLE
Podcast Links: Update capi dependency & pipe links to the frontend

### PR DESCRIPTION
**Pull request by ajwl**
## What does this change?

We need to incorporate changes in the content-api that add new spotify and google urls to Podcasts. 

* update the content-api dependency 
* add lots of data files for the tests as per the docs
* Change the frontend to display the new links 

This is a fix for a broken test `val campaignInformationType = None`

screen shot 2018-08-21 at 17 09 27

Related: 
https://github.com/guardian/content-api-models/pull/148
https://github.com/guardian/content-api-models/pull/147

### CODE REVIEW

**Comment by tomrf1** [comment]
@ajwl updating the capi client also requires a change to the test files in this repository.
See https://github.com/guardian/frontend/blob/master/docs/03-dev-howtos/15-updating-test-database.md#updating-test-database

You'll need to run `sbt test` locally, and after it's finished commit any generated files under `/data/database/`.

**Comment by ajwl** [comment]
@tomrf1 tests pass but CSS problem persists... must be something else going on

**Comment by ajwl** [comment]
@tomrf1 finally fixed 
screen shot 2018-08-22 at 12 49 50

**Review by tomrf1 — APPROVED** [review]
👍 looks good

**Pull request merged**
