### PR TITLE
tech feedback extend switch

### PR DESCRIPTION
**Pull request by johnduffell**
tech feedback is still on the back burner, hopefully can get back to it soon

and @uplne yes I know it'll come back to bite me in 3 months ;)

### CODE REVIEW

**Comment by piuccio** [comment]
expire in august, i hope you won't be on holiday. Why not making it a feature?

**Comment by johnduffell** [comment]
@piuccio it will be developed further, this is just an initial test to see if it's feasible.  It is, but I need to spend some time improving it.

**Comment by uplne** [comment]
I agree with @piuccio If it proved itself then make it a feature and just iterate on it in the future.

**Comment by johnduffell** [comment]
ok you got me https://github.com/guardian/frontend/pull/9243

**Pull request closed without merging**
