### PR TITLE
Add test of Ophan analytics for AMP

### PR DESCRIPTION
**Pull request by philwills**
https://github.com/guardian/ophan/pull/1293/files was the corresponding PR for the config living in Ophan.

In order to see this make a request, you currently need to use `AMP.toggleExperiment('amp-analytics')` in the console. You will also see some validation errors until https://github.com/ampproject/amphtml/issues/1087 is addressed.

cc @NataliaLKB @johnduffell

### CODE REVIEW

**Comment by johnduffell** [comment]
great although I think technically all the script tags should be in the head, but for now it doesn't validate anyway and it'll still work in the browser :+1:

**Comment by philwills** [comment]
@johnduffell I'm confused. I believed I had added it to the head and looking at the diff isn't disabusing me of that.

**Comment by NataliaLKB** [comment]
Looks good :+1:

**Comment by johnduffell** [comment]
haha oh yes, so you did :blush:

**Comment by NataliaLKB** [comment]
The only thing to note is I don't think the `amp-analytics` tag should be in the head, maybe put it in the body? Like this example: https://github.com/ampproject/amphtml/blob/dc9bf619446a1547db0649e2fe81885bb7423fc1/examples/analytics.amp.html

**Comment by philwills** [comment]
Thanks @NataliaLKB, I've updated to put the `amp-analytics` element in the body.

**Comment by NataliaLKB** [comment]
@philwills great thanks! :ship:

**Comment by philwills** [comment]
You can go to https://dashboard.ophan.co.uk/info?country=GNM&platform=amp&path=/info/developer-blog/2015/jan/05/delivering-continuous-delivery-continuously to watch the numbers tick up.

**Comment by NataliaLKB** [comment]
great! :sparkles:

**Pull request merged**
