### PR TITLE
Setup guide - Minor README  updates

### PR DESCRIPTION
**Pull request by gtrufitt**
I've run through the setup guide (automatic) for the first time and hit two very minor stumbling blocks - this PR updates the README to clarify those two points. 

I did wonder whether in ['A JDK'](https://github.com/guardian/frontend#a-jdk) section, whether the Ubuntu set-up installing 'openjdk-7-jdk' is correct? I don't use Ubuntu and there doesn't seem to be a [openjdk-8-jdk package](http://packages.ubuntu.com/search?keywords=openjdk&searchon=names&suite=trusty&section=all) in the package repo, but there does seem to be an [openjdk 8 package available](http://openjdk.java.net/projects/jdk8/). If an Ubuntu user wants to confirm, I can update this with the correct info (if needed) in this PR as well.

### CODE REVIEW

**Comment by desbo** [comment]
:+1: on the readme changes, the JDK section is asking you to install [this one](http://packages.ubuntu.com/trusty/openjdk-7-jdk), right?

**Comment by gtrufitt** [comment]
> on the readme changes, the JDK section is asking you to install this one, right?

Right. I just wanted to check that this is still the case for Ubuntu users, as [this suggests](https://www.playframework.com/documentation/2.4.x/Migration24#Java-8-support) that Java 7 support is dropped (I may be getting confused with JDK, Java etc here though)...

**Comment by rich-nguyen** [comment]
Yes, let's give a few steps for java 8 for ubuntu devs. Sent you a snippet

**Comment by gtrufitt** [comment]
> Yes, let's give a few steps for java 8 for ubuntu devs. Sent you a snippet

Perfect, thanks @rich-nguyen, I've added that in.

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
