### PR TITLE
Retain returnURL on Email verification

### PR DESCRIPTION
**Pull request by niklasvincent**
As a user, I want to return to where I was originally on the site before I started my registration journey.

This change affects the options a user is given when returning back to `profile.theguardian.com` by clicking the URL in the verification e-mail. Instead of the old "Return to the homepage" and "Edit profile", the user now gets presented with a single button named "Continue" that will take them back to the original URL.

### CODE REVIEW

**Comment by johnduffell** [comment]
does WIP mean ur not planning to merge it?  the description is missing for some reason so I'm not sure what the problem you're fixing is

**Comment by markjamesbutler** [comment]
Sorry for the WIP label, we will not great these types of pull request in future.  This PR is now ready for peer review.

**Comment by danmassie** [comment]
:+1:

**Comment by johnduffell** [comment]
:+1: great makes a lot more sense,  and a good change - thanks!

**Pull request merged**
