### PR TITLE
Encode URL as query parameter (URI component)

### PR DESCRIPTION
**Pull request by OliverJAsh**

### CODE REVIEW

**Comment by phamann** [comment]
:+1:

**Comment by rtyley** [comment]
@akemitakagi reports that the 'become a new member' link is broke for her - she gets sent to:

https://profile.theguardian.com/register?returnUrl=https%3A%2F%2Fmembership.theguardian.com%2Fjoin%2Ffriend%2Fenter-details&skipConfirmation=true?returnUrl=https%3A%2F%2Fmembership.theguardian.com%2Fjoin%2Ffriend%2Fenter-details&skipConfirmation=true

..which gives this error:

```
Bad Request: Cannot parse parameter skipConfirmation as Boolean: should be true, false, 0 or 1
```

---------- Forwarded message ----------
From: Akemi Takagi
Date: 26 March 2015 at 14:08
Subject: The link 'become a new member' on the front page doesn't work (You may know this already...)

The link 'become a new member' on the front page doesn't work on Chrome Version 41.0.2272.104 (64-bit)

The page says :
Bad Request: Cannot parse parameter skipConfirmation as Boolean: should be true, false, 0 or 1

**Comment by mattandrews** [comment]
The link is a bit confusing but think of it like this: the URL we want people to end up at is:

`https://membership.theguardian.com/join/friend/enter-details?skipConfirmation=true`

... but this is sending them to:

`https://membership.theguardian.com/join/friend/enter-details&skipConfirmation=true`

**Comment by OliverJAsh** [comment]
As clarified with @mattandrews, the `returnUrl` needs to be `https://membership.theguardian.com/join/friend/enter-details` (URL encoded). The `skipConfirmation` query parameter is applied to the Identity URL, not as part of the `returnUrl`.

**Pull request merged**
