### PR TITLE
No commercial.js on immersive interactives with ads disabled

### PR DESCRIPTION
**Pull request by wpf500**
On immersive interactives with ads disabled, `commercial.js` doesn't add anything, so lets just not load it. `enhanced.js` doesn't add anything either and seems to have some dependencies on `commercial.js`, so disable that too!

The only thing that does might be useful is the navigation, so I've moved the navigation initialisation from enhanced to standard. From what I can tell the `navigation` module doesn't require anything that standard doesn't already have, and the `newHeaderNavigation` is already in standard, so why not put both in there?

### CODE REVIEW

**Comment by wpf500** [comment]
@stephanfowler @SiAdcock

**Comment by rich-nguyen** [comment]
ccing @guardian/commercial-dev

**Comment by SiAdcock** [comment]
My main concern with this approach is that excluding `enhanced.js` from Immersive Interactives would exclude more than just commercial dependencies. We would also exclude other functionality such as some tracking tools (notably our facade for Google Analytics) and notifications.

I know we probably don't need _all_ of the functionality loaded by `enhanced.js` on this page, but it is possible that we will end up excluding something we need. 

If we do need things like Google Analytics on Immersive Interactives articles, an alternative approach would be to bundle and include a stripped-down version of `enhanced.js` containing only the modules we need.

@NataliaLKB @sndrs: any thoughts on this?

**Comment by wpf500** [comment]
Yeah definitely agree on tracking. I thought we'd come to the conclusion that all the tracking stuff was inline on the page anyway, so this wasn't removing that stuff

**Comment by NataliaLKB** [comment]
> I know we probably don't need all of the functionality loaded by enhanced.js on this page, but it is possible that we will end up excluding something we need.

I completely agree with @SiAdcock . 

It might be best to ask @dominickendrick regarding google analytics. But from what we can tell it is definitely loaded in enhanced. Now that we are not using Omniture, it seems important to have google analytics on interactive pages

**Comment by regiskuckaertz** [comment]
Why immersive articles specifically? Can this change (at least removing `commercial`) not be applied across the board?

**Comment by wpf500** [comment]
This is for immersive interactives, not immersive articles (unfortunately there is a difference!). It only applies to the former because all other content types have things like related content which needs `commercial`/`enhanced`. It might be that they only need `enhanced` but not `commercial`, but that's a much bigger piece of work because currently `commercial` pulls in a lot of dependencies.

**Comment by SiAdcock** [comment]
Confirmed with @dominickendrick that analytics is loaded in `enhanced`, therefore unfortunately I don't think excluding `enhanced` on immersive interactive articles is the correct approach for dealing with this issue. It's a shame that `enhanced` has become this giant bundle of hugs that gets added to every page whether we need everything or not, but we're hoping to deal with that as part of the ongoing client side re-architecture.

I'm in favour of moving `navigation` to `standard` if that helps with the jank. Also happy to discuss further

**Comment by wpf500** [comment]
This is much more complicated than initially envisaged, moving to a hack (https://github.com/guardian/frontend/pull/14905) to get the desired effect in the short term (i.e. for tomorrow!)

**Pull request closed without merging**
