### PR TITLE
Update become a member link

### PR DESCRIPTION
**Pull request by joelochlann**
Based on the [results of this A/B test](https://docs.google.com/spreadsheets/d/15TutG8BfwKl7o9DWqWlYH9BEBxyQhessjJ2_E3fy2i4/edit#gid=0) we've decided to point the "Become a member free" link straight at the Membership homepage rather than going to the Friend join page via the Identity sign-in page.

@dominickendrick @stephanfowler

### CODE REVIEW

**Comment by davidrapson** [comment]
@joelochlann Build is failing but not from your change, TC reporting a `Unable to load registry %bower%` error from JSPM.

**Comment by gklopper** [comment]
Does that spreadsheet say we double revenue from "become a member" by doing this? If so, does that pass a common sense test (i.e. is our data accurate)?

**Comment by crifmulholland** [comment]
Yes, I'd be wary of basing that projection on 3 visitors completing.

**Comment by joelochlann** [comment]
Yes, fair point. I don't know much about the rationale behind this decision but I'll get @JuliaBellis involved this afternoon to prove some more information

**Comment by joelochlann** [comment]
It seems that the A/B test referenced above isn't good evidence for this change, not just because of small sample size for some results but also because they changed two variables at once (the word "free" in the link, and the destination of the link).

I'll close this pull request and we'll look at running another A/B test where we just change the immediate destination of the link (membership homepage or identity), to see what impact that particular change might have.

**Pull request closed without merging**
