### PR TITLE
Add shouldHideAdverts check to stickyAd init

### PR DESCRIPTION
**Pull request by gtrufitt**
If we're not showing ads, we shouldn't run sticky ad.

### CODE REVIEW

**Comment by OliverJAsh** [comment]
:+1:!

**Comment by gtrufitt** [comment]
Will merge this first thing, not breaking anything cos robusted so not urgent

**Comment by jbreckmckye** [comment]
If you're testing for `sensitiveContent`, you may also want to test for `config.page.section === 'childrens-books-site`, too.

**Comment by gtrufitt** [comment]
Cheers @jbreckmckye - have done that now too.

**Pull request merged**
