### PR TITLE
Wrap serviceWorker in a switch

### PR DESCRIPTION
**Pull request by GHaberis**
## What does this change?

This enables us to turn our Service Worker on/off with a feature switch `ServiceWorkerEnabled`. 

All fetch requests that originate from www.theguardian.com proxy through a Service Worker running for the site, For each request the Service Worker queries it's cache and returns a cached response if available. After debugging the service worker running for the www.theguardian.com I've seen that every fetch request intercepted by the service worker eventually falls back to the network rather than returning cached responses. This is because we never actually store put any responses in the cache. 

I therefore believe the current implementation of the Service Worker is offering no performance benefits and may in fact cause performance degradations. 

The video [Building Faster, More Resilient Apps with Service Worker (Chrome Dev Summit 2018)](https://www.youtube.com/watch?v=25aCD5XL1Jk) outlines that there could actually be performance costs of running a service worker as we are.

I've included a few useful slides from the presentation:

This demonstrates the response times with a Service Worker. The grey and the blue bars demonstrate a latency introduced when proxying fetch requests using a Service Worker. The blue shows the time the worker takes to query it's cache. We'll never achieve the ideal "Cache hit" scenario as our cache is always empty. The best we can hope for is "Cache Miss".

What's worrying is if the worker is asleep you get an additional latency whilst it wakes up (shown in grey). If a user loads www.theguardian.com and their workers asleep they'll always end up with the "Worst case" scenario.

screen shot 2018-12-04 at 13 09 49

So, how often is the worker asleep? It's hard to know. But the example (below) presented in this talk was asleep 75% of the time. So 75% of our users could be getting the "worst case" scenario and 25% a "cache miss". Both of these are undesirable and offer worse performance than no service worker at all. 

screen shot 2018-12-04 at 13 07 26

**TODO**

I'd like to turn this worker off for now and look at reimplementing the cache so we actually put responses in it where it could lead to an improvement on the browser cache - Apparently Service Workers cache a byte code representation of JavaScript which means it can be parsed quicker once retrieved.

### CODE REVIEW

**Comment by GHaberis** [comment]
@guardian/commercial-dev there's a commercial switch `BlockIASSwitch` that relies on the service worker when it's ON. It's currently OFF so doesn't do anything. By turning the `ServiceWorkerDisabled` switch ON it'll mean if you do turn on `BlockIASSwitch` nothing'll happen as no worker will be running. Is this OK? Do you intend to turn on `BlockIASSwitch` anytime soon?

**Review by SiAdcock — APPROVED** [review]
Really fascinating investigation @GHaberis, thanks for such a clear and well-presented explanation!

**Comment by GHaberis** [comment]
Following feedback from @SiAdcock I'm going to reimplement the switch as `ServiceWorkerEnabled` rather than `ServiceWorkerDisabled`.

**Comment by katebee** [comment]
@GHaberis good to know! 
I do not think we will be using the BlockIASSwitch anytime soon, but will keep it in mind ⭐️

**Review by nicl — APPROVED** [review]
Looks good! 100ms startup on mobile is definitely significant.

**Comment by NataliaLKB** [comment]
Ah really interesting!

**Comment by ScottPainterGNM** [comment]
@GHaberis I feel that we probably don't need that switch at all now, it was built when that provider was causing the site issues. @guardian/commercial-dev let me know if you disagree!

**Comment by kelvin-chappell** [comment]
Nice analysis @GHaberis and I agree with @ScottPainterGNM.  We really need to clean up our switches!

**Pull request merged**
