### PR TITLE
Jumpy page with sticky nav and adblock fix

### PR DESCRIPTION
**Pull request by Calanthe**
Temporary fix for https://github.com/guardian/frontend/issues/9841

It is temporary because there will be a proper banner for adblock users.

### CODE REVIEW

**Comment by OliverJAsh** [comment]
> It is temporary because there will be a proper banner for adblock users.

Where can I see the designs? :smile:

**Comment by Calanthe** [comment]
I don't know where or when but I hope that this week. I will send you them when I will get them.

**Comment by uplne** [comment]
:+1:

**Comment by OliverJAsh** [comment]
BTW, if you want GitHub to automatically close issues when you merge, you need to write "Fixes #" in the Git commit message. https://help.github.com/articles/closing-issues-via-commit-messages/

**Pull request merged**
