### PR TITLE
Yarn@1.1

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

- upgrades yarn
- resolves some resolves being unresolved

## What is the value of this and can you measure success?

removes some installation error messages, although `warning "babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc"` seems immovable, and not referenced anywhere in google

### CODE REVIEW

**Comment by SiAdcock** [comment]
There's a similar, although not identical, peer dependency issue raised against Yarn: @yarnpkg/yarn#4589 (originally raised against `babel-loader` and has since been closed @babel/babel-loader#517)

This might be a manifestation of the sam problem. I wonder if it happens when we install using NPM?

**Comment by SiAdcock** [comment]
The changing position of the `-s` flag kills me every time

**Comment by sndrs** [comment]
> The changing position of the -s flag kills me every time

it feel a bit like yarn has become unstable, just making changes willy nilly

**Review by SiAdcock — APPROVED** [review]
🤞

**Pull request merged**
