### PR TITLE
model Media Asset Platform as enum

### PR DESCRIPTION
**Pull request by gidsg**
## What does this change?
Models Media Asset Platform as enum

## What is the value of this and can you measure success?
More type safety

## Does this affect other platforms - Amp, Apps, etc?
No

## Screenshots
N/A

## Tested in CODE?
No

### CODE REVIEW

**Review by TBonnin — COMMENTED** [review]
Would a `scala.Enumaration` fits your need? 
If not what does the `enumeratum` lib bring that you cannot do with a plain `sealed trait`

**Comment by gidsg** [comment]
@TBonnin The main benefit of `enumeratum` for me was that it provides the implicit JSON formatter for Play. https://github.com/lloydmeta/enumeratum#playenum

**Comment by TBonnin** [comment]
@gidsg I don't see where in this PR you need this implicit json formatter. Am I missing something?

**Comment by TBonnin** [comment]
@gidsg Nevermind here https://github.com/guardian/frontend/pull/15685/files#diff-ed9aaed2c6c7363409f7357c602ba1e1R152 :D

**Review by akash1810 — APPROVED** [review]
🙌 👍

**Comment by TBonnin** [comment]
Adding a dependency for a single and narrow use case seems to be the best way to end up with a huge dependencies tree. I won't block this PR, it is up to you. However I am curious to see what extra code you will need to write to have the exact same feature without using any 3rd party lib.

**Comment by gidsg** [comment]
@TBonnin I think let's merge this for now and when I have a moment I will have a go at refactoring without the dependency. When I tried before with Scala Enumeration I got stuck in JSON formatting hell.

**Comment by TBonnin** [comment]
@gidsg Enumeration have a lot of shortcomings. I am more talking about using a sealed trait with some extra code to handle the json formatting

**Comment by gidsg** [comment]
CC @philwills

**Pull request merged**
