### PR TITLE
Tidy root directory slightly

### PR DESCRIPTION
**Pull request by jfsoul**
## What does this change?

Slight tidy up of docs in the root directory to reduce clutter:
- Removes browserlist which seems to be more thoroughly documented elsewhere anyway.
- Moves IMAGES.md to the new docs structure (bonus points for conserving history).
## What is the value of this and can you measure success?

Less clutter = happier devs
## Request for comment

@TBonnin

### CODE REVIEW

**Comment by SiAdcock** [comment]
Worth including a link to the more up-to-date browserlist documentation?

**Comment by jfsoul** [comment]
https://github.com/guardian/frontend/blob/master/docs/04-quality/01-browser-support.md

I'd say this is more easily found than the previous browserslist.

**Comment by SiAdcock** [comment]
Agreed 👍

**Comment by TBonnin** [comment]
👍  Thank you @jfsoul

**Pull request merged**
