### PR TITLE
Create admin-jobs app

### PR DESCRIPTION
**Pull request by TBonnin**
First step of the project to decouple breaking-news from fronts and instead be notified of new alerts by the new [n10n](https://github.com/guardian/mobile-n10n/) notification system.

### CODE REVIEW

**Comment by TBonnin** [comment]
cc @rich-nguyen

**Comment by johnduffell** [comment]
re costs we should think carefully about whether it needs a new app

**Comment by TBonnin** [comment]
@johnduffell valid point, at the moment it probably doesn't require a new app. 
However I think @rich-nguyen has a bigger intend for this app: moving into it all scheduled and manually trigger jobs/tasks which are currently living in admin

**Comment by TBonnin** [comment]
Renamed the app to `chore` to show the intend

**Comment by rich-nguyen** [comment]
my best suggestion is to rename `admin` `admin-tool` and `chore` `admin-jobs`

**Comment by rich-nguyen** [comment]
:+1: for the changes though. Yes @johnduffell, I want to remove the commercial jobs and facia jobs from admin.

**Comment by TBonnin** [comment]
sounds good. I will modify my PRs to `use admin-jobs`

**Comment by rich-nguyen** [comment]
ok great, admin can be renamed in another pr

**Comment by johnduffell** [comment]
sounds like you guys are way ahead of me in thinking, I couldn't be happier with that you are sorting out admin! :+1:

**Pull request merged**
