### PR TITLE
Enable HTTPS on /science

### PR DESCRIPTION
**Pull request by desbo**
See also: https://github.com/guardian/fastly-edge-cache/pull/549

### CODE REVIEW

**Comment by Jholder112233** [comment]
This is sadly going to break all of these interactives http://www.theguardian.com/science/science+content/interactive even the most recent one has a lot of http links.

What's the reason for the move?

**Comment by desbo** [comment]
@Jholder112233 commercial are using it to measure the impact of HTTPS on ads. I've checked with them and it's fine to exclude interactives from the test - will keeping everything under `science/ng-interactive` on regular HTTP be enough?

**Comment by Jholder112233** [comment]
@desbo that will cover all of the interactives served by NGW, there are still some on R2. Not sure if your change will affect those? They live on science/interactive

**Comment by johnduffell** [comment]
awesome that https is moving forward!

**Comment by desbo** [comment]
@Jholder112233 I've updated the fastly PR to not apply any of the HTTPS rules to interactives URLs.
Could you take a look and +1 here and there if you're happy?

**Comment by Jholder112233** [comment]
:+1:

**Pull request merged**
