### PR TITLE
Enable HTTPS on crosswords

### PR DESCRIPTION
**Pull request by desbo**
See also https://github.com/guardian/fastly-edge-cache/pull/550

### CODE REVIEW

**Comment by gtrufitt** [comment]
:+1:

**Comment by dominickendrick** [comment]
#### Across
1. Secure? (5)
:newspaper:

**Comment by OliverJAsh** [comment]
Crossword users will be happy to know they can play when offline. We should start adding some tracking to this. :smile:

**Comment by crifmulholland** [comment]
Yes! That's why I wanted it on https!

**Comment by paperboyo** [comment]
:gem:

**Pull request merged**
