### PR TITLE
add media analytics to curl config

### PR DESCRIPTION
**Pull request by jamesgorrie**
## What does this change?

One more place this need to be added.
Strangely didn;t break while not using bundled assets. Crumbs.
## What is the value of this and can you measure success?

Even more fixed
## Does this affect other platforms - Amp, Apps, etc?

Nope
## Screenshots

🍭 
## Request for comment

@akash1810 @sndrs 
cc: @johnduffell

### CODE REVIEW

**Comment by jamesgorrie** [comment]
Easier to see: https://github.com/guardian/frontend/pull/13656/files?w=1

**Comment by sndrs** [comment]
👍

**Comment by akash1810** [comment]
👍

**Comment by gidsg** [comment]
👍 🔀

**Pull request merged**
