### PR TITLE
Rugby league to UK edition

### PR DESCRIPTION
**Pull request by uplne**
Replacing us-sport with rugby league for UK edition

screen shot 2015-02-24 at 15 10 09

### CODE REVIEW

**Comment by rich-nguyen** [comment]
I assume you've run the numbers on this?

**Comment by michaelwmcnamara** [comment]
Rugby union tag page: 5,920 - even without any links in the nav
US sport page: 5,013 - with link in nav

Rugby League
image

US-Sports
image

**Comment by michaelwmcnamara** [comment]
QA :+1:

**Comment by johnduffell** [comment]
a daring change to the nav! looks like your build failed on a timeout, probably needs respinning

**Comment by rich-nguyen** [comment]
@michaelwmcnamara I did an analysis in Omniture, given the limited time scope of Ophan, (prior to redshift), and your query was scoped by country GB, but the nav is a global feature. What turned out to be a standard analytics exercise gave me back some fascinating results. Here are the last 12 months:

screen shot 2015-02-25 at 15 25 17

Blue is rugby league, us sports is green. They are quite seasonal, and it looks like it's dependant on trending competitions (super league vs super bowl), but it shows that for content (not just the front, because it is content that gives a section its value), rugby league should be given a run. Although the big spike in rugby league views is for a guy punching an unconscious player. Aces.

**Comment by uplne** [comment]
@rich-nguyen @michaelwmcnamara nice findings

I actually run the same numbers as Mike. But after this discussion I've pushed back on this and as there is a space for one more link in the nav I will leave the us-sport there and add rugby league...editors want it more visible because of the rugby season start.

**Comment by rich-nguyen** [comment]
:+1:

**Pull request merged**
