### PR TITLE
Downgrade svgo

### PR DESCRIPTION
**Pull request by OliverJAsh**
This is to workaround the bug in https://github.com/svg/svgo/issues/413, which is causing some of our SVGs to break (such as ).

/cc @tijanamiletic

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Just a reminder that I need to shrinkwrap this!

**Comment by rich-nguyen** [comment]
haha! was about to mention that i dont see shrinkwrap!

**Comment by rich-nguyen** [comment]
:+1:

**Comment by OliverJAsh** [comment]
Done!

**Comment by paperboyo** [comment]
Fixed? https://github.com/svg/svgo/issues/413#event-381644407 (Thanks, @GreLI!)

**Comment by OliverJAsh** [comment]
Closed in favour of https://github.com/guardian/frontend/pull/10143

**Pull request closed without merging**
