### PR TITLE
Remove travel offers refactor switch

### PR DESCRIPTION
**Pull request by kelvin-chappell**
The first to go!

/cc @regiskuckaertz

### CODE REVIEW

**Comment by regiskuckaertz** [comment]
wuhuuuuu 👍 

(please wait for my PR to go through, we have a expired switch that will break tests)

**Comment by regiskuckaertz** [comment]
(I think books, masterclasses, jobs and soulmates are good to go too, I will re-enable capi and manual today)

**Comment by regiskuckaertz** [comment]
I think `travelFragment` and `travelProminent` should go too, no?

**Comment by kelvin-chappell** [comment]
`travelFragment` is part of the blended component, isn't it?

`travelProminent` appears to respond to the `layout` parameter.  If you think that's not used I'll remove it.  I'm pretty sure it's not used.

**Comment by regiskuckaertz** [comment]
oh yeah right. Haha, I forgot about the `layout` parameter 😅  But this is a trivial change in the new code, you can safely remove the `travelProminent` template.

**Comment by kelvin-chappell** [comment]
I went too far in that last commit.  We still need the `layout` parameter.

**Comment by regiskuckaertz** [comment]
So, I will post an update of

```
<div class="adverts__row">
    @offers.map { offer => @travelCard(offer, clickMacro) }
</div>
```

to handle the `layout` parameter for travel and books

**Pull request merged**
