### PR TITLE
Define Carrot breakpoint rules

### PR DESCRIPTION
**Pull request by frankie297**
## What does this change?
Includes Mobile and Desktop rules for the Carrot

## What is the value of this and can you measure success?
Can serve the Carrot on desktop and mobile, drives more traffic to GLabs content

### Tested

- [x] Locally
- [ ] On CODE (optional)

### CODE REVIEW

**Comment by SiAdcock** [comment]
I'll bite: what is the Carrot?

**Comment by katebee** [comment]
screen shot 2018-08-01 at 09 58 28


The carrot is our unofficial codename for the **_glabs-traffic-driver_**, because carrot is quicker to say, and **_glabs-traffic-driver_** is a name that could actually apply to several different things. The **_carrot_** looks similar to a rich link, or the inline merch:

#### inline merch:

screen shot 2018-08-01 at 09 48 53

#### glabs traffic driver:

screen shot 2018-08-01 at 09 52 46


### Long live the carrot!

**Comment by SiAdcock** [comment]
Aha, looks nice, apt naming! When is the stick coming? 😜

**Review by katebee — APPROVED** [review]
👍 Great!

**Pull request merged**
