### PR TITLE
Invalidate all identity csrf cookies

### PR DESCRIPTION
**Pull request by danmassie**
Due to the application secret being rotated users are experiencing issues accessing pages that check csrf cookies. Existing cookies are not currently removed on sign out and existing cookies signed with the old secret are resulting in 500s. This updates the sign out action to discard the csrf cookie and renames the cookie to effectively remove it for all users.

### CODE REVIEW

**Comment by jamespamplin** [comment]
:+1: looks good to me

**Comment by rich-nguyen** [comment]
:+1:

**Comment by rich-nguyen** [comment]
Sounds like we should update the behaviour so that this doesn't happen again. Maybe it's possible to sever the dependency on the app secret? Identity could have it's own app secret, for example.

**Comment by danmassie** [comment]
I'll create a ticket for that Rich.

**Comment by rich-nguyen** [comment]
thanks @danmassie, add me as a contact for that one, I can give a few pointers.

**Pull request merged**
