### PR TITLE
remove contribution reminder survey ask from epic

### PR DESCRIPTION
**Pull request by michaelbjacobson**
Removes contribution reminder survey ask from epics, as per [this ticket](https://trello.com/c/JS9XjnXr). Please see screenshot below.

Screenshot 2020-05-27 at 14 25 15

### CODE REVIEW

**Comment by tjsilver** [comment]
Looks like the word 'articles' has disappeared in the screenshot...?

**Review by tjsilver — APPROVED** [review]
👍

**Comment by michaelbjacobson** [comment]
> Looks like the word 'articles' has disappeared in the screenshot...?

@tjsilver that's just the copy on this epic variant (which is only being used locally), thanks for flagging though! 🙂

**Comment by ionamckendrick** [comment]
Looks good, thanks for this Mike!

**Pull request merged**
