### PR TITLE
Add main image to hosted article

### PR DESCRIPTION
**Pull request by kelvin-chappell**
/cc @Calanthe

### CODE REVIEW

**Comment by Calanthe** [comment]
👍

**Comment by paperboyo** [comment]
Excuse the code-blind, but will it use mediaservice's `/master/` asset (as it always should if the images are to come from Grid)? Ignore me if these images aren't going through Grid/resizer route...

**Comment by kelvin-chappell** [comment]
@paperboyo We're going to revisit the way we handle images after we've got the first composer-driven campaign live.  They should be handled in the same way as normal articles ultimately.  They are coming from the grid.

**Comment by paperboyo** [comment]
Thanks, @kelvin-chappell!

> They should be handled in the same way as normal articles ultimately.

article-1326196173340-021e3f97000004b0-358038_568x386

**Pull request merged**
