### PR TITLE
update pasteup-forms

### PR DESCRIPTION
**Pull request by gidsg**
Update `pasteup-forms` to version 6. @guardian/identity @guardian/membership-and-subscriptions  please check you are OK with this (as people who use forms).

This is to support some forthcoming forms within the Discussion frontend app.

### CODE REVIEW

**Comment by rtyley** [comment]
This would probably only effect Membership on https://profile.theguardian.com/membership/edit, where we have a dotcom-styled page using data retrived by AJAX from membership - should be fine with us. 

cc @joelochlann @tomverran

**Comment by emma-p** [comment]
Should be fine with Identity too

**Comment by gidsg** [comment]
CC @sndrs please can you review and +1?

**Comment by sndrs** [comment]
:+1:

**Pull request merged**
