### PR TITLE
Retire ABRegister switch

### PR DESCRIPTION
**Pull request by OliverJAsh**

### CODE REVIEW

**Comment by OliverJAsh** [comment]
Results at https://docs.google.com/spreadsheets/d/1NHMKc3CUwkE0GkHSqNhJQUYT55Gb-zbH3QvykGIvl5k/edit?usp=sharing

`become-a-member+free` was the winner, so we're applying this permanently.

**Comment by phamann** [comment]
You haven't updated or removed the switch?

**Comment by OliverJAsh** [comment]
Updated!

**Comment by OliverJAsh** [comment]
Ping @phamann

**Comment by phamann** [comment]
:+1:

**Pull request merged**
