### PR TITLE
Remove legacy JS test infrastructure

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

There are no more legacy tests 🎉 

This change removes all the infrastructure surrounding them including dependencies (Jasmine, Karma and RequireJS), tasks and configuration

## What is the value of this and can you measure success?

Shorter build times and less redundant code

## Does this affect other platforms - Amp, Apps, etc?

No

## Does this affect GLabs Paid Content Pages? Should it have support for Paid Content?

No

## Screenshots

No

## Tested in CODE?

No

### CODE REVIEW

**Review by sndrs — COMMENTED** [review]
image
:swoon:

**Comment by sndrs** [comment]
it's happened @gustavpursche!

**Review by sndrs — APPROVED** [review]

**Comment by gustavpursche** [comment]
@sndrs @SiAdcock @GHaberis ❤️ That's beautiful, congratulations. "To [the moon, then] infinity and beyond!"

**Comment by SiAdcock** [comment]
Couldn't have done it without you, dude ❤️

**Pull request merged**
