### PR TITLE
Remove chimney ab test

### PR DESCRIPTION
**Pull request by rich-nguyen**

### CODE REVIEW

**Comment by OliverJAsh** [comment]
:+1:

**Comment by robertberry** [comment]
wowsa why did all the tests change?

**Comment by robertberry** [comment]
but yeah :+1:

**Comment by rich-nguyen** [comment]
i reran the tests with an empty data folder. It's the only to ensure that unused data files get removed. Because it's hash-based, modified files which correspond to the same request (but different response) get relocated. We should improve this system (http recorder).

**Comment by sndrs** [comment]
:crying_cat_face:

**Comment by phamann** [comment]
My guess is @rich-nguyen is just gaming his GitHub stats again, @kaelig style.

**Comment by kaelig** [comment]
:innocent:

**Comment by robertberry** [comment]
SHIP IT :ship: :shipit: 

Tests are failing now

**Comment by robertberry** [comment]
Oh wait, it is shipped. lol

**Pull request merged**
